### PR TITLE
Scripts/Spells: Implemented druid's Gore

### LINKED ISSUE #19723: Core/Script The spell Gore doesn´t work.
**Description:**

The passive spell Gore(ID:210706) given to Druid Guardian at lv.48 has an issue

Gore (passive): Using Thrash, Swipe, or Moonfire has a 15% chance to reset the cooldown on Mangle, and to cause it to generate an additional 4 rage

**Current behaviour:**

The spell doesn´t works, you can use thrash and Swipe how many times you want, that the passive effect is never activated

**Expected behaviour:**

When you use Thrash, Swipe pr Moonfire you have a 15% chance to reset the cooldown of Mangle and it will generate 4 extra rage

**Steps to reproduce the problem:**

1. Create a Druid character
2. Reach lv.48 an choose the Guardian Spec
3. Use the spell´s Thrash, Swipe, or Moonfire several times and check the cooldown and the rage generated by Mangle

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=210706/gore

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Implemented druid's gore spell

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #19723

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by offl** [comment]
#19723?

File: src/server/scripts/Spells/spell_druid.cpp [hunk 1]
```diff
@@ -1510,6 +1515,38 @@ class spell_dru_wild_growth : public SpellScriptLoader
...
+    bool Validate(SpellInfo const* /*spellInfo*/) override
+    {
+        return ValidateSpellInfo({ SPELL_DRUID_GORE_PROC });
+    }
+
+    void HandleProc(AuraEffect* aurEff, ProcEventInfo& procInfo)
+    {
+        if (SpellInfo const* spellInfo = procInfo.GetSpellInfo())
+        {
+            if (spellInfo->Id == SPELL_DRUID_BEAR_THRASH || spellInfo->Id == SPELL_DRUID_SWIPE ||
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_druid.cpp:1532]: List of spells should be done using spell_proc table
SpellFamilyMask0 0x00200800 -- Maul (0x800) & Moonfire (0x200000)
SpellFamilyMask1 0x00100000 -- Swipe (Bear)
SpellFamilyMask2 0x08000000 -- Thrash (Bear)

File: src/server/scripts/Spells/spell_druid.cpp [hunk 2]
```diff
@@ -1510,6 +1515,38 @@ class spell_dru_wild_growth : public SpellScriptLoader
...
+                spellInfo->Id == SPELL_DRUID_MAUL || spellInfo->Id == SPELL_DRUID_BASE_MOONFIRE)
+            {
+                Unit* owner = GetUnitOwner();
+
+                float chance = aurEff->GetAmount();
+                if (roll_chance_f(chance))
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_druid.cpp:1538]: Custom chance should either be stored in spell_proc table (only if not affected by mods, this spell is so use the other method) or rolled in DoCheckProc hook

File: src/server/scripts/Spells/spell_druid.cpp (hunk 1 above)
Comment (matanshukry) [reply src/server/scripts/Spells/spell_druid.cpp:1532]: this spell has proc flags set on it and a server side area dummy, it looked like the perfect candidate for a script rather than spell_proc.

how do you know when a spell should be done using the spell_proc table vs checking it on script?

Comment (Shauren) [reply src/server/scripts/Spells/spell_druid.cpp:1532]: The answer is always. If it can  be done with db, it should be done with db

File: src/server/scripts/Spells/spell_druid.cpp [hunk 3]
```diff
@@ -1510,6 +1511,36 @@ class spell_dru_wild_growth : public SpellScriptLoader
...
+
+    void HandleProc(AuraEffect* aurEff, ProcEventInfo& procInfo)
+    {
+        Unit* owner = GetUnitOwner();
+        owner->CastSpell(owner, SPELL_DRUID_GORE_PROC);
+    }
+
+    void Register() override
+    {
+        DoCheckProc += AuraCheckProcFn(spell_dru_gore::CheckProc);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_druid.cpp:1539]: My bad, I forgot `DoCheckEffectProc`, it seems more fitting

File: sql/updates/world/master/2021_02_17_00_world_druid_gore.sql [hunk 4]
```diff
@@ -0,0 +1,9 @@
+-- Attach druid's gore spell script
+DELETE FROM `spell_script_names` WHERE `ScriptName` = 'spell_dru_gore';
+INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
+(210706, 'spell_dru_gore');
+
+-- Override Gore spell proc flags
+DELETE FROM `spell_proc` WHERE `SpellId` = 210706;
+INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `SpellFamilyMask3`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance` , `Cooldown`, `Charges`) VALUES
+(210706, 65, 7, 0x00200800, 0x00100000, 0x08000000, 0, 0x00011010, 1, 1, 0x403, 0, 0, 0, 15, 0, 0);
```
Comment (Shauren) [inline sql/updates/world/master/2021_02_17_00_world_druid_gore.sql:9]: Leave 0 in fields you do not want to override (Chance)

File: src/server/scripts/Spells/spell_druid.cpp (hunk 1 above)
Comment (Robingadko) [reply src/server/scripts/Spells/spell_druid.cpp]: > 
> 
> The answer is always. If it can be done with db, it should be done with db

@Shauren, how can you know which part of flag from every spell should be taken to compose the result spell proc flag?
Swipe (Bear)
 flag [0] 0x00000000 [1] 0x00100000 [2] 0x00002000 [3] 0x00000000
Thrash (Bear)
flag [0] 0x00000000 [1] 0x00000000 [2] 0x08402000 [3] 0x00000000

For example, why did you propose SpellFamilyMask1 0x00100000 for Swipe (Bear) and SpellFamilyMask2 0x08000000 for Thrash (Bear) rather than SpellFamilyMask2 0x00002000 for both Swipe (Bear) and Thrash (Bear), or why not SpellFamilyMask2 0x08002000 for Thrash (Bear), and so on. 
Is there some rule for composing proc flags?

File: sql/updates/world/master/2021_02_17_00_world_druid_gore.sql (hunk 4 above)
Comment (matanshukry) [reply sql/updates/world/master/2021_02_17_00_world_druid_gore.sql:9]: https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/SpellMgr.cpp#L1545
SchoolMask is always overriden?

I'll use 0 for the 2 others though.

Comment (Shauren) [reply sql/updates/world/master/2021_02_17_00_world_druid_gore.sql:9]: https://github.com/TrinityCore/TrinityCore/blob/456b5be8e45f5718287a44c1a6b8ba2429051f01/src/server/game/Spells/SpellMgr.cpp#L524

Comment (matanshukry) [reply sql/updates/world/master/2021_02_17_00_world_druid_gore.sql]: For other people reading this:

Any SchoolMask value used in spell_proc will override the default. However, using value of 0 will disable that check which is preferred
