### PR TITLE
Scripts/Spells: fixed Blizzard

### LINKED ISSUE #22367: Blizzard spell - magic does not perform its function
**Description:**

Blizzard spell - magic does not perform its function.

**Current behaviour:**

after sending a spell, nothing will happen

**Expected behaviour:**

after sending the spell to a selected location, a series of ice crystals should be performed
[Blizzard spell](https://www.youtube.com/watch?v=N-A9Eku23hY) - [video](https://www.youtube.com/watch?v=N-A9Eku23hY)

**Steps to reproduce the problem:**

1. [Blizzard spell  ](https://www.wowhead.com/spell=190356/blizzard) 
2. send the charm to the chosen place
3. after sending a spell nothing happens

**Branch(es):**  : master 

**TC rev. hash/commit:** 

TrinityCore rev. 56877d236019 2018-08-25 22:47:35 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2o  27 Mar 2018 (library: OpenSSL 1.0.2o  27 Mar 2018)
Using Boost version: 1.67.0
Using MySQL version: 5.7.21
Using CMake version: 3.11.1

**Operating system:** Windows 10.0.17134

### PR DESCRIPTION
**Pull request by Nyr97**
**Changes proposed:**

-  There is no aura_dummy_periodic that controls the triggering damage, so we handle it on the areatrigger script directly by setting it to 1s.

**Issues addressed:** Closes https://github.com/TrinityCore/TrinityCore/issues/22367.

**Tests performed:** It builds and it was tested in-game.

**Known issues and TODO list:** None.

**Notes**: apparently, Blizzard and other several AoE spells are not supposed to dynamically adjust their periodic based on haste: https://us.forums.blizzard.com/en/wow/t/starfall-damage-doesn%E2%80%99t-scale-with-haste-why/854619

### CODE REVIEW

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -315,6 +320,64 @@ class spell_mage_blazing_barrier : public AuraScript
...
 
+// 190356 - Blizzard
+// 4658 - AreaTrigger Create Properties
+struct areatrigger_mage_blizzard : AreaTriggerAI
+{
+    areatrigger_mage_blizzard(AreaTrigger* areatrigger) : AreaTriggerAI(areatrigger) {}
+
+    void RefreshPeriod()
+    {
+        if (Unit* caster = at->GetCaster())
```
Comment (MaxtorCoder) [inline src/server/scripts/Spells/spell_mage.cpp:331]: Unused

Comment (Nyr97) [reply src/server/scripts/Spells/spell_mage.cpp]: Fixed.

File: src/server/scripts/Spells/spell_mage.cpp [hunk 2]
```diff
@@ -315,6 +320,66 @@ class spell_mage_blazing_barrier : public AuraScript
...
+        _refreshTimer -= Milliseconds(diff);
+
+        while (_refreshTimer <= 0s)
+        {
+            if (Unit* caster = at->GetCaster())
+                caster->CastSpell(at->GetPosition(), SPELL_MAGE_BLIZZARD_DAMAGE);
+
+            RefreshPeriod();
+
+            _refreshTimer += _period;
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_mage.cpp:353]: you can just do `Milliseconds(1000)` here or even better: assign the period to a constant value and then add the constant here, that way you can drop `RefreshPeriod` and `_period` since the period does not change

Comment (Nyr97) [reply src/server/scripts/Spells/spell_mage.cpp]: Done!

File: src/server/scripts/Spells/spell_mage.cpp [hunk 3]
```diff
@@ -315,6 +320,52 @@ class spell_mage_blazing_barrier : public AuraScript
...
+        {
+            if (Unit* caster = at->GetCaster())
+                caster->CastSpell(at->GetPosition(), SPELL_MAGE_BLIZZARD_DAMAGE);
+
+            _refreshTimer += TICK_PERIOD;
+        }
+    }
+
+private:
+    Milliseconds _refreshTimer;
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_mage.cpp:345]: we arent refreshing anything here, suggesting `_tickTimer`

Comment (Nyr97) [reply src/server/scripts/Spells/spell_mage.cpp:345]: Accepted!
