### PR TITLE
Core/Spell Misdirection exploit fix

### LINKED ISSUE #15930: Exploit/Spell, Infinite Misdirection
First of all, this has NOTHING to do  with #12913

Due to this line, in [Misdirection](http://wotlk.openwow.com/spell=34477) script
```cpp
if (GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_DEFAULT)
```
(https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_hunter.cpp#L483)

The ResetRedirectThreat() function is never called if the player use the Misdirection spell and use a mount. 
When the player mount, the aura is removed using AURA_REMOVE_BY_DEFAULT, and the RedirectThreat remains active "forever"

If is a problem in the spellScript or in the AuraRemove method, I have no idea.

hash 94e4bddb903d
branch 3.3.5

### PR DESCRIPTION
**Pull request by Asterc**
Correctly reset the redirected threat of the hunter's spell Misdirection in cases when it has RemoveMode  AURA_REMOVE_BY_DEFAULT

Closes #15930

### CODE REVIEW

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 1]
```diff
@@ -480,7 +480,8 @@ class spell_hun_misdirection : public SpellScriptLoader
 
             void OnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
             {
-                if (GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_DEFAULT)
+                if (GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_DEFAULT ||
+                   (GetTargetApplication()->GetRemoveMode() == AURA_REMOVE_BY_DEFAULT && !GetTarget()->HasAura(SPELL_HUNTER_MISDIRECTION_PROC)))
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_hunter.cpp]: "GetTargetApplication()->GetRemoveMode() == AURA_REMOVE_BY_DEFAULT" part is unneeded, it's already implicit by the previous "GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_DEFAULT" check and the || operator

Comment (Asterc) [inline src/server/scripts/Spells/spell_hunter.cpp]: Updated, thanks ^^

**Comment by jackpoz** [comment]
was the updated version tested ingame ? can I merge it ?

**Comment by Asterc** [comment]
Works for me, but i would like someone else to confirm too

**Comment by Keader** [comment]
Work for me.
After correction can no longer leave the effect "infinite".

**Comment by velinath** [comment]
Just rebuilt and tested; I was unable to reproduce the reported bug using this PR.

**Comment by jackpoz** [comment]
thank you for the fix
