### PR TITLE
Script/ZulGurub: fix the RP texts triggered when players reach certain areas

### LINKED ISSUE #17572: Missing emote message when entering Zul'Gurub
**Description**: when you enter Zul'Gurub, the message "Your callous disregard for the sovereign might of the Gurubashi Empire has been noted. The inhabitants of Zul'Gurub have been alerted to your presence." should appear in chat as if it was an emote.

I'm not sure if it happened every time you enter the raid, or only when the bind is generated (ie, the first time you enter the raid each week).

Sources: [this](http://www.wowhead.com/zone=1977/zulgurub#comments:id=1140206), [this](http://imgur.com/a/VDFgm) and [this](https://www.google.com/search?q=Your+callous+disregard+for+the+sovereign+might+of+the+Gurubashi+Empire+has+been+noted.+The+inhabitants+of+Zul%E2%80%99Gurub+has+been+alerted+to+your+presence.).

**Branch(es)**: 3.3.5

**TC hash/commit**:   baf54cf

**TDB version**:  335.61

### PR DESCRIPTION
**Pull request by Wyrserth**
**Changes proposed:**

Implement the emotes sent when a player first steps inside certain areatriggers, and save their status in the DB so they can only be triggered once for every raid reset, persisting across server restarts/grid unloads.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #17572

**Tests performed:** it works.

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp [hunk 1]
```diff
@@ -122,16 +133,73 @@ class instance_zulgurub : public InstanceMapScript
...
+                        _hakkarIntro3 = value;
+                        break;
+                }
+                if (value == DONE)
+                    SaveToDB();
+            }
+
+            void WriteSaveDataMore(std::ostringstream& oss) override
+            {
+                oss << "S " << (uint32)_hakkarIntro1 << ' ' << (uint32)_hakkarIntro2 << ' ' << (uint32)_hakkarIntro3;
```
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp]: we usually prefer
```cpp
uint32(someVariable)
```
syntax over
```cpp
(uint32)someVariable
```
just because we don't like any C-style cast.
Could you please change this line :) ?

Comment (Wyrserth) [reply src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp]: Done, thanks!

File: src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp [hunk 2]
```diff
@@ -122,16 +133,73 @@ class instance_zulgurub : public InstanceMapScript
...
+                        _hakkarIntro3 = value;
+                        break;
+                }
+                if (value == DONE)
+                    SaveToDB();
+            }
+
+            void WriteSaveDataMore(std::ostringstream& oss) override
+            {
+                oss << "S " << uint32(_hakkarIntro1) << ' ' << uint32(_hakkarIntro2) << ' ' << uint32(_hakkarIntro3);
```
Comment (Keader) [inline src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp]: i dont get why this 'S' is needed

Comment (Wyrserth) [reply src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp]: Copied that from Zul'Aman script, I think it makes sense to make sure the data is what you expect it to be.

Comment (Keader) [reply src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp]: it realy not make any difference, you're justing saving a useless information xD

**Comment by Keader** [comment]
_Question_
Is correct that all triggers scripted in this PR only occour once, EVEN if server restart?
Normally, after a soft reset (after instance take more then 15 min without players inside), blizzard normally do AreaTriggersEvents again, if boss is not defeated.
**If it should happens again after server restart** of soft reset, you can just change area trigger AI, for OnlyOnceAreaTrigger (or some name like that) and can remove all those things about save AreaTrigger state, and check if boss is alive inside script.
**If should happens first time**, ignore all comment above xD

PS: Just for reference, if you need OnlyOnceAreaTrigger: 

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp#L1030

**Comment by Wyrserth** [comment]
I honestly don't know if it's actually once per reset or raid reset, assumed it was the latter, and it's probably impossible to find good info now, But it does make more sense for it to be each raid reset. I'll change it, thanks!

File: src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp [hunk 3]
```diff
@@ -23,16 +23,19 @@ Category: Zul'Gurub
 */
 
 #include "ScriptMgr.h"
+#include "DBCStructure.h"
```
Comment (Keader) [inline src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp]: why it's needed?

Comment (Keader) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp]: Should not be ObjectAccessor.h?

Comment (Wyrserth) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp]: DBCStructure.h is needed for AreaTriggerEntry usage, other scripts don't use it so they don't need the implementation. All the common headers I find are totally unrelated to this script (like SpellInfo.h) so I think including it directly is the best way.

Or I could split the script into three separate scripts and do away with the AreaTriggerEntry argument, but that'd be useless code duplication, wouldn't it?

Comment (Keader) [reply src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp]: yeah, no problem :)

**Comment by ccrs** [comment]
Dont merge this, I have a cleanup almost done

**Comment by ccrs** [comment]
Merge after my commit, I mean

**Comment by jackpoz** [comment]
> Merge after my commit, I mean

please could you fix the merge conflicts in this PR then after your clean up commit (that will most likely be the cause of the merge conflicts) ?

**Comment by ccrs** [comment]
@Wyrserth will do that faster probably, but if he doesnt want to, I can do it soon...ish

**Comment by Wyrserth** [comment]
Sure thing, working on it now. Thanks for your work ccrs!

**Comment by ccrs** [comment]
btw, offtopic, @Wyrserth connect to IRC

**Comment by Wyrserth** [comment]
Done, tested and works. Had to rebuild without pch because I didn't want to get stuck in pch hell for the third time.
