### PR TITLE
Scripts/Spells: fixed Infusion of Light

### LINKED ISSUE #19693: Core/Script Passive ability Infusion of Light.
**Description:**

The passive ''Infusion of Light'' that it is unblocked in the level 35 of the specialization ''Holly'' it should be activated when I throw ''Holy Shock'' and has an effect critical, but not alone it is activated when ''Holy Shock'' comes out critical, if not that even without being critical the effect ''Holy Shock'' it is activated,besides also activated when they are thrown ''Flash of Light'' or ''Holy Light''.

**Current behaviour:**

The passive ''Infusion of Light'' without having effect critical or when they are thrown ''Flash of Light'' or ''Holy Light'', and they begin again the 14 sec of the passive effect. 

**Expected behaviour:**

The passive ''Infusion of Light'' has to be activated when ''Holy Shock'' have critical effect reducing the cast time of your next ''Holi Light'' by 1.5sec or increase the healing of your next ''Flash of Light'' by 51%.

**Steps to reproduce the problem:**

1. created a human paladin
2. ascended until the level 35
3. cast ''Holy Shock''
4. cast ''Flash of Light''
5. cast ''Holy Light''

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=53576/infusion-of-light

### PR DESCRIPTION
**Pull request by Nyr97**
**Changes proposed:**

-  Infusion of Light will only be triggered from Holy Shock's critical strikes (either healing or damage).
-  Infusion of Light will energize the caster if it's consumed by Holy Light.

**Issues addressed:** Closes #19693.

**Tests performed:** It builds and it works in-game.

**Known issues and TODO list:** None.

### CODE REVIEW

File: sql/updates/world/master/9999_99_99_99_world.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+DELETE FROM `spell_proc` WHERE `SpellId`=53576;
+INSERT INTO `spell_proc` (`SpellId`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `SpellFamilyMask3`, `ProcFlags`, `SpellTypeMask`, `SpellPhaseMask`, `HitMask`, `AttributesMask`, `DisableEffectsMask`, `ProcsPerMinute`, `Chance`, `Cooldown`, `Charges`) VALUES 
+(53576, 0, 10, 2097152, 65536, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0);
+
+DELETE FROM `spell_script_names` WHERE `spell_id`=54149 AND `ScriptName`='spell_pal_infusion_of_light';
+INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES 
+(54149, 'spell_pal_infusion_of_light');
+
```
Comment (Aokromes) [inline sql/updates/world/master/9999_99_99_99_world.sql:8]: missing -- and excesive row.
