### PR TITLE
Core/Instance: If a boss kills itself, still save the group to the instance

### LINKED ISSUE #16971: Boss dead by self inflicted damage don't trigger instance bind
**Description**:  If a boss dies from self inflicted damage, he won't trigger instance binding to the players

**Current behaviour**: Kill Baron Geddon, at 2%health he will self kill, no instance binding is triggered

**Expected behaviour**: Killing him should bind players to the instance.

**Steps to reproduce the problem**:

1. .go crea id 12056
2.  Kill Baron Geddon
3. Note that you won't be saved to instance

**Branch(es)**: 335

**TC hash/commit**: e38e1c0c549c

**TDB version**: 335.61

**Operating system**: Windows

**Linking model**: dynamic

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### PR DESCRIPTION
**Pull request by myran2**
**Changes proposed**:
- Before this change, if an instance boss kills itself, the instance group will not be saved to the instance.
- This change fixes this issue by adding a check to Unit::Kill

**Target branch(es)**: 335/6x

**Issues addressed**: Fixes #16971

**Tests performed**: (Does it build, tested in-game, etc)
Builds, Tested by sirikfoll

### CODE REVIEW

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -13772,20 +13772,28 @@ void Unit::Kill(Unit* victim, bool durabilityLoss)
...
+            if (instanceMap->IsDungeon() && (creditedPlayer || this == victim))
             {
                 if (instanceMap->IsRaidOrHeroicDungeon())
                 {
                     if (creature->GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_INSTANCE_BIND)
-                        ((InstanceMap*)instanceMap)->PermBindAllPlayers(creditedPlayer);
+                    {
+                        // if the boss killed itself we still need to bind players to the instance
+                        if (!creditedPlayer)
+                            creditedPlayer = ((InstanceMap*)instanceMap)->GetPlayers().getFirst()->GetSource();
```
Comment (Shauren) [inline src/server/game/Entities/Unit/Unit.cpp]: What if the instance becomes empty? Creatures can still update in grid if they are set to active
