### PR TITLE
Core/Spells: Scrolls should not be consumed, when they fail to apply

### LINKED ISSUE #18429: [335] Scrolls Are Consumed When They Fail To Apply
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**

Stat scrolls are consumed from inventory when they fail to apply to the target.

**Current behaviour:**

See description.

**Expected behaviour:**

Scrolls that fail to apply should remain in inventory.

**Steps to reproduce the problem:**

Tested with a Hunter

1. Apply a [Scroll of Agility II](http://www.wowhead.com/item=1477/scroll-of-agility-ii) to your pet
2. Attempt to apply a [Scroll of Stamina](http://www.wowhead.com/item=1180/scroll-of-stamina) while previous buff is active
3. You will receive an error: *A more powerful spell is active*
4. The scroll will be consumed from your inventory anyway

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2db9269ec1c06b5fccc45dc0a5b4f714f9b48804

**TDB version:**  TDB_full_world_335.61_2016_04_11.sql + updates

**Operating system:**  WinXP / Win 7

**Notes:**

I searched both the closed / open issues and did not see anything referencing this bug so I did not pull and compile a new core.

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by Faq**
**Changes proposed:**

- add check if there is more powerful aura applied and only then delete item if there is none.
After chenges with "A more powerful spell is already active" item is not consumed/deleted.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)
Closes #18429

**Tests performed:**
Tested in these cases:
A)
1. With 80lvl Mage.
2. .add item 17020 10 
3. .learn 43002 [Arcane Brilliance Rank3](https://woehead.way-of-elendil.fr/?spell=43002#spell-group-stack) & apply on self
4. .additem 2290 13  [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290) and use it
5. **Result:** There will be error "A more powerful spell is already active", item wont be consumed

B) 
1. Disable aura [Arcane Brilliance Rank3](https://woehead.way-of-elendil.fr/?spell=43002#spell-group-stack)
2. use [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290)
3. **Result:** Aura will be applied and item consumed

C) 
1. while active aura from [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290)
2. use again [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290)
3. **Result:** Aura timer renewed, item consumed

D) 
1. get a char with pet
2. .additem 1477 6 and apply a [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477) to you and pet
3. .additem 1180 6 and attempt to apply a [Scroll of Stamina](https://woehead.way-of-elendil.fr/?item=1180) while previous buff is active on self and then pet
4. **Result:** There will be error "A more powerful spell is already active" for both, item wont be consumed

E)
1. Before buff timer runs out on pet and you, reapply [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477)
2.  **Result:** Aura timer renewed for both, items consumed

F) 
1. While aura from [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477) active, use [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290)
2. **Result:** [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290) aura replaces [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477) 

G)
1. .additem 11566 3 [Crystal Charge](https://woehead.way-of-elendil.fr/?item=11566)
2. use item on target
3. **Result:** After items explosion effect, from 3 charges 1 consumed, 2 left.

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by illfated** [comment]
Looks promising. Just a minor question about naming:
Would it be possible to change the function name `foundPowerfulAura` to `foundMorePowerfulAura` instead?
Or would that be a step too far, that it would clash with existing naming conventions?

(I just got this idea now when reading your code, based on the description "A more powerful spell is already active".)

**Comment by Jinnaix** [comment]
Nice, you did it! This one really bothered me a lot.

**Comment by Shauren** [comment]
Such checks should not be present in `Spell::TakeCastItem()` but somewhere in `::Check*` functions

**Comment by Faq** [comment]
Any specific `::Check* `? So in the end that code wont be moved again somewhere else.

**Comment by illfated** [comment]
Good question. I am still trying to find out which one of them is more appropriate:
- `SpellCastResult Spell::CheckCasterAuras(uint32* param1) const`
- `SpellCastResult Spell::CheckItems(uint32* param1 /*= nullptr*/, uint32* param2 /*= nullptr*/) const`
- `SpellCastResult Spell::CheckCast(bool strict, uint32* param1 /*= nullptr*/, uint32* param2 /*= nullptr*/)`

**Comment by Shauren** [comment]
I think checking it near the other code that fails with `SPELL_FAILED_AURA_BOUNCED` should be good (its a DR check there)

**Comment by Faq** [comment]
ok, lets say move that check code to this line https://github.com/TrinityCore/TrinityCore/blob/b69c5560dc3d8e8f2b957773d9d91bf5b6d21e89/src/server/game/Spells/Spell.cpp#L3311

But then I fail to pass result to https://github.com/TrinityCore/TrinityCore/blob/b69c5560dc3d8e8f2b957773d9d91bf5b6d21e89/src/server/game/Spells/Spell.cpp#L4636 as `SpellCastResult` always is `SPELL_FAILED_NOT_READY` where `DestroyItemCount` gets executed.

Any help would be good.

**Comment by Shauren** [comment]
What do you mean? If write
```
    cleanupSpell(SPELL_FAILED_AURA_BOUNCED);
    return;
```
under your check, you will never reach `TakeCastItem()` so it won't be deleted

File: src/server/game/Spells/Spell.cpp [hunk 1]
```diff
@@ -3240,29 +3240,29 @@ void Spell::_cast(bool skipCheck)
...
+    };
 
-        uint32 param1 = 0, param2 = 0;
-        SpellCastResult castResult = CheckCast(false, &param1, &param2);
-        if (castResult != SPELL_CAST_OK)
-        {
-            cleanupSpell(castResult, &param1, &param2);
-            return;
-        }
+    uint32 param1 = 0, param2 = 0;
```
Comment (Shauren) [inline src/server/game/Spells/Spell.cpp:3255]: why did you move this part outside of skipCheck? That is the entire point of that arg

**Comment by Faq** [comment]
Retested.
Looks like appveyor got broken not by me.

**Comment by illfated** [comment]
(appveyor error list alignment adjusted for readability)
```
      AES.obj : error LNK2019: unresolved external symbol EVP_CIPHER_CTX_reset referenced in function "public: __cdecl Trinity::Crypto::AES::AES(bool)" (??0AES@Crypto@Trinity@@QEAA@_N@Z)           [C:\projects\trinitycore\build\src\common\common.vcxproj]
     ARC4.obj : error LNK2001: unresolved external symbol EVP_CIPHER_CTX_reset                                                                                                                       [C:\projects\trinitycore\build\src\common\common.vcxproj]
BigNumber.obj : error LNK2019: unresolved external symbol BN_is_zero           referenced in function "public: bool __cdecl BigNumber::IsZero(void)const " (?IsZero@BigNumber@@QEBA_NXZ)             [C:\projects\trinitycore\build\src\common\common.vcxproj]
BigNumber.obj : error LNK2019: unresolved external symbol BN_is_negative       referenced in function "public: bool __cdecl BigNumber::IsNegative(void)const " (?IsNegative@BigNumber@@QEBA_NXZ)     [C:\projects\trinitycore\build\src\common\common.vcxproj]
 HMACSHA1.obj : error LNK2019: unresolved external symbol HMAC_CTX_new         referenced in function "public: __cdecl HmacHash::HmacHash(unsigned int,unsigned char *)" (??0HmacHash@@QEAA@IPEAE@Z) [C:\projects\trinitycore\build\src\common\common.vcxproj]
 HMACSHA1.obj : error LNK2019: unresolved external symbol HMAC_CTX_free        referenced in function "public: __cdecl HmacHash::~HmacHash(void)" (??1HmacHash@@QEAA@XZ)                             [C:\projects\trinitycore\build\src\common\common.vcxproj]

C:\projects\trinitycore\build\bin\RelWithDebInfo\common.dll : fatal error LNK1120: 5 unresolved externals [C:\projects\trinitycore\build\src\common\common.vcxproj]
```

**Comment by Faq** [comment]
btw with this PR getting also https://gist.github.com/Faq/2b12b8ddcdf3b39b81cb282b01d9fa96

**Comment by Shauren** [comment]
I removed case "D", player should be able to intentionally change which stat type he has

**Comment by Faq** [comment]
In **D case** now, result:
"A more powerful spell is already active", [Scroll of Stamina](https://woehead.way-of-elendil.fr/?item=1180) **item lost and buff not applied**, just renewed [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477)

For other test cases result is the same.

**Comment by Shauren** [comment]
Ok thats not good, I expected buff to be applied

**Comment by Shauren** [comment]
Retesting time

**Comment by Faq** [comment]
D) 
1. get a char with pet
2. .additem 1477 6 and apply a [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477) to you and pet
3. .additem 1180 6 and attempt to apply a [Scroll of Stamina](https://woehead.way-of-elendil.fr/?item=1180) while previous buff is active on self and then pet
4. **Result:**"A more powerful spell is already active", item not consumed and aura of [Scroll of Stamina](https://woehead.way-of-elendil.fr/?item=1180) not applied.

H)
while active buff of [Scroll of Intellect II](https://woehead.way-of-elendil.fr/?item=2290), use  [Scroll of Agility II](https://woehead.way-of-elendil.fr/?item=1477)
**Result:**"A more powerful spell is already active", item will be consumed, but buff not applied.

For other test cases result didn't change.

**Comment by Shauren** [comment]
H) works for me, it removes int and adds agility

**Comment by Faq** [comment]
Sorry, looks like some of your changes were not reverted, so in the end i got merge of last 2 commits.
Retested everything, looks, good, thank you.
