### PR TITLE
Game/Maps: Instance handling bug-fix follow-up

### LINKED ISSUE #16150: [3.3.5] Entering instance resets you to homebind in specific circumstances
3.3.5, b6ed3d3fc2b8447059ff0aa0e5b6de36947fd006

Bug with new instance handling. Repro:
1. Zone into instance while not partied
2. Get invited by someone else while in the instance
3. Your party leader zones into the same instance as you
4. You leave and re-enter. This should send you to the party's instance. Instead, it sends you to your homebind.

### PR DESCRIPTION
**Pull request by Treeston**
Game/Maps: Instance handling follow-up:
- Fix a bug where a player could maintain a conflicting non-perm solo bind if they were in the instance when invited to group. Closes #16150.
- If a group is created while the leader is in an instance that nobody is bound to, the group will take over the instance and bind to it. This stops the homebind timer when reforming group after disconnects and the like.

### CODE REVIEW

File: src/server/game/Maps/MapInstanced.cpp [hunk 1]
```diff
@@ -163,7 +163,11 @@ Map* MapInstanced::CreateInstanceForPlayer(const uint32 mapId, Player* player, u
             {
                 groupBind = group->GetBoundInstance(this);
                 if (groupBind)
+                {
+                    // solo saves should be reset when entering a group's instance
+                    player->UnbindInstance(GetId(), player->GetDifficulty(IsRaid()));
```
Comment (Shauren) [inline src/server/game/Maps/MapInstanced.cpp]: Where is MapInstanced::CreateInstanceForPlayer called from? UnbindInstance is not threadsafe

File: src/server/game/Groups/Group.h [hunk 2]
```diff
@@ -194,6 +194,7 @@ class Group
         bool   AddMember(Player* player);
         bool   RemoveMember(ObjectGuid guid, const RemoveMethod &method = GROUP_REMOVEMETHOD_DEFAULT, ObjectGuid kicker = ObjectGuid::Empty, const char* reason = NULL);
         void   ChangeLeader(ObjectGuid guid);
+ static void   ConvertLeaderInstancesToGroup(Player* player, Group* group, bool switchLeader);
```
Comment (Shauren) [inline src/server/game/Groups/Group.h]: u wot

Comment (ccrs) [inline src/server/game/Groups/Group.h]: tld u m8
