### PR TITLE
Core/Spells: Fixed multiple druid's spells

### LINKED ISSUE #17410: [6.x][Spell] Prowl
**Description**:

**Current behaviour**: 
Prowl (http://www.wowhead.com/spell=5215/prowl) stays active, after jumping out of Cat Form

**Expected behaviour**: 
You're supposed to drop out of Prowl, when leaving Cat Form

**Steps to reproduce the problem**:
1. Play as a Druid
2. Enter Cat Form
3. Use and stay in Prowl
4. Exit Cat Form

**Branch(es)**: 
6.x

**TC hash/commit**:  
5fdeb0667532

**TDB version**:  
6.04

**Operating system**:  
Debian 8

prowl

### LINKED ISSUE #19741: Core/Script Spell Dash has issues.
**Description:**

Spell "Dash" not given the speed bonus and it´s not activating the "cat form" (ID:768)

**Current behaviour:**

In level 8 learn the spell "Dash". Thath consist on activate the "cat form" (ID:768) and increases movement speed by 70% during next 15 sec, while in "cat form". Actually it´s not changing to "cat form" and it´s not giving the speed bonus. If you are in "cat form" and activate the spell, then if recibe the speed bonus

**Expected behaviour:**

change to "cat form" and increases movement speed by 70% during next 15 sec.

**Steps to reproduce the problem:**

1. Create a player/Druid
2. Go up it until level 8
3. activate the spell "Dash"

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=1850/dash

### LINKED ISSUE #26207: Travelform (ground) useable
**Description:**

Travelform is bind to riding skill and only useable with learned Riding skill.

**Expected behaviour:**

If you reach lvl 10 and get the Travelform spell, you can use the Travelform without learning the Riding skill.
The Travelform should have 40% and if you reach lvl 20 you get 100% speed.
For both you dont need to learn a Riding skill, the Druid only need Riding skill for Flying and for using Mounts.

**Steps to reproduce the problem:**

1. create a Druid
2. reach lvl 10
3. try to use Travelform

**Branch(es):**

master

**TC rev. hash/commit:** 

898f97781c7f3cc5d40b4f9947571058b7ff7a75

**Operating system:** 

Win10

### LINKED ISSUE #26208: Aquatic Form useable
**Description:**

Aquatic Form can be used since you dont learn [Aquatic Form] Passive spell (276012) at lvl 17

**Expected behaviour:**

You cant use Aquatic Form till you reach lvl 17 and get the Passive Spell.

**Steps to reproduce the problem:**

1. create a Druid
2. level to 10 
3. use Travelform and jump into water

**Branch(es):**

master

**TC rev. hash/commit:** 

898f97781c7f3cc5d40b4f9947571058b7ff7a75

**Operating system:** 

Win10

### LINKED ISSUE #26219: Spell/Druid Tiger Dash missing shapeshift
**Description:**

Tiger Dash dont shapeshift you into Catform.

**Expected behaviour:**

Tiger Dash should shapeshift you into the Catform

**Steps to reproduce the problem:**

1. create a Druid
2. skill lvl 25 Talent "Tiger Dash"
3. use the spell

**Branch(es):**

master

**TC rev. hash/commit:** 

0aa3a0b0b9430d2b92e6a69e6c3bc205bfebfa57

**Operating system:** 

Win10

### LINKED ISSUE #26221: Spell/Druid Tooth and Claw missing consume
**Description:**

If you have stacks of Tooth and Claw you should consume them with using Maul.

**Expected behaviour:**

If you use Maul (6807) while you have a proc of Tooth and Claw, Maul should consume one of its stacks.

**Steps to reproduce the problem:**

1. create a Druid
2. skill lvl 50 Talent Tooth and Claw
3. autoattack until Tooth and Claw procs and try to consume them with Mangle

**Branch(es):**

master

**TC rev. hash/commit:** 

0aa3a0b0b9430d2b92e6a69e6c3bc205bfebfa57

**Operating system:** 

Win10

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Tooth And Claw proc correctly (was incorrect attribute)
- Tiger Dash will now transform to cat
- Travelform doesn't require learning riding skill
- Aquatic Form only useable if player has the spell (passive at level 17)
- Doesn't allow stag form inside water
- Birstlin Fur will now generate rage correctly
- Remove prowl aura when cat form is removed

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26221
Closes #26219
Closes #26208
Closes #26207
Closes #17410
Closes #19741

**Tests performed:**

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks quite good to me.

File: src/server/scripts/Spells/spell_druid.cpp [hunk 1]
```diff
@@ -1624,13 +1624,13 @@ class spell_dru_travel_form : public SpellScriptLoader
...
             return SPELL_DRUID_FORM_AQUATIC;
 
         if (!player->IsInCombat() && player->GetSkillValue(SKILL_RIDING) >= 225 && CheckLocationForForm(player, difficulty, requiresOutdoor, SPELL_DRUID_FORM_FLIGHT) == SPELL_CAST_OK) // Flight form
             return player->GetSkillValue(SKILL_RIDING) >= 300 ? SPELL_DRUID_FORM_SWIFT_FLIGHT : SPELL_DRUID_FORM_FLIGHT;
 
-        if (CheckLocationForForm(player, difficulty, requiresOutdoor, SPELL_DRUID_FORM_STAG) == SPELL_CAST_OK) // Stag form
+        if (!player->IsInWater() && CheckLocationForForm(player, difficulty, requiresOutdoor, SPELL_DRUID_FORM_STAG) == SPELL_CAST_OK) // Stag form
             return SPELL_DRUID_FORM_STAG;
 
         return 0;
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_druid.cpp:1636]: Shouldn't we actually also `PreventDefaultAction()` in `OnRemove` when we're returning 0 here or what is happening with 0 as triggerSpellID? (imagine a druid lvl 10 in water)  
Ref: https://www.youtube.com/watch?v=jMUE6cWcDvU

Comment (mdX7) [reply src/server/scripts/Spells/spell_druid.cpp:1636]: fyi above posted bug only disappears when reapplying travelform after aquatic form is learned
Ref: https://www.youtube.com/watch?v=uY143NdOVWY

Comment (matanshukry) [reply src/server/scripts/Spells/spell_druid.cpp:1636]: > Shouldn't we actually also PreventDefaultAction() in OnRemove when we're returning 0 here or what is happening with 0 as triggerSpellID? (imagine a druid lvl 10 in water)

This is a static method, a "utility" one, and can't actually perform `PreventDefaultAction()` in it.
However it will be called if the current spell id is also 0 (hence no form).

 > If we'd want to be 100% blizzlike we'd also have to implement this bug (enter water, use travelform, run out of water and use mount):
Yes I remember that funny bit xd I'm assuming that bug will be fixed at some point and it doesn't really give anything, so might as well make it work on tc now.
That is my opinion though.

File: src/server/scripts/Spells/spell_druid.cpp [hunk 2]
```diff
@@ -1664,10 +1686,9 @@ class spell_dru_travel_form_dummy : public SpellScriptLoader
             if (!player)
                 return SPELL_FAILED_CUSTOM_ERROR;
 
-            if (player->GetSkillValue(SKILL_RIDING) < 75)
-                return SPELL_FAILED_APPRENTICE_RIDING_REQUIREMENT;
+            uint32 spellId = (player->HasSkill(SPELL_DRUID_FORM_AQUATIC) && player->IsInWater()) ? SPELL_DRUID_FORM_AQUATIC : SPELL_DRUID_FORM_STAG;
```
Comment (ZaDarkSide) [inline src/server/scripts/Spells/spell_druid.cpp:1689]: `HasSkill(SPELL_DRUID_FORM_AQUATIC)` should be `HasSpell(SPELL_DRUID_FORM_AQUATIC)` ?
