### PR TITLE
Core/Spells: Fix warlock chaos bolt damage

### LINKED ISSUE #19667: Core/Script Warlock's spell Chaos Bolt has an issue.
**Description:**

The spell "Chaos Bolt" of the class "Warlock" has an issue.

**Current behaviour:**

When you cast "Chaos Bolt" on a target (any target) this hit the target and inflict damage, but is not a critical hit.

**Expected behaviour:**

When you cast "Chaos Bolt" on a target(any target) this hit the target with a critical hit.

**Steps to reproduce the problem:**

1. Create a character with the class "Warlock"
2. Select the specialization "Destruction" in level 10
3. Reach the level 12, learn "Chaos Bolt" and cast "Chaos Bolt" on any taget.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=116858/chaos-bolt

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Fix warlock Chaos bolt

**Issues addressed:**

Closes #19667

**Tests performed:**

Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_warlock.cpp [hunk 1]
```diff
@@ -109,6 +109,27 @@ class spell_warl_banish : public SpellScriptLoader
...
+    PrepareSpellScript(spell_warl_chaos_bolt);
+
+    bool Load() override
+    {
+        return GetCaster()->GetTypeId() == TYPEID_PLAYER;
+    }
+
+    void HandleDummy(SpellEffIndex /*effIndex*/)
+    {
+        SetHitDamage((GetHitDamage() * 2) + CalculatePct(GetHitDamage(), GetCaster()->ToPlayer()->m_activePlayerData->SpellCritPercentage));
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_warlock.cpp:124]: `damage * 2` is wrong - thats only a tooltip value (`dealing a critical strike for ${2*$s1} Chaos damage`), it includes the crit multiplier (but base damage shouldn't)

Missing `OnCalcCritChance` hook to always force critical strike

**Review by Shauren — CHANGES_REQUESTED** [review]

File: src/server/scripts/Spells/spell_warlock.cpp (hunk 1 above)
Comment (aquadeus) [reply src/server/scripts/Spells/spell_warlock.cpp:124]: oh i forgot about the critchance, because blizzard its changing descriptions always xd
