### PR TITLE
Core/Unit: Fix for Pets/Guardians not engaging combat if master is attacked

### LINKED ISSUE #24340: Core/AI: Creature Minions/Pets dont react to masters combat state
**Description:**

As it seems right now, minions & pets of creatures only get into combat with you if you attack them directly or if you are close enough for triggering their own aggro range. They dont react at all to their masters combat state. I am not sure if "masters combat state" is the correct term, but i think people will understand what i want to describe here.

**Current behaviour:**

Minions/Pets of creatures dont react to their masters combat state.

**Expected behaviour:**

Minions/Pets of creatures should react to their masters combat state.

**Steps to reproduce the problem:**

.go xyz -7481.180664 -4289.866699 10.449110 1 3.021416
Stay away far enough to not trigger aggro range
.damage 1 on Wastewander Shadow Mage

He moves to you and starts casting or directly starts casting if you are close enough. In each case, his Voidwalker wont react to you as long as you stay out of the Voidwalkers personal aggro range.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6259763469826526fc26b07ff20885d5b04a791f

**Operating system:** 

Windows 10

### PR DESCRIPTION
**Pull request by Jinnaix**
**Changes proposed:**
Long Story short:
1) a unit is always a player or a creature
2) i dont know anything about c++
3) big thanks to @Treeston for a wonderful c++ and trinitycore lesson and sadly also some thanks to @MaxtorCoder for being part of it

-  Fixes Pets/Guardians not getting into combat when their master is attacked

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** 
Closes #24340

**Tests performed:** (Does it build, tested in-game, etc.)
- [x] Builds
- [x] tested ingame

**Known issues and TODO list:** (add/remove lines as needed)

There shouldnt be any side effects

### CODE REVIEW

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -687,21 +687,18 @@ bool Unit::HasBreakableByDamageCrowdControlAura(Unit* excludeCasterChannel) cons
...
-
-        if (victim->ToPlayer()->GetCommandStatus(CHEAT_GOD))
-            return 0;
+        for (Unit* controlled : victim->m_Controlled)
+            if (Creature* cControlled = controlled->ToCreature())
+                if (CreatureAI* controlledAI = cControlled->AI())
+                    controlledAI->OwnerAttackedBy(attacker);
     }
 
+    if (Player* player = victim->ToPlayer(); player && player->GetCommandStatus(CHEAT_GOD))
```
Comment (Carbenium) [inline src/server/game/Entities/Unit/Unit.cpp:699]: Ugh, that's an abomination.

Let's rather do something along
```suggestion
    Player* player = victim->ToPlayer();
    if (player && player->GetCommandStatus(CHEAT_GOD))
```
