### PR TITLE
Core/Spells: implemented Wind Rush Totem

### LINKED ISSUE #19628: Core/Script The talent Wind Rush Totem doesn´t work.
**Description:**

The talent Wind Rush Totem (ID:192077) given to Chaman in all spec´s at lv.30 has an issue

Wind Rush Totem: Summons a totem at the target location for 15 sec., continually granting all allies who pass within 10 yards 60% increased movement speed for 5 sec.

**Current behaviour:**

The talent doesn´t work, when you summon the totem it appear but it doesn´t increase the movement speed of allies

**Expected behaviour:**

when you summon the totem it should increase 60% the movement speed of all allies who pass within 10 yards

**Steps to reproduce the problem:**

1. Create a Chaman character
2. Reach lv.10 an choose the Restoration Spec
3. Reach lv.30 and choose the talent Wind Rush Totem
4. Use the talent surrounded by allies
5. Repeat all steps in elemental and enhancement spec´s

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=192077/wind-rush-totem

### PR DESCRIPTION
**Pull request by mdX7**
**Changes proposed:**

-  implemented windrush totem

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #19628

**Tests performed:**

(Does it build, tested in-game, etc.)
build, tested ingame

**Info**
I used old timer method here, did not want to use overkill EventMap here, if EventMap is wanted i'll change it.

### CODE REVIEW

File: src/server/scripts/Spells/spell_shaman.cpp [hunk 1]
```diff
@@ -1436,6 +1438,45 @@ class spell_sha_windfury : public SpellScriptLoader
     }
 };
 
+// 192078 - Windrush Totem (Spell)
+//  12676 - AreaTriggerId
+struct areatrigger_sha_windrush_totem : AreaTriggerAI
+{
+    static uint32 const REFRESH_TIME = 4500;
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_shaman.cpp:1445]: should this be constexpr ?

Comment (mdX7) [reply src/server/scripts/Spells/spell_shaman.cpp]: sounds good, kinda unused to constexprs yet

Comment (jackpoz) [reply src/server/scripts/Spells/spell_shaman.cpp]: It seems it has to be static constexpr according to CI logs
