### PR TITLE
Scripts/Spells: Hand of Reins - Questsupport for 'Mounting Up'

### LINKED ISSUE #3977: {Quest} Mounting Up
Hello,
I have encountered a problem while questing in "Grizzly Hills" zone. 

How to reproduce the bug: 
1. Get quest from "Squire Percy".
2. Collect "Wild Carrots".
3. Try and use the "Stick" on the "Highland Mustang"s.

What should happen, what happens instead:
You should equip the "Stick", Collect 5 "Wild Carrots" than use them to lure the "Highland Mustangs" and get ticks for every mustang. (notice the quest data) instead, you collect the carrots, equip the stick, and when you try to lure the mustangs, nothing happens. you click on the item ("Stick") and it doesnt lure, or give a tick.

Some links:
http://old.wowhead.com/quest=12414 --> The quest
http://old.wowhead.com/object=189983 --> The object #1 
http://old.wowhead.com/item=37708 --> The object #2
http://old.wowhead.com/npc=26377 --> The NPC #1
http://old.wowhead.com/npc=26472 --> The NPC #2
http://old.wowhead.com/zone=394 --> The Grizzly Hills zone

I'm running Unix on hash: 37abe25 , TDB 43+
Addons: AH bot and WG.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65935-quest-mounting-up?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Lumber-Jack-2**
by @untaught closes #3977

### CODE REVIEW

File: src/server/scripts/Spells/spell_quest.cpp [hunk 1]
```diff
@@ -2422,6 +2422,40 @@ class spell_q10929_fumping : SpellScriptLoader
...
+        spell_q12414_hand_over_reins() : SpellScriptLoader("spell_q12414_hand_over_reins") { }
+        
+        class spell_q12414_hand_over_reins_SpellScript : public SpellScript
+        {
+            PrepareSpellScript(spell_q12414_hand_over_reins_SpellScript);
+            
+            void HandleScript(SpellEffIndex /*effIndex*/)
+            {
+                Unit* caster = GetCaster();
+                if (caster->IsVehicle())
```
Comment (Unholychick) [inline src/server/scripts/Spells/spell_quest.cpp]:
```cpp
Creature* caster = GetCaster()->ToCreature();
GetHitUnit()->ExitVehicle();

if (caster)
    caster->DespawnOrUnsummon();
```
Should yield the same result and also wont crash if caster is player (unlikely)
