### PR TITLE
Core/Misc: Implemented spawn tracking

### LINKED ISSUE #29705: Missing SpawnTrackingIDs
### Description

While working on quest 59949 "Who Lurks in the Pit" Horde I recorded SpawnTrackingIDs for cocoon gameobjects on 3 different characters one in reverse order.

Looking at ```SELECT * FROM `quest_poi` WHERE `QuestID`=59949;``` you will notice QuestObjectiveID 397290 has no SpawnTrackingID. You can see here ```SELECT * FROM `quest_objectives` WHERE `QuestID`=59949;``` that 5 Cocoon gameobjects  are required. 

These IDs are send individually in SMSG_QUEST_POI_UPDATE_RESPONSE as you activate the object and need to be stored in db somehow. These IDs are attached to guids and are different for Alliance. I have listed the 5 horde tracking IDs below. 

Horde
```
1 SpawnTrackingID: 1945109
2 SpawnTrackingID: 1945110
3 SpawnTrackingID: 1945111
4 SpawnTrackingID: 1945112
5 SpawnTrackingID: 1945113
```

Alliance quest 55639: 2 missing atm need to resniff in reverse order.
```
1 SpawnTrackingID: 1864794
2 SpawnTrackingID: 1864795
3 SpawnTrackingID: 1864796
```

### Expected behaviour

Should be in DB

### Steps to reproduce the problem

Read a sniff

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/3e1eec081f717fc9ca102a22b28a99030415c8aa

### Operating system

Windows 10

### Custom changes

None

### PR DESCRIPTION
**Pull request by meji46**
**Changes proposed:**

-  Implemented spawn tracking (system that modifies state UFs and visibility of creatures and gos according to the completion of a quest objetive). Based on the examples found, I've added 3 spawntracking states for the quest objective:
   - None (no quest)
   - Active (active quest objective)
   - Complete (quest objective completed or quest rewarded)

**Issues addressed:**
Closes #29705

**Tests performed:**
Builds, tested in-game, Added example for quest https://www.wowhead.com/quest=55881/purge-the-totems (.quest add 55881)

**Known issues and TODO list:** (add/remove lines as needed)
- Missing implementation for SPELL_ATTR8_ALLOW_TARGETS_HIDDEN_BY_SPAWN_TRACKING (I'll implement this in another PR after checking some cases)

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -19435,7 +19554,7 @@ void Player::_LoadQuestStatusObjectives(PreparedQueryResult result)
 {
 
     ////                                                       0        1       2
-    //QueryResult* result = CharacterDatabase.PQuery("SELECT quest, objective, data WHERE guid = '{}'", GetGUIDLow());
+    //QueryResult* result = CharacterDatabase.PQuery("SELECT quest, objective, data FROM character_queststatus_objectivesWHERE guid = '{}'", GetGUIDLow());
```
Comment (Nyr97) [inline src/server/game/Entities/Player/Player.cpp:19557]: WHERE measing space

**Comment by jackpoz** [comment]
sql/updates/world/master/2024_99_99_98_world.sql needs to be completely recreated. It drops and creates a table and then tries to delete rows from that table just dropped and created.

**Comment by jackpoz** [comment]
How many rows does
```sql
DELETE stqo
FROM `spawn_tracking_quest_objective` stqo
LEFT JOIN `quest_objectives` qo ON stqo.`QuestObjectiveId`=qo.`ID`
WHERE qo.`ID` IS NULL;
```
delete at the end of the sql update ? Are most of the rows excluded already before ?

**Comment by meji46** [comment]
> How many rows does
> 
> ```sql
> DELETE stqo
> FROM `spawn_tracking_quest_objective` stqo
> LEFT JOIN `quest_objectives` qo ON stqo.`QuestObjectiveId`=qo.`ID`
> WHERE qo.`ID` IS NULL;
> ```
> delete at the end of the sql update ? Are most of the rows excluded already before ?
672. Possibly most of these objectives are linked to serverside quests

File: src/server/game/Entities/Creature/Creature.cpp [hunk 2]
```diff
@@ -628,7 +628,7 @@ bool Creature::UpdateEntry(uint32 entry, CreatureData const* data /*= nullptr*/,
 
     ReplaceAllDynamicFlags(UNIT_DYNFLAG_NONE);
 
-    SetUpdateFieldValue(m_values.ModifyValue(&Unit::m_unitData).ModifyValue(&UF::UnitData::StateAnimID), sDB2Manager.GetEmptyAnimStateID());
+    SetUpdateFieldValue(m_values.ModifyValue(&Unit::m_unitData).ModifyValue(&UF::UnitData::StateWorldEffectsQuestObjectiveID), data ? data->spawnTrackingQuestObjectiveId: 0);
```
Comment (mdX7) [inline src/server/game/Entities/Creature/Creature.cpp:631]: add space inbetween `spawnTrackingQuestObjectiveId` and `:`

File: src/server/game/Entities/Object/Updates/ViewerDependentValues.h [hunk 3]
```diff
@@ -196,6 +202,78 @@ class ViewerDependentValue<UF::UnitData::DisplayIDTag>
...
+public:
+    using value_type = UF::UnitData::StateAnimKitIDTag::value_type;
+
+    static value_type GetValue(UF::UnitData const* unitData, Unit const* unit, Player const* receiver)
+    {
+        value_type stateAnimKitId = unitData->StateAnimKitID;
+
+        if (unit->IsCreature())
+            if (SpawnTrackingStateData const* spawnTrackingStateData = unit->GetSpawnTrackingStateDataForPlayer(receiver))
+                stateAnimKitId = spawnTrackingStateData->StateAnimKitId.value_or(0);
```
Comment (mdX7) [inline src/server/game/Entities/Object/Updates/ViewerDependentValues.h:271]: intended to use 0 here instead of default `stateAnimKitId`?

File: src/server/game/Entities/Player/Player.cpp [hunk 4]
```diff
@@ -19463,6 +19582,44 @@ void Player::_LoadQuestStatusObjectives(PreparedQueryResult result)
...
+
+    if (result)
+    {
+        do
+        {
+            Field* fields = result->Fetch();
+
+            uint32 questID = fields[0].GetUInt32();
+            Quest const* quest = sObjectMgr->GetQuestTemplate(questID);
+            auto itr = m_QuestStatus.find(questID);
```
Comment (mdX7) [inline src/server/game/Entities/Player/Player.cpp:19599]: i'd suggest early `continue` if `quest` is null instead of using null for lookup

**Review by mdX7 — COMMENTED** [review]
seems great already. Would be cool to get a command to get info about spawntracking for targeted npcs; but thats for a separate pr imo

**Review by mdX7 — APPROVED** [review]
