### PR TITLE
Scripts/Spells: Touch of the Magi - accumulate damage and DoT duration

### LINKED ISSUE #26040: Core/Spells Touch of the Magi not work
**Description:**

Spellid: 321507

When used on an enemy, it applies an aura of 210824 to him and for 8 seconds, accumulates a charge and then deals damage to the enemy. Damage is calculated for 25% of the damage done to the enemy

**Expected behaviour:**

When used, it must impose on the target the aura 210824, which for 8 seconds accumulates damage dealt to the character, and releases 25% of the damage to the target on which the aura hangs

**Steps to reproduce the problem:**

1. Create a character class mage
2. Change character spec to Arcane
3. Raise character level to 33
4. Cast spell 321507 on enemy target

**Branch(es):**

master

**TC rev. hash/commit:** 

db18aac

**Operating system:** 

Windows 10 x64

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Touch of the magi will now accumulate damage and explode for said damage over time

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26040 

**Tests performed:**

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

**Comment by Faq** [comment]
From where did you know that it was not working?

**Comment by matanshukry** [comment]
> From where did you know that it was not working?

#26040
Updated op as well.

**Comment by illfated** [comment]
title suggestion: **Scripts/Spells: Touch of the Magi**
(due to my linguistic & grammar orientation, I find the word "fixed" to be more ambiguous than useful)

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -802,6 +804,50 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
+    {
+        DamageInfo* damageInfo = eventInfo.GetDamageInfo();
+        if (damageInfo)
+            if (damageInfo->GetAttacker() == GetCaster() && damageInfo->GetVictim() == GetTarget())
+            {
+                uint32 extra = CalculatePct(damageInfo->GetDamage(), 25);
+                if (extra > 0)
+                {
+                    _sum += CalculatePct(damageInfo->GetDamage(), 25);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_mage.cpp:828]: you can use the `extra` variable here

File: src/server/scripts/Spells/spell_mage.cpp [hunk 2]
```diff
@@ -802,6 +804,50 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                    AuraEffect *auraEffect = GetTarget()->GetAuraEffect(SPELL_MAGE_TOUCH_OF_THE_MAGI_AURA, 0, GetCaster()->GetGUID());
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_mage.cpp:829]: use `*` always directly after type, no space inbetween => `AuraEffect* auraEffect`

File: src/server/scripts/Spells/spell_mage.cpp [hunk 3]
```diff
@@ -802,6 +804,50 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                    _sum += extra;
+                    AuraEffect* auraEffect = GetTarget()->GetAuraEffect(SPELL_MAGE_TOUCH_OF_THE_MAGI_AURA, 0, GetCaster()->GetGUID());
+                    auraEffect->ChangeAmount(_sum);
+                }
+            }
+    }
+
+    void AfterRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        if (_sum == 0 || GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_EXPIRE)
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:837]: `_sum` in this function is the same as `aurEff->GetAmount()`

File: src/server/scripts/Spells/spell_mage.cpp [hunk 4]
```diff
@@ -802,6 +804,50 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+        DamageInfo* damageInfo = eventInfo.GetDamageInfo();
+        if (damageInfo)
+            if (damageInfo->GetAttacker() == GetCaster() && damageInfo->GetVictim() == GetTarget())
+            {
+                uint32 extra = CalculatePct(damageInfo->GetDamage(), 25);
+                if (extra > 0)
+                {
+                    _sum += extra;
+                    AuraEffect* auraEffect = GetTarget()->GetAuraEffect(SPELL_MAGE_TOUCH_OF_THE_MAGI_AURA, 0, GetCaster()->GetGUID());
+                    auraEffect->ChangeAmount(_sum);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:830]: `auraEffect == aurEff`

File: src/server/scripts/Spells/spell_mage.cpp (hunk 3 above)
Comment (mdX7) [reply src/server/scripts/Spells/spell_mage.cpp:837]: so we can drop `_sum` completely, pog

File: src/server/scripts/Spells/spell_mage.cpp (hunk 4 above)
Comment (matanshukry) [reply src/server/scripts/Spells/spell_mage.cpp:830]: Is that smart? what if down the line we decide aurEff argument will be one that actually shouldn't be changed?
Otherwise - what would you say about removing the const from the function signature?

Comment (Shauren) [reply src/server/scripts/Spells/spell_mage.cpp:830]: But your code is doing the same - since both point to the same AuraEffect object

Comment (matanshukry) [reply src/server/scripts/Spells/spell_mage.cpp:830]: the result is the same currently because the const that is passed is the same as the one from `GetAuraEffect` and like you said, it doesn't have to be const. But in the future if someone will want to change the variable that is passed, they won't go looking into each script and check no one is doing a const_cast.

Either way `const_cast` isn't something we should do. Like I said, if it's the same I can remove the const from the signature, assuming you agree.

Comment (Shauren) [reply src/server/scripts/Spells/spell_mage.cpp:830]: Remove const from argument, I agree.

**Comment by matanshukry** [comment]
> title suggestion: **Scripts/Spells: Touch of the Magi - accumulate damage and DoT duration**
> (due to my linguistic & grammar orientation, I find the word "fixed" to be more ambiguous than useful)

Just saw it now. Better late than never I guess

File: src/server/scripts/Spells/spell_mage.cpp [hunk 5]
```diff
@@ -802,6 +804,45 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+    bool Validate(SpellInfo const* /*spellInfo*/) override
+    {
+        return ValidateSpellInfo({ SPELL_MAGE_TOUCH_OF_THE_MAGI_EXPLODE });
+    }
+
+    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
+    {
+        DamageInfo* damageInfo = eventInfo.GetDamageInfo();
+        if (damageInfo)
+            if (damageInfo->GetAttacker() == GetCaster() && damageInfo->GetVictim() == GetTarget())
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:821]: codestyle: wrap in brackets (you do it on first required inner level, then all the way to the outermost one)

File: src/server/scripts/Spells/spell_mage.cpp [hunk 6]
```diff
@@ -802,6 +804,45 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+            {
+                uint32 extra = CalculatePct(damageInfo->GetDamage(), 25);
+                if (extra > 0)
+                    aurEff->ChangeAmount(aurEff->GetAmount() + extra);
+            }
+    }
+
+    void AfterRemove(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
+    {
+        int amount = aurEff->GetAmount();
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:831]: dont use plain `int`, its `int32`

**Review by ghost — APPROVED** [review]
Looks pretty good to me. A good amount of `const` simplification, which I presume is good too.
