### PR TITLE
Core/Conditions: Add type QUEST_OBJECTIVE_PROGRESS_BAR to CONDITION_QUEST_OBJECTIVE_COMPLETE

### LINKED ISSUE #19477: Core/Conditions: CONDITION_QUEST_OBJECTIVE_COMPLETE add Type
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

Add type QUEST_OBJECTIVE_PROGRESS_BAR to `Player::IsQuestObjectiveComplete`

**Current behaviour:**

When you have a quest which has a progress bar, you can't complete it.

Got this in my console:
`Player::CanCompleteQuest:` Player 'Yy' (GUID Full: 0x08000400000000000000000000000008 Type: Player Entry: 0 Low: 8) tried to complete a quest (ID: 38819) with an unknown objective type 15`

**Expected behaviour:**

This function should have `QUEST_OBJECTIVE_PROGRESS_BAR` and then complete the quest.

**Steps to reproduce the problem:**

1. Take quest
    - http://www.wowhead.com/quest=39279/assault-on-mardum or 
    - http://www.wowhead.com/quest=38819/their-numbers-are-legion
2. Complete the bar
3. Quest can't be completed.

**Branch(es):** master

**TC rev. hash/commit:** https://github.com/TrinityCore/TrinityCore/commit/0b0d4c4011b1be37590104dae6a5b7a6ae378eef

**Operating system:** Win64

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by benlbot**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Ignore quest_objective with flags 64 in isQuestComplete(this flag seems to be related to objective with type 15 and doesn't need to be check)
-  Add IsQuestObjectiveProgressComplete in Entities/Player

**Target branch(es):** master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #19477  

**Tests performed:**
- tested ingame on quest with ProgressBar

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -6609,6 +6609,20 @@ bool Player::HasCurrency(uint32 id, uint32 count) const
     return itr != _currencyStorage.end() && itr->second.Quantity >= count;
 }
 
+bool Player::IsQuestObjectiveProgressComplete(Quest const* quest) const
+{
+	float progress = 0;
+	for (QuestObjective const& obj : quest->GetObjectives())
+	{
+		if (obj.Flags & 64) {
```
Comment (Temppus) [inline src/server/game/Entities/Player/Player.cpp]: magic number 64 + starting curly brace on new line + fix indentation in all diff lines.

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -16761,6 +16775,9 @@ bool Player::IsQuestObjectiveComplete(QuestObjective const& objective) const
     Quest const* quest = sObjectMgr->GetQuestTemplate(objective.QuestID);
     ASSERT(quest);
 
+	if (objective.Flags & 64)
```
Comment (Temppus) [inline src/server/game/Entities/Player/Player.cpp]: same magic

File: src/server/game/Entities/Player/Player.cpp (hunk 1 above)
Comment (Aokromes) [inline src/server/game/Entities/Player/Player.cpp]: tabs, tabs everywhere.

File: src/server/game/Entities/Player/Player.cpp (hunk 2 above)
Comment (Aokromes) [inline src/server/game/Entities/Player/Player.cpp]: more tabs

File: src/server/game/Entities/Player/Player.cpp [hunk 3]
```diff
@@ -16798,6 +16815,10 @@ bool Player::IsQuestObjectiveComplete(QuestObjective const& objective) const
             if (!HasCurrency(objective.ObjectID, objective.Amount))
                 return false;
             break;
+		case QUEST_OBJECTIVE_PROGRESS_BAR:
```
Comment (Aokromes) [inline src/server/game/Entities/Player/Player.cpp]: and more tabs

File: src/server/game/Entities/Player/Player.cpp [hunk 4]
```diff
@@ -6609,6 +6609,18 @@ bool Player::HasCurrency(uint32 id, uint32 count) const
     return itr != _currencyStorage.end() && itr->second.Quantity >= count;
 }
 
+bool Player::IsQuestObjectiveProgressComplete(Quest const* quest) const
+{
+    float progress = 0;
+    for (QuestObjective const& obj : quest->GetObjectives())
+        if (obj.Flags & QUEST_OBJECTIVE_FLAGS_UNK64) {
```
Comment (Temppus) [inline src/server/game/Entities/Player/Player.cpp]: brace to next line!

Comment (benlbot) [inline src/server/game/Entities/Player/Player.cpp]: ok

**Comment by funjoker** [comment]
Can someone confirm QUEST_OBJECTIVE_FLAGS_UNK64?

If this flag is confirmed give it a name.

File: src/server/game/Entities/Player/Player.cpp [hunk 5]
```diff
@@ -6609,6 +6609,19 @@ bool Player::HasCurrency(uint32 id, uint32 count) const
     return itr != _currencyStorage.end() && itr->second.Quantity >= count;
 }
 
+bool Player::IsQuestObjectiveProgressComplete(Quest const* quest) const
+{
+    float progress = 0;
+    for (QuestObjective const& obj : quest->GetObjectives())
+        if (obj.Flags & QUEST_OBJECTIVE_FLAGS_CONTRIBUTE_TO_PROGRESS_BAR)
```
Comment (tkrokli) [inline src/server/game/Entities/Player/Player.cpp]:
```
src/server/game/Entities/Player/Player.cpp:6616:25: fatal error: 
      use of undeclared identifier
      'QUEST_OBJECTIVE_FLAGS_CONTRIBUTE_TO_PROGRESS_BAR'; did you mean
      'QUEST_OBJECTIVE_FLAG_PART_OF_PROGRESS_BAR'?
        if (obj.Flags & QUEST_OBJECTIVE_FLAGS_CONTRIBUTE_TO_PROGRESS_BAR)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        QUEST_OBJECTIVE_FLAG_PART_OF_PROGRESS_BAR
src/server/game/Quests/QuestDef.h:253:5: note: 
      'QUEST_OBJECTIVE_FLAG_PART_OF_PROGRESS_BAR' declared here
    QUEST_OBJECTIVE_FLAG_PART_OF_PROGRESS_BAR               = 0x40, // h...
    ^
```

**Comment by tkrokli** [comment]
Thank you for confirming that the PR is ready, but I prefer that one of the senior developers or TC owners perform the merge, just in case any of them have got anything else to add to the discussion before merge.

**Review by ghost — APPROVED** [review]

**Review by Shauren — APPROVED** [review]
