### PR TITLE
Core/Scripts: Fix heap buffer overflow in BRD Tomb of seven event

### LINKED ISSUE #27919: Core/Scripts: Heap buffer overflow in blackrock depths instance script
### Description

Index to access C array gets incremented every 15s and it never gets checked in brd instance script during tomb of seven event
[code](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp#L432)
which leads to random crashes
ASan, please note custom changes
https://gist.github.com/Riztazz/c7f8cf436b64500ef758718d5e091328

### Expected behaviour

Validate index when accessing TombBossGUIDs array or modernize the script alltogether

### Steps to reproduce the problem

Start tomb of seven event and afk there for at least 105 seconds ( .go creature id 9039 )

### Branch

3.3.5

### TC rev. hash/commit

af5bd270c3b6628b126e0fde8aa2069a552484bd
Please note i've only studied the code on github at this commit

### Operating system

3.3.5

### Custom changes

ASan callstack is from different source alltogether so you have to ignore to threading part, but issue is related to script itself and affects TrinityCore as well

### PR DESCRIPTION
**Pull request by Riztazz**
**Changes proposed:**
Do not access out of bounds array  

**Issues addressed:**
Index was modified every 15 seconds eventually leading to heap buffer overflow

Closes #27919 

**Tests performed:**

(Does it build, tested in-game, etc.)
it builds, wasn't tested

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp [hunk 1]
```diff
@@ -429,8 +430,12 @@ class instance_blackrock_depths : public InstanceMapScript
...
-                    ++TombEventCounter;
-                    TombOfSevenEvent();
+                    if ( TombEventCounter < TOMB_OF_SEVEN_BOSS_NUM )
+                    {
+                        TombOfSevenEvent();
+                        ++TombEventCounter;
+                    }
+
                     // Check Killed bosses
                     for (uint8 i = 0; i < 7; ++i)
```
Comment (D1pp3rP1nes) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp:440]: TOMB_OF_SEVEN_BOSS_NUM

File: src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp [hunk 2]
```diff
@@ -429,8 +430,12 @@ class instance_blackrock_depths : public InstanceMapScript
                 if (TombTimer <= diff)
                 {
                     TombTimer = TIMER_TOMBOFTHESEVEN;
-                    ++TombEventCounter;
-                    TombOfSevenEvent();
+                    if ( TombEventCounter < TOMB_OF_SEVEN_BOSS_NUM )
```
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp:433]:
```suggestion
                    if (TombEventCounter < TOMB_OF_SEVEN_BOSS_NUM)
```

File: src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp [hunk 3]
```diff
@@ -29,6 +29,7 @@
 
 #define TIMER_TOMBOFTHESEVEN    15000
 #define MAX_ENCOUNTER           6
+constexpr uint8 TOMB_OF_SEVEN_BOSS_NUM{ 7 };
```
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp:32]:
```suggestion
constexpr uint8 TOMB_OF_SEVEN_BOSS_NUM = 7;
```

**Comment by jackpoz** [comment]
While at it, "7" is used around the file for GhostKillCount , might change that aswell while at it

**Comment by Riztazz** [comment]
Sorry about codestyle, force of habit. I can modernize it a bit more if you want, but adds a bit of useless noise to PR

**Comment by jackpoz** [comment]
Thanks for the PR 🚀 😃
