### PR TITLE
Core/Spells: Implement Shield of Vengeance

### LINKED ISSUE #28740: Paladin Shield of Vengeance
### Description

https://www.wowhead.com/spell=184662/shield-of-vengeance 
Applies a shield that absorbs 0 damage.

### Expected behaviour

Creates a barrier of holy light that absorbs [30 / 100 * Total health * (1 + Versatility)] damage for 15 sec.

When the shield expires, it bursts to inflict Holy damage equal to the total amount absorbed, divided among all nearby enemies.

### Steps to reproduce the problem

Just create palading and use that spell

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/f0fa05773f9b4880b130ee245391a8ec34163587

### Operating system

Debian 11

### Custom changes

None

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement Shield of Vengeance (paladin)

**Issues addressed:**

Closes #28740 #19696

**Tests performed:**

Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 1]
```diff
@@ -1427,6 +1428,62 @@ class spell_pal_selfless_healer : public AuraScript
...
+        OnEffectRemove += AuraEffectApplyFn(spell_pal_shield_of_vengeance::HandleRemove, EFFECT_0, SPELL_AURA_SCHOOL_ABSORB, AURA_EFFECT_HANDLE_REAL);
+    }
+};
+
+// 184689 - Shield of Vengeance (damage)
+class spell_pal_shield_of_vengeance_damage : public SpellScript
+{
+    PrepareSpellScript(spell_pal_shield_of_vengeance_damage);
+
+    uint8 targetsCount = 0;
```
Comment (Nyr97) [inline src/server/scripts/Spells/spell_paladin.cpp:1467]: set it at the bottom (preferibly as private)

**Review by Nyr97 — CHANGES_REQUESTED** [review]
