### PR TITLE
Various quest system fixes (seasonal quests, timed quests and more)

### LINKED ISSUE #11187: On crash players lose xp, rep but quests can't be redone (15$ bounty)
**Rev:** All
**DB:** N/A

**Bug:**

When the server crashes between player updates, players lose XP and rep but quests that have been completed are still marked as rewarded which means they cannot be done again to regain the XP and rep.

**Details:**

Quests that are completed are marked rewarded instantly but nothing else is saved until the player save interval has passed. To remedy the bug above, the following should be saved along with quest completion status
- Player's current XP
- Player's current Rep (all factions)
- Player's current level and unspent talents
- Player's inventory (to save quest rewards and items otherwise unobtainable)

By saving those items when a quest is marked completed, the player has minimal loss at crash since these all depend on being able to redo a quest which givent he current coding is not possible.

**[See my other suggestion below about QUEST_STATUS_PENDING](https://github.com/TrinityCore/TrinityCore/issues/11187#issuecomment-27929031)**

**Notes:**

Consider when a player completes several quests, earning several thousand XP, a level, a talent point and rep with a faction which cannot be gained via mob kills (ie: some factions like Argent Dawn can be gained by dungeon runs but most can't).

Having a GM grant the level and unspent talent would be simple enough but figuring out which quests were completed, how much xp, which factions gained rep (including "spill over" to other factions) and calculating that rep, and giving the player back quest rewards would be time consuming at best.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1412763-on-crash-players-lose-xp-rep-but-quests-can-t-be-redone?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #15279: [3.3.5] Core/quest: Timed quests shouldn't turn failed once completed
rev. d69a31d23812
Example:
http://www.wowhead.com/quest=2969/freedom-for-all-creatures

Take the quest, complete it with .quest complete, then wait until the timer expire, you will see the quest will turn failed and you cannot turn it any more.

If I'm not wrong, once the quest completed the timer must turn off.

A similar issue was fixed here: https://github.com/TrinityCore/TrinityCore/pull/12959

### LINKED ISSUE #18913: Core: Quest requirement check character_queststatus_seasonal
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**   In the DB we have the quest http://www.wowhead.com/quest=8883/valadar-starsong which should not be available until http://www.wowhead.com/quest=8867/lunar-fireworks is rewarded. If you create a new character, everything is fine, but if you have an old character who completed these 2 quests last year, the NPC will show the 2 quests together. If I'm not wrong, the actual check is done in both table `character_queststatus_seasonal` and `character_queststatus_rewarded`, but it must be done only in `character_queststatus_rewarded`.

PS: `.lookup quest` shows that these 2 quests are not rewarded or taken.

**Current behaviour:** Quest requirement uses `character_queststatus_seasonal`

**Expected behaviour:** Quest requirement must use `character_queststatus_rewarded` only

**Steps to reproduce the problem:**

1. Find a character who completed these 2 quests (8867, 8883)
2.  `.go c id 15895`
3. Notice that the NPC proposes both quests

**Branch(es):** 3.3.5 / master

**TC rev. hash/commit:**  rev. 591a25500d98

**TDB version:**  

**Operating system:**  

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5

- [x] 3.3.5

**Issues addressed:** Closes #18913 Closes #11187 Closes #15279

**Tests performed:** Compiles

Unify quest status checking function, use dedicated function instead of direct map checks
Fixed seasonal quest chains and ability to complete the same quests rewarded in past
Update area dependent auras on quest status change (they often requires specific quest status)
Send all not stored quest rewards by mail
When casting quest reward spell, check if it is not self casted, if so - use player to cast this spell
Perform full db save on quest reward to prevent data desynchronization
Don't allow to fail completed timed quests, except for quests which are completed right from the start
Don't allow to share pooled quests, if they are not available in the current pool (eg sharing easy dalaran weeklies, stored at alt character)
Remove seasonal quest if rewarded quest is removed
Don't complete whole quest on AreaExplore event, check if there are no more requirements that should be fulfilled
Quests with flag QUEST_SPECIAL_FLAGS_PLAYER_KILL can be only credited in quest zone

**Code review and tests required**

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -15029,6 +15042,8 @@ void Player::RewardQuest(Quest const* quest, uint32 reward, Object* questGiver,
                 Item* item = StoreNewItem(dest, itemId, true, Item::GenerateItemRandomPropertyId(itemId));
                 SendNewItem(item, quest->RewardChoiceItemCount[reward], true, false);
             }
+            else // send by mail
+                SendItemRetrievalMail(itemId, quest->RewardChoiceItemCount[reward]);
```
Comment (Shauren) [inline src/server/game/Entities/Player/Player.cpp]: should never happen. you cannot turn in a quest on retail with full inventory

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -14962,6 +14967,10 @@ void Player::CompleteQuest(uint32 quest_id)
         if (Quest const* qInfo = sObjectMgr->GetQuestTemplate(quest_id))
             if (qInfo->HasFlag(QUEST_FLAGS_TRACKING))
                 RewardQuest(qInfo, 0, this, false);
+
+        // area auras may change on quest completion
+        UpdateZoneDependentAuras(GetZoneId());
+        UpdateAreaDependentAuras(GetAreaId());
```
Comment (joschiwald) [inline src/server/game/Entities/Player/Player.cpp]: that is done in Player::SendQuestUpdate

Comment (xinef1) [inline src/server/game/Entities/Player/Player.cpp]: I've noted in my to do list to check what's going on there but forgot to check it before pushing. It should do the same thing, you are right

**Comment by ForesterDev** [comment]
Perform full db save on quest reward to prevent data desynchronization

How does this change affect performance?

**Comment by xinef1** [comment]
It's performance irrelevant compared to other bottlenecks

**Comment by Viste** [comment]
good PR but, some reputation quests are broken with him and after merge you PR for optimization into TC  need reslove conflict )

**Comment by xinef1** [comment]
@Viste Any details?

**Comment by tkrokli** [comment]
@xinef1 : Do you mind fixing the 3 conflicts between your branch and TC 3.3.5 in `Player.cpp` ?
I don't know enough about how the 2 quest related changes affect each other to fix all the conflicts.

**Comment by xinef1** [comment]
@tkrokli on it, poke me on irc if you need something

**Comment by Viste** [comment]
@xinef1 need some time to more proper tests for correct info

File: src/server/game/Entities/Player/Player.cpp [hunk 3]
```diff
@@ -15852,6 +15858,17 @@ void Player::RemoveRewardedQuest(uint32 questId, bool update /*= true*/)
         m_RewardedQuestsSave[questId] = QUEST_FORCE_DELETE_SAVE_TYPE;
     }
 
+    // Remove seasonal quest also
+    if (Quest const* qInfo = sObjectMgr->GetQuestTemplate(questId))
+    {
+        uint16 eventId = sGameEventMgr->GetEventIdForQuest(qInfo);
```
Comment (tkrokli) [inline src/server/game/Entities/Player/Player.cpp]: https://travis-ci.org/TrinityCore/TrinityCore/builds/197388841
```
src/server/game/Entities/Player/Player.cpp:15864:41: fatal error: 
      no member named 'GetEventIdForQuest' in 'GameEventMgr'
        uint16 eventId = sGameEventMgr->GetEventIdForQuest(qInfo);
                         ~~~~~~~~~~~~~  ^
```
I would have thought that it would be enough that `GetEventIdForQuest` is defined in `GameEventMgr.h` (which is in the #include list in this file). I presume you know why this one fails. Perhaps an additional declaration is needed?

Comment (tkrokli) [inline src/server/game/Entities/Player/Player.cpp]: Sorry, my bad. I looked up the function in the `master` branch here on TC and thought I was looking at 3.3.5 source. It is not in the 3.3.5 branch, so you will need to add it in this PR to make it work,

Comment (tkrokli) [inline src/server/game/Entities/Player/Player.cpp]: D'oh. You removed `GetEventIdForQuest()` yourself in your PR https://github.com/TrinityCore/TrinityCore/pull/18684 in December.

**Comment by xinef1** [comment]
Will fix tonight, merged using github :p

**Comment by Killyana** [comment]
@Viste Can you provide some examples of reputation quests broken by this PR?

**Comment by Viste** [comment]
@Killyana if time bless me add info tomorrow

**Comment by Viste** [comment]
12470 12456 8519 13343 with pr don't work, after remove work fine

**Comment by Killyana** [comment]
What do you mean by "don't work"?

**Comment by tkrokli** [comment]
@Viste - 3 are from Dragonblight/Northrend, 1 from Silithus/Kalimdor. What is the common thread?
- http://www.wowhead.com/quest=12470/mystery-of-the-infinite
- http://www.wowhead.com/quest=12456/the-plume-of-alystros
- http://www.wowhead.com/quest=8519/a-pawn-on-the-eternal-board
- http://www.wowhead.com/quest=13343/mystery-of-the-infinite-redux

**Comment by Viste** [comment]
@Killyana @tkrokli soryy that report was inncorect and send me by my friends, i look by myself today and post correct report.

**Comment by Viste** [comment]
Ok in first after apply commit some npc has no daily quests:
http://wowhead.com/npc=24393
http://wowhead.com/npc=28705
http://wowhead.com/npc=28742
http://wowhead.com/npc=34912
http://wowhead.com/npc=34882
links to quest post later

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Player/Player.cpp

**Comment by Aokromes** [comment]
@xinef1 go get bounty :)

**Comment by xinef1** [comment]
@ariel- deserves it more :)
