### PR TITLE
Scripts/Spells: fixed Cold Snap

### LINKED ISSUE #19591: Core/Script The spell Cold Snap doesn´t work.
**Description:**

The spell Cold Snap(ID:235219) given to Mage Frost at lv.51 has an issue

Cold Snap: Resets the cooldown of your Frost Nova, Cone of Cold, Ice Barrier, and Ice Block

**Current behaviour:**

The spell doesn´t work, it doesn´t reset the cooldown of any spell 

**Expected behaviour:**

when you use the spell it should reset the cooldown of the spell´s that appear in the spell description

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.51 an choose the Frost Spec
3. Use the spell´s Frost Nova, Cone of Cold, Ice Barrier and Ice Block
4. Use the spell Cold Snap and check the cooldown´s

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=235219

### PR DESCRIPTION
**Pull request by Nyr97**
**Changes proposed:**

-  Frost Nova gets its charge restored now.

**Issues addressed:** Closes https://github.com/TrinityCore/TrinityCore/issues/19591.

**Tests performed:** It builds and it was tested in-game.

**Known issues and TODO list:** None.

### CODE REVIEW

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -450,29 +450,27 @@ class spell_mage_cold_snap : public SpellScript
...
-            SPELL_MAGE_ICE_BLOCK
+            SPELL_MAGE_CONE_OF_COLD,
+            SPELL_MAGE_FROST_NOVA
         });
     }
 
     void HandleDummy(SpellEffIndex /*effIndex*/)
     {
-        GetCaster()->GetSpellHistory()->ResetCooldowns([](SpellHistory::CooldownStorageType::iterator itr)
+        std::vector<uint32> spellsToReset =
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_mage.cpp:462]: you are creating a new vector for each cast but the list never changes, so we can make it constant;
use
```c
static uint32 constexpr SpellsToReset[] = {
    SPELL_MAGE_ICE_BLOCK,
    SPELL_MAGE_ICE_BARRIER,
    SPELL_MAGE_CONE_OF_COLD
};
```
outside the function, like its done in `spell_rog_roll_the_bones`.
Usage doesnt change btw
