### PR TITLE
Scripts/Stratholme: Baroness Anastari rework

### LINKED ISSUE #20335: [3.3.5] Stratholme - Baroness Anastari
**Description:**

Baroness Anastari is currently missing her Possess spell.

**Current behaviour:**

When you fight her she possesses no one.

**Expected behaviour:**

When you do this encounter she is supposed to possess anyone else who isn't the main threat target.
She has to go invisible and the target will act like mind control.

**Steps to reproduce the problem:**

1. Go to Stratholme's elder entrance. 
2. .additem [Key to the City]
3. Open the first gate
4. Go straight to the next one further ahead.
5. Follow the path until the last gate
6. Fight Baroness Anastari with a party of 2 or more ( Pets should work aswell )
7. Wait the whole encounter to realize she will never cast the spell

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

 950bfef86502+

**TDB version:**  335.63

**Operating system:** Windows 10

### PR DESCRIPTION
**Pull request by Nitair**
**Changes proposed:**
- Original rework was written by @hiMalleus (https://github.com/TrinityCore/TrinityCore/pull/20336)

- Changed handling how the script does get the player GUID

- Changed `DoCast(me->GetVictim(),SPELL_XXX);` to `DoCastVictim(SPELL_XXX);` to match all things together

- added register model like implemented here https://github.com/TrinityCore/TrinityCore/commit/fb87ac8e8da3d215d4988b8c2fa25d7a98cf9ee0

- replaced essential parts of boolean `_invisible` and `REACT_STATE` to spell `17250` which is used by baroness anastari to get invisible / get stunned

**Target branch(es):** 3.3.5/master
- [X] 3.3.5

**Issues addressed:**
- Closes #20335
- Fixes #20336 

**Tests performed:**
- Performed tests with 2 accounts (rogue & paladin)
- Performed tests with a hunter (with and without pet)
- Tested possession phase
- Tested case if you are soloing Baroness with pet
- Tested if PvP Trinket can be used to cancel the possession
- Theoretical research via wowhead (+comments) and wowpedia (+patch-changes)

**Known issues and TODO list:**
- [X] Does build x86 release on Windows 10 Pro (Version 1709 / OS Build 16299.334)
- [X] Does build x64 on Ubuntu Server Release: 17.10 
- [X] Handle SetObjectScale in #20336 , which I've removed, because there's no change of ObjectScale (good to see here: https://www.youtube.com/watch?v=wqygMyNzwe4)
- [ ] If player got possessed, you can hit the player down to 50% to become control again, but player will not get full health as it should
- [x] Handle situation if player does solo her, also with pet & elemental etc. (http://www.wowhead.com/npc=10436/baroness-anastari#comments:id=62785)
- [x] Check if PvP Trinket does clear possession (it shouldn't)

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 1]
```diff
@@ -88,37 +88,83 @@ class boss_baroness_anastari : public CreatureScript
...
-                //13 seconds until we should cast this again
-                Silence_Timer = 13000;
-            } else Silence_Timer -= diff;
-
+                    _events.ScheduleEvent(EVENT_SPELL_SILENCE, Seconds(13));
+                    break;
+                case EVENT_SPELL_POSSESS:
+                    if (Unit* possessTarget = SelectTarget(SELECT_TARGET_RANDOM, 1, 0, true, false))    // Random target to be possessed
+                    {
+                        if (possessTarget && possessTarget->IsAlive())
```
Comment (Riztazz) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: No need to check possessTarget in here, you're already checking it above

**Comment by Riztazz** [comment]
Nitpicking but you could change Seconds(x) to Xs (4s for example), someday someone is gonna drop that typedefs since TC allows chrono literals now

**Comment by Nitair** [comment]
@Riztazz , are you sure? I guess BossAI is used for raids but for dungeons as well? And thanks for reviewing :)

**Comment by Shauren** [comment]
BossAI is meant for any instance bosses

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 2]
```diff
@@ -16,66 +16,82 @@
...
-    CreatureAI* GetAI(Creature* creature) const override
-    {
-        return GetStratholmeAI<boss_baroness_anastariAI>(creature);
-    }
-
-    struct boss_baroness_anastariAI : public ScriptedAI
+    struct boss_baroness_anastariAI : public BossAI
     {
-        boss_baroness_anastariAI(Creature* creature) : ScriptedAI(creature)
+        boss_baroness_anastariAI(Creature* creature) : BossAI(creature, TYPE_BARONESS)
```
Comment (Nitair) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: I don't know if `TYPE_BARONESS` correct.

**Comment by Nitair** [comment]
I'm sorry. It's the first time that I touch an instance / a boss script.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 2 above)
Comment (tkrokli) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: `TYPE_BARONESS` refers to this line in `stratholme.h`:
https://github.com/TrinityCore/TrinityCore/blob/fb31cb7c047f4d79e7bea04b72175e6ef251a317/src/server/scripts/EasternKingdoms/Stratholme/stratholme.h#L27-L30
... meaning the value it represents is 2. Not sure if that is what you intended.

**Comment by jackpoz** [comment]
everyone started somewhere :)

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 3]
```diff
@@ -16,112 +16,140 @@
...
+    {
+        if (!me->IsVisible())
         {
-            Initialize();
-        }
+            Player* possessedTarget = ObjectAccessor::FindConnectedPlayer(_possessedTargetGuid);
 
-        void JustEngagedWith(Unit* /*who*/) override
-        {
+            if (possessedTarget->IsAlive())
```
Comment (Riztazz) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Now you have to check if pointer exists, previously when i complained about that you had your pointer in 'if' so you automatically checked, now you dont

Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: @Riztazz thanks for advice... I did change that :D

**Comment by Nitair** [comment]
I don't know how to prevent loosing cast time if players are attacking Baroness Anastari... But the other stuff is working fine

**Comment by Riztazz** [comment]
Spells probably missing NO_PUSH_BACK attribute, now the question is why and should we hack it in spellmgr ;p

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 4]
```diff
@@ -16,112 +16,144 @@
...
+        _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+    }
 
-        void JustDied(Unit* /*killer*/) override
-        {
-            instance->SetData(TYPE_BARONESS, IN_PROGRESS);
-        }
+    void JustDied(Unit* /*killer*/) override
+    {
+        me->GetInstanceScript()->SetData(TYPE_BARONESS, IN_PROGRESS);
```
Comment (joschiwald) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]:
```
instance->SetData(TYPE_BARONESS, IN_PROGRESS);
```
was fine

Comment (tkrokli) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Oh right. Fair point. I didn't think about that earlier.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 5]
```diff
@@ -16,112 +16,144 @@
...
+    EventMap _events;
+    ObjectGuid _possessedTargetGuid;
 
-        void Reset() override
+    void Reset() override
+    {
+        if (!me->IsVisible())
         {
-            Initialize();
+            if (Player* possessedTarget = ObjectAccessor::FindConnectedPlayer(_possessedTargetGuid))
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: `ObjectAccessor::GetPlayer`. You don't want to find players outside of your map (or maybe not even in world) and manipulate them.

_(Whenever you touch stuff outside your map, there be dragons.)_

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 6]
```diff
@@ -16,112 +16,144 @@
...
+            {
+                if (possessedTarget->IsAlive())
+                {
+                    possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESSED);
+                    possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESS);
+                    me->SetReactState(REACT_AGGRESSIVE);
+                    me->SetVisible(true);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: If the possessed target is dead for some reason, you want to stay invisible? Sounds wrong.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 7]
```diff
@@ -16,112 +16,144 @@
...
+            switch (eventId)
             {
-                if (rand32() % 100 < 80)
-                    DoCastVictim(SPELL_SILENCE);
-                //13 seconds until we should cast this again
-                Silence_Timer = 13000;
-            } else Silence_Timer -= diff;
-
-            DoMeleeAttackIfReady();
+            case EVENT_SPELL_BANSHEEWAIL:
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: `case` should be indented

```cpp
switch (expr)
{
    case LABEL:
        DoStuff();
```

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 8]
```diff
@@ -16,112 +16,144 @@
...
+                DoCastVictim(SPELL_BANSHEEWAIL);
+                _events.ScheduleEvent(EVENT_SPELL_BANSHEEWAIL, 4s);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: `_events.Repeat(4s)` for all occurrences of this pattern

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 9]
```diff
@@ -16,112 +16,144 @@
...
+            case EVENT_SPELL_POSSESS:
+                if (Unit* possessTarget = SelectTarget(SELECT_TARGET_RANDOM, 1, 0, true, false))    // Random target to be possessed
+                {
+                    if (possessTarget->IsAlive())
+                    {
+                        me->CastStop();
+                        DoCast(possessTarget, SPELL_POSSESS);
+                        DoCast(possessTarget, SPELL_POSSESSED);
+                        me->SetReactState(REACT_PASSIVE);
+                        me->SetVisible(false);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: I really don't like this, it feels like a hack. Are you sure there's no invisibility + stun spell cast by Baroness here?

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 10]
```diff
@@ -16,112 +16,144 @@
...
+                        _possessedTargetGuid = possessTarget->GetGUID();
+                        _events.ScheduleEvent(EVENT_CHECK_POSSESSED, 0s);
+                    }
+                    else
+                        _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+                }
+                break;
+            case EVENT_INVISIBLE:
+                if (Player* possessedTarget = ObjectAccessor::FindConnectedPlayer(_possessedTargetGuid))    // When there's a possessed target
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: same as above, `ObjectAccessor::GetPlayer`

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 11]
```diff
@@ -16,112 +16,144 @@
...
+                {
+                    possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESS);
+                    possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESSED);
+                    me->SetVisible(true);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: if the player isn't found, you stay invisible forever and softlock the encounter?

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 12]
```diff
@@ -16,112 +16,144 @@
...
+                    me->SetReactState(REACT_AGGRESSIVE);
+                    _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+                }
+                break;
+            case EVENT_CHECK_POSSESSED:
+                if (!me->IsVisible())
+                {
+                    if (Player* possessedTarget = ObjectAccessor::FindConnectedPlayer(_possessedTargetGuid))
+                    {
+                        if (!possessedTarget->HasAura(SPELL_POSSESSED) || possessedTarget->GetHealthPct() <= 50)
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: I think there is a helper for checking hp <= pct.... `IsHealthBelow` something or another I think?

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: also this whole event feels hacky

is there maybe a dummy periodic on the possess aura that you could attach a spellscript to or something?

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 13]
```diff
@@ -16,112 +16,144 @@
...
+        _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+    }
 
-        void JustDied(Unit* /*killer*/) override
-        {
-            instance->SetData(TYPE_BARONESS, IN_PROGRESS);
-        }
+    void JustDied(Unit* /*killer*/) override
+    {
+        instance->SetData(TYPE_BARONESS, IN_PROGRESS);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: are you sure this is intended?

**Comment by Treeston** [comment]
also, random aside - don't merge `3.3.5` into your PR branch, it causes the tree to look super awkward (and complicates merges).

instead, rebase your PR branch on `3.3.5` (only if necessary, will require a force push to push to github)

_*(note: double-check your git tree before you force push, force pushing can delete stuff if you screwed up during the rebase)*_

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 7 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: its in switch case? Or do I miss something?
```
while (uint32 eventId = _events.ExecuteEvent())
        {
            switch (eventId)
            {
            case EVENT_SPELL_BANSHEEWAIL:
                DoCastVictim(SPELL_BANSHEEWAIL);
                _events.ScheduleEvent(EVENT_SPELL_BANSHEEWAIL, 4s);
```

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: you have
```cpp
switch(expr)
{
case LABEL:
    stuff();
```

should be
```cpp
switch (expr)
{
    case LABEL:
        stuff();
```

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 5 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Isn't `ObjectAccessor::FindConnectedPlayer` fetch only on current map? But I agree, I could take `ObjectAccessor::GetPlayer`

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 6 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: That's why I'm checking if target is alive
```
                    if (possessTarget->IsAlive())
                    {
                        me->CastStop();
                        DoCast(possessTarget, SPELL_POSSESS);
                        DoCast(possessTarget, SPELL_POSSESSED);
                        me->SetReactState(REACT_PASSIVE);
                        me->SetVisible(false);
                        _possessedTargetGuid = possessTarget->GetGUID();
                        _events.ScheduleEvent(EVENT_CHECK_POSSESSED, 0s);
                    }
```

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 5 above)
Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: How would `FindConnectedPlayer` know what map to look on?

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 6 above)
Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: What if it dies between then and now?

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 9 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Baroness Anastari don't have any stuns. Only the possess and silence. I was thinking about a spell, but I couldn't find any reference to that. I've found in mangos core a spell, but I'm not sure if this is the right way (because I couldn't find ANY reference).

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: I suspect there's a stun+invisibility aura that she casts on herself...

**Comment by Nitair** [comment]
@Treeston , thanks for your advice. Wasn't sure about that (because first time contributing here). I will perform, I needed, a rebase.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 9 above)
Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]:
```
ID - 17250 Possess
=================================================
Category = 0, SpellIconID = 1, activeIconID = 0, SpellVisual = (4579,0)
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000190 (SPELL_ATTR0_ABILITY, SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
AttributesEx1: 0x10000000 (SPELL_ATTR1_DONT_DISPLAY_IN_AURA_BAR)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0.00
Duration: ID (4)  120000, 0, 120000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 39 (SPELL_AURA_SCHOOL_IMMUNITY), value = 1, misc = 127 (127), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 5000
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), value = 5000, misc = 0 (0), miscB = 0, periodic = 0

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 12 (SPELL_AURA_MOD_STUN), value = 1, misc = 0 (0), miscB = 0, periodic = 0
```

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: ^that's my suspicion but will check if we have sniffs

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 11 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Well, I guess I did a failure here (`if (me->IsVisible())` should be `if (!me->IsVisible())`)

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: anyway if you change to non-hack aura as outlined [here](https://github.com/TrinityCore/TrinityCore/pull/21687/files/0ade97b44389f47bc8dabf5df09610c81c1d500c#r178469545) then all of this just because a ->removeaura call without needing to worry about visibility/reactstate weirdness.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 9 above)
Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: (@Keader promised to check sniffs and see if she casts the spell, annoy him if he forgets)

Comment (Keader) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]:
```
ServerToClient: SMSG_AURA_UPDATE (0x0496) Length: 23 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137614
GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
[0] Slot: 2
[0] Spell ID: 17250 (Possess)
[0] Flags: 63 (EffectIndex0, EffectIndex1, EffectIndex2, NotCaster, Positive, Duration)
[0] Level: 59
[0] Charges: 0
[0] Max Duration: 120000
[0] Duration: 119999

ServerToClient: SMSG_SPELL_START (0x0131) Length: 31 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137615
Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Caster Unit GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Cast Count: 0
Spell ID: 17250 (Possess)
Cast Flags: 11 (PendingCast, HasTrajectory, Unknown3)
Time: 0
Target Flags: 0 (Self)

ServerToClient: SMSG_SPELL_GO (0x0132) Length: 42 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137616
Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Caster Unit GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Cast Count: 0
Spell ID: 17250 (Possess)
Cast Flags: 265 (PendingCast, Unknown3, Unknown7)
Time: 3880364410
Hit Count: 1
[0] Hit GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Miss Count: 0
Target Flags: 2 (Unit)
Target GUID: 0x0

[3] UpdateType: Values
[3] GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
[3] UNIT_FIELD_CHARM: xxxxxx/xxxxxxx
[3] UNIT_FIELD_CHARM + 1: 41943040/1.880791E-37
[3] UNIT_FIELD_TARGET: xxxxxx/xxxxxx
[3] UNIT_FIELD_TARGET + 1: 41943040/1.880791E-37
[3] UNIT_FIELD_FLAGS: 788544/1.104985E-39


ServerToClient: SMSG_AURA_UPDATE (0x0496) Length: 30 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137627
GUID: Full: 0x28000000322F2D4 Type: Player Low: xxxxx Name: PlayerXXXX
[0] Slot: 18
[0] Spell ID: 17246 (Possessed)
[0] Flags: 161 (EffectIndex0, Duration, Negative)
[0] Level: 59
[0] Charges: 0
[0] Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
[0] Max Duration: 120000
[0] Duration: 120000

```

**Comment by Nitair** [comment]
Damned... Edited wrong repo... :/

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 14]
```diff
@@ -52,18 +53,18 @@ struct boss_baroness_anastari : public BossAI
...
     {
-        if (!me->IsVisible())
+        if (me->HasAura(SPELL_POSSESS_INV))
         {
-            if (Player* possessedTarget = ObjectAccessor::FindConnectedPlayer(_possessedTargetGuid))
+            if (Player* possessedTarget = ObjectAccessor::GetPlayer(me->GetMap(), _possessedTargetGuid))
             {
                 if (possessedTarget->IsAlive())
                 {
                     possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESSED);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: iirc instancemap has some method for removing auras by id from all players, could be used here
also don't forget to reset guid

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 15]
```diff
@@ -125,22 +126,22 @@ struct boss_baroness_anastari : public BossAI
                 }
                 break;
             case EVENT_INVISIBLE:
-                if (Player* possessedTarget = ObjectAccessor::FindConnectedPlayer(_possessedTargetGuid))    // When there's a possessed target
+                if (Player* possessedTarget = ObjectAccessor::GetPlayer(me->GetMap(), _possessedTargetGuid))    // When there's a possessed target
                 {
                     possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESS);
                     possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESSED);
-                    me->SetVisible(true);
+                    possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESS_INV);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: this aura is on self

**Comment by Keader** [comment]
(idk if you saw)

```
ServerToClient: SMSG_AURA_UPDATE (0x0496) Length: 23 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137614
GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
[0] Slot: 2
[0] Spell ID: 17250 (Possess)
[0] Flags: 63 (EffectIndex0, EffectIndex1, EffectIndex2, NotCaster, Positive, Duration)
[0] Level: 59
[0] Charges: 0
[0] Max Duration: 120000
[0] Duration: 119999

ServerToClient: SMSG_SPELL_START (0x0131) Length: 31 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137615
Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Caster Unit GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Cast Count: 0
Spell ID: 17250 (Possess)
Cast Flags: 11 (PendingCast, HasTrajectory, Unknown3)
Time: 0
Target Flags: 0 (Self)

ServerToClient: SMSG_SPELL_GO (0x0132) Length: 42 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137616
Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Caster Unit GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Cast Count: 0
Spell ID: 17250 (Possess)
Cast Flags: 265 (PendingCast, Unknown3, Unknown7)
Time: 3880364410
Hit Count: 1
[0] Hit GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Miss Count: 0
Target Flags: 2 (Unit)
Target GUID: 0x0

[3] UpdateType: Values
[3] GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
[3] UNIT_FIELD_CHARM: xxxxxx/xxxxxxx
[3] UNIT_FIELD_CHARM + 1: 41943040/1.880791E-37
[3] UNIT_FIELD_TARGET: xxxxxx/xxxxxx
[3] UNIT_FIELD_TARGET + 1: 41943040/1.880791E-37
[3] UNIT_FIELD_FLAGS: 788544/1.104985E-39


ServerToClient: SMSG_AURA_UPDATE (0x0496) Length: 30 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137627
GUID: Full: 0x28000000322F2D4 Type: Player Low: xxxxx Name: PlayerXXXX
[0] Slot: 18
[0] Spell ID: 17246 (Possessed)
[0] Flags: 161 (EffectIndex0, Duration, Negative)
[0] Level: 59
[0] Charges: 0
[0] Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
[0] Max Duration: 120000
[0] Duration: 120000

ServerToClient: SMSG_SPELL_HEAL_LOG (0x0150) Length: 32 ConnIdx: 0 Time: 02/19/2010 20:32:35.000 Number: 137630
Target GUID: Full: 0x28000000322F2D4 Type: Player Low: xxxxxxx Name: xxxxxx
Caster GUID: Full: 0xF1300028C400C56C Type: Creature Entry: 10436 (Baroness Anastari) Low: 50540
Spell ID: 17246 (Possessed)
Damage: 39550
Overheal: 37657
Absorb: 0
Critical: false
Debug output: false

```

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 9 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: @Treeston 17250 does the stun?

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: yes, check the three effects listed in spellwork i pasted

* effect 0: immunity to all effects, applied to self
* effect 1: invisibility, strength 5000, applied to self
* effect 2: stun, applied to self

**Comment by Nitair** [comment]
@Keader thanks for that output. I'll take a look further if I'm more focused on this script. :)

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 14 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Won't be overwritten by ` if (Unit* possessTarget = SelectTarget(SELECT_TARGET_RANDOM, 1, 0, true, false))` ?

Comment (Treeston) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Yeah, I guess so. Still cleaner if you don't leave anything "lying around" from the previous attempt.

Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: I would just add `_possessedTargetGuid.Clear();` after https://github.com/TrinityCore/TrinityCore/pull/21687/files#diff-db60b62d3ff54ba02d4f8c161fe09c8dR133 and I guess in `Reset()` also?

**Comment by Aokromes** [comment]
after the big amount of changes the sd2 (C) can be removed

**Comment by Nitair** [comment]
@Aokromes I did remove the reference of SD2 already

**Comment by Aokromes** [comment]
I mean:

 * Copyright (C) 2006-2009 ScriptDev2 <https://scriptdev2.svn.sourceforge.net/>

**Comment by Nitair** [comment]
@Aokromes oh missed that one. Thanks :)

**Comment by Aokromes** [comment]
you missed the one on .h :P

**Comment by Nitair** [comment]
@Aokromes I did not much in there. I've just added `#define RegisterStratholmeCreatureAI(ai_name) RegisterCreatureAIWithFactory(ai_name, GetStratholmeAI)`, but the other data is untouched. I don't know if I should remove this copy. Maybe I do some more changes into the `.h` file

**Comment by Aokromes** [comment]
yes, but the file changed a lot since the original sd2 version.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 16]
```diff
@@ -16,112 +15,138 @@
...
-    CreatureAI* GetAI(Creature* creature) const override
-    {
-        return GetStratholmeAI<boss_baroness_anastariAI>(creature);
-    }
+struct boss_baroness_anastari : public BossAI
+{
+    boss_baroness_anastari(Creature* creature) : BossAI(creature, TYPE_BARONESS) { }
 
-    struct boss_baroness_anastariAI : public ScriptedAI
+    EventMap _events;
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: `BossAI` already has an `EventMap`

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 17]
```diff
@@ -16,112 +15,138 @@
...
-            BansheeWail_Timer = 1000;
-            BansheeCurse_Timer = 11000;
-            Silence_Timer = 13000;
-            //Possess_Timer = 35000;
-        }
+        instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_POSSESS);
+        instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_POSSESSED);
 
-        InstanceScript* instance;
+        if (me->HasAura(SPELL_POSSESS_INV))
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: check seems unnecessary here

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 18]
```diff
@@ -16,112 +15,138 @@
...
+        _events.ScheduleEvent(EVENT_SPELL_SILENCE, 13s);
+        _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+    }
 
-        void JustEngagedWith(Unit* /*who*/) override
-        {
-        }
+    void JustDied(Unit* /*killer*/) override
+    {
+        instance->SetData(TYPE_BARONESS, IN_PROGRESS);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: if this is required by the instancescript, explain this in a comment

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 19]
```diff
@@ -16,112 +15,138 @@
...
                     DoCastVictim(SPELL_SILENCE);
-                //13 seconds until we should cast this again
-                Silence_Timer = 13000;
-            } else Silence_Timer -= diff;
-
-            DoMeleeAttackIfReady();
+                    _events.ScheduleEvent(EVENT_SPELL_SILENCE, 13s);
+                    break;
+                case EVENT_SPELL_POSSESS:
+                    if (Unit* possessTarget = SelectTarget(SELECT_TARGET_RANDOM, 1, 0, true, false))    // Random target to be possessed
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: comment feels pretty superfluous to me

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 20]
```diff
@@ -16,112 +15,138 @@
...
+                    {
+                        if (possessTarget->IsAlive())
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: possessTarget can't be dead if it's in your threat list

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 21]
```diff
@@ -16,112 +15,138 @@
...
+                        {
+                            me->CastStop();
+                            DoCast(possessTarget, SPELL_POSSESS);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: some of these should probably be triggered casts... (hey @Keader check the sniff since you already have it)

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 22]
```diff
@@ -16,112 +15,138 @@
...
+                            _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+                    }
+                    break;
+                case EVENT_INVISIBLE:
+                    if (Player* possessedTarget = ObjectAccessor::GetPlayer(*me, _possessedTargetGuid))    // When there's a possessed target
+                    {
+                        possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESS);
+                        possessedTarget->RemoveAurasDueToSpell(SPELL_POSSESSED);
+                        me->RemoveAurasDueToSpell(SPELL_POSSESS_INV);
+                        possessedTarget->SetFullHealth();
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: ewwwww, don't do this

maybe there's a spell?

@Keader

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 23]
```diff
@@ -16,112 +15,138 @@
...
+                        _possessedTargetGuid.Clear();
+                        _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+                    }
+                    break;
+                case EVENT_CHECK_POSSESSED:
+                    if (me->HasAura(SPELL_POSSESS_INV))
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: why is this check necessary?

just call cancelevent when removing the aura, no need to check every tick whether you still have it...

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 24]
```diff
@@ -16,112 +15,138 @@
...
+                    {
+                        if (Player* possessedTarget = ObjectAccessor::GetPlayer(*me, _possessedTargetGuid))
+                        {
+                            if (!possessedTarget->HasAura(SPELL_POSSESSED) || possessedTarget->HealthBelowPct(50))
+                                _events.ScheduleEvent(EVENT_INVISIBLE, 0s);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: do you really need a separate event for this? it's only ever invoked from here...

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 25]
```diff
@@ -16,112 +15,138 @@
...
+                        me->RemoveAurasDueToSpell(SPELL_POSSESS_INV);
+                        possessedTarget->SetFullHealth();
+                        _possessedTargetGuid.Clear();
+                        _events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+                    }
+                    break;
+                case EVENT_CHECK_POSSESSED:
+                    if (me->HasAura(SPELL_POSSESS_INV))
+                    {
+                        if (Player* possessedTarget = ObjectAccessor::GetPlayer(*me, _possessedTargetGuid))
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: should you handle the case where the possessed target has disappeared somehow?

currently you'll just stay invisible forever and soft lock

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 26]
```diff
@@ -16,112 +15,138 @@
...
+                            else
+                                _events.ScheduleEvent(EVENT_CHECK_POSSESSED, 1s);
+                        }
+                    }
+                    break;
+            }
         }
-    };
-
+        DoMeleeAttackIfReady();
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: newline before this

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 27]
```diff
@@ -16,112 +15,138 @@
...
+                        if (Player* possessedTarget = ObjectAccessor::GetPlayer(*me, _possessedTargetGuid))
+                        {
+                            if (!possessedTarget->HasAura(SPELL_POSSESSED) || possessedTarget->HealthBelowPct(50))
+                                _events.ScheduleEvent(EVENT_INVISIBLE, 0s);
+                            else
+                                _events.ScheduleEvent(EVENT_CHECK_POSSESSED, 1s);
+                        }
+                    }
+                    break;
+            }
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: casting check before end of loop body, check how other scripts do it

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 24 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: As I see its needed to go instantly to `EVENT_INVISIBLE` if the conditions `if (!possessedTarget->HasAura(SPELL_POSSESSED) || possessedTarget->HealthBelowPct(50))` are met. If player somehow looses this aura or if player has below 50% HP

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 28]
```diff
@@ -16,112 +15,135 @@
...
+                        _possessedTargetGuid.Clear();
+                        events.CancelEvent(EVENT_CHECK_POSSESSED);
+                        events.ScheduleEvent(EVENT_SPELL_POSSESS, 20s, 30s);
+                    }
+                    break;
+                case EVENT_CHECK_POSSESSED:
+                    if (Player* possessedTarget = ObjectAccessor::GetPlayer(*me, _possessedTargetGuid))
+                    {
+                        if (!possessedTarget->HasAura(SPELL_POSSESSED) || possessedTarget->HealthBelowPct(50))
+                            events.ScheduleEvent(EVENT_INVISIBLE, 0s);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: my earlier point still stands - why is this a separate event? why not just run the "remove auras" logic here?

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp [hunk 29]
```diff
@@ -16,112 +15,135 @@
...
+                    events.Repeat(18s);
+                    break;
+                case EVENT_SPELL_SILENCE:
                     DoCastVictim(SPELL_SILENCE);
-                //13 seconds until we should cast this again
-                Silence_Timer = 13000;
-            } else Silence_Timer -= diff;
-
-            DoMeleeAttackIfReady();
+                    events.ScheduleEvent(EVENT_SPELL_SILENCE, 13s);
```
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: `.Repeat`

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp (hunk 28 above)
Comment (Nitair) [reply src/server/scripts/EasternKingdoms/Stratholme/boss_baroness_anastari.cpp]: Oh I get you now

**Review by Treeston — APPROVED** [review]
