### PR TITLE
Scripts/Commands: Fix trinity_string usage and enhance commands

### LINKED ISSUE #16733: [3.3.5] Core/Command: .npc delete guid and wp show off not working properly
d55d32fa0f7a

Both commands don't work properly because of the same fault. 
.wp show off doesn't delete the visual waypoint marker (because it can't find the guid)
.npc del guid also doesn't work because of the same reason.

Looking to the code:

cs_npc.cpp line 492:
unit = handler->GetSession()->GetPlayer()->GetMap()->GetCreature(ObjectGuid(HighGuid::Unit, cr_data->id, lowguid));

unit is always 0 (null)

cs_wp.cpp line 1025:
Creature\* creature = handler->GetSession()->GetPlayer()->GetMap()->GetCreature(ObjectGuid(HighGuid::Unit, VISUAL_WAYPOINT, guid));

creature is always 0 (null)

Unfortunately I couldn't find exactly where the problem is. ObjectGuid() seems to be correct. It contains the correct guid. Maybe it's GetCreature().

### LINKED ISSUE #18241: gameobject commands not working
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
The gameobject commands dont seem to be working properly together.
The gameobject target gives links that contain the gameobject DB guid.
Because of the new guid changes .gps command however searches with the ingame guid (So a gameobject that has DB guid X will have ingame guid Y which has a dynamically generated guid counter).

I guess the root causes here are that there are two guids and both are needed by the commands.
Also some commands need the entry for which there is a completely another link type.
It would be probably nice to have something like `|color|Hgameobject:entry:dbguid:ingameguid|h[name]|h|r` so one link can be used for everything and it would work/not work depending on if the info needed is available in the link.

Also .gob add command does not work for some reason. The gameobjects dont save up in DB.

**Current behaviour:**
Gameobject link from .gob tar gives DB guids. However .gps command uses core generated guids to search. The error message says player not found and should say gameobject not found.
The .gob add command does not save gameobjects to DB.

**Expected behaviour:**
Gameobject link from .gob tar should probably contain the ingame guid as well. The gps command needs to know the ingame guid to search properly (uniquely identify the gameobject) It also needs the DB guid or gameobject entry to make the guid to search with.
The error message should vary depending on what arguments were provided. For example when giving a gameobject link, it should say that no gameobject was found.
The spawned gameobjects should save to db.

**Steps to reproduce the problem:**

1. Try spawning a gameobject with .gob add 35
2. See that it is there
3. Try target it with .gob target and see that it fails to target the gameobject
4. See the gameobject table in DB and see that there are no spawns there.
5. Restart the server and go to where you spawned the object and see that it isnt there.
6. Conclusion: No gameobjects are saved and they cannot be targeted. Targeting fails because it searches the objects from DB where they dont exist.
1. Go to an existing gameobject.
2. Use .gob target on it and it should succeed because it is in DB
3. Use .gps <link of the gameobject>
4. See that it fails and the error message incorrectly says "Cannot find player"
5. Conclusion: the gps command cannot be used on the object links (even though it is intended to)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  ed2cd6b34f849f9cc9adb86318457155e47f7314

**TDB version:**  62

**Operating system:**  windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### LINKED ISSUE #19127: command modify faction crash
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
the command modify faction crash the world server
**Current behaviour:** (Tell us what happens.)
when I change a faction of an npc when I type .mod fac 1 to an npc mob the world server crash
**Expected behaviour:** (Tell us what should happen instead.)
when I type .mod fac 1 to npc the faction change without crashing the world server
**Steps to reproduce the problem:**

1. type .mod faction to an npc
2. it change the npc faction
3. dont crash the world server

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master 
**TC rev. hash/commit:**  
 8aacc07
**TDB version:**  
  703.00 and latest I keep all uptodate 2017_02_13 
**Operating system:**  
windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### LINKED ISSUE #20023: [master] World server crash when use command.
**Description:**

When you use command "character deleted list" world server crash

**Current behaviour:**

https://gist.github.com/HannibalRoG/42ce5c6db40983b6d8b9bbc6513f9403

**Branch(es):**

master

**TC rev. hash/commit:** 

Revision: TrinityCore rev. df66b903e37f 2017-07-12 01:23:59 +0200 (6.x branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  7.2.0+updates

**Operating system:**

### PR DESCRIPTION
**Pull request by Rochet2**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

~~Waiting for https://github.com/TrinityCore/TrinityCore/pull/18978 to merge first!~~

Tries to fix trinity_string related format differences and more:
- Change many %d to %u
- Change many %i to %u
- Change many %u and %llu to %s and change uint64 values to std::to_string(val).c_str()
- Change int64 to string before formatting and change all format characters for them to %s
- Change uint64 to string before formatting and change all format characters for them to %s
- Change many atoi to atoul when trying to get an uint32 value from user
- Change many atoi to atoul when trying to get an uint32 value from user
- Add .c_str() call to convert std::string to const char* before formatting
- Remove format characters that were not used in code (in DB there was %s but nothing in c++)
- Remove arguments that had no format characters (in c++ there was something formatted, but in DB there was no format character like %s)
- Change types in code to match the surrounding code better (for example return type was uint32 and returned variable was int)
- Remove unnecessary `(char*)` casts for `const char*` variables
- `.modify faction` now works without arguments as described in `.help`
- LANG_COMMAND_DELOBJREFERCREATURE (274) no longer says that a nonexistant creature references it, because owner can be more than a creature. Instead it says that a nonexistant owner references it. Printed guid should tell what type the owner is.
- Change __some__ usages of snprintf to use Trinity::StringFormat instead
- Fix typos (IE: Wypoint scipt -> Waypoint script)
- Convert __some__ `container.size()` to string before formatting
- Change __some__ std::strtoull to atoull

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)
Closes #19127
Closes #20023

**Tests performed:** (Does it build, tested in-game, etc.)
Does build.

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Fix the code (the IF condition here looks funny) and the message (the guids are in wrong order) and the types in here: https://github.com/TrinityCore/TrinityCore/pull/18978#discussion_r100573183 (usage of LANG_COMMAND_DELOBJREFERCREATURE in cs_gobject.cpp)
- [x] Fix the PR after https://github.com/TrinityCore/TrinityCore/pull/18978 is merged.

### CODE REVIEW

File: sql/updates/world/master/xxxx_xx_xx_x1_world.sql [hunk 1]
```diff
@@ -0,0 +1,97 @@
+UPDATE `trinity_string` SET `content_default`='Up to %i expansions are allowed now.' WHERE  `entry`=61;
```
Comment (Aokromes) [inline sql/updates/world/master/xxxx_xx_xx_x1_world.sql]: merge this world file with previous file.

Comment (Rochet2) [inline sql/updates/world/master/xxxx_xx_xx_x1_world.sql]: " I hope these commits are not merged together. This is because of the first being a cherry pick of 3.3.5 branch commit and the second is more work built on top of that."

Still want it though?

Comment (Aokromes) [inline sql/updates/world/master/xxxx_xx_xx_x1_world.sql]: then 2 different PRs is the way, we cannot partialy merge PRs.

Comment (Rochet2) [inline sql/updates/world/master/xxxx_xx_xx_x1_world.sql]: The PRs depend on each other though so making separate PRs now would make the other have conflicts with master so not sure that is possible in a good way.

Guess I need to merge them then if there is no other way.

Comment (Aokromes) [inline sql/updates/world/master/xxxx_xx_xx_x1_world.sql]: you can create 2 separate PRs and fix conflicts when the 1st is merged.

**Comment by Kittnz** [comment]
needs a bit of updating it seems

**Comment by Rochet2** [comment]
> needs a bit of updating it seems

Added more info to todo and top of PR description. Waiting on other PR to fix this one.

**Comment by Shauren** [comment]
The other one is now merged

**Comment by Rochet2** [comment]
Would be cool if we could ignore the type of variables when printing them.
Using something like
http://pastebin.com/aYrebMhy
or http://fmtlib.net/latest/api.html#format-api

**Comment by Rochet2** [comment]
Updated PR and descriptions.

**Comment by Rochet2** [comment]
Fixed the bad merge

**Comment by jackpoz** [comment]
merge this to stop users from reporting the same crashes over and over ?

**Comment by Aokromes** [comment]
3.3.5a version of this was merged months ago, this fixes at least few crashes......

**Comment by jackpoz** [comment]
merge it and hope for the best

**Comment by Rochet2** [comment]
@Aokromes What PR are you referring to?
If it is one of mine, then https://github.com/TrinityCore/TrinityCore/pull/18978 and https://github.com/TrinityCore/TrinityCore/pull/18278 are the same PR but the first one is a cherry pick to from 3.3.5 to master branch.

Those PRs were attempting to fix gameobject targetting which did not work and when it worked it was working in an unreliable manner (possibly selecting unwanted gobs).

This PR we are in tries to solve crashes and issues with commands trying to use the new lowguids that are uint64. This is solved by conversion to string so we can insert the numbers easily to commands.

Just making sure if something was unclear.
I guess fixing the crashes would be nice :)
