### PR TITLE
Core/AI: Implement OnAuraApplied and OnAuraRemoved hooks

### LINKED ISSUE #26894: Core/SAI: OnAuraApplied and OnAuraRemoved event types
### Description

Would be nice to have simple OnAuraApplied and OnAuraRemoved event types
That SMART_EVENT_HAS_AURA is something else
Its params makes it act like OnAuraApplied and something like 'on update if aura is not applied' which is not OnAuraRemoved of course

To be honest I even don't understand how some of those scripts works
Something crazy like here probably https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=32642
So when creature has 1 stack of aura(OnAuraApplied), it sets phase 1 and in phase 1 another event is called when aura has no stack(removed), it's just crazy

Technically it just evades after first SAI tick https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=7383

### Expected behaviour

above

### Steps to reproduce the problem

none

### Branch

3.3.5

### TC rev. hash/commit

325bdc0ab070

### Operating system

Win 8.1

### Custom changes

none

### PR DESCRIPTION
**Pull request by offl**
**Changes proposed:**

-  Implement OnAuraApplied and OnAuraRemoved hooks

**Issues addressed:**

Closes #26894

**Tests performed:**

builds, tested in-game with:
```sql
--
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 128;

DELETE FROM `creature_text` WHERE `CreatureID` = 128;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(128,0,0,"Aura applied!",12,0,100,0,0,0,0,0,""),
(128,1,0,"Aura removed!",12,0,100,0,0,0,0,0,"");

DELETE FROM `smart_scripts` WHERE `entryorguid` = 128 AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(128,0,0,0,89,0,100,0,50280,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Aura 'Oily Coat' Applied - Say Line 0"),
(128,0,1,0,90,0,100,0,50280,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,"On Aura 'Oily Coat' Removed - Say Line 1");
```

### CODE REVIEW

**Comment by Ovahlord** [comment]
You might also want to add the remove mode to the aura-removed hook so you can tell if the aura was removed by dispel, death or expiration

File: src/server/game/AI/CreatureAI.h [hunk 1]
```diff
@@ -156,6 +156,12 @@ class TC_GAME_API CreatureAI : public UnitAI
         // Called when a channeled spell finishes
         virtual void OnChannelFinished(SpellInfo const* /*spell*/) { }
 
+        // Called when aura is applied
+        virtual void OnAuraApplied(SpellInfo const* /*spell*/) { }
```
Comment (Shauren) [inline src/server/game/AI/CreatureAI.h]: Both of these should have AuraApplication* as argument

**Comment by offl** [comment]
> You might also want to add the remove mode to the aura-removed hook so you can tell if the aura was removed by dispel, death or expiration

I see no such param in enumerated strings

File: src/server/game/AI/SmartScripts/SmartScriptMgr.h [hunk 2]
```diff
@@ -187,8 +187,12 @@ enum SMART_EVENT
     SMART_EVENT_ON_SPELL_FAILED          = 84,      // SpellID, CooldownMin, CooldownMax
     SMART_EVENT_ON_SPELL_START           = 85,      // SpellID, CooldownMin, CooldownMax
     SMART_EVENT_ON_DESPAWN               = 86,      // NONE
+    SMART_EVENT_SEND_EVENT_TRIGGER       = 87,      // don't use on 3.3.5a
+    SMART_EVENT_AREATRIGGER_EXIT         = 88,      // don't use on 3.3.5a
+    SMART_EVENT_ON_AURA_APPLIED          = 89,      // SpellID, CooldownMin, CooldownMax
+    SMART_EVENT_ON_AURA_REMOVED          = 90,      // SpellID, CooldownMin, CooldownMax
```
Comment (mdX7) [inline src/server/game/AI/SmartScripts/SmartScriptMgr.h:193]: we might wanna be able to pass `aurApp->GetRemoveMode()` aswell, and for apply we might want to use `AuraEffectHandleModes` in sai too.

That allows us to handle stuff on remove by interrupt only / script only / expire only or for apply only on apply, only on refresh etc

Comment (Shauren) [reply src/server/game/AI/SmartScripts/SmartScriptMgr.h:193]: eh, AuraEffectHandleModes is hardly ever used in aura scripts, doubt it will be needed

Comment (offl) [reply src/server/game/AI/SmartScripts/SmartScriptMgr.h:193]: OnAuraApplied: Unit has aura {Spell} applied.
OnAuraRemoved: Unit has aura {Spell} removed.

No remove mode param

Comment (mdX7) [reply src/server/game/AI/SmartScripts/SmartScriptMgr.h:193]: > OnAuraApplied: Unit has aura {Spell} applied. OnAuraRemoved: Unit has aura {Spell} removed.
> 
> No remove mode param

Yes, but do we want to limit ourselves?

Comment (offl) [reply src/server/game/AI/SmartScripts/SmartScriptMgr.h:193]: I like limits in scripting, it doesn't allow to create dumb stuff
