### PR TITLE
Core/Movement: properly fix aura interrupts during movement

### LINKED ISSUE #22908: [3.3.5] Core/Spell: Creature interrupting own channel cast caused by UpdateSplineMovement
**Description:** Creatures are interrupting own channel cast caused by UpdateSplineMovement

**Current behaviour:** Creatures like Supressors (Valithria Dreamwalker) is interrupting own channel cast, caused by UpdateSplineMovement

**Expected behaviour:** UpdateSplineMovement stop while Channel is active

**Steps to reproduce the problem:**

1. use .go crea id 36789 
2. use .i set 0 3 , .i set 1 3 , .i set 2 3 , .i set 3 3, and start fight (just to not evade caused by Sequence Break)
3. Check that Suppressors will not cast suppression (70588)

Stack Trace based in Spell::Finish() with ok = false, for spell 70588

```
>	worldserver.exe!Spell::finish(bool ok)Linha 3771	C++
 	worldserver.exe!Spell::cancel()Linha 3167	C++
 	worldserver.exe!Unit::InterruptSpell(CurrentSpellTypes spellType, bool withDelayed, bool withInstant)Linha 3026	C++
 	worldserver.exe!Unit::InterruptNonMeleeSpells(bool withDelayed, unsigned int spell_id, bool withInstant)Linha 3089	C++
 	worldserver.exe!Unit::RemoveAurasWithInterruptFlags(unsigned int flag, unsigned int except)Linha 4024	C++
 	worldserver.exe!Unit::UpdatePosition(float x, float y, float z, float orientation, bool teleport)Linha 12744	C++
 	worldserver.exe!Unit::UpdateSplinePosition()Linha 513	C++
 	worldserver.exe!Unit::UpdateSplineMovement(unsigned int t_diff)Linha 488	C++
 	worldserver.exe!Unit::Update(unsigned int p_time)Linha 452	C++
 	worldserver.exe!Creature::Update(unsigned int diff)Linha 722	C++
 	worldserver.exe!TempSummon::Update(unsigned int diff)Linha 52	C++
 	worldserver.exe!Trinity::ObjectUpdater::Visit<Creature>(GridRefManager<Creature> & m)Linha 407	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,Creature>(Trinity::ObjectUpdater & v, ContainerMapList<Creature> & c)Linha 46	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >(Trinity::ObjectUpdater & v, ContainerMapList<TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > & c)Linha 52	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > >(Trinity::ObjectUpdater & v, ContainerMapList<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c)Linha 53	C++
 	worldserver.exe!VisitorHelper<Trinity::ObjectUpdater,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >(Trinity::ObjectUpdater & v, TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c)Linha 59	C++
 	worldserver.exe!TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >::Visit(TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c)Linha 93	C++
 	worldserver.exe!Grid<Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull> > > >,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >::Visit<Trinity::ObjectUpdater>(TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor)Linha 92	C++
 	worldserver.exe!NGrid<8,Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull> > > >,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >::VisitGrid<Trinity::ObjectUpdater,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >(const unsigned int x, const unsigned int y, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor)Linha 154	C++
 	worldserver.exe!Map::Visit<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >(const Cell & cell, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor)Linha 964	C++
 	worldserver.exe!Map::VisitNearbyCellsOf(WorldObject * obj, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & gridVisitor, TypeContainerVisitor<Trinity::ObjectUpdater,TypeMapContainer<TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<DynamicObject,TypeNull> > > > > > & worldVisitor)Linha 725	C++
 	worldserver.exe!Map::Update(unsigned int t_diff)Linha 794	C++
 	worldserver.exe!InstanceMap::Update(unsigned int t_diff)Linha 3853	C++
 	worldserver.exe!MapUpdateRequest::call()Linha 43	C++
 	worldserver.exe!MapUpdater::WorkerThread()Linha 115	C++
```

Related with: #21048, #19984, #18549
The fix of ariel-/ccrs not work for this case.

PS: #21048 is still open, but is valid only for master (not cherry-picked ariel/ccrs fix yet)

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  5a46faf17637315d98ed4431b0c4b655d0090243

### PR DESCRIPTION
**Pull request by Ovahlord**
**Changes proposed:**
The current movement update logic is interrupting auras before movement generators had their turn with updating their movement state. This was leading to the edge case issue that auras that should get interrupted by movement were falsely removed because the unit was still considered as moving while it might have stopped in the same update tick.

The most prominent case is the interrupting of instant cast channeled spells during chase movement.

We now wait until the movement generators had their shot to update their movement so the nasty dictatorship of UpdatePosition comes to an end.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
fixes #22908 properly this time

**Tests performed:** (Does it build, tested in-game, etc.)
- tested ingame on my 434 branch. Should be the same result on 335

### CODE REVIEW

**Comment by jackpoz** [comment]
@ccrs could you take a look at this ?

**Comment by Shauren** [comment]
Did I get it right? You skip interrupting auras on the update tick that finishes movement, even if position did actually change?

**Comment by Ovahlord** [comment]
No. I do not skip it, I keep the position update info until the movement gerators have been updated as well and then I process the interrupts. It still happens in the same update tick.

File: src/server/game/Entities/Unit/Unit.h [hunk 1]
```diff
@@ -1763,6 +1763,14 @@ class TC_GAME_API Unit : public WorldObject
         void UpdateSplineMovement(uint32 t_diff);
         void UpdateSplinePosition();
 
+        void InterruptMovementBasedAuras();
+
+        struct
+        {
+            bool Relocated = false;
+            bool Turned = false;
+        } m_positionUpdateInfo;
```
Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.h]: C-style bby
better move it to the variable declaration block 😄

Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.h]: and maybe give the structure a cool name too

Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.h]: and even maybe transform into a class? dunnow, these days choosing between class and struct seems more like a preference to me... rather than an actual difference

Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.h]: and even maybe drop the `m_` naming style 💃

**Comment by ccrs** [comment]
apart from the nitpicking changes, the theory feels solid to me
though as always its not the general scenario that matters, but the edge cases...

if enough testing is done, feels good to me

File: src/server/game/Entities/Unit/Unit.h (hunk 1 above)
Comment (Ovahlord) [reply src/server/game/Entities/Unit/Unit.h]: Well, as for the struct, I just did not feel like giving it a name because this place here is the only location where it's actually used so I thought it would be the best to just put it in there right away instead of making it a global thing

File: src/server/game/Entities/Unit/Unit.h [hunk 2]
```diff
@@ -1809,6 +1818,7 @@ class TC_GAME_API Unit : public WorldObject
         bool _isWalkingBeforeCharm;     ///< Are we walking before we were charmed?
 
         SpellHistory* m_spellHistory;
+		PositionUpdateInfo _positionUpdateInfo;
```
Comment (illfated) [inline src/server/game/Entities/Unit/Unit.h]: Tab indent, making the indent differ from the lines above.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 3]
```diff
@@ -379,6 +379,7 @@ Unit::Unit(bool isWorldObject) :
     _oldFactionId = 0;
     _isWalkingBeforeCharm = false;
     _instantCast = false;
+	_positionUpdateInfo = PositionUpdateInfo();
```
Comment (illfated) [inline src/server/game/Entities/Unit/Unit.cpp]: irregular indent, tab maybe?

**Comment by illfated** [comment]
Thank you for taking your time to adjust the spacing.
Feel free to minimize my comments above by clicking **[Resolve conversation]**.

File: src/server/game/Entities/Unit/Unit.cpp (hunk 3 above)
Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.cpp]: @Shauren is this necessary?

File: src/server/game/Entities/Unit/Unit.h [hunk 4]
```diff
@@ -714,6 +714,14 @@ enum ReactiveType
     MAX_REACTIVE
 };
 
+struct PositionUpdateInfo
+{
+    PositionUpdateInfo() : Relocated(false), Turned(false) { }
```
Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.h]: you can just add an inline initialization in both bool
`relocated = false`

File: src/server/game/Entities/Unit/Unit.cpp (hunk 3 above)
Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.cpp]: most likely no, I think if you remove everything the user defined constructor should be called
or if you remove it and choose for the inline initialize like I commented bellow it also should not be necessary

_should_

Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.cpp]: https://arne-mertz.de/2015/08/new-c-features-default-initializers-for-member-variables/

2015, but yet an enjoyable reading

Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.cpp]: https://www.fluentcpp.com/2018/06/15/should-structs-have-constructors-in-cpp/

this one too, fun fun 😄

Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.cpp]: https://www.fluentcpp.com/2017/06/13/the-real-difference-between-struct-class/

image

File: src/server/game/Entities/Unit/Unit.h (hunk 4 above)
Comment (Ovahlord) [reply src/server/game/Entities/Unit/Unit.h]: I know but I just followed the remaining struct code styles.

File: src/server/game/Entities/Unit/Unit.cpp (hunk 3 above)
Comment (ccrs) [reply src/server/game/Entities/Unit/Unit.cpp]: (btw I posted these posts cause I genually look for them to know myself, I thought they might be handy for you or the lurkers, or both 😄)

**Comment by Ovahlord** [comment]
@ccrs there. Now ffs lemme push the shiny button :D got more spicy movement stuff in the works

**Comment by Exeasd** [comment]
@Ovahlord Can i know why did the last commit happen [https://github.com/TrinityCore/TrinityCore/pull/24068/commits/5c7d972462cee44bd0aedf487448d4c13b926e83](this one for players.) Im curious bcoz with that commit player's channeling spells still can get interrupted when ya stop moving and start channeling right at the time ya stopped moving (easiest to test with jumping and trying to cast channeling spell, you will get false positive quite often that way.)
