### PR TITLE
Scripts/Spells: Aspect of the Cheetah

### LINKED ISSUE #19611: Core/Scripts: Aspect of the Cheetah is missing Effect 2
**Description:**

The spell ''Aspect of the Cheetah'' [Spell ID: 186257] of the Hunter class, has an issue.

**Current behaviour:**

The spell ''Aspect of the Cheetah'' [Spell ID: 186257] increases the movement speed by 90% for 3 sec, but then it does not increase the character's movement speed by 30% for 9 sec.

**Expected behaviour:**

The spell ''Aspect of the Cheetah'' [Spell ID: 186257] should increase the movement speed by 90% for 3 sec and then by 30% for another 9 sec.

**Steps to reproduce the problem:**

1. Create a Hunter character.
2. Reach level 22 in order to learn the spell ''Aspect of the Cheetah'' [Spell ID: 186257].
3. Then use the spell ''Aspect of the Cheetah'' [Spell ID: 186257].

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=186257/aspect-of-the-cheetah

### PR DESCRIPTION
**Pull request by MartGon**
**Changes proposed:**

-  Aspect of the cheetah script. http://www.wowhead.com/spell=186257/aspect-of-the-cheetah

**Target branch(es):** master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #19611

**Tests performed:** Tested in-game. Working as intended.

**Known issues and TODO list:** 

None, as far as I know.

### CODE REVIEW

File: sql/updates/world/master/9999_99_99_99_world.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+DELETE FROM spell_script_names WHERE spell_id=186257 AND ScriptName="spell_hun_aspect_cheetah";
```
Comment (tkrokli) [inline sql/updates/world/master/9999_99_99_99_world.sql]: Only delete by `ScriptName`. Also missing NewLine after line 2.
Also, please use back ticks around table + column names.
Suggestion:
```sql
-- Hunter spell Aspect of the Cheetah (186257)
DELETE FROM `spell_script_names` WHERE `ScriptName`= 'spell_hun_aspect_cheetah';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(186257, 'spell_hun_aspect_cheetah');
```

Comment (MartGon) [inline sql/updates/world/master/9999_99_99_99_world.sql]: Ok, sorry, going to fix it.

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 2]
```diff
@@ -1011,6 +1013,41 @@ class spell_hun_tnt : public SpellScriptLoader
             return new spell_hun_tnt_AuraScript();
         }
 };
+// -186257 - Aspect of the cheetah
+class spell_hun_aspect_cheetah : public SpellScriptLoader
+{
+public:
```
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_hunter.cpp]: indentation

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 3]
```diff
@@ -1011,6 +1013,41 @@ class spell_hun_tnt : public SpellScriptLoader
...
+    spell_hun_aspect_cheetah() : SpellScriptLoader("spell_hun_aspect_cheetah") { }
+
+    class spell_hun_aspect_cheetah_AuraScript : public AuraScript
+    {
+
+        PrepareAuraScript(spell_hun_aspect_cheetah_AuraScript);
+
+        bool Validate(SpellInfo const* /*spellInfo*/) override
+        {
+            if (!sSpellMgr->GetSpellInfo(SPELL_HUNTER_ASPECT_CHEETAH_FAST))
```
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_hunter.cpp]: No need to check this spell, you call already this spell with this spellscript
You need check only SPELL_HUNTER_ASPECT_CHEETAH_SLOW
And you can use new validate

```cpp
return ValidateSpellInfo
({
      SPELL_HUNTER_ASPECT_CHEETAH_SLOW
});
```

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 4]
```diff
@@ -1011,6 +1013,41 @@ class spell_hun_tnt : public SpellScriptLoader
...
+               return false;
+            return true;
+        }
+
+        void HandleOnRemove(AuraEffect const* aurEff, AuraEffectHandleModes mode)
```
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_hunter.cpp]: comment on /*aurEff*/ and /*mode*/ because you don't use their arguments

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 5]
```diff
@@ -1036,4 +1073,5 @@ void AddSC_hunter_spell_scripts()
     new spell_hun_target_only_pet_and_owner();
     new spell_hun_t9_4p_bonus();
     new spell_hun_tnt();
+    new spell_hun_aspect_cheetah();
```
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_hunter.cpp]: Bad place. You had to respect the alphabetical order (same for enum)

Comment (MartGon) [inline src/server/scripts/Spells/spell_hunter.cpp]: Ok, thanks for pointing out those mistakes. Gointg to work on a fix for them.

File: src/server/scripts/Spells/spell_hunter.cpp (hunk 3 above)
Comment (MartGon) [inline src/server/scripts/Spells/spell_hunter.cpp]: Should I delete  SPELL_HUNTER_ASPECT_CHEETAH_FAST as it is never used?

Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_hunter.cpp]: Exactly ! Need only validate spells which are called in spell/aurascript
Also you need remove one of double empty lines at 1040 before `Register` and it's perfect, good job :)

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 6]
```diff
@@ -1011,10 +1013,48 @@ class spell_hun_tnt : public SpellScriptLoader
...
+                    SPELL_HUNTER_ASPECT_CHEETAH_SLOW
+                });
+            }
+
+            void HandleOnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+            {
+                GetCaster()->CastSpell(GetCaster(), SPELL_HUNTER_ASPECT_CHEETAH_SLOW, true);
+            }
+
+
```
Comment (tkrokli) [inline src/server/scripts/Spells/spell_hunter.cpp]: Redundant double blank line here.

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 7]
```diff
@@ -1011,10 +1012,47 @@ class spell_hun_tnt : public SpellScriptLoader
...
+            {
+                return ValidateSpellInfo
+                ({
+                    SPELL_HUNTER_ASPECT_CHEETAH_SLOW
+                });
+            }
+
+            void HandleOnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+            {
+                GetCaster()->CastSpell(GetCaster(), SPELL_HUNTER_ASPECT_CHEETAH_SLOW, true);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_hunter.cpp]: GetCaster() can be null in AuraScripts.
If Target of Aura == Caster you can use GetTarget() instead, because in AuraScripts GetTarget() cant be null.

File: src/server/scripts/Spells/spell_hunter.cpp [hunk 8]
```diff
@@ -1012,9 +1013,48 @@ class spell_hun_tnt : public SpellScriptLoader
...
+                return ValidateSpellInfo
+                ({
+                    SPELL_HUNTER_ASPECT_CHEETAH_SLOW
+                });
+            }
+
+            void HandleOnRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+            {
+                Unit *target = GetTarget();
+                target->CastSpell(target, SPELL_HUNTER_ASPECT_CHEETAH_SLOW, true);
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_hunter.cpp]: what happens if you cancel the aura before it expires?

Comment (MartGon) [inline src/server/scripts/Spells/spell_hunter.cpp]: Currently, applies the second aura ignoring how it was removed. To be honest, I have not tested that on retail.

Comment (MartGon) [inline src/server/scripts/Spells/spell_hunter.cpp]: Anyway, I got a possible fix if that's an issue. It's done by checking it's duration when the first aura is removed.

Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_hunter.cpp]: I can't trying on retail, but if it's correct you need check with this
```cpp
if (GetTargetApplication()->GetRemoveMode() == AURA_REMOVE_BY_EXPIRE)
```

Comment (MartGon) [inline src/server/scripts/Spells/spell_hunter.cpp]: I can't test it either on retail, but I asked a friend about what happens in that case and he told me that the second aura does not trigger which is the option that makes more sense. So I'm uploading the new code with that constraint.

**Review by Keader — APPROVED** [review]
Looks good to me

**Comment by MartGon** [comment]
Thanks a lot for your help and for your patience. I'm going to try avoid those kind of mistakes next time.
