### PR TITLE
Channel Followup: avoid setting an invisible gm as Channel owner

### LINKED ISSUE #17424: Exploit allowing to know a gm was online
**Description**:
You can known a gm was online and invisible if he enters a public channel allowing ownership, and someone else enters that channel and gm leaves, for example test

**Current behaviour**: Tell us what happens
ownership changes from gm to player at gm leave/disconnect

**Expected behaviour**: Tell us what should happen instead
ownership must change from gm to player on player enter if gm was 1st on that channel and invisible.

**Steps to reproduce the problem**:

1. gm enters channel test invisible.
2. players enters channel test.
3. gm leaves channel or disconnects.
3. players get ownership, and now he knows a gm was invisible inside that channel.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5a, very likely all branches.

**TC hash/commit**:  
f226ebd2004d (all revisions for years)

**TDB version**:  
any

**Operating system**:  
any.

### PR DESCRIPTION
**Pull request by ariel-**
**Changes proposed**:
- Avoid setting an invisible gm (as in .gm visible off) as channel owner, giving it away to other players.
- This can now only happen if the channel is empty or when every other member is an invisible gm, too.

**Target branch(es)**: 335/6x

**Issues addressed**: Closes #17424 

**Tests performed**: It builds correctly, tested it with a couple of gm accounts and a player account, it consistently gave channel owner to player when the gms were invisible, and then player joined the channel

### CODE REVIEW

File: src/server/game/Chat/Channels/Channel.cpp [hunk 1]
```diff
@@ -262,13 +270,28 @@ void Channel::LeaveChannel(Player* player, bool send)
...
+            for (itr = _playersStore.begin(); itr != _playersStore.end(); ++itr)
+            {
+                if (!itr->second.IsInvisible())
+                {
+                    found = true;
+                    break;
+                }
+            }
+
+            auto itr2 = found ? itr : _playersStore.begin();
```
Comment (jackpoz) [inline src/server/game/Chat/Channels/Channel.cpp]:
```
if (itr == _playersStore.end())
  itr = _playersStore.begind();
```
you can avoid using "found" variable in this way, you can avoid itr2 too

File: src/server/game/Chat/Channels/Channel.cpp [hunk 2]
```diff
@@ -262,13 +270,28 @@ void Channel::LeaveChannel(Player* player, bool send)
...
+        // If the channel owner left and there are players still inside, pick a new owner
+        // do not pick invisible gm owner unless there only invisible gms in that channel (rare)
         if (changeowner && _ownershipEnabled && !_playersStore.empty())
         {
-            auto itr = _playersStore.begin();
-            ObjectGuid newowner = itr->first;
-            itr->second.SetModerator(true);
-            SetOwner(newowner);
+            bool found = false;
+            PlayerContainer::iterator itr;
```
Comment (jackpoz) [inline src/server/game/Chat/Channels/Channel.cpp]: does a const_iterator work too here ?

Comment (ariel-) [inline src/server/game/Chat/Channels/Channel.cpp]: No, I need it to be mutable, see https://github.com/TrinityCore/TrinityCore/pull/17597/files/3f3018a1c4652a6a91b87f3a4799e3e047f9d724#diff-9b9481224e87b63170bb0bb1028e7a07R290

**Comment by ariel-** [comment]
Anything left to do here?
