### PR TITLE
Core/GameObjects: Fixed an issue where traps were not redirected to Grounding Totem 

### LINKED ISSUE #16145: [3.3.5] Grounding Totem - Missing huntertraps
Huntertraps no redirect to grouding totem
Link:
Freezing Trap
http://www.wowhead.com/spell=60192/freezing-trap

Grounding totem
http://www.wowhead.com/spell=8177/grounding-totem

rev.https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

### PR DESCRIPTION
**Pull request by Goatform**
Closes #16145

### CODE REVIEW

**Comment by Goatform** [comment]
@jackpoz, it's ready now.

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 1]
```diff
@@ -1803,6 +1803,8 @@ void GameObject::CastSpell(Unit* target, uint32 spellId, bool triggered /*= true
     if (Unit* owner = GetOwner())
     {
         trigger->setFaction(owner->getFaction());
+        if (owner->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PVP_ATTACKABLE))
```
Comment (Vincent-Michael) [inline src/server/game/Entities/GameObject/GameObject.cpp]: https://github.com/TrinityCore/TrinityCore/blob/478cc756eb05591f36857be3ffd1895684529710/src/server/game/Entities/Object/Object.cpp#L1202 really need?

**Comment by Keader** [comment]
Work for me :+1:
