### PR TITLE
Core/AI: Fix assertion triggered with PetAI derived scripts

### LINKED ISSUE #21247: [CRASH] .npc add <pet creature id> crash
**Description:**
Executing command ".npc add 19668" and attacking the spawned npc triggers an assert
>D:\wow\TrinityCore\src\server\game\AI\CoreAI\PetAI.cpp:546 in PetAI::CanAttack ASSERTION FAILED:
me->GetCharmInfo()

**Steps to reproduce the problem:**

1. ".npc add 19668"
2. Attack the spawned creature
3. Crash

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 3d7166c1c78e 2018-01-16 14:44:04 -0300 (3.3.5 branch) (Win64, RelWithDebInfo, Static)

**TDB version:**  335.something

**Operating system:** Windows 10

[3d7166c1c78e_worldserver.exe_[16-1_20-42-30].txt](https://github.com/TrinityCore/TrinityCore/files/1636581/3d7166c1c78e_worldserver.exe_.16-1_20-42-30.txt)

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Fix assert triggered when spawning a Creature with AI inheriting from PetAI. The Creature will have a default AI instead.
- Remove unneeded null check since there's a check already few lines above

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #21247

**Tests performed:** (Does it build, tested in-game, etc.)
- built locally in Debug mode
- spawned Shadowfiend ".npc add 19668" and worldserver showed the error log. Attacking the NPC didn't trigger any assert.
- cast Shadowfiend spell, no error log appeared (meaning the PetAI is still loaded when allowed)
- tamed a Creature as a Pet (even if this test should be unrelated to the code involved)

**Known issues and TODO list:** (add/remove lines as needed)

none

### CODE REVIEW

**Comment by ariel-** [comment]
What about passing/checking CharmInfo on PetAI constructor?

**Comment by jackpoz** [comment]
and what do you plan to do in the constructor if CharmInfo is null ?

File: src/server/game/Scripting/ScriptMgr.cpp [hunk 1]
```diff
@@ -1599,7 +1600,19 @@ CreatureAI* ScriptMgr::GetCreatureAI(Creature* creature)
     ASSERT(creature);
 
     GET_SCRIPT_RET(CreatureScript, creature->GetScriptId(), tmpscript, nullptr);
-    return tmpscript->GetAI(creature);
+    CreatureAI* ai = tmpscript->GetAI(creature);
+
+    // Don't allow PetAI if there's no charm info in the creature
+    if (dynamic_cast<PetAI*>(ai))
```
Comment (Treeston) [inline src/server/game/Scripting/ScriptMgr.cpp]: "meh"

can't we make a new virtual method on `CreatureAI` that's called `IsValid` or something?

**Review by Treeston — CHANGES_REQUESTED** [review]

File: src/server/game/Scripting/ScriptMgr.cpp (hunk 1 above)
Comment (Shauren) [reply src/server/game/Scripting/ScriptMgr.cpp]: no, because then you are putting control back in hands of script and the point of this validation is to harden the core against bad scripts

Comment (jackpoz) [reply src/server/game/Scripting/ScriptMgr.cpp]: @Shauren what if we do
```c++
virtual bool CreatureAI::IsAIAllowed(Creature* creature) { return true;}
```
and then
```c++
bool PetAI::IsAIAllowed(Creature* creature) final override { return !!creature->GetCharmInfo(); }
```
using final override we should keep the check in the core without allowing any script to override it

Comment (Treeston) [reply src/server/game/Scripting/ScriptMgr.cpp]: @Shauren but a script has to _active_ suppress an inherited `IsAIAllowed`, while currently just inheriting from `PetAI` _passively_ causes crashes.

Comment (ariel-) [reply src/server/game/Scripting/ScriptMgr.cpp]: Then set PetAi as final so no one can inherit it

Comment (Treeston) [reply src/server/game/Scripting/ScriptMgr.cpp]: that'd lead to tons of code duplication

Comment (Shauren) [reply src/server/game/Scripting/ScriptMgr.cpp]: how about throwing an exception from PetAI constructor when charminfo is missing?

Comment (Treeston) [reply src/server/game/Scripting/ScriptMgr.cpp]: and catching that in `ScriptMgr`? that's reasonable, :+1:

Comment (Treeston) [reply src/server/game/Scripting/ScriptMgr.cpp]: if we catch it there we'd be leaking the half-constructed object, no?

**Comment by ariel-** [comment]
What if we fix the shadowfiend script instead? It's the only script inheriting from PetAI anyways

File: src/server/game/Scripting/ScriptMgr.cpp (hunk 1 above)
Comment (Shauren) [reply src/server/game/Scripting/ScriptMgr.cpp]: no, thats not how exceptions from constructors work, you do not return anything, you dont even get a pointer to use with operator delete (tl;dr, dont worry about it)

File: src/server/game/Entities/Unit/Unit.cpp [hunk 2]
```diff
@@ -10450,7 +10450,7 @@ void Unit::UpdateCharmAI()
                     if (isPossessed() || IsVehicle())
                         i_AI = new PossessedAI(ToCreature());
                     else
-                        i_AI = new PetAI(ToCreature());
+                        i_AI = new PetAI(ToCreature()); // <-- is there always a valid charm info at this point ?
```
Comment (jackpoz) [inline src/server/game/Entities/Unit/Unit.cpp]: is there always a valid charm info at this point or should be handle the exception ?

**Comment by jackpoz** [comment]
@Shauren leaving aside for a moment the fact that I used std::exception instead of a custom one (that should be somehow generic like InvalidAIException or so), is the current code what you had in mind ?
Tested ingame and debugged with breakpoints, both spawning the npc with command and with Priest spell, it worked correctly.

**Comment by Shauren** [comment]
Yes, thats exactly what I meant

**Comment by shamage** [comment]
@Shamage

yes in this sense, now it's okay :) thank you

File: src/server/game/AI/AIException.h [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+
+#include "Define.h"
+
+class TC_GAME_API InvalidAIException : public std::exception
+{
+public:
+    InvalidAIException(char const* const _message);
+    ~InvalidAIException() throw() { }
+
+    char const* what() const throw() override { return msg_.c_str(); }
```
Comment (Shauren) [inline src/server/game/AI/AIException.h]: replace `throw()` with `noexcept`

**Review by Shauren — CHANGES_REQUESTED** [review]

File: src/server/game/AI/AIException.h [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+
+#ifndef TRINITY_AIEXCEPTION_H
+#define TRINITY_AIEXCEPTION_H
+
+#include "Define.h"
+
+class TC_GAME_API InvalidAIException : public std::exception
+{
+public:
+    InvalidAIException(char const* const _message);
```
Comment (Shauren) [inline src/server/game/AI/AIException.h]: second const is unneccessary here (the one after *)

File: src/server/game/AI/CreatureAISelector.cpp [hunk 5]
```diff
@@ -84,8 +85,16 @@ namespace FactorySelector
...
 
         // scriptname in db
-        if (CreatureAI* scriptedAI = sScriptMgr->GetCreatureAI(creature))
-            return scriptedAI;
+        try
+        {
+            if (CreatureAI* scriptedAI = sScriptMgr->GetCreatureAI(creature))
+                return scriptedAI;
+        }
+        catch (const InvalidAIException& e)
```
Comment (Shauren) [inline src/server/game/AI/CreatureAISelector.cpp]: const after type

File: src/server/game/AI/AIException.h [hunk 6]
```diff
@@ -0,0 +1,39 @@
+/*
+* Copyright (C) 2008-2018 TrinityCore <https://www.trinitycore.org/>
+* Copyright (C) 2005-2009 MaNGOS <http://getmangos.com/>
```
Comment (Shauren) [inline src/server/game/AI/AIException.h]: and mangos shouldnt be here, its our own new file

**Review by Shauren — APPROVED** [review]

File: src/server/game/AI/AIException.cpp [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+ *
+ * You should have received a copy of the GNU General Public License along
+ * with this program. If not, see <http://www.gnu.org/licenses/>.
+ */
+
+#include "AIException.h"
+
+InvalidAIException::InvalidAIException(char const* _message)
+{
+    message().assign(_message);
```
Comment (Treeston) [inline src/server/game/AI/AIException.cpp]: do we really need a `.cpp` for this? `<string>` is visible in the header

File: src/server/game/AI/AIException.h [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+class TC_GAME_API InvalidAIException : public std::exception
+{
+public:
+    InvalidAIException(char const* _message);
+    ~InvalidAIException() throw() { }
+
+    char const* what() const noexcept override { return msg_.c_str(); }
+
+protected:
+    std::string & message() throw() { return msg_; }
```
Comment (Treeston) [inline src/server/game/AI/AIException.h]: is it required that this be a non-const ref?

if not, `msg_` could be a `const` member

File: src/server/game/AI/AIException.cpp (hunk 7 above)
Comment (jackpoz) [reply src/server/game/AI/AIException.cpp]: it always makes sense to declare in .h and then implement in .cpp

Comment (Treeston) [reply src/server/game/AI/AIException.cpp]: it doesn't if you're adding a whole new compilation unit for no particular reason...

File: src/server/game/AI/AIException.h (hunk 8 above)
Comment (Treeston) [reply src/server/game/AI/AIException.h]: is that a yes or a no? I don't care if it's the same as some other class...
