### PR TITLE
Core/Unit: Fix movement hiccups in water

### LINKED ISSUE #21872: [MMAP] NPC movement hiccups
**Description:**

NPC's movement is strange:

1. moving over obstacles (objects too high to walk over)
2. moving up/down (hiccupping) inside houses, caves, instances (wmo's ?)
3. moving up/down (hiccupping) when underwater

**Current behaviour:**

Incorrect movement. I'm pretty sure this all worked correctly in one of he previous revisions - not sure which (~month ago)

**Expected behaviour:**

1. NPC's should NOT walk on top of / over obstacles when their movement is set as random (not sure what should happen for waypoint movement)
2. NPC's shouldn't hiccup when stepping from terrain to house and vice versa. Narrow places cause NPC's to move into the ceiling...
3. underwater/water NPC's should swim or walk on the ocean floor (like crabs) 

**Steps to reproduce the problem:**

1. A great example for this bug(s) is Darkshire. Observe various moving NPC's there:
Town Crier (entry 468) for example, is showing first two symptoms: [https://gph.is/2qTpgLI](https://gph.is/2qTpgLI) 
Watcher Jordan (entry 887) moves over the fountain.
Night Watch Guard (entry 10038, spawn id: 6133) gets stuck in house wall above the ground (at one point he disappeared inside the wall completely).
2. Various crabs at Zoram Strand (and other underwater places): [https://gph.is/2F7V0So](https://gph.is/2F7V0So)
Blackfathom Deeps' underwater parts exhibit all these problems. Try attacking one of the murlocs/nagas and swim underwater and above the water.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. f1ab32fbb7d5 2018-04-22 17:22:26 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.1u  22 Sep 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.60.0
Using MySQL version: 5.5.58
Using CMake version: 3.10.2
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 byte
mmaps directory located in ./mmaps. Total size: 2152621724 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Win 10 x64

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

- Add UNIT_FLAG_SWIMMING to Creatures that can enter water when in combat
- Fix creatures with Swim creature_movement_template but without UNIT_FLAG_SWIMMING flag not sticking to the bottom of the sea, i.e. crabs

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #21872

**Tests performed:** (Does it build, tested in-game, etc.)
None

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Something about charmed units

### CODE REVIEW

**Comment by Killyana** [comment]
I made some tests and the only issues I found is about charmed units (not summoned pets).
If you charm a creature that has "Movement type: Swim: false" then go to the water and brake the charm, it will behave weirdly (it will react passive and keeps following you)
This doesn't happen to creature that cannot walk at the ground, they will just stay in the water, this looks to be the correct way to handle this cases.

So must probably do the same for creature that cannot swim, they will not enter water and remains at the edge.

I changed  "if (IsPet())" to "if (IsPet() && IsSummon())"  but the charmed creature was still able to enter the water

To reproduce:
1. .go c 36874
2. .cast 260
3. go to the water
4. dismiss the creature
5. notice the behaviour

**Comment by Killyana** [comment]
Also If you send the controlled unit (.go c 36874) to attack mobs in the water it will not move.
If you .npc info you will see * UNIT_FLAG_SWIMMING (0x8000)  is missing

If you mind control a crab Entry: 2231 it will not get * UNIT_FLAG_SWIMMING (0x8000)  until it starts a combat

File: src/server/game/Entities/Creature/Creature.cpp [hunk 1]
```diff
@@ -2669,6 +2669,13 @@ CreatureMovementData const& Creature::GetMovementTemplate() const
     return GetCreatureTemplate()->Movement;
 }
 
+bool Creature::CanEnterWater() const
+{
```
Comment (Ovahlord) [inline src/server/game/Entities/Creature/Creature.cpp]: Isn't there CanSwim already? Why not just adding the pet check there instead?

Comment (illfated) [reply src/server/game/Entities/Creature/Creature.cpp]: I don't know the coding involved, but there is a technical difference between creatures being blocked (by their AI) from entering water and the same creatures being able to swim if you spawn them in water.

Comment (jackpoz) [reply src/server/game/Entities/Creature/Creature.cpp]: CanEnterWater() means a Unit can walk into water mesh, i.e. setting the NAV_WWATER filter in MMAPs to allow crossing rivers/lakes and reach enemies in water.

CanSwim() means the Unit is able to lift itself above sea bottom and reach targets floating in the water.

An Unit with CanEnterWater() but without CanSwim() will walk at the bottom of the sea, like a crab for example, and the Z coordinate returned by MMAPs will be GetGroundHeight() and not GetGroundOrWaterLevel().
In current TC crabs sometime get water level,  making them teleport at water level and then instantly sink to the bottom (as they are missing the flags that would allow them to swim)

**Comment by jackpoz** [comment]
@Killyana a lot of checks are missing in this PR and a lot of cases still need to be handled,  thanks for the tests

File: src/server/game/Entities/Creature/Creature.cpp (hunk 1 above)
Comment (Ovahlord) [reply src/server/game/Entities/Creature/Creature.cpp]: The 'teleport' is not properly solved by using the unit flag. It's actually handled by a currently wrong handled spline flag: Walkmode which is actually CanSwim. It has been corrected on master already and I've also backported it for 4.3.4 (and it solves the visual issue you describe) and I am sure this applies to 335 as well.

As for the ground underwater movement I would simply go with Groundlevel by default if CanSwim returns false or the unitflag is not set.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 2]
```diff
@@ -12647,14 +12647,19 @@ bool Unit::IsFalling() const
...
     if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_CANNOT_SWIM))
         return false;
     if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED)) // is player
         return true;
     if (HasFlag(UNIT_FIELD_FLAGS_2, 0x1000000))
         return false;
-    if (IsPet() && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PET_IN_COMBAT))
+    if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PET_IN_COMBAT))
         return true;
     return HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_RENAME | UNIT_FLAG_SWIMMING);
```
Comment (VincentVanclef) [inline src/server/game/Entities/Unit/Unit.cpp]: why is UNIT_FLAG_RENAME here xD? What does that have to do with swimming?

Comment (Shauren) [reply src/server/game/Entities/Unit/Unit.cpp]: I know it seems stupid but that function was ripped from the client and that was the flag value used there

**Comment by jackpoz** [comment]
@Ovahlord did you have another way to solve the same issue or should I continue working on this PR ?

**Comment by Ovahlord** [comment]
I think u can just finish this one here.

**Comment by jackpoz** [comment]
> If you charm a creature that has "Movement type: Swim: false" then go to the water and brake the charm, it will behave weirdly (it will react passive and keeps following you)

This happens even without going inside any water if I use ".cast 260" . Maybe it's an unrelated bug ?

**Comment by jackpoz** [comment]
Turns out PathFinding always adds WATER filter if the creature is in water (according to map/vmap) which makes every creature always go into water anyway

**Comment by illfated** [comment]
Hm, so would it be necessary to remove water from quite a lot of specific tiles, to make it work as expected?

**Comment by jackpoz** [comment]
more like handle this case in a different way:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/PathGenerator.cpp#L640-L641

**Comment by illfated** [comment]
Interesting, thanks. I see quite a few edge cases in our future. ;-)

File: src/server/game/Entities/Creature/Creature.cpp (hunk 1 above)
Comment (Faq) [reply src/server/game/Entities/Creature/Creature.cpp]: > As for the ground movement, I would simply go with groundlevel if CanSwim returns false. No need to do additional fancy magic. If a unit is not able to swim it should stick on the ground in all cases. Just move the unit flag and pet check to the CanSwim helper and be done with it and keep the path generator changes to ignore water level of CanSwim returns false.

Sounds plain and simple. If no swim flag, it walks, no matter, there is water or not.

**Comment by jackpoz** [comment]
This PR contains some useful information to fix the issue (which is in the end related mostly to UNIT_FLAG_SWIMMING flag).
If anyone would like to continue working on it, feel free to do it.

File: src/server/game/Entities/Creature/Creature.cpp (hunk 1 above)
Comment (jackpoz) [reply src/server/game/Entities/Creature/Creature.cpp:2698]: This is already in 335 and that didn't fix the issue

**Comment by jackpoz** [comment]
> I made some tests and the only issues I found is about charmed units (not summoned pets).
> If you charm a creature that has "Movement type: Swim: false" then go to the water and brake the charm, it will behave weirdly (it will react passive and keeps following you)
> This doesn't happen to creature that cannot walk at the ground, they will just stay in the water, this looks to be the correct way to handle this cases.
> 
> So we must probably do the same for creature that cannot swim, they will not enter water and remains at the edge.
> 
> I changed "if (IsPet())" to "if (IsPet() && IsSummon())" but the charmed creature was still able to enter the water
> 
> To reproduce:
> 
> 1. .go c 36874
> 2. .cast 260
> 3. go to the water
> 4. dismiss the creature
> 5. notice the behaviour

this seems to work now

**Comment by jackpoz** [comment]
> Also If you send the controlled unit (.go c 36874) to attack mobs in the water it will not move.
> If you .npc info you will see * UNIT_FLAG_SWIMMING (0x8000) is missing

Fixed this one too with https://github.com/TrinityCore/TrinityCore/pull/24020/commits/322c1d40d5fe1e71b712e39cb8392bb85d73ab76

**Comment by jackpoz** [comment]
> If you mind control a crab Entry: 2231 it will not get * UNIT_FLAG_SWIMMING (0x8000) until it starts a combat

And fixed this one too

**Comment by jackpoz** [comment]
This PR is ready to be tested. If possible please re-test all the cases described in the different comments of this PR. I will host it at https://tcubuntu.northeurope.cloudapp.azure.com/test/ where every new account will have gm seclevel 3 to make things easier to test.

**Comment by jackpoz** [comment]
I cleaned up the code a bit and changed Creature::UpdateMovementFlags() to use CanSwim()

**Comment by Shauren** [comment]
creature_movement_template.Swim is now ignored, this is not ok

**Comment by jackpoz** [comment]
@Shauren it's checked at https://github.com/TrinityCore/TrinityCore/pull/24020/files#diff-2222cde2ff898034f0ce38bba2d5755cbdeef050c328b2d56599bc6d6664afc1R2713 . If I pull in combat a mob with .Swim false, the mob evades when I enter water and the mob cannot reach me.

**Comment by gygyti** [comment]
what about Segacedi?

-> **[https://imgur.com/a/UYbEIJe](https://imgur.com/a/UYbEIJe)**

[https://www.wowhead.com/npc=32664/segacedi](https://www.wowhead.com/npc=32664/segacedi)

**Comment by Faq** [comment]
@gygyti make a new issue.

**Comment by jackpoz** [comment]
@gygyti have you tried before and after this PR ?

**Comment by gygyti** [comment]
before this PR, I did not check Segacedi, there was only a check on 0dee695

**Comment by gygyti** [comment]
not sure if this is relevant, but I'll add this video 

https://user-images.githubusercontent.com/77268574/107887339-7c482a80-6f16-11eb-9c9c-68208924b9c1.mp4

**Comment by jackpoz** [comment]
any explaination with the video or ?

**Comment by gygyti** [comment]
this crab in my opinion should not do such jumps

**Comment by jackpoz** [comment]
Are you in combat with it ? Do you have .gm on ? Why is it even following you ?

**Comment by gygyti** [comment]
I just hit him to be aggressive, gm is off (it's not a gm account. Regular player )

**Comment by jackpoz** [comment]
shouldn't it be red then ? was your character in combat ?

**Comment by Faq** [comment]
This goes nowhere, now looks like that is pet. @gygyti just make a new issue where is this all described in details.

**Comment by gygyti** [comment]
these are not pets 
entry: 3106, 3104
@Faq I can open a new issue, but everything is described in this thread 

https://user-images.githubusercontent.com/77268574/107984698-8e3ed180-6fd9-11eb-96d8-85ba33651271.mp4


https://user-images.githubusercontent.com/77268574/107984708-9434b280-6fd9-11eb-95a3-11f07acb823d.mp4

**Comment by jackpoz** [comment]
@gygyti could you please reproduce that on https://tcubuntu.northeurope.cloudapp.azure.com/ ?

**Comment by gygyti** [comment]
wow no, they swim fine on tcubuntu.northeurope.cloudapp.azure.com

**Comment by gygyti** [comment]
but why then such a difference?  should i set up worldserver.conf?

**Comment by illfated** [comment]
> but why then such a difference? should i set up worldserver.conf?

It could have something to do with the maps/vmaps/mmaps files generated from your game client, and how they affect the creature movement. Troubleshooting your game client map issues could sometimes come down to comparing your output from `.server debug` with one from a better working server.

I also have the disadvantage of owning the enGB client (2006—2010) instead of the enUS one, which in some forums is seen as a guaranteed source of client bugs for gameobjects and more.

TrinityCore rev. c3165dce316d 2021-02-19 18:13:10 +0100 (3.3.5 branch) (Win64, Release, Static)
```sql
TC> server debug
TrinityCore rev. c3165dce316d 2021-02-19 18:13:10 +0100 (3.3.5 branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1i  8 Dec 2020 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50732
Using CMake version: 3.19.2
Compiled on: Windows 10.0.19042
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21021
TC> _
```

**Comment by gygyti** [comment]
wow, didn't even think about it. I would like to get a client which is at tcubuntu.northeurope.cloudapp.azure.com 

TrinityCore rev. 8b2fd345e7b0 2020-12-13 12:49:32 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Using MySQL version: 100327
Using CMake version: 3.13.4
Compiled on: Linux 4.19.0-12-amd64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /data/maps. Total size: 251987687 bytes
vmaps directory located in /data/vmaps. Total size: 658130721 bytes
mmaps directory located in /data/mmaps. Total size: 1962380076 bytes
Using ruRU DBC Locale as default. All available DBC locales: ruRU
Using World DB: TDB 335.21011

**Comment by illfated** [comment]
> I would like to get a client which is at tcubuntu.northeurope.cloudapp.azure.com

I think you meant to say that you would like to have a copy the maps/vmaps/mmaps files from the tcubuntu server, but that is understandable. TC does not share binary/compiled files, though, so we may have to get used to having less perfect server files than tcubuntu.northeurope.cloudapp.azure.com . You could try asking in IRC or Discord if someone else has got equally accurate files to share personally with you.

You could also try downloading (torrent) a clean and good enUS game client from a trusted source (read all the available user comments before downloading) and see if that helps you generate more correct dbc/maps/vmaps/mmaps files for your own use. I have not experimented much with that myself, but I sort of know that I should if I want more precise maps than the ones I am using.

**Comment by Aokromes** [comment]
notice:

maps directory located in ./maps. Total size: 251987687 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1962379500 bytes

vs

maps directory located in /data/maps. Total size: 251987687 bytes
vmaps directory located in /data/vmaps. Total size: 658130721 bytes
mmaps directory located in /data/mmaps. Total size: 1962380076 bytes

**Comment by gygyti** [comment]
interesting difference in size.
I've always been tempted to find the old original 3.3.5 disk and get the data from there. This will definitely be the best.

By the way, the warlock's pets (possibly other mages, hunters) often fall into the ground, and in places like airships (ICC battles on ships, too) they do not obey orders at all. (I'll open a new issue about this)

**Comment by jackpoz** [comment]
> rinityCore rev. [8b2fd34](https://github.com/TrinityCore/TrinityCore/commit/8b2fd345e7b0581e74add60db5410e1ae109c5fd) 2020-12-13 12:49:32 +0200 (3.3.5 branch) (Unix, RelWithDebInfo, Static)

This branch was merged on 2021-01-10, update your worldserver
