### PR TITLE
Core/Spells: Fix incanters flow

### LINKED ISSUE #19586: Core/Script The talent Incanter´s Flow doesn´t work.
**Description:**

The talent Incanter´s Flow(ID:1463) given to Mage Frost at lv.45 has an issue

Incanter´s Flow (passive): Magical energys flow´s through you while in combat, building up to 20% increased damage and them diminiching down to 4% increased damage, cycling every 10 sec.

**Current behaviour:**

The talent doesn´t work, the effect is nerver activated

**Expected behaviour:**

While you are in combat your damage will be increase 20% and them will diminiching down by 4% until get normal, this effect will happen every 10 sec. 

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.45, choose the Frost Spec and the talent Incanter´s Flow from lv.45 branch
3. Attack an enemy and check the magical damage

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=1463/incanters-flow

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Fix mage talent incanter's flow

Closes #19586

**Tests performed:**

Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -1098,6 +1099,56 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+            return;
+        }
+
+        if (Aura* aura = GetTarget()->GetAura(SPELL_MAGE_INCANTERS_FLOW))
+        {
+            uint32 stacks = aura->GetStackAmount();
+            if (aurEff->GetAmount() == 0 || (stacks == 1 && aurEff->GetAmount() == 1)) // 0 = stack up, 1 = remove stack
+            {
+                if (stacks == 5)
+                    const_cast<AuraEffect*>(aurEff)->SetAmount(1);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:1127]: Can you store the direction (up/down) as a member of this script instead of having to `const_cast` aurEff?

File: src/server/scripts/Spells/spell_mage.cpp [hunk 2]
```diff
@@ -1098,6 +1099,56 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                    GetTarget()->CastSpell(GetTarget(), SPELL_MAGE_INCANTERS_FLOW, true);
+            }
+            else if (stacks > 1 && aurEff->GetAmount() == 1)
+                aura->ModStackAmount(-1);
+        }
+        else
+            GetTarget()->CastSpell(GetTarget(), SPELL_MAGE_INCANTERS_FLOW, true);
+    }
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:1140]: This entire hook is unneccessary, SPELL_MAGE_INCANTERS_FLOW will be removed by interrupt flag when you remove the talent

**Review by Shauren — CHANGES_REQUESTED** [review]

File: src/server/scripts/Spells/spell_mage.cpp (hunk 1 above)
Comment (Shauren) [reply src/server/scripts/Spells/spell_mage.cpp]: Not what I had in mind

File: src/server/scripts/Spells/spell_mage.cpp [hunk 3]
```diff
@@ -724,6 +725,52 @@ class spell_mage_imp_mana_gems : public AuraScript
...
+
+        if (Aura* aura = GetTarget()->GetAura(SPELL_MAGE_INCANTERS_FLOW))
+        {
+            uint32 stacks = aura->GetStackAmount();
+            if (aurEff->GetAmount() == 0 || (stacks == 1 && aurEff->GetAmount() == 1)) // 0 = stack up, 1 = remove stack
+            {
+                AuraEffect* aurEff = GetAura()->GetEffect(EFFECT_0);
+
+                int8 up = 0;
+                int8 down = 1;
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:752]: That is not what I had in mind

**Review by Shauren — APPROVED** [review]
