### PR TITLE
Script/Spells: shaman spells

### LINKED ISSUE #26182: Core/Spell - Not working spells, Shaman class 9.0.2
**Description:**
The following spells do not work:
(318038) Flametongue Weapon - Does nothing when used.
(8143) Tremor Totem - The summoned totem does nothing, or is not summoned at all (Npc id: 5913). 
(5394) Healing Stream Totem - The summoned totem does nothing (Npc id: 3527). Heal spell from totem, 52042
(192222) Liquid Magma Totem - The summoned totem does nothing (Npc id: 97369). Totem using spell 192226 (this only visual)
(73920) Healing Rain - Does nothing when used. Visual spell 147490, heal spell 73921.
(192058) Capacitor Totem - The summoned totem does nothing (Npc id: 61245). Totem using spell, 118905.

**Expected behaviour:**

(318038) Flametongue Weapon - Should apply an effect to the weapon on the left hand when used.
(8143) Tremor Totem - When used, must remove stun debuffs from party members or allies within 30m.
(5394) Healing Stream Totem - Heals allies (47% of Spell power) within 40m every 2 seconds for 15 seconds.
(192222) Liquid Magma Totem - The summoned totem attacks the enemy with liquid magma.
(73920) Healing Rain - Heals allies within the radius for 10 seconds. [(26.5% of Spell power) * 6 * 2 / 2]
(192058) Capacitor Totem - When a totem is summoned, after 2 seconds it explodes, stunning enemies within a radius of 8m, for 3 seconds.

**Steps to reproduce the problem:**

1. Create a Shaman class character.
2. Give a character 60 lvl.
3. Try using any of the spells listed.

**Branch(es):**

master

**TC rev. hash/commit:** 

c86cffe

**Operating system:** 

Windows 10 x64

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Flametongue Weapon
- Tremor Totem
- Healing Stream Totem
- Liquid Magma Totem
- Healing Rain

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26182 

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

File: src/server/scripts/Spells/spell_shaman.cpp [hunk 1]
```diff
@@ -415,40 +426,148 @@ class spell_sha_elemental_blast : public SpellScriptLoader
...
+    {
+        return ValidateSpellInfo({ SPELL_SHAMAN_FLAMETONGUE_ATTACK });
+    }
+
+    void HandleEffectProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+
+        Unit* attacker = eventInfo.GetActor();
+        int32 damage = int32(attacker->GetTotalAttackPowerValue(BASE_ATTACK) * 0.0264f);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_shaman.cpp:479]: where does 0.0264f come from?

File: src/server/scripts/Spells/spell_shaman.cpp [hunk 2]
```diff
@@ -415,40 +426,148 @@ class spell_sha_elemental_blast : public SpellScriptLoader
...
+            m_summon->DisappearAndDie();
+    }
+
+    void Register()
+    {
+        OnEffectRemove += AuraEffectRemoveFn(spell_sha_healing_rain_aura::HandleEffecRemoved, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY, AURA_EFFECT_HANDLE_REAL);
+        OnEffectPeriodic += AuraEffectPeriodicFn(spell_sha_healing_rain_aura::HandleEffectPeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
+    }
+
+    TempSummon* m_summon;
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_shaman.cpp:530]: we're using `_<name>` for private variables instead of `m_<name>` nowadays

File: src/server/scripts/Spells/spell_shaman.cpp [hunk 3]
```diff
@@ -415,40 +426,148 @@ class spell_sha_elemental_blast : public SpellScriptLoader
...
+
+    void Register()
     {
-        return new spell_sha_flametongue_AuraScript();
+        OnEffectHitTarget += SpellEffectFn(spell_sha_healing_rain::HandleSummon, EFFECT_0, SPELL_EFFECT_DUMMY);
+        OnEffectHitTarget += SpellEffectFn(spell_sha_healing_rain::HandleAura, EFFECT_1, SPELL_EFFECT_APPLY_AURA);
     }
+
+private:
+    TempSummon* m_summon;
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_shaman.cpp:570]: same here

File: src/server/scripts/Spells/spell_shaman.cpp (hunk 1 above)
Comment (Ovahlord) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: Tooltip. Most attack power formulas are in the tooltips

Comment (Warpten) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: It's also in Attack power coefficient on the spell

Comment (Warpten) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: It's also in Attack power coefficient on the spell

Comment (matanshukry) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: @Warpten is it possible to get it through some object rather than hardcode then?
I've tried to use `aurEff->GetSpellEffectInfo()->BonusCoefficient` and `aurEff->GetSpellEffectInfo()->BonusCoefficientFromAP`, but both return 0.0f

Comment (Robingadko) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: > It's also in Attack power coefficient on the spell

Not for this spell. I also was not able to get the coefficient value from anywhere.

Comment (matanshukry) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: @Robingadko then again Spellwork gets it from somewhere, so there has to be someway to get it without hardcoding.

Comment (Robingadko) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: @matanshukry I may be wrong but as far as I understand SpellWork takes that metadata info from SpellDescriptionVariables.db2 which is not loaded by server.

Comment (Robingadko) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: @matanshukry According to tooltip the damage is max((0.0264 * Attack power), 1) so that there's no zero damage at low levels.

Comment (matanshukry) [reply src/server/scripts/Spells/spell_shaman.cpp:479]: @Robingadko I missed that max, thanks

**Comment by P-Kito** [comment]
Im surprised that there is no areatrigger involved

**Comment by matanshukry** [comment]
Actually recently I thought about using areatrigger for spell scripts and was wondering how did these spells work without it.

I'll go over it again soon to verify that and compare.
