### PR TITLE
Core/GameObject: implement restock mechanic for non-consumable gameobjects

### LINKED ISSUE #23451: Core/GameObject: Restock for chests
**Description:** The restock for gobs type chest is not implemented or implemented wrongly: https://github.com/TrinityCore/TrinityCore/commit/7011aabb56f061fc889ec42ce32b7605ceb35b53

GAMEOBJECT_TYPE_CHEST = 3
data2: chestRestockTime (time in seconds)
data3: consumable (State: Boolean flag)

Chest that must Restock/despawn:

- The ones with data2=0 AND data3=0: this chests didn't despawn and regenerate loots instantly, they all contains unique quest item
``` sql
SELECT * FROM gameobject_template WHERE TYPE=3 AND data2=0 AND data3=0;
```

- The ones with data2>0 AND data3=0: this chests didn't despawn and regenerate loots after X secs= data2 , they could contains quest item or any kind of item, If the chest contain 2 items or more and only one is looted the restock must reset the looted item inside the gob after X secs= data2
``` sql
SELECT * FROM gameobject_template WHERE TYPE=3 AND data2>0 AND data3=0;
```

- The ones with data2>0 AND data3=1: this chests despawns once empty and regenerate loots after X secs= data2  if not all items are looted (it depawns once empty), they could contains quest items or any kind of item, If the chest contains 2 items or more and only one is looted the restock must reset the looted item inside the gob after X secs= data2
``` sql
SELECT * FROM gameobject_template WHERE TYPE=3 AND data2>0 AND data3=1;
```

- The ones with data2=0 AND data3=1, this chests despawns once empty and doesn't regenerate loots.
``` sql
SELECT * FROM gameobject_template WHERE TYPE=3 AND data2=0 AND data3=1;
```

This must be implemented with https://github.com/TrinityCore/TrinityCore/issues/15730#issuecomment-486457812 to avoid having conflict with respawn/Restock

**Branch(es):** both

**TC rev. hash/commit:** rev. 9083fc149d61

### PR DESCRIPTION
**Pull request by Wyrserth**
**Changes proposed:**

Some gameobject chests should never despawn (data3 = 0) but instead they become inactive until their loot is restocked (data2 > 0).

This PR implements this behavior, and fixes the following cases:

-  Only one quest item inside the gameobject, it is looted: chest becomes inactive (not usable) until the restock time passes. Then it regens the loot and becomes activable.
-  Two quest items inside the gameobjects, one is looted: the other remains available and the gameobject remains active. When the restock timer elapses, the other item is regenerated.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** closes #23451 by fixing the remaining issues listed there.

**Tests performed:** it works.

### CODE REVIEW

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 1]
```diff
@@ -2321,6 +2348,27 @@ void GameObject::SetLootState(LootState state, Unit* unit)
     }
 }
 
+void GameObject::SendLootStateUpdateToNearbyPlayers()
```
Comment (Shauren) [inline src/server/game/Entities/GameObject/GameObject.cpp]: What exactly is the point of this function here

Comment (Wyrserth) [reply src/server/game/Entities/GameObject/GameObject.cpp]: Gameobjects don't send update field changes when their loot state changes, this causes some issues like gameobjects being still active after a player loots the last quest item. This forces an update to all nearby players so they see the gameobject as activable or not activable depending on state.

Comment (Shauren) [reply src/server/game/Entities/GameObject/GameObject.cpp]: Just call `AddToObjectUpdateIfNeeded()` to schedule the update at the end of Map::Update, you are talking about GAMEOBJECT_DYNAMIC field which is always sent (if object gets its update sent), don't force immediate packet

Comment (Wyrserth) [reply src/server/game/Entities/GameObject/GameObject.cpp]: Fixed, thanks!

**Comment by Killyana** [comment]
Everything looks fine, there's an issue about the gob state not being updated on client side when the player fulfill a quest objective, but it's an old issue that could be fixed later.
Some gobs have wrong loots and must be fix to avoid abuse like:
https://woehead.way-of-elendil.fr/?object=1765
``` sql
DELETE FROM `gameobject_loot_template` WHERE `entry`=1570 AND `Item`!=3706;
