### PR TITLE
Scripts/Mage: Implemented Flurry

### LINKED ISSUE #19585: Core/Script The spell Flurry doesn´t work.
**Description:**

The spell Flurry(ID:44614) given to Mage Frost at lv.20 has an issue

Flurry: Unleach a flurry of ice shards, striking the target 3 time for a total of (x) frost damage. Each shard reduces the target´s movement speed by 70% for 1 sec

**Current behaviour:**

The spell doesn´t work at all, when you cast the spell nothing happen, you don´t attack the target and any visual effect is activated

**Expected behaviour:**

when you use the spell you should strike the target 3 times with ice shards for (x) total damage and each ice shards should reduce the movement of the target 70% for 1 sec 

**Steps to reproduce the problem:**

1. Create a Mage character
2. Reach lv.20 and choose the Frost Spec
3. Use the spell Flurry in an enemy

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=44614/flurry

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement flurry talent

**Issues addressed:**

Closes #19585

**Tests performed:**

Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -816,6 +818,81 @@ class spell_mage_flame_on : public AuraScript
...
+    {
+        return ValidateSpellInfo
+        ({
+            SPELL_MAGE_FLURRY_DAMAGE
+        });
+    }
+
+    void EffectHit(SpellEffIndex)
+    {
+        GetCaster()->m_Events.AddEventAtOffset(new FlurryEvent(GetCaster(), GetHitUnit()->GetGUID(), GetEffectValue() - 1), randtime(200ms, 300ms));
```
Comment (Ovahlord) [inline src/server/scripts/Spells/spell_mage.cpp:863]: milliseconds like this usually imply that such events should happen alongside the main proc so better remove it alltogether and just move it into the effect handler

Comment (Shauren) [reply src/server/scripts/Spells/spell_mage.cpp:863]: No, EFFECT_1 of this spell is a SPELL_EFFECT_TRIGGER_MISSILE which also deals damage

Comment (Ovahlord) [reply src/server/scripts/Spells/spell_mage.cpp:863]: So why not attaching that part to the missile then?
