### PR TITLE
Script/Spell: fix Midsummer's Juggling Torch

### LINKED ISSUE #17446: [3.3.5] [Achievement] Torch Juggler - Midsummer Fire Festival
Achievement [Torch Juggler] doesn't seems to work, when you use the Item http://www.wowhead.com/item=34599 nothing happens, no animation.

This is how it should work:

https://www.youtube.com/watch?v=iK-R09RM6Fo

3.3.5a
bdec8297d0349baa03cda3ff193c486c9a046000
TDB 61

### PR DESCRIPTION
**Pull request by Rothend**
**Changes proposed:**

This PR fixes the on-use effect of the item [Juggling Torch](https://www.wowhead.com/item=34599) and the related [Torch Juggler](https://www.wowhead.com/achievement=272) achievement.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes #17446

**Tests performed:** tested, works.

### CODE REVIEW

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 1]
```diff
@@ -1668,6 +1668,106 @@ class spell_midsummer_ribbon_pole_periodic_visual : public AuraScript
...
+            torchSpellID = SPELL_JUGGLE_TORCH_MEDIUM;
+            torchShadowSpellID = SPELL_JUGGLE_TORCH_SHADOW_MEDIUM;
+        }
+        else
+        {
+            torchSpellID = SPELL_JUGGLE_TORCH_FAST;
+            torchShadowSpellID = SPELL_JUGGLE_TORCH_SHADOW_FAST;
+        }
+
+        GetCaster()->CastSpell(spellDest.GetPosition(), torchSpellID);
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_holiday.cpp:1735]: is .GetPosition() needed even if spellDest is already of type Position ?

Comment (Rothend) [reply src/server/scripts/Spells/spell_holiday.cpp:1735]: You're right, it's a leftover of some experimentation with WorldLocation on my part. Thanks, will remove now!

**Comment by jackpoz** [comment]
Thanks for the PR :)
