### PR TITLE
Core/Creatures: Profession trainer fixes

### LINKED ISSUE #22903: Professions
**Description:**

For some reason I can learn more than 2 primary professions.

**Current behaviour:**

I just went and learned Alchemy and Herbalism and for some reason it'll let me learn Tailoring, Blacksmithing and Engineering. The whole lot pretty much.

**Expected behaviour:**

Should not be able to have more than 2 professions learned unless of course you change the setting from 2 to whatever in the config.

**Steps to reproduce the problem:**

1. Go to any profession trainer and you should (well I can) learn all the primary professions.

**Branch(es):**

3.3.5a

**TC rev. hash/commit:** 

TrinityCore rev. 66720e5fd940 2018-12-31 11:50:16 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** Windows Server 2016

### PR DESCRIPTION
**Pull request by Ghaster**
**Changes proposed:**

- Correctly check TriggerSpell for professions instead of ReqAbility.
- Fixed an issue, where profession ranks counted towards the max profession amount.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #22903 

**Tests performed:** Builds, tested by attempting to train more than two professions, along with training next rank of a profession.

**Known issues and TODO list:**
- Cleanup?

### CODE REVIEW

File: src/server/game/Entities/Creature/Trainer.cpp [hunk 1]
```diff
@@ -48,10 +48,17 @@ namespace Trainer
             if (!player->IsSpellFitByClassAndRace(trainerSpell.SpellId))
                 continue;
 
+            SpellInfo const* trainerSpellInfo = sSpellMgr->AssertSpellInfo(trainerSpell.SpellId);
+            if (!trainerSpellInfo)
```
Comment (jackpoz) [inline src/server/game/Entities/Creature/Trainer.cpp]: AssertSpellInfo() is supposed to never return null

File: src/server/game/Entities/Creature/Trainer.cpp [hunk 2]
```diff
@@ -132,9 +139,19 @@ namespace Trainer
             return false;
 
         SpellInfo const* trainerSpellInfo = sSpellMgr->AssertSpellInfo(trainerSpell->SpellId);
-        if (trainerSpellInfo->IsPrimaryProfessionFirstRank() && !player->GetFreePrimaryProfessionPoints())
+        if (!trainerSpellInfo)
```
Comment (jackpoz) [inline src/server/game/Entities/Creature/Trainer.cpp]: AssertSpellInfo() is supposed to never return null (here too)

**Review by jackpoz — CHANGES_REQUESTED** [review]

**Comment by Treeston** [comment]
Could do with some more explanation. What logic error does this address?

`ReqAbility` is what? What is the changed check supposed to test for, and what did it (incorrectly) test for instead?

Changes look correct to me, but could do with elaboration.

**Comment by Ghaster** [comment]
When adding a spell to a trainer, one can add up to 3 spells, that the player needs to have, before they can learn that spell. That is what `ReqAbility` is for.

Before the trainer revamp, `ReqAbility` was not stored anywhere, but was rather generated by the core from the SpellID. An issue was that the `ReqAbility` that was stored in the core, was not the same `ReqAbility` that the server would send to the client (as seen here): https://github.com/TrinityCore/TrinityCore/blob/59e94fd9bb1ff82d9a34a6c693b680039c3a68b9/src/server/game/Handlers/NPCHandler.cpp#L199-L223

With the trainer revamp, this has now been fixed, as `ReqAbility` is now stored alongside all the other requirements. However, some of the checks related to making sure the player does not learn more than two professions, were not updated to take advantage of the "new" `ReqAbility` values. This PR fixes that.

**Comment by LewisPotato** [comment]
How do I know when this fix has been implemented? Cause I plan on recompiling when the issue is fixed.

**Comment by msoky** [comment]
> How do I know when this fix has been implemented? Cause I plan on recompiling when the issue is fixed.

it will be there https://github.com/TrinityCore/TrinityCore/commits/3.3.5

File: src/server/game/Entities/Creature/Trainer.cpp (hunk 1 above)
Comment (Shauren) [reply src/server/game/Entities/Creature/Trainer.cpp]: This is impossible to fail (Assert would be correct) - thanks to startup checks

**Review by jackpoz — APPROVED** [review]

**Review by Treeston — APPROVED** [review]
