### PR TITLE
Scripts/Battle for Mount Hyjal:Fix wrong npc text,trash movment,archimode last phase

### LINKED ISSUE #24904: [3.3.5] Mount Hyjal Bugs
**Description:**

In mount Hyjal there seem to be a few bugs.

The first is that all trash monsters should spawn in running. At the moment they're walking.

Archimonde's fire wall has a visible Doomfire Spirit (infernal model) running around ,this should be invisible.

In the final phase (less than 10% health) Archimonde's finger of death was doing damage, but the Protection of Elune buff the raid gets (which I did get) should prevent all damage.

**Expected behaviour:**

- [ ] Trash mobs should run.
- [ ] Doomfire Spirit should be invisible.
- [ ] Players should take no damage once Archimonde reaches 10% health so they can enjoy watching the wisps finish him off.

**Steps to reproduce the problem:**

1. Step 1 Run the Mount Hyjal instance and see the monsters walking, rather than running.
2. Step 2 At the end fight Archimonde (I'm afraid I don't know a good way to skip to the end), the Doomfire Spirits (creature template 18104) will be visible.
3. Step 3 Get Archimonde down to 10% and you will get Protection of Elune (https://www.wowhead.com/spell=38528/protection-of-elune) cast on you. He will start to spam Finger of death (https://www.wowhead.com/spell=39369/finger-of-death), which should do no damage thanks to the protection.

**Branch(es):**

3.3.5, (not tested on master)

**TC rev. hash/commit:** 

3ac1992afbeb

**Operating system:**

Windows 10

### PR DESCRIPTION
**Pull request by leelf00**
**Changes proposed:**
Improve Batle for Mount Hyjal script behavior.Changes Reference Video(https://www.youtube.com/watch?v=LUIlwEVnUig )

- [x] Fixed wrong npc text in for Jaina,Thrall,Tyrande.
- [x] Changed Hyjal trash mobs movement from walk to run.
- [x] Fixed Archimode drain worldtree event.
- [x] Fixed Archimode below 10% hp phase.Case Protection of elune on player.
- [x] Fixed Protection of elune prevent damage from Finger of Death.
- [x] Added some missing mobs creature text.
- [x] Fixed meteor visual effect unvisiable when spawn Giant Infernal.
- [x] Fixed DoomFire Spirit summoned by Archimode  can visiable to player.
- [x] Fixed Gargoyle and Frost wyrm not being able to fly。

**Issues addressed:**

Close #24904

**Tests performed:**

Test in game

### CODE REVIEW

**Comment by leelf00** [comment]
Gargoyle and Frost Wyrm way path is strange.They fallen down after spawned in sky.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp [hunk 1]
```diff
@@ -401,6 +399,7 @@ void hyjalAI::Reset()
 
         case TYRANDE:
             Faction = 2;
+            DoCast(me, SPELL_TRUESHOT_AURA, true);
```
Comment (Faq) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:402]: DoCastSelf could be used

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:402]: Thanks.I get it.

**Review by leelf00 — COMMENTED** [review]
Fix code style. 
Fix meteor visual effect unvisiable when spawn Giant Infernal.
Fix DoomFire Spirit summoned by Archimode can visiable to player.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 2]
```diff
@@ -284,23 +290,27 @@ class boss_archimonde : public CreatureScript
 
             Enraged = false;
             HasProtected = false;
+            WorldtreeTraget = reinterpret_cast<Creature*>(me->SummonCreature(WORLDTREE_CHANNEL_TARGET, 5503.713f, -3523.436f, 1608.781f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 360000s));
```
[the remark this answers is not in the document]
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:293]: Anything wrong this line?

[the remark this answers is not in the document]
Comment (ccrs) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:293]: its not a good idea to store a pointer for later access, better store the guid and look for it when you need it
and why did you cast it at all? even if the pointer approach would be safe, why not just use the original pointer type?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 3]
```diff
@@ -290,7 +290,8 @@ class boss_archimonde : public CreatureScript
 
             Enraged = false;
             HasProtected = false;
-            WorldtreeTraget = reinterpret_cast<Creature*>(me->SummonCreature(WORLDTREE_CHANNEL_TARGET, 5503.713f, -3523.436f, 1608.781f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 360000s));
+            summons.DespawnAll();
+            Creature* WorldtreeTraget = reinterpret_cast<Creature*>(me->SummonCreature(WORLDTREE_CHANNEL_TARGET, 5503.713f, -3523.436f, 1608.781f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 360000s));
```
Comment (Aokromes) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]: i wonder if there is any spell doing this.

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]: I Think Channel Spell 39140 need a target to cast.Any other idea?

Comment (Aokromes) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]: if you jump into irc i can share you one sniff.

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]: discord.com?

Comment (Aokromes) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]: you can reach me there too yes.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 4]
```diff
@@ -387,18 +398,62 @@ class boss_archimonde : public CreatureScript
                             DoAction(ACTION_ENRAGE);
                     events.ScheduleEvent(EVENT_DISTANCE_CHECK, 5s);
                     break;
+                case EVENT_PROTECTION_OF_ELUNE: // hp below 10% only cast finger of death
+                    events.Reset();
+                    events.ScheduleEvent(EVENT_FINGER_OF_DEATH_LAST_PHASE, 1s);
+                    CastProtectionOfElune(true);
+                    me->GetMotionMaster()->Clear();
+                    me->GetMotionMaster()->MoveIdle();
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:406]: there might be something else to call than Clear() + MoveIdle(), I don't remember though what was the right function

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 5]
```diff
@@ -531,6 +588,7 @@ class boss_archimonde : public CreatureScript
         uint32 _unleashSpell;
         bool Enraged;
         bool HasProtected;
+        std::list<Unit*> spellProtectionOfEluneTargets;
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:591]: Storing Unit* is the most common way for scripts to cause a crash when the Unit* is deleted, leaving a pointer to free'd memory

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp [hunk 6]
```diff
@@ -189,6 +195,7 @@ hyjal_trashAI::hyjal_trashAI(Creature* creature) : EscortAI(creature)
     useFlyPath = false;
     damageTaken = 0;
     memset(DummyTarget, 0, sizeof(DummyTarget));
+    SetRun();
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:198]: The constructor should only initialize fields, not call any ingame related code

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp]: I create a new function to do this.Updated code.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 4 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:406]: At last phase.Archimode should not move,only case finger of death.I want to prevent Archimode move.

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:406]: Updated this code.Removed

File: sql/updates/world/3.3.5/9999_99_99_world.sql [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+(9233, 'Outstanding! Killing a Pit Lord such as Azgalor is no small feat, my friend. If we had more time, I would love to hear the story of you and your companions. Archimonde will not give us that pause, however. My scouts have already reported that the Legion is amassing an immense force outside our camp, and Archimonde is very close to the World Tree. We are evacuating with the help of Lady Proudmoore. You should head to the World Tree at once. The fate of our world is still undecided.', '', 15448, 0, 1, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
```
Comment (offl) [inline sql/updates/world/3.3.5/9999_99_99_world.sql:13]: These 2 are sniffed? If not, better to use high IDs(last in npc_text)

File: sql/updates/world/3.3.5/9999_99_99_world.sql [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+(17932, 0, 1, '', 12, 0, 100, 0, 0, 0, 18485, 0, 'Horde Grunt say slay'),
+(17932, 0, 2, '', 12, 0, 100, 0, 0, 0, 18488, 0, 'Horde Grunt say slay'),
+(17932, 0, 3, '', 12, 0, 100, 0, 0, 0, 18490, 0, 'Horde Grunt say slay'),
+(17932, 1, 0, '', 12, 0, 100, 0, 0, 0, 18487, 0, 'Horde Grunt say death'),
+(17933, 0, 0, '', 12, 0, 100, 0, 0, 0, 18493, 0, 'Tauren Warrior say slay'),
+(17933, 0, 1, '', 12, 0, 100, 0, 0, 0, 18494, 0, 'Tauren Warrior say slay'),
+(17933, 1, 0, '', 12, 0, 100, 0, 0, 0, 18495, 0, 'Tauren Warrior say death'),
+(17936, 0, 1, '', 12, 0, 100, 0, 0, 0, 18510, 0, 'Horde Shaman say slay'),
+(17936, 1, 0, '', 12, 0, 100, 0, 0, 0, 18496, 0, 'Horde Shaman say death'),
+(17772, 7, 0, '', 16, 0, 100, 0, 0, 0, 15310, 0, 'jaina hyjal horde base SUCCESS');
```
Comment (offl) [inline sql/updates/world/3.3.5/9999_99_99_world.sql:44]: Text should be filled and shouldn't create mismatches with broadcast_text, actually there should be an error for that like in npc_text (validation reasons)

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 3 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]: Actually all you have to do here is spawn WORLDTREE_CHANNEL_TARGET in DB and then cast 39140 on self or nullptr(both ways should work but should be tested), ideally store guid of WORLDTREE_CHANNEL_TARGET in instance script and cast spell on it using instance->GetCreature (there's one example in this file)

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 9]
```diff
@@ -284,23 +290,28 @@ class boss_archimonde : public CreatureScript
 
             Enraged = false;
             HasProtected = false;
+            summons.DespawnAll();
+            Creature* WorldtreeTraget = reinterpret_cast<Creature*>(me->SummonCreature(WORLDTREE_CHANNEL_TARGET, 5503.713f, -3523.436f, 1608.781f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 360000s));
+            DoCast(WorldtreeTraget, SPELL_DRAIN_WORLD_TREE);
+            WorldtreeTraget->AI()->DoCast(me, SPELL_DRAIN_WORLD_TREE_TRIGGERED);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:296]: That is handled by spell script in this file, doesn't work?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 10]
```diff
@@ -387,18 +398,54 @@ class boss_archimonde : public CreatureScript
...
+            {
+                if (Unit* target = (*iter)->GetVictim())
+                    if (target->IsAlive() && target->GetTypeId() == TYPEID_PLAYER)
+                    {
+                        if (apply)
+                            target->AddAura(SPELL_PROTECTION_OF_ELUNE, target);
+                        target->ApplySpellImmune(SPELL_HAND_OF_DEATH, IMMUNITY_ID, SPELL_HAND_OF_DEATH, apply);
+                        target->ApplySpellImmune(SPELL_FINGER_OF_DEATH, IMMUNITY_ID, SPELL_FINGER_OF_DEATH, apply);
+                        target->ApplySpellImmune(SPELL_FINGER_OF_DEATH_LAST_PHASE, IMMUNITY_ID, SPELL_FINGER_OF_DEATH_LAST_PHASE, apply);
+                        target->ApplySpellImmune(0, IMMUNITY_ID, SPELL_FINGER_OF_DEATH_LAST_PHASE, apply);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: >In the final phase (less than 10% health) Archimonde's finger of death was doing damage, but the Protection of Elune buff the raid gets (which I did get) should prevent all damage.
#24904

That aura fails to apply on players or effect simply does not work? Because Apply Aura: Spell School Immunity (Physical, Holy, Fire, Nature, Frost, Shadow, Arcane) of spell Protection of Elune should work here.
I've never seen ApplySpellImmune being used for player directly in scripts, doesn't it create exploit(immunities will be stored after logout and never removed)? They kinda can be cleaned in instance script but it more looks like you need to figure out why spell does not work.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 11]
```diff
@@ -514,13 +561,14 @@ class boss_archimonde : public CreatureScript
...
-                TEMPSUMMON_TIMED_DESPAWN, 27s);
-
-            me->SummonCreature(NPC_DOOMFIRE,
+                TEMPSUMMON_TIMED_DESPAWN, 27s));
+            DoomfireSpirit->SetVisible(false);
+            Creature* Doomfire = reinterpret_cast<Creature*>(me->SummonCreature(NPC_DOOMFIRE,
                 target->GetPositionX()-15.0f, target->GetPositionY()-15.0f, target->GetPositionZ(), 0,
-                TEMPSUMMON_TIMED_DESPAWN, 27s);
+                TEMPSUMMON_TIMED_DESPAWN, 27s));
+            Doomfire->SetVisible(false);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:571]: flags_extra 128 in creature_template is more preferable & legit here, but it can break something, should be tested

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp [hunk 12]
```diff
@@ -1172,12 +1194,14 @@ class npc_frost_wyrm : public CreatureScript
             Initialize();
             instance = creature->GetInstanceScript();
             go = false;
+            me->SetCanFly(true);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1197]: It shouldn't be called in scripts, also those SetDisableGravity wont work like this without extra_flags 512 (it only 'works' currently because of SetCanFly, but if removed, they'll stop flying)
They just should have creature_template_movement with Flight = 1, same with npc_gargoyle

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp [hunk 13]
```diff
@@ -1503,6 +1524,47 @@ class alliance_rifleman : public CreatureScript
...
+    }
+
+    struct alliance_horde_guardAI : public ScriptedAI
+    {
+        alliance_horde_guardAI(Creature* creature) : ScriptedAI(creature) {}
+
+        void JustDied(Unit* /*killer*/) override
+        {
+            Talk(TRASH_SAY_DEATH);
+            me->SetRespawnDelay(me->GetRespawnDelay()+480); // prevent respawn in combat,add wave spawn time to delay respawn
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1544]: >// prevent respawn in combat,add wave spawn time to delay respawn

Do they really behave like this? I mean was this confirmed?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp [hunk 14]
```diff
@@ -1503,6 +1524,47 @@ class alliance_rifleman : public CreatureScript
...
+        {
+            if (!who || me->GetVictim())
+                return;
+
+            if (me->IsValidAttackTarget(who))
+            {
+                if (me->IsWithinDistInMap(who, 10))
+                    AttackStart(who);
+            }
+        }
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1562]: What you're trying to fix by overriding MoveInLineOfSight?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1544]: Generic C++ scripts for trash is something we usually remove because functions they has weren't confirmed or unnecessary

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp [hunk 15]
```diff
@@ -831,7 +831,10 @@ void hyjalAI::UpdateAI(uint32 diff)
                     }
                     else if (BossGUID[i] == BossGUID[1])
                     {
-                        Talk(SUCCESS);
+                        if (me->GetEntry()!=JAINA) // jaina yell success after select gossip
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:834]: Contradiction here
```cpp
// jaina yell success after select gossip
```
but
```txt
!= JAINA
```

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp [hunk 16]
```diff
@@ -94,6 +94,7 @@ class npc_jaina_proudmoore : public CreatureScript
                         StartEvent(player);
                         break;
                     case GOSSIP_ACTION_INFO_DEF + 3:
+                        me->AI()->Talk(5);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp:97]: Magic number

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp [hunk 17]
```diff
@@ -946,6 +948,7 @@ void hyjalAI::WaypointReached(uint32 waypointId, uint32 /*pathId*/)
             if (Creature* creature = ObjectAccessor::GetCreature(*me, DummyGuid))
             {
                 hyjalAI* ai = ENSURE_AI(hyjalAI, creature->AI());
+                ai->Talk(7);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:951]: Magic number

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp [hunk 18]
```diff
@@ -825,6 +830,12 @@ class npc_necromancer : public CreatureScript
 
         void JustEngagedWith(Unit* /*who*/) override { }
 
+        void JustDied(Unit* killer) override
+        {
+            hyjal_trashAI::JustDied(killer);
+            me->AI()->Talk(TRASH_SAY_DEATH);
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:836]: Just Talk(TRASH_SAY_DEATH); ?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 9 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:296]: The orignal script for SPELL_DRAIN_WORLD_TREE is broken.Archimode just stand and do nothing after spawned

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 10 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: Protection of elune (38528) not prevent any damage,only has visual effect.Any suggestion to add Spell School Immunity effect to spell Protection of elune?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 12 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1197]: Add creature_template_movement with Flight = 1 and remove SetCanFly in script will work correctly?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1544]: Any suggestions to prevent they respawned between waves?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 14 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1562]: Ths guards are not autoattack.They just stand until take damage.A bit defference from retail version.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 18 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:836]: Any function to handle it in db?I can't find a way.

File: sql/updates/world/3.3.5/9999_99_99_world.sql (hunk 7 above)
Comment (leelf00) [reply sql/updates/world/3.3.5/9999_99_99_world.sql:13]: What is the difference between high ID and low ID?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp (hunk 15 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:834]: Accoding to the reference video,Jaina yell success after select gossip,not yell after reach waypoint.So I move the behavior from here.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 12 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp]: It works.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: They shouldn't?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 9 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:296]: That is only part of it

File: sql/updates/world/3.3.5/9999_99_99_world.sql (hunk 7 above)
Comment (offl) [reply sql/updates/world/3.3.5/9999_99_99_world.sql]: If they're not sniffed, at some point we may have conflicts with actually sniffed texts

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 14 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1558]: We can't override it each time something doesn't work

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp (hunk 15 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:839]: You force here any creature except Jaina to yell, take a closer look at the check

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 18 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:836]: Yes, in SAI. But I doubt it's a good idea to have both SAI and C++ at once

File: sql/updates/world/3.3.5/9999_99_99_world.sql [hunk 19]
```diff
@@ -0,0 +1,53 @@
...
+(921063, 'Outstanding! Killing a Pit Lord such as Azgalor is no small feat, my friend. If we had more time, I would love to hear the story of you and your companions. Archimonde will not give us that pause, however. My scouts have already reported that the Legion is amassing an immense force outside our camp, and Archimonde is very close to the World Tree. We are evacuating with the help of Lady Proudmoore. You should head to the World Tree at once. The fate of our world is still undecided.', '', 15448, 0, 1, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
```
Comment (offl) [inline sql/updates/world/3.3.5/9999_99_99_world.sql:13]: 50016, 50017

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: On Retail Server guards never respawn between waves.But in TC it does.I can't find a way to solve it.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp (hunk 15 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp]: I made a mistake.Updated code for this.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 10 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: It already has that immunity

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: But all that code does is only delays respawn for a random time, it can't guarantee they will not respawn between waves

Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: To me it looks they don't respawn at all, meaning respawn time simply can be increased in DB to one day or 7 days
Maybe they are forced to respawn when player starts boss 2 or boss 4 but that should be done in instance script

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 14 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1558]: Can't reproduce with mobs at first base

Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1558]: That sounds like a generic bug or something related to specific creature

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 10 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: If immunities are saved after logout and that creates exploit I mentioned, you can leave it as it is(without any fix), or investigate why aura immunity does not work in that case
Or script that aura to apply immunities on aura apply and remove immunities on aura remove, that way immunities will be always corrently removed

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 14 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1558]: I think I expressed.Guards not autoattack when trashs move in sight,they just stand until taken any damage from trashs.After guards kill the target,they immediately returned to its original position without autoattack another targe in sight.

Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1558]: Generic bug or not a bug, it happens everywhere

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 10 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: use SpellScript to add immunity on Protection of elune (38528) and remove immunity  after disappeared?Can you give me a code example for reference?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 14 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1558]: Ok。I remove these code lines.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 10 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: spell_dk_improved_blood_presence

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: "Spell `38528` Effect `Index: EFFECT_0 AuraName: 4` of script `spell_protection_of_elune` did not match dbc effect data - handler bound to hook `AfterEffectApply` of AuraScript won't be executed" I got this error.The Insert Statement INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
(38528,'spell_protection_of_elune');

Code :

// Protection of Elune 38528
class spell_protection_of_elune : public AuraScript
{
    PrepareAuraScript(spell_protection_of_elune);

    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return ValidateSpellInfo(
        {
            SPELL_PROTECTION_OF_ELUNE
        });
    }

    void HandleEffectApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        Unit* target = GetTarget();
        if (target->HasAura(SPELL_PROTECTION_OF_ELUNE))
        {
            target->ApplySpellImmune(SPELL_HAND_OF_DEATH, IMMUNITY_ID, SPELL_HAND_OF_DEATH, true);
            target->ApplySpellImmune(SPELL_FINGER_OF_DEATH, IMMUNITY_ID, SPELL_FINGER_OF_DEATH, true);
            target->ApplySpellImmune(SPELL_FINGER_OF_DEATH_LAST_PHASE, IMMUNITY_ID, SPELL_FINGER_OF_DEATH_LAST_PHASE, true);
            target->ApplySpellImmune(0, IMMUNITY_ID, SPELL_FINGER_OF_DEATH_LAST_PHASE, true);
        }
    }

    void HandleEffectRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        Unit* target = GetTarget();
        if (!target->HasAura(SPELL_PROTECTION_OF_ELUNE))
        {
            target->ApplySpellImmune(SPELL_HAND_OF_DEATH, IMMUNITY_ID, SPELL_HAND_OF_DEATH, false);
            target->ApplySpellImmune(SPELL_FINGER_OF_DEATH, IMMUNITY_ID, SPELL_FINGER_OF_DEATH, false);
            target->ApplySpellImmune(SPELL_FINGER_OF_DEATH_LAST_PHASE, IMMUNITY_ID, SPELL_FINGER_OF_DEATH_LAST_PHASE, false);
            target->ApplySpellImmune(0, IMMUNITY_ID, SPELL_FINGER_OF_DEATH_LAST_PHASE, false);
        }
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_protection_of_elune::HandleEffectApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_protection_of_elune::HandleEffectRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: It's SPELL_AURA_SCHOOL_IMMUNITY, not SPELL_AURA_DUMMY
HasAura checks are not needed
In Validate you need to validate spells you use in script, not the spell you scripted
aurEff > /*aurEff*/

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:443]: Ok

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 20]
```diff
@@ -387,18 +398,49 @@ class boss_archimonde : public CreatureScript
...
+                case EVENT_FINGER_OF_DEATH_LAST_PHASE:
+                    DoCast(SelectTarget(SelectTargetMethod::Random, 0), SPELL_FINGER_OF_DEATH_LAST_PHASE);
+                    events.ScheduleEvent(EVENT_FINGER_OF_DEATH_LAST_PHASE, 1s);
+                    break;
                 default:
                     break;
             }
         }
 
+        void CastProtectionOfElune(bool apply)
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:427]: This whole method can be removed, just cast SPELL_PROTECTION_OF_ELUNE once, without AddAura

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp [hunk 21]
```diff
@@ -188,17 +201,25 @@ class npc_thrall : public CreatureScript
...
                     uint32 AzgalorEvent = GetInstanceData(DATA_AZGALOREVENT);
                     if (KazrogalEvent == NOT_STARTED)
+                    {
                         AddGossipItemFor(player, GOSSIP_ITEM_BEGIN_HORDE_MID, GOSSIP_ITEM_BEGIN_HORDE_OID, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
+                        SendGossipMenuFor(player, 9225, me->GetGUID());
+                    }
                     else if (KazrogalEvent == DONE && AzgalorEvent == NOT_STARTED)
+                    {
                         AddGossipItemFor(player, GOSSIP_ITEM_AZGALOR_MID, GOSSIP_ITEM_AZGALOR_OID, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
+                        SendGossipMenuFor(player, 50016, me->GetGUID());
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp:211]: Forgot to change this one

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp [hunk 22]
```diff
@@ -188,17 +201,25 @@ class npc_thrall : public CreatureScript
...
+                    }
                     else if (AzgalorEvent == DONE)
+                    {
                         AddGossipItemFor(player, GOSSIP_ITEM_HORDE_RETREAT_MID, GOSSIP_ITEM_HORDE_RETREAT_OID, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
+                        SendGossipMenuFor(player, 50017, me->GetGUID());
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp:216]: Forgot to change this one

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 9 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: That is because he is invisible when you test it, all of that works correctly not inside instance(without any changes)
There is a way to fix it but it requires more changes in instance script. This PR is already too big to review it easy

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp]: I found position and movement is wrong of original world tree channel trigger.The trigger keep walking and interrupt ths channel spell.Updated code

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp (hunk 11 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:547]: I test flags_extra 128,seems to work correctly.

File: sql/updates/world/3.3.5/9999_99_99_world.sql [hunk 23]
```diff
@@ -0,0 +1,66 @@
...
+INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES
+(38528,'spell_protection_of_elune');
+
+-- change wrong position and movement type of worldtree channel target
+DELETE FROM `creature` WHERE `guid`=6747;
+INSERT INTO `creature`(`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
+(6747, 22418, 534, 0, 0, 1, 1, 0, 0, 5502.2876, -3525.4714, 1607.9094, 2.61799, 7200, 0, 0, 1, 0, 0, 0, 0, 0, '', 0);
+
+-- update doomfire(18095) and doomfire_spirit(18104) flag_extra to 128
+UPDATE `creature_template` SET `flags_extra`=128 WHERE `entry` IN (18095,18104);
```
Comment (offl) [inline sql/updates/world/3.3.5/9999_99_99_world.sql:63]: `flags_extra` = `flags_extra`|128

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 24]
```diff
@@ -514,17 +537,17 @@ class boss_archimonde : public CreatureScript
             if (!target)
                 return;
 
-            me->SummonCreature(NPC_DOOMFIRE_SPIRIT,
+            Creature* DoomfireSpirit = reinterpret_cast<Creature*>(me->SummonCreature(NPC_DOOMFIRE_SPIRIT,
```
Comment (offl) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:540]: Revert changes around

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: Do you know how to find all guids of a entry in instance?Can you give me a code example for reference?

Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: I recommend to first figure out how it works on retail to not implement something that may be not necessary

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:1540]: Ok.I will revent this for before figure out how it works on retail vision.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 18 above)
Comment (offl) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp:836]: Both me->AI()->Talk can be just changed to Talk(BLAH_BLAH);

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp (hunk 13 above)
Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal_trash.cpp]: Changes have revent

**Comment by Aokromes** [comment]
@offl there is something missing here? :)

**Comment by leelf00** [comment]
Is it still someting wrong in code?

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 25]
```diff
@@ -284,23 +289,28 @@ class boss_archimonde : public CreatureScript
 
             Enraged = false;
             HasProtected = false;
+            summons.DespawnAll();
+            WorldtreeTragetGUID=instance->GetGuidData(DATA_CHANNEL_TARGET);
+            if (Creature* WorldtreeTraget = ObjectAccessor::GetCreature(*me, WorldtreeTragetGUID)){
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:294]:
```suggestion
            if (Creature* WorldtreeTraget = ObjectAccessor::GetCreature(*me, WorldtreeTragetGUID))
            {
```

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 26]
```diff
@@ -284,23 +289,28 @@ class boss_archimonde : public CreatureScript
...
+                DoCast(WorldtreeTraget, SPELL_DRAIN_WORLD_TREE);
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:295]: Initialize() method is supposed to only initialize C++ class member fields. It's not supposed to cast spells or unsummon mobs.
Please move this part to Reset() or wherever it's supposed to be

Comment (jackpoz) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:295]: Now I wonder, is this spell actually even cast ingame ? did you check if it works ?

Comment (leelf00) [reply src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:295]: Thank you for reply.The spell only has a visual effect,found in sniff and video.

**Comment by Aokromes** [comment]
this can be merged? @jackpoz @Shauren

**Comment by jackpoz** [comment]
@leelf00 could you please do another test ingame with the latest changes ? after that we can merge this PR

**Comment by leelf00** [comment]
Ok.I will test it this weekend.

**Comment by leelf00** [comment]
@jackpoz .I tested the dungeon ingame.It seems OK.

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp [hunk 27]
```diff
@@ -289,18 +293,25 @@ class boss_archimonde : public CreatureScript
...
         }
 
         void Reset() override
         {
             Initialize();
             _Reset();
-            me->RemoveAllAuras();                              // Reset Soul Charge auras.
+            DoomfireSpiritGUID.Clear();
+            summons.DespawnAll();
+            WorldtreeTragetGUID=instance->GetGuidData(DATA_CHANNEL_TARGET);
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp:304]:
```suggestion
            WorldtreeTragetGUID = instance->GetGuidData(DATA_CHANNEL_TARGET);
```

File: src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp [hunk 28]
```diff
@@ -831,7 +836,10 @@ void hyjalAI::UpdateAI(uint32 diff)
                     }
                     else if (BossGUID[i] == BossGUID[1])
                     {
-                        Talk(SUCCESS);
+                        if (me->GetEntry()==THRALL) // thrall yell success after boss deaded,jaina yell success after select gossip
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjalAI.cpp:839]:
```suggestion
                        if (me->GetEntry() == THRALL) // thrall yell success after boss deaded,jaina yell success after select gossip
```

**Comment by jackpoz** [comment]
Thanks for the PR 🚀 😃
