### PR TITLE
Core/Spell: Divine Storm

### LINKED ISSUE #18383: [Master] Paladin Spell: Divine Storm (53385) - No function
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** http://www.wowhead.com/spell=53385/divine-storm

**Current behaviour:** (Tell us what happens.)
Casting [Divine Storm](http://www.wowhead.com/spell=53385/divine-storm) consumes 3 [Holy Power](http://wow.gamepedia.com/Holy_Power) but has no effect.

http://imgur.com/a/mfGt0

**Expected behaviour:** (Tell us what should happen instead.)
Casting [Divine Storm](http://www.wowhead.com/spell=53385/divine-storm) should deal damage to nearby enemies

**Steps to reproduce the problem:**

1.  `.learn 53385`
2.  `.learn 35395`
3.  Use [Crusader Strike](http://www.wowhead.com/spell=35395/crusader-strike) 3 times on an enemy
4. Use [Divine Storm](http://www.wowhead.com/spell=53385/divine-storm)

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.) Master

**TC rev. hash/commit:**  fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65

**TDB version:**  703.00

**Operating system:**  Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by DoctorKraft**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Fix "Divine Storm" (http://www.wowhead.com/spell=53385/divine-storm)

**Target branch(es):**

- [*] master

**Issues addressed:**

Closes #18383 

**Tests performed:**

Build & Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 1]
```diff
@@ -403,7 +402,7 @@ class spell_pal_divine_steed : public SpellScriptLoader
     }
 };
 
-// 53385 - Divine Storm
+// Divine Storm - 53385
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_paladin.cpp]: keep the `id - name` style

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 2]
```diff
@@ -463,40 +464,14 @@ class spell_pal_divine_storm_dummy : public SpellScriptLoader
...
-
-            void HandleDummy(SpellEffIndex /*effIndex*/)
+            void FilterTargets(std::list<WorldObject*>& targets)
             {
-                if (!_targetCount || ! GetHitUnit())
-                    return;
-
-                int32 heal = GetEffectValue() / _targetCount;
-                GetCaster()->CastCustomSpell(GetHitUnit(), SPELL_PALADIN_DIVINE_STORM_HEAL, &heal, NULL, NULL, true);
+                Trinity::Containers::RandomResizeList(targets, 0);
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_paladin.cpp]: size 0?

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 3]
```diff
@@ -413,37 +412,39 @@ class spell_pal_divine_storm : public SpellScriptLoader
...
-            }
-
-        private:
-            uint32 healPct;
-
             bool Validate(SpellInfo const* /*spellInfo*/) override
             {
-                if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STORM_DUMMY))
+                if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STORM_DAMAGE) ||
+                    !sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STORM_DUMMY))
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_paladin.cpp]: as side note: we have a ValidateSpellInfo function now
```
return ValidateSpellInfo(
{
    SPELL_PALADIN_DIVINE_STORM_DAMAGE,
    SPELL_PALADIN_DIVINE_STORM_DUMMY
});

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 4]
```diff
@@ -413,37 +412,39 @@ class spell_pal_divine_storm : public SpellScriptLoader
...
             {
                 Unit* caster = GetCaster();
-                caster->CastCustomSpell(SPELL_PALADIN_DIVINE_STORM_DUMMY, SPELLVALUE_BASE_POINT0, (GetHitDamage() * healPct) / 100, caster, true);
+
+                std::list<Unit*> targetList;
+                float radius = GetSpellInfo()->GetEffect(EFFECT_0)->CalcRadius(GetCaster());
+
+                Trinity::NearestAttackableUnitInObjectRangeCheck u_check(caster, caster, radius);
+                Trinity::UnitListSearcher<Trinity::NearestAttackableUnitInObjectRangeCheck> searcher(caster, targetList, u_check);
+                caster->VisitNearbyObject(radius, searcher);
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_paladin.cpp]: why are you not using the spell's targets?

File: src/server/scripts/Spells/spell_paladin.cpp (hunk 2 above)
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: Yes because this spell is used only for visual but with target > 0 you have a second visual on target hit but SPELL_PALADIN_DIVINE_STORM_DAMAGE give this visual and the radius it's 16 yards

File: src/server/scripts/Spells/spell_paladin.cpp (hunk 4 above)
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: Hm? Because this spell it's only for one target. We need casting 1 spell per target (sniff src)

File: src/server/scripts/Spells/spell_paladin.cpp (hunk 3 above)
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: Oh nice !

**Comment by matukaa** [comment]
I'd suggest doing this otherwise, if you want to be blizzlike.
OnCast -> caster->SendPlaySpellVisualKit(73892, 0); (Blizzard uses this one to make the visual)
OnEffectHitTarget(SPELL_EFFECT_DUMMY) -> caster->CastSpell(GetHitUnit(), 224239, true);

it will be just like on blizz, no need to modify targets, etc. (src is sniffing, obviously)

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 5]
```diff
@@ -413,96 +416,39 @@ class spell_pal_divine_storm : public SpellScriptLoader
...
-            void CountTargets(std::list<WorldObject*>& targetList)
-            {
-                _targetCount = targetList.size();
-            }
-
-            void HandleDummy(SpellEffIndex /*effIndex*/)
-            {
-                if (!_targetCount || ! GetHitUnit())
+                Unit* caster = GetCaster();
+                Unit* target = GetExplTargetUnit();
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_paladin.cpp]: why ExplTargetUnit instead of HitUnit? what is the target type of this effect in db2?

Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: TARGET_UNIT_SRC_AREA_ENEMY

Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: What is the difference with HitUnit and ExplTargetUnit ?

**Comment by DoctorKraft** [comment]
Ohhhh thanks @matukaa for your clarification. I did not know for SpellVisualKit, i agreed my first commit it's a big hack x) It's better now 👍
