### PR TITLE
Scripts/Trial Of The Crusader: Fixed Anub'arak Pursuing Spikes movement

### LINKED ISSUE #23010: Creature/Script: Anub'Arak TOC
**Description:** ~~On 10 mode only one Nerubian Burrower spawn instead of 2 and on 25 mode only 2 Nerubian Burrower spawns instead of 4.~~

Once under ground there's no spikes at all.

**Branch(es):**3.3.5

**TC rev. hash/commit:**  rev. f04e90f63842

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Change MoveChase to AttackStart to allow movement
-  Remove duplicate EVENT_SUBMERGE (added here: https://github.com/TrinityCore/TrinityCore/commit/1f9db80b69379f3abc4b2f8bb5dbc26ec971cc92)

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #23010

**Tests performed:** tested in-game

### CODE REVIEW

File: src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp [hunk 1]
```diff
@@ -370,7 +370,6 @@ class boss_anubarak_trial : public CreatureScript
                             break;
                         }
                         case EVENT_EMERGE:
-                            events.ScheduleEvent(EVENT_SUBMERGE, 80*IN_MILLISECONDS, 0, PHASE_MELEE);
```
Comment (Keader) [inline src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp:373]: are you sure about it?

**Comment by Keader** [comment]
ty Jildor :)
