### PR TITLE
Scripts/Blood Furnace: Broggok improvements

### LINKED ISSUE #23285: Creature/Script: Broggok
**Description:** The script of Broggok must be updated after recent changes.
Once the lever activated the first cell open and you  get aggro by Orcs, but once all this orcs killed the second cell will never open.
If you fail in the encounter the lever didn't respawn:  https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp#L156

``` diff
diff --git a/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h b/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h
index a0979027b1..ac4288b5f6 100644
--- a/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h
+++ b/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h
@@ -50,7 +50,8 @@ enum BFCreatureIds
     NPC_THE_MAKER               = 17381,
     NPC_BROGGOK                 = 17380,
     NPC_KELIDAN_THE_BREAKER     = 17377,
-    NPC_PRISONER                = 17398,
+    NPC_PRISONER1               = 17398,
+    NPC_PRISONER2               = 17429,
     NPC_BROGGOK_POISON_CLOUD    = 17662
 };
diff --git a/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp b/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp
index 2e061c600d..a1ede3e306 100644
--- a/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp
+++ b/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp
@@ -65,7 +65,8 @@ class instance_blood_furnace : public InstanceMapScript
                     case NPC_KELIDAN_THE_BREAKER:
                         KelidanTheBreakerGUID = creature->GetGUID();
                         break;
-                    case NPC_PRISONER:
+                    case NPC_PRISONER1:
+                    case NPC_PRISONER2:
                         StorePrisoner(creature);
                         break;
                     default:
@@ -75,7 +76,7 @@ class instance_blood_furnace : public InstanceMapScript
 
             void OnUnitDeath(Unit* unit) override
             {
-                if (unit->GetTypeId() == TYPEID_UNIT && unit->GetEntry() == NPC_PRISONER)
+                if (unit->GetTypeId() == TYPEID_UNIT && (unit->GetEntry() == NPC_PRISONER1 || unit->GetEntry() == NPC_PRISONER2))
                     PrisonerDied(unit->GetGUID());
             }
 
@@ -204,29 +205,30 @@ class instance_blood_furnace : public InstanceMapScript
             {
                 float posX = creature->GetPositionX();
                 float posY = creature->GetPositionY();
+                float posZ = creature->GetPositionZ();
 
-                if (posX >= 405.0f && posX <= 423.0f)
+                if (posX >= 405.0f && posX <= 423.0f && posZ <= 17)
                 {
-                    if (posY >= 106.0f && posY <= 123.0f)
+                    if (posY >= 106.0f && posY <= 123.0f && posZ <= 17)
                     {
                         PrisonersCell5.insert(creature->GetGUID());
                         ++PrisonerCounter5;
                     }
-                    else if (posY >= 76.0f && posY <= 91.0f)
+                    else if (posY >= 76.0f && posY <= 91.0f && posZ <= 17)
                     {
                         PrisonersCell6.insert(creature->GetGUID());
                         ++PrisonerCounter6;
                     }
                     else return;
                 }
-                else if (posX >= 490.0f && posX <= 506.0f)
+                else if (posX >= 490.0f && posX <= 506.0f && posZ <= 17)
                 {
-                    if (posY >= 106.0f && posY <= 123.0f)
+                    if (posY >= 106.0f && posY <= 123.0f && posZ <= 17)
                     {
                         PrisonersCell7.insert(creature->GetGUID());
                         ++PrisonerCounter7;
                     }
-                    else if (posY >= 76.0f && posY <= 91.0f)
+                    else if (posY >= 76.0f && posY <= 91.0f && posZ <= 17)
                     {
                         PrisonersCell8.insert(creature->GetGUID());
                         ++PrisonerCounter8;
```

**Branch(es):**3.3.5

**TC rev. hash/commit:** rev. db53747eb8ca

### PR DESCRIPTION
**Pull request by kuskmen**
**Changes proposed:**
-  This changes fix lever respawn after encounter resets. 
-  After first encounter, future encounters have invalid "PrisonersCounterX" data leading into invalid encounters. (only the first cell opens).

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #23285 

**Tests performed:** Tested it in game and it works as intended, but surely it needs more thorough testing imo. 

**Known issues and TODO list:**
- [ ] When I see the script for the prisoners and cells it makes me puke, but for now I tried to make as little changes as possible in order to make it work, later when I have time I might think of refactoring.

### CODE REVIEW

**Comment by illfated** [comment]
title suggestion: **Scripts/Blood Furnace: Broggok improvements**

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp [hunk 1]
```diff
@@ -169,28 +170,37 @@ class instance_blood_furnace : public InstanceMapScript
...
                 HandleGameObject(PrisonCellGUIDs[DATA_PRISON_CELL8 - DATA_PRISON_CELL1], false);
             }
 
-            void ResetPrisoners(GuidSet const& prisoners)
+            void ResetPrisoners(GuidSet& prisoners)
             {
+                std::list<ObjectGuid> deadPrisoners;
                 for (GuidSet::const_iterator i = prisoners.begin(); i != prisoners.end(); ++i)
-                    if (Creature* prisoner = instance->GetCreature(*i))
+                    if (Creature * prisoner = instance->GetCreature(*i))
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: this loop could be changed to store "i" in the loop as another variable (currentItr ?), increment "i" while the iterator is still valid, then process currentItr and call prisoners.erase(currentItr) if the prisoner is not alive.
This way you don't need another container (unless there is another reason not to modify it)

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp [hunk 2]
```diff
@@ -169,28 +170,37 @@ class instance_blood_furnace : public InstanceMapScript
...
+                    {
+                        if (!prisoner->IsAlive()) deadPrisoners.insert(std::begin(deadPrisoners), prisoner->GetGUID());
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: please don't put the statement after the if check on the same line, it makes it hard to read and annoying to debug

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp (hunk 1 above)
Comment (kuskmen) [reply src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: I tried doing something of sort, but I end up with access violation exception (or sort of) leaving log like "unable to advance iterator" or something like that. I try to implement what you mean, still new to c++ language constructs but it is a learning curve so I will get there sooner or later.

Comment (jackpoz) [reply src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: I usually check http://www.cplusplus.com/reference/ like http://www.cplusplus.com/reference/set/set/erase/ or https://en.cppreference.com/w/ like https://en.cppreference.com/w/cpp/container/set/erase to check how to avoid invalidating an iterator.

There might be some nice tutorials online about iterators, a short tl;dr is if you erase the iterator from a container, the iterator will most likely be invalid and you can't increment it anymore. If you store the current iterator into another variable, then you have 2 different iterators, so you can increment (safely) one and use the other one as parameter for erase().

I would suggest to trying to solve it by yourself, that's the best way to learn, but let me know anyway if you prefer me to post a snippet of the code already updated.

**Comment by illfated** [comment]
@jackpoz : Maybe it is obvious, but I will mention it anyway.
Could be a good idea to edit the commit title when merging.

**Comment by kuskmen** [comment]
@illfated Actually I asked in discord if there are any branch name/commits conventions for the project and as far as I recall I was replied that there were none.

**Comment by illfated** [comment]
OK, maybe they thought you asked if there is a written code style description on how to write the title names for PR/issues/commits. With regards to that, there is no written convention. It is more or less based on existing conventions, as well as inspired by **git** conventions when it comes to how to write a useful commit message for a programming environment.

(`<Rant>`)
That said, I need to tell you that I am to a minor degree autistic and have a bad tendency to get caught up in details (grammar, code style, naming conventions, anything). So a lot of what I have written is based on what I have seen during the time I have used TC source (since 2013) and been a contributor (since 2015). I do not blame you at all, I just try to suggest what I would like to "tidy up" regarding cosmetic stuff, but you are more than welcome to tell me when it feels like I am nagging or talking too much rubbish (from your point of view).

Back to topic: What I have become used to as a TC convention, is to name PR titles based on either directory structure/contents or what part of the source will be most affected by the PR changes.

Example: although "Core" seems to be used for almost everything except for SQL/DB content + instance scripts, there is a directory path relevance too:
- /src/server/game/ -- most of the code beneath here can be referred to as "Core"
- /src/server/scripts/ -- this directory & subfolders is usually referred to as "Scripts"

I could go on about more details of the conventions, but it is usually better to browse https://github.com/TrinityCore/TrinityCore/pulls to get a feeling for what most people use, or just ask if you would like more input.

(`</Rant>`)

**Comment by kuskmen** [comment]
@illfated, on the contrary of what you start to feel, I love getting feedback at all levels of detail, the smaller the detail the better it is for me. I only have one rule of thumb here, do not follow blind "orders", with that in mind, as long as people are giving me reasonable explanations of their feedback I would love to hear what they offer, luckily ever since I contribute for this project I've only seen such feedbacks so please don't feel bad for telling me "cosmetic", little stuff in fact, please do it more often if possible, it would be amazing if I can gather as much information/experience as possible from you guys :)

**Comment by Killyana** [comment]
I notice an other issue in this encounter but it's not related to this pr, if you .gm on after being aggro by the first prisoners, they will not return to the prison cell but will follow you, looks to be related to the movement generator.

**Comment by illfated** [comment]
Heh -- sounds like the good old "NPC evade, then follow forever" bug.

**Comment by sirikfoll** [comment]
About the lever, it shouldn't despawn at all, I remember checking that ^^
I was working on a rewrite for this instance back in the day, but never finished it, I will leave it here in case you find something useful there (spawns in the summon group are wrong) https://github.com/sirikfoll/TrinityCore/commit/d161ca180026acabd75c1426a7134c6b00beb11e

**Comment by kuskmen** [comment]
@sirikfoll btw I had the same feeling but I am taking @Killyana bugs without a doubt :D unless proven wrong.

**Comment by Killyana** [comment]
Yes it doesn't despawns, only states is reset in as of wype.

**Comment by kuskmen** [comment]
@Killyana okay, I will amend the logic.

**Comment by Killyana** [comment]
Th gob is a goober with consumable =0 so it's possible you will get the issue that this PR fixes:
https://github.com/TrinityCore/TrinityCore/pull/23299

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp [hunk 3]
```diff
@@ -169,28 +170,37 @@ class instance_blood_furnace : public InstanceMapScript
...
                 ResetPrisoners(PrisonersCell8);
+                PrisonerCounter8 = PrisonersCell8.size();
                 HandleGameObject(PrisonCellGUIDs[DATA_PRISON_CELL8 - DATA_PRISON_CELL1], false);
             }
 
-            void ResetPrisoners(GuidSet const& prisoners)
+            void ResetPrisoners(GuidSet& prisoners)
             {
+                std::list<ObjectGuid> deadPrisoners;
                 for (GuidSet::const_iterator i = prisoners.begin(); i != prisoners.end(); ++i)
```
Comment (Keader) [inline src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: why it is not a foreach? '-'

Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: According to the blame view (https://github.com/TrinityCore/TrinityCore/blame/3.3.5/src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp#L191), Shauren is currently the last one to have edited that line (see also https://github.com/TrinityCore/TrinityCore/commit/9b316fe689d06af14d800bcb22992da2e6157225#diff-71f0dbd6c5a0bebf11dfc16eda2993aeR210). I presume he will be able to tell you why.

Comment (jackpoz) [reply src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: @Keader did you read https://github.com/TrinityCore/TrinityCore/pull/23300/files#r286423369 ?

Comment (Keader) [reply src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: Nope, make more sense, i agree with you :)

**Comment by Aokromes** [comment]
what's the state of this?

**Comment by kuskmen** [comment]
I will fix whatever is left from the review whenever I have the chance, it is currently a problem because of exams I am currently taking at the end of the semester and I don't have much time to code :/

**Comment by kuskmen** [comment]
@jackpoz , @Killyana , @Aokromes I think this is ready to be reviewed and merged now.

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp [hunk 4]
```diff
@@ -169,28 +182,32 @@ class instance_blood_furnace : public InstanceMapScript
...
 
-            void ResetPrisoners(GuidSet const& prisoners)
+            void ResetPrisoners(GuidSet& prisoners)
             {
-                for (GuidSet::const_iterator i = prisoners.begin(); i != prisoners.end(); ++i)
-                    if (Creature* prisoner = instance->GetCreature(*i))
+                for (GuidSet::const_iterator i = prisoners.begin(); i != prisoners.end();)
+                    if (Creature * prisoner = instance->GetCreature(*i))
+                    {
+                        i = !prisoner->IsAlive() ? prisoners.erase(i) : ++i;
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: please rewrite this line to use a simple if/else

Comment (kuskmen) [reply src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: Right, better for debugging, I am still rusty.

**Comment by jackpoz** [comment]
is there anything left to do in this PR ? could you test it ingame again so we can merge it ?

**Comment by kuskmen** [comment]
@jackpoz , nope there is nothing left and I already tested it, it is working as intended :)

**Comment by Aokromes** [comment]
ref "When I see the script for the prisoners and cells it makes me puke, but for now I tried to make as little changes as possible in order to make it work, later when I have time I might think of refactoring." if you jump irc i can supply sniffs

**Comment by jackpoz** [comment]
Thanks for the PR :)

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp [hunk 5]
```diff
@@ -169,28 +182,35 @@ class instance_blood_furnace : public InstanceMapScript
...
                 HandleGameObject(PrisonCellGUIDs[DATA_PRISON_CELL8 - DATA_PRISON_CELL1], false);
             }
 
-            void ResetPrisoners(GuidSet const& prisoners)
+            void ResetPrisoners(GuidSet& prisoners)
             {
-                for (GuidSet::const_iterator i = prisoners.begin(); i != prisoners.end(); ++i)
-                    if (Creature* prisoner = instance->GetCreature(*i))
+                for (GuidSet::const_iterator i = prisoners.begin(); i != prisoners.end();)
+                    if (Creature * prisoner = instance->GetCreature(*i))
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp]: when instance->GetCreature(*i) returns NULL, the iterator is not incremented, leading to an infinite loop
