### PR TITLE
Game/Maps: Clean up instance zone-in handling

### LINKED ISSUE #15561: 3.3.5a relog/dc should not leave party
Hello , sorry for open issue but since my english is bad and can't find issue

I needed to open issue

after relog or dc makes player leave party but it should not leaving party because in instance or dungeon it gives leaving..

is there any way to fix it?

again, sorry.

regards,

rev. f50df72

### LINKED ISSUE #15758: [335a] Can't revive after dying in instance
3.3.5 branch
core hash c04c409f41b2c459aba2b8a2c0c705123d1217d6

Well, this one is a little tricky... 
How to reproduce:
1- Enter any dungeon instance with a party,
2- Tell them not to get out of the instance and get disconnected (alt+f4, log off, etc) or get connection issues (like cable disconnection?)
3- Wait until party expels you or server takes you out of the party because of disconnection... you will disappear from the map.
4- Log in again while your previous party is whitin the instance, you will be on the same map but in a diferent instance than the group, this is normal and ok.
5- Get killed by monsters whitin YOUR instance, you will be taken as ghost to the nearest graveyard but your corpse will remain within YOUR instance.
6- Let the original party invite you again
7- Enter the instance as ghost...
At this point you are entering the SAME instance than your party and you SHOULD revive at entering; your old instance map should be removed and your coprse should appear inside the group's instance because it is now your instance also... but this doesn't happen... you enter the instance as a ghost and remain a ghost... unable to revive because your corpse is not in THIS instance of the map... also your party cannot revive you since your corpse is not there.

### PR DESCRIPTION
**Pull request by Treeston**
Game/Maps: Clean up instance zone-in handling:
- Rename Map::CanEnter to Map::CannotEnter. Return value changed from boolean (true means player can enter) to enum Map::EnterState (CAN_ENTER=0 means player can enter, any other value is a reason for deny).
- Move hack-y player error messages from within Map::CanEnter to the function calling CanEnter as appropriate (primarily WorldSession::HandleAreaTriggerOpcode).
- Modify WorldSession::HandleAreaTriggerOpcode to properly revive the player upon touching the portal leading to the instance they died in even if they are currently unable to zone in. Fixes and closes #15758.
- Modify Player::LoadFromDB to log player into the instance ID they logged out of, then begin homebind timer as appropriate. Fixes and closes #15561.

### CODE REVIEW

File: src/server/game/Maps/MapInstanced.cpp [hunk 1]
```diff
@@ -278,8 +278,8 @@ bool MapInstanced::DestroyInstance(InstancedMaps::iterator &itr)
     return true;
 }
 
-bool MapInstanced::CanEnter(Player* /*player*/)
+Map::EnterState MapInstanced::CannotEnter(Player* player)
```
Comment (Ascathor) [inline src/server/game/Maps/MapInstanced.cpp]: home/travis/build/TrinityCore/TrinityCore/src/server/game/Maps/MapInstanced.cpp:281:51: fatal error: 
      unused parameter 'player'
      [-Wunused-parameter]
  ...player)
     ^

Just comment it out again, even though I do not know why it needs player as handed variable.

File: src/server/game/Maps/Map.h [hunk 2]
```diff
@@ -373,7 +373,23 @@ class Map : public GridRefManager<NGridType>
...
+        enum EnterState
+        {
+            CAN_ENTER = 0,
+            CANNOT_ENTER_ALREADY_IN_MAP = 1, // Player is already in the map
+            CANNOT_ENTER_NO_ENTRY, // No map entry was found for the target map ID
+            CANNOT_ENTER_UNINSTANCED_DUNGEON, // No instance template was found for dungeon map
+            CANNOT_ENTER_DIFFICULTY_UNAVAILABLE, // Requested instance difficulty is not available for target map
+            CANNOT_ENTER_NOT_IN_RAID, // Target instance is a raid instance and the player is not in a raid group
+            CANNOT_ENTER_CORPSE_IN_DIFFERENT_INSTANCE, // Player is dead and their corpse is not in target instance
+            CANNOT_ENTER_INSTANCE_BIND_MISMATCH, // Player's instance bind does not
```
Comment (Ascathor) [inline src/server/game/Maps/Map.h]: What does it mean ? I think you forgot a part. Was it supposed to be "does not match to instance" or something ?

**Comment by Ascathor** [comment]
Great job, don't mind my noobish comments. :) Just things I noticed.

File: src/server/game/Maps/Map.cpp [hunk 3]
```diff
@@ -2989,20 +2990,14 @@ bool InstanceMap::CanEnter(Player* player)
                 if (iPlayer->IsGameMaster()) // bypass GMs
                     continue;
                 if (!player->GetGroup()) // player has not group and there is someone inside, deny entry
-                {
-                    player->SendTransferAborted(GetId(), TRANSFER_ABORT_MAX_PLAYERS);
-                    return false;
-                }
+                    return CANNOT_ENTER_MAX_PLAYERS;
                 // player inside instance has no group or his groups is different to entering player's one, deny entry
                 if (!iPlayer->GetGroup() || iPlayer->GetGroup() != player->GetGroup())
```
Comment (Ascathor) [inline src/server/game/Maps/Map.cpp]: Couldn't this be replaced with if (player->GetGroup() || (!iPlayer->GetGroup() || iPlayer->GetGroup() != player->GetGroup()) to be more efficient ?

**Comment by Treeston** [comment]
@Ascathor any comments are helpful, thanks for donating your time

File: src/server/game/Maps/Map.cpp (hunk 3 above)
Comment (Treeston) [inline src/server/game/Maps/Map.cpp]: Generated code should be the same, and your version is harder to read. Also you missed a !, it should be
`!player->GetGroup() || !iPlayer->GetGroup() || player->GetGroup != iPlayer->GetGroup()`
and you could even omit the second check out of the three completely.

Comment (Ascathor) [inline src/server/game/Maps/Map.cpp]: That I forgot there, friend. However, if you did it like this:

if (!player->GetGroup() ||
   !iPlayer->GetGroup() ||
   !player->GetGroup() != iPlayer->GetGroup())

You have clear, readable code that is reduced and allows you to place comments after that. However, I assume that's mostly a case of codestyle decision. Both work here quite well.

**Comment by Treeston** [comment]
Adding TODO: Fix #15561 while I'm at it.

Current plan: Store instance ID in character DB along with location info, and zone them into that instance if possible upon login.

File: src/server/game/Miscellaneous/Language.h [hunk 4]
```diff
@@ -1203,7 +1203,8 @@ enum TrinityStrings
 
     LANG_NPCINFO_INHABIT_TYPE                     = 11008,
     LANG_NPCINFO_FLAGS_EXTRA                      = 11009,
-    LANG_INSTANCE_LOGIN_GAMEMASTER_EXCEPTION      = 11010
+    LANG_INSTANCE_LOGIN_GAMEMASTER_EXCEPTION      = 11010,
 
+    LANG_INSTANCE_BIND_MISMATCH = 11014
```
Comment (Ascathor) [inline src/server/game/Miscellaneous/Language.h]: Probably me being somewhat fussy with this, but values should be aligned with spaces. Before someone elses fusses over this :P

**Comment by ccrs** [comment]
:clap: :clap: :clap:

**Comment by Re3os** [comment]
Nice very nice @Treeston

File: src/server/game/Entities/Player/Player.cpp [hunk 5]
```diff
@@ -18667,37 +18691,68 @@ bool Player::Satisfy(AccessRequirement const* ar, uint32 target_map, bool report
...
 }
 
-bool Player::IsInstanceLoginGameMasterException() const
+bool Player::CheckInstanceValidity(bool /*isLogin*/)
 {
-    if (CanBeGameMaster())
-    {
-        ChatHandler(GetSession()).SendSysMessage(LANG_INSTANCE_LOGIN_GAMEMASTER_EXCEPTION);
+    // game masters' instances are always valid
+    if (IsGameMaster())
```
Comment (ccrs) [inline src/server/game/Entities/Player/Player.cpp]: Maybe change this into CanBeGameMaster() ?

Comment (Treeston) [inline src/server/game/Entities/Player/Player.cpp]: No, because it would produce a Heisenbug. Game master capability is checked [over here](https://github.com/TrinityCore/TrinityCore/pull/16110/files#diff-5589ee47b3a7ad220cff105a8fe7eac3R17179).
