### PR TITLE
Scripts/Karazhan: make Barnes properly start the Opera Event

### LINKED ISSUE #21881: Karazhan Issues with Opera Event
**Description:**

After talking to Barnes to start the "Opera Event" he walks to the middle of the opera hall and he should introduce one of the events that should occur, however he doesnt introduce any event and then he walks back out of the hall. The curtain opens but there is no boss, so you get stucked in the hall and not being able to enter again because the "Instance is in Combat".

**Current behaviour:**

Opera Event is not working, Barnes doesn't introduce the event.

**Expected behaviour:**

Opera Event Should work.

**Steps to reproduce the problem:**

1. Step. Enter Karazhan and kill Moroes to be able to talk with Barnes.
2. Step Talk to Barnes and enter the opera event.
3. Step Watch how he walks back and the you get stucked in.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 52cfea6d9c47+ 2018-04-25 11:14:01 +0200 (3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using Boost version: 1.65.1
Using MySQL version: 5.6.39
Using CMake version: 3.10.2
Compiled on: Windows 10.0.16299
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Disabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 588247501 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.64

**Operating system:** Win 10 x64

### PR DESCRIPTION
**Pull request by Maxwelllmj**
**Changes proposed:**

Make Barnes properly start the Opera Event
-  

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #21881

**Tests performed:** win10

**Known issues and TODO list:** 

- [1 ]  Make Barnes properly start the Opera Event

### CODE REVIEW

**Comment by Gooyeth** [comment]
The pull needs to be corrected.

**Comment by Maxwelllmj** [comment]
I deleted other changes.

**Comment by Kittnz** [comment]
Can broadcast text be used for this?

**Comment by Maxwelllmj** [comment]
@Kittnz  I found the gossipMenuItemID.

**Comment by illfated** [comment]
Suggestion for recommended PR title format:
**Scripts/Karazhan: make Barnes properly start the Opera Event**

(if that description is incorrect or less than precise, feel free to modify so it describes the PR)

File: src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp [hunk 1]
```diff
@@ -354,6 +354,7 @@ class npc_barnes : public CreatureScript
                     break;
                 case GOSSIP_ACTION_INFO_DEF + 2:
                     CloseGossipMenuFor(player);
+                    m_uiEventId = urand(1, 3);
```
Comment (Gooyeth) [inline src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp]: It must be random?, if so, maybe use `urand(EVENT_OZ, EVENT_RAJ)`

Comment (illfated) [reply src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp]: Good point, better use enum if the numbers corresponds with existing enums (otherwise it looks like "magic" numbers).

File: src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp [hunk 2]
```diff
@@ -822,6 +822,12 @@ class npc_grandmother : public CreatureScript
         {
             npc_grandmotherAI(Creature* creature) : ScriptedAI(creature) { }
 
+            bool GossipHello(Player* player) override
```
[the remark this answers is not in the document]
Comment (illfated) [reply src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp]: Oh. gossip menu option missing from Barnes? (sorry, haven't checked)
If yes, I concur, it is better to set up the gossip option in DB.

**Comment by Maxwelllmj** [comment]
@Gooyeth In db  the gossipmenuid is 7441， But it is 7443 in code.

**Comment by Gooyeth** [comment]
@Maxwelllmj: Yes, but you must use 7441.

In the DB MenuID 7441 -> ActionMenuID 7442 -> ActionMenuID 7443

**Comment by Gooyeth** [comment]
@Maxwelllmj: Apply for Grandmother #21982

**Review by Gooyeth — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by Keader** [comment]
Tested in game?
Working fine?
