### PR TITLE
Scripts/Westfall: Implement Quest: "Murder Was The Case That They Gave Me"

### LINKED ISSUE #29299: Murder Was The Case That They Gave Me
### Description

Murder Was The Case That They Gave Me
https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me
The problem is that it is not possible to start a dialogue with the Homeless

### Expected behaviour

Talk to some of the homeless people who attacked Jansen to find any information about who killed Hmurobrov.
https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me
Homeless ID
• 42414
• 42415
• 42416
• 42417

### Steps to reproduce the problem

Quest Murder Was The Case That They Gave Me
https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me
Talk to some of the homeless people who attacked Jansen to find any information about who killed Hmurobrov.
Homeless ID
• 42414
• 42415
• 42416
• 42417
The problem is that it is not possible to start a dialogue with the Homeless

### Branch

master

### TC rev. hash/commit

[8c26b93](https://github.com/TrinityCore/TrinityCore/commit/8c26b9350d4817d05530f4fd1a9c1c0a4f26edcc)

### Operating system

Windows 7 x64

### Custom changes

no

### PR DESCRIPTION
**Pull request by Naddley**
- re-spawn Hobo spawns with createobject2
- pooled spawns

**Changes proposed:**

-  scripted quest "Murder Was The Case That They Gave Me" ID: 26209

**Issues addressed:**

Closes #29299

**Tests performed:**

build, tested ingame

**Known issues and TODO list:** (add/remove lines as needed)

None

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 1]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+    {
+        if (!player)
+            return;
+
+        _events.CancelEventGroup(Events::MurderWasTheCaseThatTheyGaveMe::GroupOOC);
+        me->SetFacingToObject(player);
+
+        uint16 slot = player->FindQuestSlot(Quests::MurderWasTheCaseThatTheyGaveMe);
+
+        if (player->GetQuestSlotCounter(slot, 0) == 0)
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: a simple constexpr array with a loop could do better here, especially since it's it's the same syntax all over:

```suggestion
    struct ClueData
    {
        uint8 counterIndex;
        uint32 spellId;
        Text::HoboText textId;
    };

    static constexpr ClueData clues[4] =
    {
        { 0u, Spells::HoboInformation1, Text::HoboText::HoboSayClueOne   },
        { 1u, Spells::HoboInformation2, Text::HoboText::HoboSayClueTwo   },
        { 2u, Spells::HoboInformation3, Text::HoboText::HoboSayClueThree },
        { 3u, Spells::HoboInformation4, Text::HoboText::HoboSayClueFour  },
    };
```

then you can use a for loop, mind you auto here might be not permited, but you can replace it with the correct type, we replace return with break here:

```suggestion
for (auto const& clue : clues)
    {
        if (player->GetQuestSlotCounter(slot, clue.counterIndex) == 0)
        {
            player->CastSpell(player, clue.spellId);
            Talk(clue.textId, player);
            me->DespawnOrUnsummon(12s);
            break;
        }
    }
```

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 2]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+        {
+            _flee = true;
+            me->DoFleeToGetAssistance();
+            Talk(Text::HoboText::HoboFlee);
+        }
+    }
+
+    void JustDied(Unit* who) override
+    {
+        if (who->IsCreature() && who->ToCreature()->IsAIEnabled())
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: iirc there's no need to check IsAIEnabled anymore in scripts when accessing AI since there's no way it's ever null, there's a tick in between where AI is filled with a "nullAI" type

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 3]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+
+    void Reset() override
+    {
+        ScriptedAI::Reset();
+        _events.Reset();
+        _bribeFailed = false;
+        _hoboRage = false;
+        _flee = false;
+        me->SetNpcFlag(UNIT_NPC_FLAG_GOSSIP);
+        me->SetUnitFlag(UNIT_FLAG_IMMUNE_TO_PC);
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: Use SetImmuneToPC helper instead

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 4]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+    }
+};
+
+// 79168 - Hobo Aggro
+class spell_westfall_aggro_hobo : public SpellScript
+{
+    void HandleDummy(SpellEffIndex /*effIndex*/)
+    {
+        if (Creature* creature = GetHitCreature())
+            if (creature->IsAIEnabled())
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: same thing here with AI check

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 5]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+                return true;
+        }
+
+        me->RemoveNpcFlag(UNIT_NPC_FLAG_GOSSIP);
+        CloseGossipMenuFor(player);
+        if (roll_chance_i(clueGainChance))
+            GiveClue(player);
+        else
+        {
+            me->RemoveUnitFlag(UNIT_FLAG_IMMUNE_TO_PC);
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: Use SetImmuneToPC helper

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 6]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+            AttackStart(player);
+        }
+
+        return false;
+    }
+
+    void GiveClue(Player* player)
+    {
+        if (!player)
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: is there any need to check this?

File: src/server/scripts/EasternKingdoms/zone_westfall.cpp [hunk 7]
```diff
@@ -289,6 +355,285 @@ class spell_westfall_despawn_jangolode_actor : public SpellScript
...
+            me->DoFleeToGetAssistance();
+            Talk(Text::HoboText::HoboFlee);
+        }
+    }
+
+    void JustDied(Unit* who) override
+    {
+        if (who->IsCreature() && who->ToCreature()->IsAIEnabled())
+            who->ToCreature()->AI()->DoAction(Actions::MurderWasTheCaseThatTheyGaveMe::HoboAggroActionDone);
+        me->CastSpell(me, Spells::SummonRagamuffinLooter);
```
Comment (Nyr97) [inline src/server/scripts/EasternKingdoms/zone_westfall.cpp]: DoCastSelf

**Comment by andsim** [comment]
i have not been able finish this mission

**Comment by Nyr97** [comment]
It'd be good to have feedback as to why you couldn't so the owner can apply the appropriate fix for it.

**Comment by Foldor1** [comment]
I've just tested and it's working fine for me - The quest can be completed

**Review by mdX7 — APPROVED** [review]
