### PR TITLE
Core/MMaps: Fix crash introduced in commit 32e8b65

### LINKED ISSUE #16910: [6.x] Crash regarding MMaps and Terrain Swap
**Description**: This is a crash issue that happens when MMaps are enabled and you try to teleport or enter a location that uses Terrain Swap

**Current behaviour**: The server crashes with the following call stack https://gist.github.com/DJScias/38fa629f607dc6970be96a6bc09850fc (I know it says revision unknown, but git is being a tool. It uses the TC Hash/commit found below)

**Expected behaviour**: The server shouldn't crash and use the proper MMaps in the Terrain Swap.

**Steps to reproduce the problem**:

1. Enable MMaps
2. Enable Terrain Swap on a location like Lion's Landing, Dominion Point , this is done through the DB table terrain_swap_defaults and terrain_phase_info. (If you don't know the TerrainSwapMap id's, it's 1061 for Dominion Point and 1062 for Lion's Landing)
3. Go to said location that uses Terrain Swaps (like Lion's Landing, Dominion Point), 
4. Get instantly crashed with the above crashlog

**Branch(es)**: 6x

**TC hash/commit**: https://github.com/TrinityCore/TrinityCore/commit/363731aac827f3eab051064ba466cef49f6cc111 I'm still using 6.2.3, reluctant to go 6.2.4 yet. But this would not be fixed even if I was on 6.2.4

**TDB version**: latest TDB 6.03

**Operating system**: Windows 10 Pro, 64-bit

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

### PR DESCRIPTION
**Pull request by et65**
**Changes proposed**:
- Fix crash introduced in commit 32e8b6506fc064fdba134d692dfe99298e43f055 related to mmaps and terrain swap.
- Also fix remaining memory leaks scenarios in MMapManager.
- Now map base tiles are loaded at map loading, like phased tiles, and unloaded at map unloading (also like phased tiles). Non phased maps are not loaded into base tiles attribute but when unloading map, retrieved by "dtNavMesh::removeTile" data parameter and free by "dtFree" function. No more usage of `DT_TILE_FREE_DATA` which allowed recast navigation to auto free datas at tile remove that is not what we want.

**Target branch(es)**: 6x

**Issues addressed**: Closes #16910

**Tests performed**: Move in game through many locations. Also tested scenario described in the issue.

### CODE REVIEW

File: src/common/Collision/Management/MMapManager.cpp [hunk 1]
```diff
@@ -518,32 +523,21 @@ namespace MMAP
 
         // header xy is based on the swap map's tile set, wich doesn't have all the same tiles as root map, so copy the xy from the orignal header
         header->x = oldTile->header->x;
-        header->y = oldTile->header->y;
+        header->y = oldTile->header->y;;
```
Comment (Aokromes) [inline src/common/Collision/Management/MMapManager.cpp]: double ;;

Comment (et65) [inline src/common/Collision/Management/MMapManager.cpp]: Bad copy paste, thanks x)

**Comment by jackpoz** [comment]
did you test this using a memory leak detector like valgrind ?

**Comment by et65** [comment]
@jackpoz : No, I'm a little busy these days.

Can anyone do the test?

**Comment by et65** [comment]
@jackpoz : I've just run Dr Memory, and no more memory leaks concerning mmaps. Just a warning fixed in a new commit.

**Comment by jackpoz** [comment]
I doubt users will run Dr Memory/valgrind so it's more of debugging it line but line and checking with valgrind all the possible cases to ensure no new leaks/crashes are added

**Comment by et65** [comment]
@jackpoz : It's what I've done and no more memory leaks ;)

**Comment by DJScias** [comment]
@et65 Hello there,

Sorry for the late responses, github didn't beep me.
I'll apply these changes to my local and see what happens.

Kind regards,
DJScias

**Comment by DJScias** [comment]
@et65 Hello there,

Can confirm the crash is gone, there's still a bug related to pathwalking of the NPCs in regards of terrain swaps though but that wasn't part of the issue.

Kind regards,
DJScias

**Comment by et65** [comment]
@DJScias : Thanks for your feedback.
