### PR TITLE
[3.3.5] Core/Loot: Fix conditional Master Loot

### LINKED ISSUE #14328: [3.3.5] Core/LootMgr: Master Loot in VOA
When Use Master Loot In Instance [ VOA ] 
1 - Boss Dead
2- Player Check Boss Loot [ See item 1 is usable For he ] [ item 2 In not Usable [Red] ]
3- Master Looter Check Boss Loot to Send Item for Playrs
4- Item 1 Buged [ cannot loot ] Item 2 Send secces
( if All player check loot Boss and See Items and item avalable for them (example : pala Set pala) this item is Buged and master looter cannot loot )
Boss loot buged and cannot loot on any mode [ free for all ] and other . Cannot loot
<<>> I test it jsut occured On VOA . ICC is OK <<>>>
sry for bad english

https://github.com/TrinityCore/TrinityCore/commit/b6e27a0144aebc3bfe9ba1339c4cec59574609c5
Last
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9406992-3-3-5-master-loot-bug-in-voa?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #17768: Core/Loot Issue with item Reins of the Grand Black War Mammoth
**Description**:
Item Reins of the Grand Black War Mammoth(item=43959 | item=44083 ) can not be looted from [Toravon the Ice Watcher(npc=38433)](http://www.wowhead.com/npc=38433/toravon-the-ice-watcher) if the group is using Master Looter

I saw it fails on the check in player.cpp at line 25699

``` cpp
    if (!qitem && item->is_blocked)
    {
        SendLootRelease(GetLootGUID());
        return;
    }
```

but i dunno what causes that, note that this item is a conditional loot(different items for alliance and horde),could be related, or not.

**Current behaviour**: Everybody can see and try to loot the item, but nobody can actually loot the item, it fails for all of them.

**Expected behaviour**: Master looter should be able to select the player who will receive the item and be able to do so.

**Steps to reproduce the problem**:
1. Run sql bellow to increase the drop chance(original is 1%)

``` sql
DELETE FROM `creature_loot_template` WHERE `Entry`=38433 and`Item` IN(1,49426);
UPDATE `creature_loot_template` SET `Chance`=100 WHERE `Entry`=38433 and`Item`=2;
```
1. Assemble a raid group(2 players are enough)
2. Change lootMode to Master loot
3. .go crea id 38433 (just the leader with the master loot are enough)
4. Kill Toravon (.damage is fine)
5. Try to loot the Mount
6. See that you are not able to loot it

**Branch(es)**: 3.3.5

**TC hash/commit**:  70b3373da1d0

### PR DESCRIPTION
**Pull request by arbylee**
**Changes proposed:**
-  Fixes an issue with conditional loot with group loot type of masterloot.

There is a follow_loot_rules flag originally introduced by 869ea349 that was meant to force certain quest items to follow group looting rules.

From what I can tell, that flag was accidentally used in the logic for NonQuestNonFFAConditionalLoot related calls, probably because there's a simple struct with the misleading name of QuestItem that is being used for Quest items, FFA items, AND Conditional items.  I've renamed this to NotNormalItem (similar to the naming of "FillNotNormalLootFor") to prevent further confusion

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #17768 closes #14328

**Tests performed:** 
Builds and tested in game.  The Reins of the Grand Black War Mammoth can now be master looted

### CODE REVIEW

**Comment by Re3os** [comment]
nice!!

File: src/server/game/Loot/LootMgr.h [hunk 1]
```diff
@@ -180,24 +180,24 @@ struct TC_GAME_API LootItem
     const AllowedLooterSet & GetAllowedLooters() const { return allowedGUIDs; }
 };
 
-struct QuestItem
+struct NotNormalItem
```
Comment (Shauren) [inline src/server/game/Loot/LootMgr.h]: Since you are renaming it already, wouldn't it be better if you included the word "Loot" in the name as well?

Comment (arbylee) [inline src/server/game/Loot/LootMgr.h]: As in NotNormalLootItem? That seems reasonable to me

**Comment by Ghost-R** [comment]
@arbylee Dos this pull fix problem for master loot items [Head of Onyxia]: Hode 49643/Alliance 49644 ?

**Comment by arbylee** [comment]
@Ghost-R Yes, I just tried it out with and without these changes. Head of Onyxia has conditions on it (Horde/Alliance check) so it was affected by this bug as well. Thanks for the test case

**Comment by Aokromes** [comment]
Any opposition to merge this? if no i will merge it on 24h
