### PR TITLE
Core/Spells: Fixed Consecration

### LINKED ISSUE #25761: Spell: Consecration
**Description:**
Consecration(class:paladin) does not work.

Branch(es):
master

TrinityCore rev. 5710f377e76e 2020-12-23 17:53:13 +0100 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

OS: Win

**Steps to reproduce the problem:**
1)Create characters paladin.
2)cmd .levelup 5.
4)Use spell Consecration ( https://www.wowhead.com/spell=26573/consecration )

### PR DESCRIPTION
**Pull request by mdX7**
**Changes proposed:**

-  Fixed Consecration damage
-  Implemented Hammer of the Righteous
-  Partly implemented Consecrated Ground (slow is implemented, size increase is not)

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #25761

**Tests performed:**

(Does it build, tested in-game, etc.)
build, tested ingame

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Consecrations radius is not increased when talented into Consecrated Ground. That requires spell modifiers to be also applied on areatriggers, which is not part of this pr. Ref spellid: 204054. Differences in sniff shown here: https://gist.github.com/mdX7/44a1fbf29e51f1c0aafd5a059590ccf2/revisions

### CODE REVIEW

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 1]
```diff
@@ -44,6 +46,12 @@ enum PaladinSpells
     SPELL_PALADIN_BLESSING_OF_LOWER_CITY_SHAMAN  = 37881,
     SPELL_PALADIN_BLINDING_LIGHT_EFFECT          = 105421,
     SPELL_PALADIN_CONCENTRACTION_AURA            = 19746,
+    SPELL_PALADIN_CONSECRATED_GROUND_PASSIVE     = 204054,
+    SPELL_PALADIN_CONSECRATED_GROUND_SLOW        = 204242,
+    SPELL_PALADIN_CONSECRATION                   = 26573,
+    SPELL_PALADIN_CONSECRATION_DAMAGE            = 81297,
+    SPELL_PALADIN_CONSECRATION_PROTECTION_AURA   = 188370,
+    SPELL_PALADIN_CONSECRATION_PROTECTION_MOD    = 344172,
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_paladin.cpp:54]: This is autolearned passive aura, you should not cast it

**Review by Shauren — CHANGES_REQUESTED** [review]
