### PR TITLE
Core/Spells Add EffectAttributesFlags with NoScaleWithStack (0x40

### LINKED ISSUE #26021: Core/Spells Prayer of Mending aura (41635) value is multiplied by stack amount
**Description:**

When casting spell 41635 (prayer of mending aura) with spell modifiers with SPELLVALUE_BASE_POINT0 and SPELLVALUE_AURA_STACK, it will show the text `Heals for <value> the next time you take damage.`.
Instead of <value> though, it will show the result of BasePoint * AuraStack. It should only show the BasePoint.

The place where we multiply the value by the stack amount is this:
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L670

**Expected behaviour:**

The value should not be multiplied by the stack amount.
Not for this spell specifically anyway, and probably others too - depending on some condition.

**Steps to reproduce the problem:**

1. Cast spell 41635 with both modifiers as specified above
2. Note the actual tooltip shown in game is a product of the 2 values, rather than just the base points values

**Branch(es):**

master

**TC rev. hash/commit:** 

23144d0665504e2e24ee790e900bb8de0df4aa08

**Operating system:** 

Windows 10

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Defined enum EffectAttributesFlags with NoScaleWithStack value (0x40) and implemeneted

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26021 

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

@mdX7 Thanks for helping figuring this out!

### CODE REVIEW

File: src/server/game/Spells/SpellInfo.cpp [hunk 1]
```diff
@@ -372,6 +372,7 @@ SpellImplicitTargetInfo::StaticData  SpellImplicitTargetInfo::_data[TOTAL_SPELL_
 };
 
 SpellEffectInfo::SpellEffectInfo(SpellInfo const* spellInfo, SpellEffectEntry const* _effect)
+    : EffectAttributes(EFFECT_ATTRIBUTES_FLAGS_NO_SCALE_WITH_STACK)
```
Comment (mdX7) [inline src/server/game/Spells/SpellInfo.cpp:375]: we should initialize it with _NONE

Comment (matanshukry) [reply src/server/game/Spells/SpellInfo.cpp:375]: yeah that should of been `EFFECT_ATTRIBUTES_FLAGS_NONE`. Was definitely a mistake. I'll fix that

**Review by Shauren — APPROVED** [review]
