### PR TITLE
Core/Misc : Personal spawn

### LINKED ISSUE #18254: [master] Personal Spawning (Invisibility) (50$ bounty)
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** On Retail there are some personalized events (cosmetics, dialogs).
This means only one player can see the NPCs or GOs for these events. For other players, these NPCs and GOs are invisible.
(Example: Mardum Starting Area, Sevis Brightflame at the Gates)

**Current behaviour:** NYI.

**Expected behaviour:** Method to set a player as only seer for temp spawns should be implemented.

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** master 

**TC rev. hash/commit:**  7624c7cd95fda9f0406fa8b00d8f9febe42ba820

**TDB version:**  703.00

**Operating system:**  Win 10

### PR DESCRIPTION
**Pull request by Traesh**
**Changes proposed:**

-  Add a parameter "visibleBySummonerOnly" to the "SummonCreature" function to allow summon to be visible only by summoner
- Automatically set "visibleBySummonerOnly" to true for spell with SummonPropertiesFlag & 0x10 (see PR conversation for more informations)
- If summon is personnal spawn, all aggro is redirected to summoner, unless victim is also a personnal spawn with same summoner

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**
- Closes #18254

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled, tested ingame

**Known issues and TODO list:** 

- None

### CODE REVIEW

**Comment by jackpoz** [comment]
In which cases could this be needed ? Wondering if saving a list of guids will fit the needs

**Comment by Aokromes** [comment]
Legion specific spawns.

**Comment by jackpoz** [comment]
what's a legion specific spawn ?

**Comment by Aokromes** [comment]
Some creatures spawns only for the player started a quest, etc.

**Comment by Traesh** [comment]
I remember seeing a "group spawn", an escort NPC (actually just showing you the path, no action at all) only visible by an entire group at quest start.

I will check if i can find it back

**Comment by Traesh** [comment]
Not only in legion, already since Cataclysm at least. For example, in gnome start zone, one of the first quest spawn a gnome that guide you to the exit. In Pandaren start zone, the female pandaren show you the path to a cavern for the next quest. Theses NPCs are only visible by the summoner.

I remember seeing a "group spawn", an escort NPC only visible by an entire group at quest start. I will check if i can find it back. If i can't or if it has been deprecated, maybe a simple "bool visibleBySummonerOnly" would be enough

**Comment by Shauren** [comment]
What about summoned creatures that enter combat with other summoned creatures as part of one quest? With your code they won't be able to see each other and will never fight

**Comment by jackpoz** [comment]
> an escort NPC only visible by an entire group at quest start

what about relogging and players joining the group after ? I wonder if the guid set implementation should be hidden in a class that can take care of caching the guids etc, handling all the different possible conditions (summoner, single player, group members, etc)

**Comment by Krudor** [comment]
I think it's a bit more complicated than this :P
Shauren's point is one, but personal spawns can also show up for other players as a different creature entry.
There's a quest where you run around with Yrel in Draenor. You see Yrel, but other players instead see a creature named something like "Draenei Vindicator" or something similiar.

**Comment by GlassFace** [comment]
or another think , Creatures summoned with this method can see each other easily ( because all summoned with same caster , both enemy and friendly ) and they can fight each other . and this is usefull for many quests for escorting and fighting that u only see , like WOD area quests

**Comment by Traesh** [comment]
Cannot find any evidence of "group personnal spawn", the only quest i had in mind was not using this system :) Switched to "bool visibleOnlyBySummoner", lot simplier.

Now visibility check only apply on players, creatures will be able to see each other and fight if necessary

@Krudor You are perfectly right, but these are two differents system :)

**Comment by LuigiElleBalotta** [comment]
Question: do GameObjects have personal spawn too?

**Comment by Riztazz** [comment]
Convo with shocker earlier today about this system, just leaving it here in case we were right ;p

```
14:25 <+Riztazz> Shocker: got any clues about personal spawns?;p
14:25 <%Shocker> what personal spawns?
14:25 <+Riztazz> https://github.com/TrinityCore/TrinityCore/issues/18254
14:26 <%Shocker> no idea how blizz does it, but i'm positive it needs a server-side custom visibility thing
14:26 <%Shocker> most likely in CanSeeOrDetect
14:26 <%Shocker> long story short: IsPersonalCreature && creature->GetOwner() != seer => return false
14:26 <+Riztazz> yeah, the how part is easy, the hard part is figuring out when and for whom its supposed to work ;p
14:27 <%Shocker> oh. well, i dont think there is any way to figure this out automatically
14:27 <%Shocker> sounds like fully server-side controlled
14:28 <%Shocker> my 2cents: implement a new smart AI action OR modify the current ones to take a new param in consideration: is personal = 0/1
14:29 <+Riztazz> shauren will cockblock
14:30 -!- Malcrom_Android [~AndChat39@1B8D97BA.71E6B73B.39A15EFE.IP] has joined #trinity
14:30 <%Shocker> you made me curious, any idea of an npc that must be personal and has a summon_creature spell?
14:30 <%Shocker> wanting to see the summon properties/whatever for that spell
14:32 <+Riztazz> we did check with Traesh, there are some flags that are similar
14:32 <+Riztazz> gimme a sec
14:32 <%Shocker> for every spell?
14:32 <+Riztazz> ID - 73306 Summon Lilian Voss (Guardian)
14:32 <+Riztazz> 88988 this one as well
14:33 <+Riztazz> 92238 Summon Tarindrella
14:33 <+Riztazz> but nothing that would make sense ;p
14:33 <%Shocker> well, yeah, 0x100 and 0x8 shared for all
14:34 <%Shocker> flags are too "old" to be for the new personal system
14:34 <+Riztazz> ye
14:34 <+Riztazz> those were present in wotlk
14:36 <%Shocker> what's shared is the summon slot (quest)
14:36 <%Shocker> but.. that is also used for many other spells
14:36 <+Riztazz> maybe they changed it since cata
14:36 <+Riztazz> because first personal spawns appeared in cata
14:37 <+Riztazz> and all summon spells with that summon slot are personal
14:37 -!- Polaretto1 [~Polaretto@Rizon-A9BF0A04.cust.vodafonedsl.it] has quit [Quit: http://www.kiwiirc.com/ - A hand crafted IRC client]
14:37 <%Shocker> are you sure? too many spells, let me see how many
14:37 <+Riztazz> could be
14:37 <+Riztazz> someone would need to check somehow :P
14:38 <%Shocker> hm
14:38 <%Shocker> 336 spells
14:38 <+Riztazz> not too many
14:39 <%Shocker> there are 13k summon spells and only 336 have summonproperties with slot 6
```

**Comment by Krudor** [comment]
http://www.wowhead.com/npc=91911/draenei-vindicator
Here's the creature I was talking about. The comment there explains it quite nicely.

**Comment by Traesh** [comment]
Slot 6 from SummonProperties seem interesting, but we found Aysa from Wandering Island being a personal spawn and not having summon slot 6

Three possibilities (by Riztazz™) :

1. Slot 6 is generic way, but there is some script handled personal spawn
2. Slot 6 is generic way, or else handled by a specific flag
3. We are wrong

**Comment by Riztazz** [comment]
Those Aysa summon spells have 0x800000 flag in common, did some more research and most summon spells from wandering isle use that flag, could be some kind of different personal summon settings?
Its not group related, we did check that with @Traesh

**Comment by meji46** [comment]
79263, 79265, 79663, 79664, 79665, 79712  (personal spawns) Rise of the Brotherhood & Livin' the Life quests (https://www.youtube.com/watch?v=g1iLm_KtIuw all players have their own invocations)

74436 (not sure)

**Comment by Traesh** [comment]
@Riztazz They don't have Slot 6 but they all have flag 0x2000 and 0x100, like Aysa

**Comment by meji46** [comment]
79712 only has flag 16

**Comment by Traesh** [comment]
Are they moving ? Maybe they are just in a specific phase ?

If no, it was option 3 :p

**Comment by meji46** [comment]
Rise of the Brotherhood: player accepts quest, he enters in a specific phase (232?). In that phase, he casts summon spells. I did the quest in retail with a friend and: 
I could only see my friend and my summons
I accepted the quest after him (~20-30s later) but I saw the whole event

Livin' the Life: use the item (player casts summon spells). Only caster sees his summoned creatures (no phases & no invisibility auras)

**Comment by Riztazz** [comment]
It seems that personal spawns were present since wotlk, lol

**Comment by Riztazz** [comment]
Change 0x00000010 (this is called hexadecimal) to decimal and see which one it is ;p

**Comment by meji46** [comment]
¿? I know hexadecimal

I'm talking about possible problems with summoned vehicles (4), pets (2) and controlled npcs (3). 

For example a player in a summoned vehicle with flag 16. Others players will only see the player but no the vehicle

**Comment by BAndysc** [comment]
There are much more personal spawns which aren't using slot 6, eg: 97633, 97635, 98069, 98201, 98758... Actually summons with property 3100 look suspiciously "personally" (tho it is only a guess)

**Comment by meji46** [comment]
Can you provide any example of non-personal summon with flag 16?

**Comment by BAndysc** [comment]
Ok, sorry, I was almost certain that NPCs from Hot Rod in Goblin starting area (66597 Rolling with my Homies: Summon Ace, 66599 Summon Gobber, 66600 Summon Izzy) were visible by everyone, but I have just tested it and nope - noone else could see npcs in my hot rod :o

**Comment by Traesh** [comment]
Just removed personal spawn from vehicle spawn, could create some troubles. If a vehicle exist as a personal spawn, some more test will be needed before enabling it

**Comment by funjoker** [comment]
Can abybody verfify the flag for personal spawn?

**Comment by Riztazz** [comment]
There is a spawn in Death knight starting zone which is personal spawn - tested with @Traesh.
ID - 52363 Call Salanar

So we were pretty sure this is what handles visibility in cases like that

**Comment by funjoker** [comment]
An addition to the discussion.
Groups do not effect Personal Spawns, because every player get's their own Personal Spawns, when they do the same quest with delay. First person who starts is first person who finishs.

**Comment by meji46** [comment]
Yep, I commented that above about the quest Rise of the Brotherhood

About personal summoned vehicles, in quest "Krolmir, Hammer of Storms", every player get their own vehicle and it's logic that players can't see other players or their vehicles

**Comment by BAndysc** [comment]
Also important thing with personal summons: what if npc visible to others attacks personal summon. Will other people see npc attacking air? I have tested http://www.wowhead.com/quest=14070 and it looks like those summoned npcs do not have threat list. I have attacked Bruno Flameretardant, then my friend entered combat with him (but later we didn't attack) and our summoned npcs were fighting with Bruno. At the beginning Bruno was chasing me, later, even though my friend didn't attack Bruno, he gained aggro (but I was still in combat).

So first thought: maybe all personal summons cannot have aggro?

On the other hand Orkus from spell 89983 can be attacked by Vanndar in the quest. BUT Vanndar is as well personal summon. But maybe there is flag strictly associated with personal summon: something like "threat goes to summoner"? When we compare this spell with Ace from goblins, there are only two differences. Orkus summon spell (can have threatlist) has flag 1024 and Rolling with my homies spells (cannot have threat list) have flag 512. Ability to have threat list seems natural (so I think if there was a flag for this, the flag would say "cannot have threatlist", NOT "can have threatlist), so I would say we should investigate flag 512 as well.

**Comment by BAndysc** [comment]
Also, there is no need to exclude vehicles: there is no spells with flag 16 and type SUMMON_TYPE_VEHICLE2, there is only one spell with flag 16 and type SUMMON_TYPE_VEHICLE:

      spell ID npc entry    spell name
      69522     36901    Summon Submerge Bunny

And it is bunny for Call of Duty in Vashj'ir, so it actually is personal.

When it goes to flag 16 and category SUMMON_CATEGORY_VEHICLE, all those spell but few are cameras - so yes, they should be personal and I am guess the rest is also personal sumons.

https://gist.github.com/BAndysc/06edb53f030bddcd5e0d257b23ca104d

**Comment by BAndysc** [comment]
Also, I believe there is no need to exclude vehicles: there is no spells with flag 16 and type SUMMON_TYPE_VEHICLE2, there is only one spell with flag 16 and type SUMMON_TYPE_VEHICLE:

      spell ID npc entry    spell name
      69522     36901    Summon Submerge Bunny

And it is bunny for Call of Duty in Vashj'ir, so it actually is personal.

When it goes to flag 16 and category SUMMON_CATEGORY_VEHICLE, all those spells until cata have camera in name - so yes, they should be personal. I do not know MoP+ content, but I guess the rest also should be personal. Can anyone confirm it?

https://gist.github.com/BAndysc/06edb53f030bddcd5e0d257b23ca104d

**Comment by Traesh** [comment]
Here is a list of all spells with summon properties & 16 (thanks to @Shocker)

https://mega.nz/#!rxp22ZrR!vnXerfa0D7mRHOceWTDLoHEC27R6pDjQIQp1CrqedoQ

I tested at least 50 of them randomly, only personal spawn so far

**Comment by funjoker** [comment]
Well feels legit.
Checked some spells i know and they are actually all personal spawns.
So it works.

**Comment by LuigiElleBalotta** [comment]
Status about this is still "in testing"?

**Comment by BAndysc** [comment]
Visibility to attackers is strongly connected with it as I have mentioned it in previous comment: https://github.com/TrinityCore/TrinityCore/pull/19231#issuecomment-284155332 

Otherwise other players (who do not see our personal spawn) might see a npc fighting with the air, which is another bug.

**Comment by funjoker** [comment]
When having the original spawn in target. your target is redirected to the personal spawn donno if it's clientside. Also visualy its almost impossible to see a creature swap there.

**Comment by Krudor** [comment]
You sure about that threat change? I think I've seen creatures fight personal spawns of other players, and it looks like they're just fighting something invisible.

**Comment by Traesh** [comment]
@Krudor Not 100% but at least 90% sure, i tested with the only personnal spawn i knew can fight, the gobelin's one (see BAndysc comments) and they indeed have no aggro to non-personnal spawn NPCs.

I looked some personnal spawn spells like http://www.wowhead.com/spell=125641 and it appear that when the NPC should be able to fight, Blizzard switch to another system (http://www.wowhead.com/spell=125989), where you see the NPC as Kovok, and other players see it as Young Kunchong

**Comment by BAndysc** [comment]
As far as I remember Zuni in quest An Ancient Enemy (24814) also never gains aggro.

**Comment by funjoker** [comment]
what about target redirect?

If you have oringal npc as target your targt gets redirected to personal spawn

**Comment by Traesh** [comment]
@funjoker if it's handled like the scenes, it's client side. If a NPC with same entry & exact same coordinates spawn and the other disappear, the client redirect the focus on the new spawn

**Comment by Shauren** [comment]
Pretty sure there is a special field for that in CreateObject block - SmoothPhasing

**Comment by jcmillions** [comment]
I'm sure this has been mentioned already, but I'll say it just incase it hasn't. When you make a demon hunter and accept the first quest, I think that first quest adds personal spawns

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Object/Object.h

**Comment by funjoker** [comment]
If you ride on an npc which is personal spawn the player gets invisible for other players.

**Comment by Caydan** [comment]
Notice, that also messages from personal spawned creature should only be visible for its owner.

**Comment by Aokromes** [comment]
@caydan nope, i have seen texts of personal spawns outside personal spawn.

**Comment by funjoker** [comment]
well :D whisper function is implemented so np

**Comment by funjoker** [comment]
I guess the redirect is handle when DestroyObject is in same SMSG_UPDATE_OBJECT of Creation of Object.

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Object/Object.h

**Comment by Seyden** [comment]
Whats missing? I will finish it

**Comment by Lopfest** [comment]
I didnt test this, but good job.
Do you think you can implement automatic personal spawn despawn on summoer logout into this PR?

**Comment by funjoker** [comment]
I guess this spawn despawn is a own thing about temporary spawns and summon flags

**Comment by funjoker** [comment]
This PR must be done by someone else.
Traesh is not into opensource anymore (atm)

**Comment by funjoker** [comment]
It's alive. Praise the sun ^^

**Comment by funjoker** [comment]
Any news ?

**Comment by Traesh** [comment]
Don't know, work great on my AshamaneCore, merge it ?

File: src/server/game/Combat/ThreatManager.cpp [hunk 1]
```diff
@@ -415,11 +416,28 @@ void ThreatManager::addThreat(Unit* victim, float threat, SpellSchoolMask school
 void ThreatManager::doAddThreat(Unit* victim, float threat)
 {
     uint32 redirectThreadPct = victim->GetRedirectThreatPercent();
+    Unit* redirectTarget = victim->GetRedirectThreatTarget();
```
Comment (Shauren) [inline src/server/game/Combat/ThreatManager.cpp]: Why is this weird threat redirection needed? Shouln't you make it that personal spawns cannot see any players except their "owner" (and his pets/guardians/other summons) (pretty sure this isnt here for aggro on spawn event)

Comment (Traesh) [reply src/server/game/Combat/ThreatManager.cpp]: Because personal spawns can attack non-personal spawns, the attacked creature must attack the owner and not the personal spawn

**Comment by meji46** [comment]
Are personal vehicles working properly? (Owner's invisibility)

Personal summons must inherit owner's phases dynamically

**Comment by Lopfest** [comment]
btw, what about personal gameobject spawns? I have two spells for that: 115426, 115435

**Comment by funjoker** [comment]
Dead PR?
Ignoring?

**Comment by funjoker** [comment]
need :D

File: src/server/game/Entities/Creature/TemporarySummon.h [hunk 2]
```diff
@@ -60,12 +60,16 @@ class TC_GAME_API TempSummon : public Creature
...
+        void SetVisibleBySummonerOnly(bool visibleBySummonerOnly) { m_visibleBySummonerOnly = visibleBySummonerOnly; }
+        bool IsVisibleBySummonerOnly() const { return m_visibleBySummonerOnly; }
+
         const SummonPropertiesEntry* const m_Properties;
     private:
         TempSummonType m_type;
         uint32 m_timer;
         uint32 m_lifetime;
         ObjectGuid m_summonerGUID;
+        bool m_visibleBySummonerOnly;
```
Comment (joschiwald) [inline src/server/game/Entities/Creature/TemporarySummon.h]: do we need this boolean? we could read this from summonproperties directly

Comment (Shauren) [reply src/server/game/Entities/Creature/TemporarySummon.h]: I assume this is for scripts that do summoning without a spell

**Review by Shauren — APPROVED** [review]

**Comment by jackpoz** [comment]
@Traesh what about pvp ? is it handled in this PR ?

**Comment by Traesh** [comment]
@jackpoz any example where a personal spawn should help you in pvp ?

**Comment by jackpoz** [comment]
Well I cast a spell to spawn a personal spawn with an ally char, walked close by with a horde char and the spawn attacked and killed the horde.

So my question is more like "is pvp handled at all or was it ignored in the implementation ?"

**Comment by Traesh** [comment]
Hum no you're right it was ignored, the personal spawn should completely ignore the other players
