### PR TITLE
Scripts/Wandering Isle: Implement quest 29420 (The Spirit's Guardian)

### LINKED ISSUE #30625: DB/QUEST :  quest  https://www.wowhead.com/quest=29420/the-spirits-guardian
### Description

This quest is part of the first chaine quest of pandaren starting zone.
When you enter the cave you should have https://www.wowhead.com/spell=98035/flame-spout comming from ground like this : https://www.youtube.com/watch?v=l-lrrVScFv4.
But instead you receive constantly invisible damages and you die.
After that you have a wall of flammes that don't let you reach : https://www.wowhead.com/npc=54135/master-li-fei

### Expected behaviour

Blizzlike, like the video.

### Steps to reproduce the problem

.add quest 29420
Go to the cave

### Branch

master

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/2a51a6454912df635099572d07789a1d6789ff4d 2025-01-21 14:11:54 +0100 (master branch)

### Operating system

Windows 10

### Custom changes

None

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement quest 29420 (The Spirit's Guardian)

Issues addressed:

closes #30625

**Tests performed:**

Tested in-game

### CODE REVIEW

File: sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+-- Areatrigger 7736
+DELETE FROM `areatrigger_scripts` WHERE `entry`=7736;
+INSERT INTO `areatrigger_scripts` VALUES
+(7736, 'SmartTrigger');
+
+-- Conditions
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceGroup`=1 AND `SourceEntry`=7736;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
+(30, 0, 7736, 0, 0, 47, 0, 29420, 2, 0, 0, 0, 0, '', 'Areatrigger 7736 only triggers when quest 29420 is taken'),
+(30, 0, 7736, 0, 0, 1, 0, 92571, 0, 0, 1, 0, 0, '', 'Areatrigger 7736 only triggers when player has not aura 92571');
```
Comment (Naddley) [inline sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql:12]: wrong SourceGroup in DELETE

File: sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=32 AND `SourceEntry`=59626;
+INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `ConditionStringValue1`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
+(32, 5, 59626, 0, 0, 47, 0, 29420, 2, 0, '', 0, 0, 0, '', 'Flame Spout gets visible if Quest: 29420 is completed');
```
Comment (Naddley) [inline sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql:16]: missing SourceGroup in DELETE

File: sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+-- SAI
+DELETE FROM `smart_scripts` WHERE `entryorguid`=7736 AND `source_type`=2;
+INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
+(7736, 2, 0, 0, 46, 0, 100, 0, 7736, 0, 0, 0, 0, '', 86, 92571, 2, 19, 60176, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On Trigger - Cast CSA Area Trigger Dummy Timer Aura');
```
Comment (Naddley) [inline sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql:21]: param1 is not needed anymore for EventType 46

File: sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+(102399, 5849, 0, 29423, 0, 0, 2, 3, 0, 9);
+
+-- Texts
+DELETE FROM `creature_text` WHERE `CreatureID`=60176;
+INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
+(60176, 0, 0, 'The fire spirit is upset. It\'s dangerous to enter the shrine now...', 12, 0, 100, 396, 0, 0, 59680, 0, 'Huojin Monk to Player');
+
+-- Creature
+UPDATE `creature_template` SET `unit_flags`=33555200, `AIName`='SmartAI' WHERE `entry`=59626; -- 59626 (Flame Spout) - Flame Spout
+UPDATE `creature_template_addon` SET `auras`='96112' WHERE `entry`=59626; -- 59626 (Flame Spout) - Shrink
```
Comment (Naddley) [inline sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql:54]: missing script for spell

**Review by Naddley — CHANGES_REQUESTED** [review]

**Review by mdX7 — APPROVED** [review]
