### PR TITLE
[WIP] Core/Spells: Implemented various rogue spells:

### LINKED ISSUE #26309: Core/Spell - Not working spells, Rogue class 9.0.2
Description:
13750 (adrenaline rush) - It doesn't increase energy on 50
14161 (Cruelty) - Passive skill. It doesn't work.
76806 (Mastery:Main Gauche) - Does nothing when used.
79134 (Venomous Wounds)- Doesn't work both parts of this passive skill.
14062 (Night Stalker) - Skills makes a right speed, but makes a weak damage.
328077  (Death symbol) - Does nothing when used.
53 (backstab) - Damage behind the targer doesn't increase.
343160  (Intent) - Does nothing when used.
193537 - Does nothing when used.
200758 - Does nothing when used.
193315, 279876 - There is a chances which is not appear.
193358 - Both parts of this skills does not work.
193359 - Does nothing when used.
200806 - Does nothing when used.
5171 (meat grinder) - It doesn't have a cooldown and work only 1-time in game. 
408 (blow to the kidneys) - Do not depends on combo points. Stun enemy just for 1 sec.
315341 (Between the eyes) - Must make a debuff on enemy and take a high damage by combat points.

Expected behaviour:
13750 (adrenaline rush) - Increase energy by 50 and increase battle speed.
14161 (Cruelty) - there must be a change to return combat points back.1 combat point - 20% chance. 5 points - 100%
76806 (Mastery:Main Gauche) - there must be a chance to make a automatic attack by the offhand.
79134 (Venomous Wounds) -Garrote or Rupture deal Bleed damage to a poisoned target. If an enemy dies while afflicted by your Rupture, you regain energy based on its remaining duration.
14062 (Night Stalker) is active, you move 20% faster and your abilities deal 50% more damage.
328077 (Death symbol) - Symbols of Death provide a guaranteed critical strike with the next ability that extends the streak.
343160 (Intent) When you use invisibility there must be a buff on "meat grinder"  and 185438 give 2 combat points.
53 (backstab) must increase damage when you are behind on your enemy.
193537 (Weapon master) Shadowstrike and Backstab have a 15% chance to hit the target twice each time they deal damage.
193315, 279876 - There must be a 35% chance to have a buff which makes a next "185763 pistol shot" free of combat points + 2x damage.
193359 - Abilities, which is use combo-points increase power of the 79096 spell.
200806 (bleeding) - bleeding effects are accelerated by 100%
5171 (meat grinder) - Increase battle speed by 50%
408 (blow to the kidneys) - Stuns enemy. Stun-time depends of the combo points.
315341 (Between the eyes) - Damage doesn't depends on combo points and there is no debuff on enemy.

**Steps to reproduce the problem:**

Create a Rogue class character.
Give a character 60 lvl.
Try using any of the spells listed.

**TC rev. hash/commit:**

2420f4e

**Operating system:** 

Windows 10 x64

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

- Changed _ValidateSpellInfo a bit to handle arrays
- Spells
  - Ruthlessness
  - Mastery: Main Gauche
  - Venomous Wounds
  - Night Stalker
  - Symbols of Death
  - Backstab
  - Premeditation
  - Grand Melee
  - True Bearing
  - Exsanguinate
  - Slice and Dice
  - Between the Eyes
  - Roll the Bones

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26309

**Tests performed:**

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:**

- [x] 193358 Grand Melee (Roll The Bones enhancement) - need to cast a spell with duration.
- [x] 5171 Slice and Dice - Need to set duration for each enhancement - need to cast a spell with duration.

### CODE REVIEW

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 1]
```diff
@@ -303,6 +406,99 @@ class spell_rog_killing_spree : public SpellScriptLoader
...
+    static uint32 const SpellsLength = std::extent<decltype(Spells)>::value;
+
+    bool Validate(SpellInfo const* /*spellInfo*/) override
+    {
+        return ValidateSpellInfo(Spells);
+    }
+
+    void HandleDummy(SpellEffIndex /*effIndex*/)
+    {
+        int32 idx = irand(0, SpellsLength);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_rogue.cpp:490]: Requires #26945
```cpp
    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        int currentDuration = 0;
        for (int i = 0; i < SpellsLength; i++)
        {
            if (Aura* aura = GetCaster()->GetAura(Spells[i]))
            {
                currentDuration = aura->GetDuration();
                GetCaster()->RemoveAura(aura);
            }
        }

        std::vector<uint32> possibleBuffs(std::begin(Spells), std::end(Spells));
        Trinity::Containers::RandomShuffle(possibleBuffs);

        // https://www.icy-veins.com/wow/outlaw-rogue-pve-dps-rotation-cooldowns-abilities
        // 1 Roll the Bones buff  : 100.0 % chance;
        // 2 Roll the Bones buffs : 19 % chance;
        // 5 Roll the Bones buffs : 1 % chance.
        int8 chance = irand(1, 100);
        int8 numBuffs = 1;
        if (chance <= 1)
            numBuffs = 5;
        else if (chance <= 20)
            numBuffs = 2;

        for (int i = 0; i < numBuffs; i++)
        {
            uint32 spellId = possibleBuffs[i];
            CastSpellExtraArgs args;
            args.TriggerFlags = TRIGGERED_FULL_MASK;
            args.AddSpellMod(SPELLVALUE_DURATION, GetSpellInfo()->GetDuration() + currentDuration);
            GetCaster()->CastSpell(GetCaster(), spellId, args);
        }
    }
```

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 2]
```diff
@@ -202,6 +269,42 @@ class spell_rog_deadly_poison : public SpellScriptLoader
...
+    void HandleProc(AuraEffect* aurEff, ProcEventInfo& procInfo)
+    {
+        Spell const* procSpell = procInfo.GetProcSpell();
+        int32 amount = aurEff->GetAmount() * procSpell->GetPowerTypeCostAmount(POWER_COMBO_POINTS).get() * 1000;
+
+        if (Unit* target = GetTarget())
+        {
+            if (Aura* aura = target->GetAura(SPELL_ROGUE_SLICE_AND_DICE))
+                aura->SetDuration(aura->GetDuration() + amount);
+            // else // TODO cast SPELL_ROGUE_SLICE_AND_DICE with duration = amount
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_rogue.cpp:297]: Requires #26945
```cpp
else
[
    CastSpellExtraArgs args;
    args.TriggerFlags = TRIGGERED_FULL_MASK;
    args.AddSpellMod(SPELLVALUE_DURATION, amount);
    target->CastSpell(target, SPELL_ROGUE_SLICE_AND_DICE, args);
}

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 3]
```diff
@@ -355,80 +577,199 @@ class spell_rog_rupture : public SpellScriptLoader
...
+    {
+        Unit* caster = GetCaster();
+        if (_hasPremeditationAura)
+        {
+            if (caster->HasAura(SPELL_ROGUE_SLICE_AND_DICE))
+                if (Aura* premeditationPassive = caster->GetAura(SPELL_ROGUE_PREMEDITATION_PASSIVE))
+                    if (AuraEffect const* auraEff = premeditationPassive->GetEffect(EFFECT_1))
+                        SetHitDamage(GetHitDamage() + auraEff->GetAmount());
+
+            // Grant up to 10 seconds of slice and dice
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_rogue.cpp:624]: Requires #26945

According to my tests on retail (~20 tries) its always 10s instead of "up to" 10
```cpp
    CastSpellExtraArgs args;
    args.TriggerFlags = TRIGGERED_FULL_MASK;
    args.AddSpellMod(SPELLVALUE_DURATION, 10*IN_MILLISECONDS); 
    target->CastSpell(target, SPELL_ROGUE_SLICE_AND_DICE, args);
```

**Comment by Aokromes** [comment]
Conflicting files
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Auras/SpellAuraEffects.h
src/server/scripts/Spells/spell_rogue.cpp
