### PR TITLE
Core/Player: implement PlayerChoice

### LINKED ISSUE #19173: Missing Structure SMSG_DISPLAY_PLAYER_CHOICE
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:** SMSG_DISPLAY_PLAYER_CHOICE wrong structure

**Current behaviour:**  Missing Struct 

**Expected behaviour:** Needs Legion struct to make SPELL_EFFECT_LAUNCH_QUEST_CHOICE running.

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Branch(es):** master

**TC rev. hash/commit:**  dd3dd5991d94de67fcb8fae36e857ce0fe045791

**TDB version:**  703.00

**Operating system:**  Win 10

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by Traesh**
**Changes proposed:**

- Handle Player Choices opcodes & spell_effect
- Add OnPlayerChoiceResponse PlayerScript

**Target branch(es):** master

- master

**Issues addressed:** Closes #19173

**Tests performed:** (Does it build, tested in-game, etc.)
build, work ingame

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Add locale tables
- [x] Add support for item/currency/rep/itemChoice rewards (Won't be fix in this PR)

### CODE REVIEW

File: src/server/game/Handlers/QuestHandler.cpp [hunk 1]
```diff
@@ -673,3 +673,11 @@ void WorldSession::HandleRequestWorldQuestUpdate(WorldPackets::Quest::RequestWor
 
     SendPacket(response.Write());
 }
+
+void WorldSession::HandlePlayerChoiceResponse(WorldPackets::Quest::PlayerChoiceResponse& packet)
+{
+    if (!GetPlayer())
```
Comment (joschiwald) [inline src/server/game/Handlers/QuestHandler.cpp]: this can never happen because of STATUS_LOGGEDIN

File: src/server/game/Server/Packets/QuestPackets.cpp [hunk 2]
```diff
@@ -599,3 +599,79 @@ WorldPacket const* WorldPackets::Quest::WorldQuestUpdate::Write()
...
+    data.FlushBits();
+    data << int32(response.ResponseID);
+    data << int32(response.ChoiceArtFileID);
+
+    data.WriteBits(response.Answer.length(), 9);
+    data.WriteBits(response.Header.length(), 9);
+    data.WriteBits(response.Description.length(), 11);
+    data.WriteBits(response.Confirmation.length(), 7);
+
+    data.WriteBit(response.Reward.is_initialized());
```
Comment (joschiwald) [inline src/server/game/Server/Packets/QuestPackets.cpp]: flush bits here and not on top of bytebuffer operator overloads

File: src/server/game/Globals/ObjectMgr.cpp [hunk 3]
```diff
@@ -9937,3 +9938,101 @@ void ObjectMgr::LoadSceneTemplates()
...
+    {
+        do
+        {
+            ++responseCount;
+            Field* fields = responses->Fetch();
+
+            int32 choiceId      = fields[0].GetInt32();
+            int32 ResponseID    = fields[1].GetInt32();
+
+            PlayerChoice& choice = _playerChoiceContainer[choiceId];
```
Comment (Shauren) [inline src/server/game/Globals/ObjectMgr.cpp]: validate that choiceId is valid

File: src/server/game/Globals/ObjectMgr.cpp [hunk 4]
```diff
@@ -9937,3 +9938,101 @@ void ObjectMgr::LoadSceneTemplates()
...
+        do
+        {
+            ++rewardCount;
+            Field* fields = rewards->Fetch();
+
+            int32 choiceId      = fields[0].GetInt32();
+            int32 ResponseID    = fields[1].GetInt32();
+
+            PlayerChoice& choice = _playerChoiceContainer[choiceId];
+            PlayerChoiceResponse& response = choice.Responses[ResponseID];
```
Comment (Shauren) [inline src/server/game/Globals/ObjectMgr.cpp]: validate that choiceId and ResponseID are valid

File: src/server/game/Globals/ObjectMgr.cpp [hunk 5]
```diff
@@ -9937,3 +9938,101 @@ void ObjectMgr::LoadSceneTemplates()
...
+            response.Reward = reward;
+
+        } while (rewards->NextRow());
+    }
+    else
+    {
+        TC_LOG_INFO("server.loading", ">> Loaded 0 player choices responses reward. DB table `playerchoice_response_reward` is empty.");
+    }
+
+    TC_LOG_INFO("server.loading", ">> Loaded %u player choices in %u ms.",          choiceCount,    GetMSTimeDiffToNow(oldMSTime));
```
Comment (Shauren) [inline src/server/game/Globals/ObjectMgr.cpp]: all of these timings are a lie, log after each loop

Comment (Shauren) [reply src/server/game/Globals/ObjectMgr.cpp]: no need to track `coiceCount` separately, just log the .size() with SZFMTD specifier

**Review by Shauren — CHANGES_REQUESTED** [review]

File: src/server/scripts/Commands/cs_debug.cpp [hunk 6]
```diff
@@ -71,6 +71,7 @@ class debug_commandscript : public CommandScript
             { "sellerror",     rbac::RBAC_PERM_COMMAND_DEBUG_SEND_SELLERROR,     false, &HandleDebugSendSellErrorCommand,       "" },
             { "setphaseshift", rbac::RBAC_PERM_COMMAND_DEBUG_SEND_SETPHASESHIFT, false, &HandleDebugSendSetPhaseShiftCommand,   "" },
             { "spellfail",     rbac::RBAC_PERM_COMMAND_DEBUG_SEND_SPELLFAIL,     false, &HandleDebugSendSpellFailCommand,       "" },
+            { "playerchoice",  rbac::RBAC_PERM_COMMAND_DEBUG_SEND_SPELLFAIL,     false, &HandleDebugSendPlayerChoiceCommand,    "" },
```
Comment (Shauren) [inline src/server/scripts/Commands/cs_debug.cpp]: remember to either change it when finishing PR or remove

**Comment by Shauren** [comment]
Locales won't be handled in this PR
Inserts non-english data to main table?

File: src/server/game/Globals/ObjectMgr.cpp [hunk 7]
```diff
@@ -9937,3 +9938,118 @@ void ObjectMgr::LoadSceneTemplates()
...
+        {
+            ++rewardCount;
+            Field* fields = rewards->Fetch();
+
+            int32 choiceId      = fields[0].GetInt32();
+            int32 ResponseID    = fields[1].GetInt32();
+
+            if (_playerChoiceContainer.find(choiceId) == _playerChoiceContainer.end())
+            {
+                TC_LOG_ERROR("sql.sql", "Table `playerchoice_response_reward` has nonexistent choiceId: %u, skipped", choiceId);
```
Comment (Shauren) [inline src/server/game/Globals/ObjectMgr.cpp]: Always log the entire PK in case of error to be able to quickly identify offending rows

File: src/server/game/Globals/ObjectMgr.cpp [hunk 8]
```diff
@@ -9937,3 +9938,118 @@ void ObjectMgr::LoadSceneTemplates()
...
+        {
+            ++responseCount;
+            Field* fields = responses->Fetch();
+
+            int32 choiceId      = fields[0].GetInt32();
+            int32 ResponseID    = fields[1].GetInt32();
+
+            if (_playerChoiceContainer.find(choiceId) == _playerChoiceContainer.end())
+            {
+                TC_LOG_ERROR("sql.sql", "Table `playerchoice_response` has nonexistent choiceId: %u, skipped", choiceId);
```
Comment (Shauren) [inline src/server/game/Globals/ObjectMgr.cpp]: PK log

File: src/server/game/Server/Packets/QuestPackets.cpp [hunk 9]
```diff
@@ -599,3 +599,79 @@ WorldPacket const* WorldPackets::Quest::WorldQuestUpdate::Write()
...
+    return data;
+}
+
+WorldPacket const* WorldPackets::Quest::DisplayPlayerChoice::Write()
+{
+    _worldPacket << int32(Choice.ChoiceId);
+    _worldPacket << uint32(Choice.Responses.size());
+    _worldPacket << SenderGUID;
+    _worldPacket.WriteBits(Choice.Question.length(), 8);
+    _worldPacket.WriteBit(0); // CloseChoiceFrame
```
Comment (Shauren) [inline src/server/game/Server/Packets/QuestPackets.cpp]: You know what it is. Define a field in packet class instead of a placeholder comment

File: src/server/game/Server/Packets/QuestPackets.h [hunk 10]
```diff
@@ -22,6 +22,7 @@
 #include "ItemPacketsCommon.h"
 #include "QuestDef.h"
 #include "ObjectGuid.h"
+#include "ObjectMgr.h"
```
Comment (Shauren) [inline src/server/game/Server/Packets/QuestPackets.h]: Massive objection.
Forward declare `PlayerChoice` and use a pointer to it in packet class.

File: src/server/game/Globals/ObjectMgr.h [hunk 11]
```diff
@@ -1514,6 +1555,15 @@ class TC_GAME_API ObjectMgr
             return nullptr;
         }
 
+        PlayerChoice const* GetPlayerChoice(int32 choiceId) const
```
Comment (soulfrost) [inline src/server/game/Globals/ObjectMgr.h]: move implentation out of class scope?

File: src/server/game/Spells/SpellEffects.cpp [hunk 12]
```diff
@@ -5666,6 +5666,17 @@ void Spell::EffectEnableBattlePets(SpellEffIndex /*effIndex*/)
     plr->GetSession()->GetBattlePetMgr()->UnlockSlot(0);
 }
 
+void Spell::EffectLaunchQuestChoice(SpellEffIndex effIndex)
+{
+    if (effectHandleMode != SPELL_EFFECT_HANDLE_HIT_TARGET)
+        return;
+
+    if (!unitTarget || unitTarget->GetTypeId() != TYPEID_PLAYER)
```
Comment (soulfrost) [inline src/server/game/Spells/SpellEffects.cpp]: IsPlayer() ?

**Comment by tkrokli** [comment]
@Traesh : to find the info you need to please travis-ci's complaint about `auth_database.sql`, check https://github.com/Traesh/TrinityCore/commit/e573607ccd01e3e4ae2142f8ef56cce66b173b8a#diff-1ba0de69017826217e09c546694ee146R2226 and run the SQL query below to get the info you need to insert on a new line 2227 (beneath the existing line 2226, extend the SQL query):
```sql
SELECT * FROM `auth`.`updates` WHERE `name`='9999_99_99_99_auth.sql';
```
(of course, if you use a different name for your PR auth DB, modify as needed)

Format the resulting output the same way as https://github.com/Traesh/TrinityCore/commit/e573607ccd01e3e4ae2142f8ef56cce66b173b8a#diff-1ba0de69017826217e09c546694ee146R2226 and replace the semicolon at the end of line 2226 with a comma.

**Comment by funjoker** [comment]
ADD LOCALES HERE ALREADY! xD

**Comment by Traesh** [comment]
@funjoker Add a bounty here already :D

**Comment by Traesh** [comment]
This one's for you @funjoker

File: src/server/game/Globals/ObjectMgr.cpp [hunk 13]
```diff
@@ -10087,3 +10087,69 @@ void ObjectMgr::LoadPlayerChoices()
...
+
+            AddLocaleString(question, locale, data.Question);
+        } while (result->NextRow());
+
+        TC_LOG_INFO("server.loading", ">> Loaded " SZFMTD " Player Choice locale strings in %u ms", _playerChoiceLocaleContainer.size(), GetMSTimeDiffToNow(oldMSTime));
+    }
+
+    oldMSTime = getMSTime();
+
+    //                                               0         1           2       3       4       5            6
```
Comment (tkrokli) [inline src/server/game/Globals/ObjectMgr.cpp]: Remove 12 spaces before 0 for this comment line to be useful.

**Comment by funjoker** [comment]
:* ^^

File: src/server/game/Globals/ObjectMgr.h [hunk 14]
```diff
@@ -1326,6 +1384,18 @@ class TC_GAME_API ObjectMgr
             if (itr == _pointOfInterestLocaleStore.end()) return nullptr;
             return &itr->second;
         }
+        PlayerChoiceLocale const* GetPlayerChoiceLocale(uint32 ChoiceID) const
+        {
+            PlayerChoiceLocaleContainer::const_iterator itr = _playerChoiceLocaleContainer.find(ChoiceID);
+            if (itr == _playerChoiceLocaleContainer.end()) return nullptr;
+            return &itr->second;
+        }
+        PlayerChoiceResponseLocale const* GetPlayerChoiceResponseLocale(uint32 ChoiceID, uint32 ResponseID) const
```
Comment (soulfrost) [inline src/server/game/Globals/ObjectMgr.h]: move implentation out of class scope?

File: src/server/game/Server/Packets/QuestPackets.h [hunk 15]
```diff
@@ -633,9 +637,35 @@ namespace WorldPackets
...
+
+        class PlayerChoiceResponse final : public ClientPacket
+        {
+        public:
+            PlayerChoiceResponse(WorldPacket&& packet) : ClientPacket(CMSG_CHOICE_RESPONSE, std::move(packet)) { }
+
+            void Read() override;
+
+            int32 ChoiceID;
+            int32 ResponseID;
```
Comment (soulfrost) [inline src/server/game/Server/Packets/QuestPackets.h]: initializating?

**Comment by tkrokli** [comment]
BTW,  `sql/base/auth_database.sql` needs to be updated too, either right before or during merge, for the `rbac_permissions`, `rbac_linked_permissions` and `updates` tables ("the usual suspects").

File: src/server/game/Globals/ObjectMgr.h (hunk 14 above)
Comment (Traesh) [reply src/server/game/Globals/ObjectMgr.h]: Consistency, all other implentation are in class scope

File: src/server/game/Handlers/QuestHandler.cpp [hunk 16]
```diff
@@ -673,3 +673,8 @@ void WorldSession::HandleRequestWorldQuestUpdate(WorldPackets::Quest::RequestWor
 
     SendPacket(response.Write());
 }
+
+void WorldSession::HandlePlayerChoiceResponse(WorldPackets::Quest::PlayerChoiceResponse& packet)
+{
+    sScriptMgr->OnPlayerChoiceResponse(GetPlayer(), packet.ChoiceID, packet.ResponseID);
```
Comment (joschiwald) [inline src/server/game/Handlers/QuestHandler.cpp]: generic rewards should be handled here

File: src/server/game/Globals/ObjectMgr.cpp [hunk 17]
```diff
@@ -9817,6 +9818,40 @@ bool ObjectMgr::GetRealmName(uint32 realmId, std::string& name, std::string& nor
...
+{
+    auto itr = _classExpansionRequirementStore.find(class_);
+    if (itr != _classExpansionRequirementStore.end())
+        return itr->second;
+    return EXPANSION_CLASSIC;
+}
+
+SceneTemplate const* ObjectMgr::GetSceneTemplate(uint32 sceneId) const
+{
+    auto itr = _sceneTemplateStore.find(sceneId);
```
Comment (soulfrost) [inline src/server/game/Globals/ObjectMgr.cpp]: can be done just like 
```c
    return Trinity::Containers::MapGetValuePtr(_sceneTemplateStore, sceneId);
```

File: src/server/game/Globals/ObjectMgr.cpp [hunk 18]
```diff
@@ -9817,6 +9818,40 @@ bool ObjectMgr::GetRealmName(uint32 realmId, std::string& name, std::string& nor
...
+    if (itr != _sceneTemplateStore.end())
+        return &itr->second;
+
+    return nullptr;
+}
+
+PlayerChoice const* ObjectMgr::GetPlayerChoice(int32 choiceId) const
+{
```
Comment (soulfrost) [inline src/server/game/Globals/ObjectMgr.cpp]: can be done just like 
```c
    return Trinity::Containers::MapGetValuePtr(_playerChoiceContainer, choiceId);
```

File: src/server/game/Globals/ObjectMgr.h (hunk 14 above)
Comment (soulfrost) [reply src/server/game/Globals/ObjectMgr.h]: can be done just like 
```c
    return Trinity::Containers::MapGetValuePtr(_playerChoiceResponseLocaleContainer, std::make_pair(ChoiceID, ResponseID));

```

and same above

**Comment by Shauren** [comment]
adding rewards

File: sql/updates/world/master/9999_99_99_99_playerchoice.sql [hunk 19]
```diff
@@ -0,0 +1,83 @@
+DELETE FROM `command` WHERE `name` IN ('debug send playerchoice');
+INSERT INTO `command` (`name`, `permission`, `help`) VALUES
+('debug send playerchoice', 869, 'Syntax: .debug send playerchoice $choiceId\r\nSend given choice to player.');
+
+DROP TABLE IF EXISTS `playerchoice`;
+CREATE TABLE `playerchoice` (
+  `ChoiceID` INT (10) NOT NULL,
+  `Question` VARCHAR (255),
```
Comment (joschiwald) [inline sql/updates/world/master/9999_99_99_99_playerchoice.sql]: can we have VerifiedBuild columns here?

**Review by Shauren — APPROVED** [review]
