### PR TITLE
[3.3.5] Naxxramas clean-up and bug-fix follow-up

### LINKED ISSUE #14966: [3.3.5][Spell] Jagged Knife
rev: https://github.com/TrinityCore/TrinityCore/commit/7c01638d45b3eaed7af124a43f21cc6d15407667

How it is:
npc=29836 cast http://wotlk.openwow.com/spell=55348 and http://wotlk.openwow.com/spell=55521
Both Spellvisuals look like cubes.
Proof:
http://i.imgur.com/WOm9mvj.jpg

How it should be:
Both Spellvisuals should look like knifes

### PR DESCRIPTION
**Pull request by Treeston**
Naxxramas follow-up. Includes lots of little things fixes, code style improvements that are apparent now that I'm more familiar with the core than I was when I started this whole thing, and corrections to bugs found during our Naxx10 QC runs.
- Maexxna:
  - TODO: Web Wrap deals damage through Ice Block / Divine Shield (see issue #16658)
  - Web Wrap no longer targets pets
- Heigan the Unclean:
  - Ripped out all the hack-y code in `instance_naxxramas.cpp` that handled eruptions before, along with all previous eruption spawns.
  - Replaced it with sniffed spawn locations and room partitions, as well as new eruption tile handling wholly contained in `boss_heigan`.
- Loatheb:
  - Sniffed Spore timings
  - Cleanup
- Thaddius:
  - Get rid of the ugly timed reset hack in instance script. SetRespawnTime does what we want.
  - Put players in combat with Thaddius when the encounter starts. This prevents them from dropping out of combat between phases.
  - Clean up Ball Lightning behavior. Thaddius will now prefer attacking available targets in melee range even if his primary target leaves melee range.
- Instructor Razuvious:
  - Death Knight Understudies now break free of mind control when Instructor Razuvious dies, causing them to properly be affected by "Hopeless"
  - Razuvious has been informed that Rubik's Cubes become noticably easier to solve if you buy six-colored ones. (closes #14966)
    - Thus, he will no longer take out his frustration on raid groups by throwing unsolved two-colored variants at them.
- Gothik the Harvester:
  - Put a bit of a dampener on his rapid-fire shadow-bolting action. Now properly waits a second between casts.
- Four Horsemen:
  - Baron Rivendare is no longer vulnerable to Stun, Snare and Shackle (heh, bet you nobody tried _that_ one) effects.
  - Fixed edge case where the Horsemen encounter would sometimes fail to properly start.
- Sapphiron:
  - Minus a ton of hacks:
    - Blizzard now uses proper spell for spawning
    - LoS check for ice blocks moved to spellscript instead of using ApplySpellImmune hacks
  - Ice block handling cleaned up. Players can no longer clip outside their block.
  - Timer cleanup. Air phase is now no longer stupid.
  - Can no longer die during air phase (prevent looting issues).
  - Now properly knocks people away from below him during air phase
  - Clean up birth GO spawn handling
  - People can no longer take frost damage while turned into an ice block

### CODE REVIEW

File: sql/updates/world/2016_02_09_NAXXCLEANUP.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- Naxxramas instance cleanup
+
+-- Thaddius
+-- Move UNIT_FLAG_STUNNED | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_NOT_SELECTABLE (thaddius' base state) to creature_template instead of applying it in script
+UPDATE `creature_template` SET `unit_flags`=33816896 WHERE `entry`=15928;
```
Comment (joschiwald) [inline sql/updates/world/2016_02_09_NAXXCLEANUP.sql]: stunned flag should be applied by spell

**Comment by chaodhib** [comment]
Great work so far. Here is a bit of feedback. From data taken from sniff, a few observations regarding Sapphiron:

Sapphiron pops a NPC  (entry 16474) using 28560. This NPC lifetime is 30s (at least in 10man. maybe it's different in 25man). Besides 28547, this NPC cast 24780 on itself. Looks like an aura that trigger  some server side spell (24781). Also it looks like this NPC has a target and its movement is not actually random (the spell I just talked about earlier probably plays a role in this. maybe that spell change the target of the NPC periodically):

ServerToClient: SMSG_AURA_UPDATE (0x4707) Length: 16 ConnIdx: 2 Time: 06/16/2012 22:48:32.489 Number: 8335

> ServerToClient: SMSG_AURA_UPDATE (0x4707) Length: 16 ConnIdx: 2 Time: 06/16/2012 **22:48:32.489** Number: 8335
> GUID: Full: 0xF130405A0000C4D9 Type: Creature Entry: 16474 Low: 50393
> [0] Slot: 1
> [0] Spell ID: 24780 (24780)
> [0] Flags: EffectIndex0, NotCaster (9)
> [0] Level: 83
> [0] Charges: 0
> 

> ServerToClient: SMSG_ON_MONSTER_MOVE (0x6E17) Length: 61 ConnIdx: 2 Time: 06/16/2012 **22:48:32.489** Number: 8336
> GUID: Full: 0xF130405A0000C4D9 Type: Creature Entry: 16474 Low: 50393
> Toggle AnimTierInTrans: false
> Position: X: 3522.51 Y: -5260.718 Z: 137.5148
> Move Ticks: 1587262
**Spline Type: FacingTarget (3)
> Facing GUID: Full: XXXXXX Type: Player Low: XXXXXX Name:  XXXXXX**
> Spline Flags: SmoothGroundPath, Walkmode (3145728)
> Move Time: 2855
> Waypoints: 2
> Waypoint Endpoint: X: 3516.209 Y: -5266.508 Z: 137.5568
> [0] Waypoint: X: 3518.859 Y: -5264.113 Z: 137.5358

This video also support that: https://www.youtube.com/watch?v=Ved83wzwS0Y We can clearly see in it that the blizzard follows the player.

Also I found another spell used by Sapphiron: 85667. It's a server side spell. It is used not only by Sapphiron but every boss of the dungeon. According to wowhead, it's a global taunt. That's interesting.

**Comment by chaodhib** [comment]
Also, from the same video as above, we can see that the iceblock also makes you immune to the blizzard.

**Comment by Treeston** [comment]
Yeah, iceblock has an immunity to all frost damage built in in the latest PR. However, due to #16658, this only works for the blizzard right now, not the aura.

**Comment by Treeston** [comment]
Blizzard behavior is now fully implemented using sniffed values.

**Comment by Kittnz** [comment]
Great work here @Treeston

File: src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp [hunk 2]
```diff
@@ -177,49 +181,6 @@ class achievement_spore_loser : public AchievementCriteriaScript
...
-                AfterEffectApply += AuraEffectApplyFn(spell_loatheb_necrotic_aura_warning_AuraScript::HandleEffectApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
-                AfterEffectRemove += AuraEffectRemoveFn(spell_loatheb_necrotic_aura_warning_AuraScript::HandleEffectRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
-            }
-        };
-
-        AuraScript* GetAuraScript() const override
-        {
-            return new spell_loatheb_necrotic_aura_warning_AuraScript();
-        }
-};
```
Comment (joschiwald) [inline src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp]: i don't think removing the aurascript is a good solution, because you can't guarantee that the eventmap is ticking right

File: src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp [hunk 3]
```diff
@@ -211,12 +211,12 @@ class boss_anubrekhan : public CreatureScript
                         events.ScheduleEvent(EVENT_SPAWN_GUARD, 3 * IN_MILLISECONDS);
 
                         events.ScheduleEvent(EVENT_LOCUST_ENDS, RAID_MODE(19, 23) * IN_MILLISECONDS);
-                        events.ScheduleEvent(EVENT_LOCUST, 90000);
+                        events.ScheduleEvent(EVENT_LOCUST, 90 * IN_MILLISECONDS);
```
Comment (joschiwald) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: btw. e4e55a3dcbd846fd583b4fc86344d88ca63588d7

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: You mean `events.Repeat`?

File: src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp (hunk 2 above)
Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp]: What could cause the eventmap to go out of sync with buff durations?

**Comment by Treeston** [comment]
Heigan cleanup finally done. `instance_naxxramas.cpp` is now officially free of boss scripts using it to do its dirty work with terrible hackery.

File: src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp (hunk 3 above)
Comment (sirikfoll) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: events.ScheduleEvent(EVENT_LOCUST, Milliseconds(90))

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: You mean `Seconds(90)`. I see.

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: Do we have something to replace `urandms` too? `something(Seconds(7),Seconds(9))`?

Comment (joschiwald) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: not yet

File: src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp (hunk 2 above)
Comment (joschiwald) [inline src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp]: in this example nothing, that happens only if the boss has a spell with casttime

since the emote depends on the aura, it should be controlled by this aura, it's my oppinion

File: src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp (hunk 3 above)
Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: Gonna stick with `uint32`s for now until the core supports `std::chrono` in more places (diff gets called with it etc).

Comment (Naios) [inline src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp]: The TaskScheduler supports Schedule(Seconds(min), Seconds(max)). Also the Eventmap supports multiple overloads. (I don't think tc will support std::chrono) as difftime since you would need to change almost all scripts.

File: src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp (hunk 2 above)
Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp]: Meh, there's already another timed announcement _without_ an aurascript in the boss (it doesn't coincide with expiry).

**Comment by chaodhib** [comment]
I had a bit of time to test Sapphiron. Here is some additional feedback:
- The blizzard is buggy if only one player is alive: the blizzard follows the only remaining player for about 10s then stops each time. I didn't encounter that problem with 2 players.
- The blizzards can overlap creating multiple dots at the same time (i know its a bug that affect all AoEs atm)
- I don't think the blizzard is supposed to be summoned right on top of a player. This needs investigation but i think they are summoned in a random position and run toward a player as soon as they are active.
- When hovering with the mouse on an iceblock (in p2), my cursor changes as if it were an interactive game object (ex a door). (minor issue)

**Comment by chaodhib** [comment]
interesting video to see the behavior of the blizzard: https://www.youtube.com/watch?v=FkKFziguBpc

i'm not entiretly sure but it looks like 2 blizzards should give 2 debuffs and not just one. Also looks like they dont pop right on the players.

File: src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp [hunk 4]
```diff
@@ -144,25 +158,31 @@ class boss_sapphiron : public CreatureScript
...
-                EnterPhaseGround();
+                EnterPhaseGround(true);
             }
 
             void SpellHitTarget(Unit* target, SpellInfo const* spell) override
             {
                 switch(spell->Id)
                 {
-                    case SPELL_ICEBOLT:
+                    /*case SPELL_ICEBOLT:
```
Comment (chaodhib) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: commented code here. should it be removed maybe?

File: src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp [hunk 5]
```diff
@@ -359,56 +381,252 @@ class boss_sapphiron : public CreatureScript
...
+        class spell_sapphiron_frost_breath_SpellScript : public SpellScript
+        {
+            PrepareSpellScript(spell_sapphiron_frost_breath_SpellScript);
+
+            bool Validate(SpellInfo const* /*spell*/) override
+            {
+                return !!sSpellMgr->GetSpellInfo(SPELL_FROST_EXPLOSION);
+            }
+
+            void HandleTargets(std::list<WorldObject*>& targetList)
```
Comment (chaodhib) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: This is a good start. However, this isnt blizzlike. This spell should work by LOS in reference to Saphiron. Also the spell SPELL_FROST_BREATH is linked to SPELL_FROST_EXPLOSION. Both are cast at the same time. Dont ask me why however, I dont know :/

File: src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp [hunk 6]
```diff
@@ -359,56 +381,252 @@ class boss_sapphiron : public CreatureScript
...
-                        target->ApplySpellImmune(0, IMMUNITY_ID, SPELL_FROST_EXPLOSION, true);
-                        targets.push_back(target);
+                        it = targetList.erase(it);
+                        toRemove.push_back(target);
+                        continue;
+                    }
+                    
+                    bool found = false;
+                    for (GameObject* block : blocks)
+                        if (block->IsInBetween(GetCaster(), target, 2.0f) && GetCaster()->GetExactDist2d(block) + 5 >= GetCaster()->GetExactDist2d(target))
```
Comment (chaodhib) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: This is a good start. However, this isnt blizzlike. This spell should work by LOS in reference to Saphiron. Also the spell SPELL_FROST_BREATH is linked to SPELL_FROST_EXPLOSION. Both are cast at the same time. Dont ask me why however, I dont know :/

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: It's a workaround for the LoS bug, like the comment says. Once LoS works properly with GO edges, it can be removed.

Comment (chaodhib) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: Oh ok. my bad then. didnt saw any comment.

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: Eh, it used to be in the PR, guess I removed it at some point.
I should put a comment in the code anyway, I'll do that next time I work on this a bit.

Could you give me a breakdown of relevant wpp output (just smsg_spell_cast/smsg_spell_go) for the frost breath and linked spells if you have a time? Saves me the work of parsing it.

File: src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp (hunk 4 above)
Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: Yeah, that's old iceblock handling code that I commented for later reference but forgot to remove before pushing this.

I'll get rid of it the next time I work on this.

File: src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp (hunk 6 above)
Comment (chaodhib) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: Sure, I'll try to do that tonight.

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp]: Too late, already sorted it myself :)

**Comment by Treeston** [comment]
Ported the whole thing to `std::chrono` because I am a glutton for punishment

File: src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp [hunk 7]
```diff
@@ -82,10 +82,10 @@ class boss_loatheb : public CreatureScript
             void EnterCombat(Unit* /*who*/) override
             {
                 _EnterCombat();
-                events.ScheduleEvent(EVENT_NECROTIC_AURA, 17 * IN_MILLISECONDS);
-                events.ScheduleEvent(EVENT_DEATHBLOOM, 5 * IN_MILLISECONDS);
-                events.ScheduleEvent(EVENT_SPORE, RAID_MODE(36,18) * IN_MILLISECONDS);
-                events.ScheduleEvent(EVENT_INEVITABLE_DOOM, 2 * MINUTE * IN_MILLISECONDS);
+                events.ScheduleEvent(EVENT_NECROTIC_AURA, Seconds(17));
+                events.ScheduleEvent(EVENT_DEATHBLOOM, Seconds(5));
+                events.ScheduleEvent(EVENT_SPORE, Seconds(18));
```
Comment (chaodhib) [inline src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp]: typo?

Comment (Treeston) [inline src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp]: Intended.
First spore is 18 seconds on both modes. Intervals afterwards differ depending on raid mode.
`- First spore now spawns properly after 18 seconds on 10-man (down from 36 seconds). Time between subsequent spawns is unchanged.`

**Comment by Treeston** [comment]
Alright, gents. Testing, please!

**Comment by tkrokli** [comment]
Smells like a test weekend coming up... ;)

**Comment by Treeston** [comment]
Quite possibly tomorrow and on sunday, yes. I won't be around on saturday.
