### PR TITLE
Scripts/Spells: Mage Ice Lance, Splitting Ice, Thermal Void

### LINKED ISSUE #19087: [master] Mage - Ice Lance
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Ice Lance doesn't damage the enemy.

**Current behaviour:**
Ice Lance doing 0 damage.

**Expected behaviour:**
Ice Lance should damage the enemy.

**Steps to reproduce the problem:**

1. Select Mage
2. Cast Ice Lance

**Branch(es):** master

**TC rev. hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/8aacc07727835ad3f81bebde3308cfdc4de2f26e

**TDB version:**  703.00 + updates

**Operating system:**  Windows 10 64-bit

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by Ryzen-0**
**Changes proposed:**

- Ice Lance
- Splitting Ice
- Thermal Void

**Target branch(es):** 3.3.5/master
- [ ] 3.3.5
- [x] master

Closes #19087 

**Tests performed:**

Needed a bit more to fully fix Ice Lance but it's a bit playable now at least.

**Known issues and TODO list:

- [ ] x3 damage on frozen target
- [ ] lower damage of second lance triggered by Splitting Ice to 80% (now it deals 100%)
- [x] Chain Reaction 

I need someone else who teach me how to reduce damage of spell triggered by Splitting Ice but more important would be x3 damage on frost target.

### CODE REVIEW

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -695,6 +701,79 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                        int32 increaseDuration = eff0->CalcValue() * IN_MILLISECONDS;
+                        int32 newDuration = (icyVeins->GetDuration() + increaseDuration);
+                        icyVeins->SetDuration(newDuration);
+                    }
+            }
+        }
+
+        if (Aura* fingersOfFrost = caster->GetAura(SPELL_MAGE_FINGERS_OF_FROST))
+        {
+            uint8 stack = fingersOfFrost->GetStackAmount();
```
Comment (illfated) [inline src/server/scripts/Spells/spell_mage.cpp:741]:
```cpp
/home/travis/build/TrinityCore/TrinityCore/src/server/scripts/Spells/spell_mage.cpp:741:19: fatal error: 
      unused variable 'stack' [-Wunused-variable]
            uint8 stack = fingersOfFrost->GetStackAmount();
                  ^
```
Another case of unused variable (which could be present further down as well, not sure), so you may want to reconsider what can be used in that line.

Comment (illfated) [reply src/server/scripts/Spells/spell_mage.cpp:741]: I am not a real coder, but I wonder if you either should drop `uint8 stack` and leave
```cpp
fingersOfFrost->GetStackAmount();
```
or change the line below to be
```cpp
stack->ModStackAmount(-1);
```

Comment (Ovahlord) [reply src/server/scripts/Spells/spell_mage.cpp:741]: yes, he can just drop that line

File: src/server/scripts/Spells/spell_mage.cpp [hunk 2]
```diff
@@ -695,6 +701,79 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+            fingersOfFrost->ModStackAmount(-1);
+        }
+
+        // if( target->HasAuraState(AURA_STATE_FROZEN))
+            caster->CastSpell(target, SPELL_MAGE_ICE_LANCE_TRIGGER, true); // TODO damage x3 on frozen target
+
+        // Splitting Ice
+        if (caster->HasAura(SPELL_MAGE_SPLITTING_ICE)) {
```
Comment (Ovahlord) [inline src/server/scripts/Spells/spell_mage.cpp:749]: Please. we are the cool kids here.  Bracket into a new line

File: src/server/scripts/Spells/spell_mage.cpp [hunk 3]
```diff
@@ -762,8 +764,8 @@ class spell_mage_ice_lance : public SpellScript
         }
 
         // Chain Reaction (TODO)
-        if (Aura* chainReaction = caster->GetAura(SPELL_MAGE_CHAIN_REACTION)) {
-            uint8 stack = chainReaction->GetStackAmount();
+        if (Aura* chainReaction = caster->GetAura(SPELL_MAGE_CHAIN_REACTION))
+        {
```
Comment (Ovahlord) [inline src/server/scripts/Spells/spell_mage.cpp:768]: no need for brackets for a single function call after a if condition

File: src/server/scripts/Spells/spell_mage.cpp [hunk 4]
```diff
@@ -695,6 +701,84 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                    }
+                }
+            }
+        }
+
+        // if( target->HasAuraState(AURA_STATE_FROZEN))
+            caster->CastSpell(target, SPELL_MAGE_ICE_LANCE_TRIGGER, true); // TODO damage x3 on frozen target
+
+        // Splitting Ice
+        if (caster->HasAura(SPELL_MAGE_SPLITTING_ICE))
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:747]: You don't need to handle Splitting Ice at all. That talent applies a spell modifier (JUMP_TARGETS) that makes 228598 cleave automatically using chain target selection (like chain lightning) with a modified damage using ChainAmplitude column from SpellEffect.db2

File: src/server/scripts/Spells/spell_mage.cpp [hunk 5]
```diff
@@ -695,6 +701,84 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+            SPELL_MAGE_ICE_LANCE,
+            SPELL_MAGE_ICE_LANCE_TRIGGER
+        });
+    }
+
+    void HandleOnHit(SpellEffIndex /*effIndex*/)
+    {
+        Unit* caster = GetCaster();
+        Unit* target = GetHitUnit();
+        if (!caster && !target)
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:721]: In `SpellScript` "Hit" hook caster is never null (target might be if you are hitting a gameobject or item)

File: src/server/scripts/Spells/spell_mage.cpp [hunk 6]
```diff
@@ -695,6 +701,84 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                if ((*itr)->GetGUID() == target->GetGUID()) continue;
+                caster->CastSpell((*itr), SPELL_MAGE_ICE_LANCE_TRIGGER, true); // TODO 80% of the damage intead of 100%
+                break;
+            }
+        }
+
+        // Chain Reaction
+        if (targetFrozen || caster->HasAura(SPELL_MAGE_FINGERS_OF_FROST))
+        {
+            if (Aura* chainReaction_aura = caster->GetAura(SPELL_MAGE_CHAIN_REACTION))
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:766]: Don't search for existing aura to add a stack. Simply cast the spell again, it will automatically stack

File: src/server/scripts/Spells/spell_mage.cpp [hunk 7]
```diff
@@ -695,6 +701,84 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+                        int32 increaseDuration = eff0->CalcValue() * IN_MILLISECONDS;
+                        int32 newDuration = (icyVeins->GetDuration() + increaseDuration);
+                        icyVeins->SetDuration(newDuration);
+                    }
+                }
+            }
+        }
+
+        // if( target->HasAuraState(AURA_STATE_FROZEN))
+            caster->CastSpell(target, SPELL_MAGE_ICE_LANCE_TRIGGER, true); // TODO damage x3 on frozen target
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:744]: To fix damage multiplier you need to modify `SpellClassMask[0] |= 0x20000;` on EFFECT_0 for spell 44544 in `SpellMgr::LoadSpellInfoCorrections`

File: src/server/scripts/Spells/spell_mage.cpp [hunk 8]
```diff
@@ -695,6 +701,84 @@ class spell_mage_water_elemental_freeze : public SpellScript
...
+    }
+
+    void HandleOnHit(SpellEffIndex /*effIndex*/)
+    {
+        Unit* caster = GetCaster();
+        Unit* target = GetHitUnit();
+        if (!caster && !target)
+            return;
+
+        bool targetFrozen = target->HasAuraState(AURA_STATE_FROZEN);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_mage.cpp:724]: After you correct SpellClassMask as I mentioned in other comment, you will be able to stop checking if caster has SPELL_MAGE_FINGERS_OF_FROST, and only check aurastate using `target->HasAuraState(AURA_STATE_FROZEN, GetSpellInfo(), caster);`

**Review by Shauren — CHANGES_REQUESTED** [review]

File: src/server/scripts/Spells/spell_mage.cpp (hunk 7 above)
Comment (Ryzen-0) [reply src/server/scripts/Spells/spell_mage.cpp:744]: This part is the most tough to me, so at row 3105 from
const_cast<SpellEffectInfo*>(spellInfo->GetEffect(EFFECT_0))->SpellClassMask = flag128(685904631, 1151048, 0, 0);

to
const_cast<SpellEffectInfo*>(spellInfo->GetEffect(EFFECT_0))->SpellClassMask = flag128(685904631|0x20000, 1151048, 0, 0);

? Maybe i need to learn the "whole story" about SpellClassMask before continue...

Comment (Shauren) [reply src/server/scripts/Spells/spell_mage.cpp:744]: no, just put
`const_cast<SpellEffectInfo*>(spellInfo->GetEffect(EFFECT_0))->SpellClassMask[0] |= 0x20000;` there and remove what was already there

File: src/server/scripts/Spells/spell_mage.cpp (hunk 8 above)
Comment (Ryzen-0) [reply src/server/scripts/Spells/spell_mage.cpp]: All done as you wrote to me.
Now when i have Finger of Frost buff, Ice Lance damage do the right job :) ...but when i dont have Finger of Frost buff and use Ice Lance on frozen target, by Frost Nova for example, the damage is not triple.

It's harder than i thought, but it almost done.

In the while i will try to learn how spells works (using also SpellWork software) in SpellEffect.db2

File: sql/updates/world/master/9999_99_99_30455_world.sql [hunk 9]
```diff
@@ -0,0 +1,3 @@
+-- mage ice lance
+DELETE FROM spell_script_names WHERE spell_id IN (30455);
```
Comment (illfated) [inline sql/updates/world/master/9999_99_99_30455_world.sql:2]: Any good reason for deleting by spell ID and not by script name?

Comment (Ryzen-0) [reply sql/updates/world/master/9999_99_99_30455_world.sql:2]: I thought it was a safer way: could a spell use more than 1 script name? I am pretty new on these works; if it's the right way i will change ofc.

Comment (illfated) [reply sql/updates/world/master/9999_99_99_30455_world.sql:2]: Also, please use backticks around the DB table column names. They are usually unique, but in a very few cases, a random column name could be the same as some SQL keyword.

File: src/server/scripts/Spells/spell_mage.cpp (hunk 8 above)
Comment (Shauren) [reply src/server/scripts/Spells/spell_mage.cpp]: That would mean that Frost Nova is not setting `AURA_STATE_FROZEN` properly

**Comment by Aokromes** [comment]
closes https://github.com/TrinityCore/TrinityCore/issues/19087

**Comment by illfated** [comment]
> Closes #19087

Maybe add that in a separate line at the end of the main PR comment?

**Comment by Shauren** [comment]
Fixing remaining bugs myself and merging (splitting ice makes you drop 2 charges of fingers of frost but it should be 1)

**Comment by Ovahlord** [comment]
That's a bug that exists since 4.x and that simply is that the charges are not charges but stacks instead. So spell_proc's charge column wont work in that scenario

**Comment by illfated** [comment]
BTW, remove the "(draft)" part of the PR title, either before or during merge (commit title).
