### PR TITLE
Core/Chat: general cleanup and revamping:

### LINKED ISSUE #17424: Exploit allowing to know a gm was online
**Description**:
You can known a gm was online and invisible if he enters a public channel allowing ownership, and someone else enters that channel and gm leaves, for example test

**Current behaviour**: Tell us what happens
ownership changes from gm to player at gm leave/disconnect

**Expected behaviour**: Tell us what should happen instead
ownership must change from gm to player on player enter if gm was 1st on that channel and invisible.

**Steps to reproduce the problem**:

1. gm enters channel test invisible.
2. players enters channel test.
3. gm leaves channel or disconnects.
3. players get ownership, and now he knows a gm was invisible inside that channel.

**Branch(es)**: 3.3.5 / 6.x (Select the branch(es) affected by this issue) 
3.3.5a, very likely all branches.

**TC hash/commit**:  
f226ebd2004d (all revisions for years)

**TDB version**:  
any

**Operating system**:  
any.

### PR DESCRIPTION
**Pull request by ariel-**
**Changes proposed**: General cleanup of code in game/Chat folder
- Const correctness
- Code standards
- Proper use of map iterators and map::at instead of operator[]-ing-everything

**Target branch(es)**: 335/6x

**Tests performed**: (Does it build, tested in-game, etc)
It builds and works properly.

### CODE REVIEW

**Comment by Aokromes** [comment]
@ariel- can you give a look to #8411 ? :)

**Comment by ariel-** [comment]
Interesting, will take a look for sure 👍

File: src/server/game/Chat/Channels/Channel.h [hunk 1]
```diff
@@ -269,19 +284,21 @@ class TC_GAME_API Channel
...
-        uint32 _channelId;
-        uint32 _Team;
-        ObjectGuid _ownerGUID;
-        std::string _name;
-        std::string _password;
-        PlayerContainer playersStore;
-        BannedContainer bannedStore;
+        typedef GuidUnorderedSet BannedContainer;
+
+        bool AnnounceEnabled;           //< Whether we should broadcast a packet whenever a player joins/exits the channel
```
Comment (Shauren) [inline src/server/game/Chat/Channels/Channel.h]: all of these names should start with underscore and lowercase letter if they are not public

File: src/server/game/Chat/Channels/Channel.cpp [hunk 2]
```diff
@@ -288,7 +306,8 @@ void Channel::KickOrBan(Player const* player, std::string const& badname, bool b
         return;
     }
 
-    if (!playersStore[good].IsModerator() && !player->GetSession()->HasPermission(rbac::RBAC_PERM_CHANGE_CHANNEL_NOT_MODERATOR))
+    PlayerInfo& info = PlayersStore.at(good);
```
Comment (Shauren) [inline src/server/game/Chat/Channels/Channel.cpp]: is the `good` key guaranteed to be found in the map at this point?

Comment (ariel-) [inline src/server/game/Chat/Channels/Channel.cpp]: if (!IsOn(good)) check handles this case and stops execution prematurely before reaching this line.

File: src/server/game/Chat/Channels/Channel.cpp [hunk 3]
```diff
@@ -191,36 +191,38 @@ void Channel::JoinChannel(Player* player, std::string const& pass)
...
+    PlayerInfo& pinfo = _playersStore[guid];
     pinfo.flags = MEMBER_FLAG_NONE;
-    playersStore[guid] = pinfo;
+    pinfo.invisible = !player->isGMVisible();
 
     WorldPacket data;
     MakeYouJoined(&data);
     SendToOne(&data, guid);
 
-    JoinNotify(guid);
```
Comment (jackpoz) [inline src/server/game/Chat/Channels/Channel.cpp]: by looking at this PR I have no clue if this line was removed on purpose (whatever the purpose would be) or if it was removed by accident

File: src/server/game/Chat/Channels/Channel.cpp [hunk 4]
```diff
@@ -191,36 +191,38 @@ void Channel::JoinChannel(Player* player, std::string const& pass)
...
     {
         // Update last_used timestamp in db
-        if (!playersStore.empty())
-            UpdateChannelUseageInDB();
+        UpdateChannelUseageInDB();
 
         // If the channel has no owner yet and ownership is allowed, set the new owner.
-        if (!_ownerGUID && _ownership)
+        // or if the owner was a GM with .gm visible off
+        // don't do this if the new player is, too, an invis GM, unless the channel was empty
```
Comment (jackpoz) [inline src/server/game/Chat/Channels/Channel.cpp]: this ".gm visible off" stuff seems unrelated to "Changes proposed:" section of the PR description

**Comment by jackpoz** [comment]
The (misleading) description of this PR suggests that there are only codestyle changes while instead there is a mix of both codestyle and behavior changes, making it impossible to review and being a pain to revert if needed.

The codestyle changes on their own are very difficult to check, there is no way to ensure all variables got renamed without any typo to a wrong name unless they are renamed locally too using IDEs like Visual Studio. A PR with just const-correctness and another PR with just std::map operators would have allowed a much smoother review.

File: src/server/game/Chat/Channels/Channel.cpp (hunk 4 above)
Comment (ariel-) [inline src/server/game/Chat/Channels/Channel.cpp]: Well, I added those changes in the commit description, and I don't feel like repeating myself, if you want I can copy them to the PR desc too

**Comment by ariel-** [comment]
The renames were done with VS2015 Rename feature.

File: src/server/game/Chat/Channels/Channel.cpp (hunk 3 above)
Comment (ariel-) [inline src/server/game/Chat/Channels/Channel.cpp]: Silly me, I removed it when testing 💃

**Comment by ariel-** [comment]
Well I'm splitting this. The PR will now handle general nice up of code, instead of changing how it works, updating....

**Comment by ariel-** [comment]
Test fix for #8411: http://i.imgur.com/COD7MNY.png

Required a major rewrite in ChannelMgr/Channel.cpp, I have locally branched this off this PR; I'm warning there were many lines changed; So, should I close this and squash it with the other one? Or do you prefer reviewing this first?

**Comment by jackpoz** [comment]
this PR looks ready to be merged (if those .at() changes have already been tested and are not going to trigger any issue).

**Comment by jackpoz** [comment]
btw is ```char const*``` the TC standard ?

**Comment by Shauren** [comment]
you mean const and * placement? yes.

File: src/server/game/Chat/Channels/Channel.h [hunk 5]
```diff
@@ -148,106 +146,121 @@ class TC_GAME_API Channel
...
+        void MakeNotInLfg(WorldPacket* data) const;                                         //? 0x21
+        void MakeVoiceOn(WorldPacket* data, ObjectGuid guid) const;                         //+ 0x22
+        void MakeVoiceOff(WorldPacket* data, ObjectGuid guid) const;                        //+ 0x23
+
+        void SendToAll(WorldPacket* data, ObjectGuid guid = ObjectGuid::Empty) const;
+        void SendToAllButOne(WorldPacket* data, ObjectGuid who) const;
+        void SendToOne(WorldPacket* data, ObjectGuid who) const;
+
+        bool IsOn(ObjectGuid who) const { return _playersStore.count(who) != 0; }
+        bool IsBanned(ObjectGuid guid) const { return _bannedStore.count(guid) != 0; }
```
Comment (Rochet2) [inline src/server/game/Chat/Channels/Channel.h]: Isn't using count considered a bad practice? Guess it doesnt matter really, but just thought it was weird that this was changed for no real reason.

Comment (Shauren) [inline src/server/game/Chat/Channels/Channel.h]: No, this is the simplest way to check if an element exists in a set

File: src/server/game/Chat/Channels/Channel.h [hunk 6]
```diff
@@ -269,19 +286,20 @@ class TC_GAME_API Channel
         }
 
         typedef std::map<ObjectGuid, PlayerInfo> PlayerContainer;
-        typedef GuidSet BannedContainer;
+        typedef GuidUnorderedSet BannedContainer;
```
Comment (Rochet2) [inline src/server/game/Chat/Channels/Channel.h]: Since GuidSet was changed to unordered, maybe PlayerContainer can be changed to unorderd as well?
Not sure if it can be just swapped. Cant see any uses in this diff for the map's ordering.

Comment (jackpoz) [inline src/server/game/Chat/Channels/Channel.h]: inb4 PR to change it from unordered to ordered

Comment (ariel-) [inline src/server/game/Chat/Channels/Channel.h]: Well, BannedContainer is just for element checking, so the change to unordered can't hurt.

PlayerContainer on the other hand; being ordered means that when a player leaves, next owner is searched from the player with the lowest guid in the channel, and as discussed in the PR page, this is meant to only be a cleanup, not modify the behaviour, and making PlayerContainer unordered will change it.
