### PR TITLE
Scripts/Spells: Implement warlock talent "Bilescourge Bombers"

### LINKED ISSUE #29141: Warlock/Spell: Bilescourge Bombers
### Description

https://www.wowhead.com/spell=267211/bilescourge-bombers

Does not work. spends soul shard's, there is an animation (a second, as if they started and interrupted the cast), but nothing happens. does not work.

### Expected behaviour

Tear open a portal to the nether above the target location, from which several Bilescourge will pour out of and crash into the ground over 6 sec, dealing (27.6% of Spell power) Shadow damage to all enemies within 8 yards.

### Steps to reproduce the problem

Just create a warlock and try to use spell.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/9ad227f0756aa91f9b772ecf13b40c1f38863e68

### Operating system

Debian 11

### Custom changes

Debian 11

### PR DESCRIPTION
**Pull request by Eliminationzx**
**Changes proposed:**

-  Implement warlock talent "Bilescourge Bombers"

**Issues addressed:**

Closes #29141

**Tests performed:**

build,  tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_warlock.cpp [hunk 1]
```diff
@@ -1490,6 +1494,78 @@ class spell_warl_volatile_agony : public SpellScript
...
+
+    void OnUpdate(uint32 diff) override
+    {
+        _tickTimer -= Milliseconds(diff);
+
+        while (_tickTimer <= 0s)
+        {
+            if (Unit* caster = at->GetCaster())
+            {
+                if (AreaTrigger* targetAreaTrigger = caster->GetAreaTrigger(SPELL_WARLOCK_BILESCOURGE_BOMBERS))
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_warlock.cpp:1534]: it looks like this is the areatrigger of this script. You can use `at` directly, like you did in the if above instead. `at` is always valid in `AreaTriggerAI`, so no need to nullcheck it explicitly.

File: src/server/scripts/Spells/spell_warlock.cpp [hunk 2]
```diff
@@ -1490,6 +1494,78 @@ class spell_warl_volatile_agony : public SpellScript
...
+        OnEffectLaunch += SpellEffectFn(spell_warl_bilescourge_bombers::HandleLaunch, EFFECT_0, SPELL_EFFECT_CREATE_AREATRIGGER);
+    }
+};
+
+// Bilescourge Bombers - 15141
+struct areatrigger_warl_bilescourge_bombers : AreaTriggerAI
+{
+    areatrigger_warl_bilescourge_bombers(AreaTrigger* areatrigger) : AreaTriggerAI(areatrigger), _tickTimer(TICK_PERIOD) {}
+
+    static constexpr Milliseconds TICK_PERIOD = Milliseconds(500);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_warlock.cpp:1524]: you can write `500ms` here instead of `Milliseconds(500)`

File: src/server/scripts/Spells/spell_warlock.cpp [hunk 3]
```diff
@@ -1490,6 +1494,78 @@ class spell_warl_volatile_agony : public SpellScript
...
+
+    void OnUpdate(uint32 diff) override
+    {
+        _tickTimer -= Milliseconds(diff);
+
+        while (_tickTimer <= 0s)
+        {
+            if (Unit* caster = at->GetCaster())
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_warlock.cpp:1532]: i'd move the caster if outside the while. Reason being: the while-body is only executed multiple times if we have a lag, and if that happens `GetCaster()` is valid throughout the entire iteration, so we dont have to nullcheck it each iteration but only once before iterations happen

**Review by mdX7 — COMMENTED** [review]
looks quite good already, SpellVisualID indeed looks rather weird - i'll check and report back in a bit

File: src/server/scripts/Spells/spell_warlock.cpp (hunk 1 above)
Comment (Eliminationzx) [reply src/server/scripts/Spells/spell_warlock.cpp:1534]: There are two area triggers involved:
- A target area trigger created by Spell 267211.
- An area trigger at the caster's position created by Spell 282248.

The visual effect of the Bilescourge crashing into the ground should start from the caster's position area trigger and move toward the target area trigger, ending with the impact at the target location.

Comment (mdX7) [reply src/server/scripts/Spells/spell_warlock.cpp]: aye, thanks for the heads up

**Comment by mdX7** [comment]
orphan spellvisual packet structure was broken in wpp, i pushed a fix. Resulting packet looks like this:
```
ServerToClient: SMSG_PLAY_ORPHAN_SPELL_VISUAL (0x4D0038) Length: 57 ConnIdx: 1 Time: 01/01/2025 11:23:31.063 Number: 22098
SourceLocation: X: 1947.3429 Y: -4578.035 Z: 66.451675
SourceRotation: X: 0 Y: 0 Z: 0
TargetLocation: X: 1959.9059 Y: -4570.5244 Z: 66.450874
Target: Full: 0x0
TargetTransport: Full: 0x0
SpellVisualID: 75806
TravelSpeed: 0.5
LaunchDelay: 0
MinDuration: 0
SpeedAsTime: True
```

**Comment by Eliminationzx** [comment]
> orphan spellvisual packet structure was broken in wpp, i pushed a fix. Resulting packet looks like this:
> 
> ```
> ServerToClient: SMSG_PLAY_ORPHAN_SPELL_VISUAL (0x4D0038) Length: 57 ConnIdx: 1 Time: 01/01/2025 11:23:31.063 Number: 22098
> SourceLocation: X: 1947.3429 Y: -4578.035 Z: 66.451675
> SourceRotation: X: 0 Y: 0 Z: 0
> TargetLocation: X: 1959.9059 Y: -4570.5244 Z: 66.450874
> Target: Full: 0x0
> TargetTransport: Full: 0x0
> SpellVisualID: 75806
> TravelSpeed: 0.5
> LaunchDelay: 0
> MinDuration: 0
> SpeedAsTime: True
> ```

ayee, thanks
