### PR TITLE
Core/Entities: Fix some weird movement due to los issues

### LINKED ISSUE #21121: Tools/vmap: AoE randomly hits out of LoS in caves
**Description:**

DeathKnight AoE spells randomy does not work in caves. 

**Current behaviour:**

DeathKnight AoE spells randomy does not work in caves. Video of this bug: https://youtu.be/p_qnxZ0Pt9g

`vmap.enableLOS = 0` fix problem.

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  f0614b57a59a8525a6634e1465a83ef8fa27839e

**TDB version:**  CHANGEME Version of the TrinityCore database

**Operating system:** CHANGEME OS

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

- Made LoS check use collisionHeight instead of midsection. Value was too low.
- Gnomes will now have a breath bar more quickly than for example a tauren.
- Changes have been made to checking for ground z as well, some tweeking might be needed but removed most of the scattered +2.0f/+0.5f/we. Which I think is better now.

**Target branch(es):** 3.3.5/master

- 3.3.5
- master

**Issues addressed:** Closes #21121  #19744

**Tests performed:**
- Builds (local)
- Ran around  in the world to find some issues but didn't really notice any.
- Checked out the new beasts of northrend fight, no issues.
- The bronze drakes didn't pop out of the ground in tanaris.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] There is a place in dun morogh up a hill with trolls where a troll sometimes goes undermap when chasing you, will looking into that.
  - Not sure if my changes are related to this. -5067.1655237 -245.251724 442.975647 and -5070.35791 -245.135208 442.975647 are in LoS with each other, while they most likely shouldn't.

- Still not very sure what to do when collisionheight is 0, added a default one for now.

Any help & feedback is welcome, I feel like I might have removed too much of those 0.5f's...

Happy holidays :)

### CODE REVIEW

File: src/server/game/Entities/Creature/Creature.cpp [hunk 1]
```diff
@@ -1045,6 +1044,8 @@ bool Creature::Create(ObjectGuid::LowType guidlow, Map* map, uint32 phaseMask, u
     if (!CreateFromProto(guidlow, entry, data, vehId))
         return false;
 
+    UpdatePositionData();
```
Comment (jackpoz) [inline src/server/game/Entities/Creature/Creature.cpp]: what is this change for ?

File: src/server/game/Entities/Creature/Creature.cpp [hunk 2]
```diff
@@ -2888,7 +2889,7 @@ void Creature::UpdateMovementFlags()
     // Set the movement flags if the creature is in that mode. (Only fly if actually in air, only swim if in water, etc)
     float ground = GetFloorZ();
 
-    bool isInAir = (G3D::fuzzyGt(GetPositionZMinusOffset(), ground + 0.05f) || G3D::fuzzyLt(GetPositionZMinusOffset(), ground - 0.05f)); // Can be underground too, prevent the falling
+    bool isInAir = (G3D::fuzzyGt(GetPositionZMinusOffset(), ground) || G3D::fuzzyLt(GetPositionZMinusOffset(), ground)); // Can be underground too, prevent the falling
```
Comment (jackpoz) [inline src/server/game/Entities/Creature/Creature.cpp]: what was the purpose of +/- 0.05 fuzzyGt/Lt and why is it removed now ?

File: src/server/game/Entities/Creature/Creature.cpp (hunk 1 above)
Comment (Golrag) [reply src/server/game/Entities/Creature/Creature.cpp]: If I call it earlier assertion will trigger in GetColllisionHeight, or crash in GetUInt32Value. Can't remember which one it was.

**Comment by jackpoz** [comment]
after this PR I would suggest to find a place for 2.03128f so that it is defined only in a single place (no need to worry about that now, it's more important to fix the LoS issues)

File: src/server/game/Entities/Creature/Creature.cpp (hunk 2 above)
Comment (Shauren) [reply src/server/game/Entities/Creature/Creature.cpp]: It was definitely intended here, don't want creatures toggling flight/walk like mad based on inaccurancies during spline update

Comment (Golrag) [reply src/server/game/Entities/Creature/Creature.cpp]: Will place it back then, but I would like to have those 0.05f's defined somewhere for consistency, any good place for it ?

**Comment by Golrag** [comment]
Alright, the value is from legion db2's btw. 335 has 2.031 so I chose the legion one.

File: src/server/game/Entities/Creature/Creature.cpp (hunk 2 above)
Comment (Faq) [reply src/server/game/Entities/Creature/Creature.cpp]: SharedDefines.h is not ok to store such?

**Comment by Killyana** [comment]
It could fix https://github.com/TrinityCore/TrinityCore/issues/19744 also ?

**Comment by Golrag** [comment]
Seems like it

File: src/server/game/Entities/Creature/Creature.cpp (hunk 1 above)
Comment (Golrag) [reply src/server/game/Entities/Creature/Creature.cpp]: Seems like https://github.com/TrinityCore/TrinityCore/issues/20028 is back now with these changes so, I will maybe revert those changes and let the default param do the job

File: src/server/game/Entities/Creature/Creature.cpp [hunk 3]
```diff
@@ -1464,6 +1455,15 @@ bool Creature::CreateFromProto(ObjectGuid::LowType guidlow, uint32 entry, Creatu
     if (!UpdateEntry(entry, data))
         return false;
 
+    UpdatePositionData();
+    SetZoneScript();
+    if (GetZoneScript() && data)
+    {
+        entry = GetZoneScript()->GetCreatureEntry(guidlow, data);
```
Comment (Shauren) [inline src/server/game/Entities/Creature/Creature.cpp]: great, you completely broke GetCreatureEntry hook.

Comment (Golrag) [reply src/server/game/Entities/Creature/Creature.cpp]: Will still trigger an assert then, doing it in UpdateEntry doesnt feel right to me as we are not really updating a position. Reverting it and leaving the default collisionheight deal with it sounds like a better option to me

**Comment by Keader** [comment]
Can you check if it fix Killing Spree too?
If target is so close of you, Effect1 is not working
Stop work after 95456ab5d8bd623481d315ae55dfbb44b45ba9f5
if you run a little with target, spell work fine

```
Effect 1: Id 3 (SPELL_EFFECT_DUMMY)
BasePoints = 1
Targets (18, 16) (TARGET_DEST_CASTER, TARGET_UNIT_DEST_AREA_ENEMY)
Radius (Id 13) 10,00
```

**Comment by Golrag** [comment]
Can't reproduce it like in the video :)

File: src/server/game/Entities/Object/Object.cpp [hunk 4]
```diff
@@ -2567,7 +2550,26 @@ float WorldObject::GetFloorZ() const
...
         return m_staticFloorZ;
-    return std::max<float>(m_staticFloorZ, GetMap()->GetGameObjectFloor(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ()));
+    return std::max<float>(m_staticFloorZ, GetMap()->GetGameObjectFloor(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ() + GetCollisionHeight()));
+}
+
+float WorldObject::GetMapWaterOrGroundLevel(float x, float y, float z, float* ground/* = nullptr*/) const
+{
+    if (Unit const* unit = ToUnit())
+    {
+        *ground = z;
```
Comment (jackpoz) [inline src/server/game/Entities/Object/Object.cpp]: is this some new code that doesn't handle the case of ground = nullptr or was it just copied from somewhere ? I'd prefer to handle that case too to avoid crashes (or ASSERT() is ground is never supposed to be null)

**Comment by jackpoz** [comment]
should we merge this PR and let the users report back any new issue ?

File: src/server/game/Entities/Object/Object.cpp (hunk 4 above)
Comment (Golrag) [reply src/server/game/Entities/Object/Object.cpp]: It should be removed and let Map::GetWaterOrGroundLevel deal with it

**Comment by Golrag** [comment]
Might still be some issues like I described in my PR. I'm still not very sure if my previous PR caused it or this one as ```GetMap()->isInLineOfSight``` with those coordinates returns true.

**Comment by jackpoz** [comment]
Brace yourself

**Comment by jackpoz** [comment]
This PR is most likely causing https://github.com/TrinityCore/TrinityCore/issues/21969#issuecomment-770276557 and https://github.com/TrinityCore/TrinityCore/issues/26024 

1. This PR assumes a lot of height map/vmap functions are used only for LoS but they are actually used also to find the floor Z and using a full collision height might pick the floor above instead
2. A lot of +0.5f/+2.0f were not a default "half collision heigth" but an empyrical delta that worked well enough when taking the Z of mmaps (which was approximated) and trying to match it to the right floor map/vmap Z

I would say full collision height should used only for LoS checks and either half or a fixed amount should be used when getting the floor Z for waypoints/paths/etc.

**Comment by illfated** [comment]
Thank you for the notice. Nice to know. 👍🏻
