### PR TITLE
Core/Spells: fix issues with delayed spells and auras

### LINKED ISSUE #22272: Core/Spells: Spells applying aura with a speed do not stack properly
**Description:**

Spells with a speed (= fly time) applying auras do not reapply on target if another aura with same id and caster is already present. Thus timer is not refreshed nor stacks incremented. 

**Current behaviour:**

New spell cast does not increment stacks.

**Expected behaviour:**

New spell cast does increment stacks.

**Steps to reproduce the problem:**

1. `.npc add 17256` (Hellfire channeler)
2. `.cast 30531` from your player character two times or more.

The creature still has one stack, while the aura should stack up to 99 times.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

(using last revision atm)
TrinityCore rev. cbacc72d934c 2018-08-15 20:14:16 +0200 (3.3.5 branch) (Win64, Debug, Static)

**Operating system:** 
Windows 10 x64

**Additional notes:** 
It seems related to this block: https://github.com/TrinityCore/TrinityCore/blob/cbacc72d934c10448762b67a0fa97ea4eb38cb63/src/server/game/Spells/Spell.cpp#L2767-L2773
Removing the GetAura does seem to fix the problem but cause other issues (can give more details if this is useful to you).

### PR DESCRIPTION
**Pull request by PolarCookie**
**Changes proposed:**
Improve upon https://github.com/TrinityCore/TrinityCore/commit/28288698441524081d583af95f19cb1c9fb90387 to restore aura stacking.

The issue with #21609 #21612 was that _spellAura was reused between targets without resetting for the same spell cast.
Ideally I would like to just NULL it between target handling here,
https://github.com/TrinityCore/TrinityCore/blob/a10870571558424033c2ffb41e4759e6581c8d86/src/server/game/Spells/Spell.cpp#L3465
but I don't know what side effects this could cause.

Ariels solution was incomplete as he forced delayed spells into 
https://github.com/TrinityCore/TrinityCore/blob/a10870571558424033c2ffb41e4759e6581c8d86/src/server/game/Spells/Spell.cpp#L2822
this PR switches it into the other block.

**Target branch(es):**
3.3.5

**Issues addressed:** 
Closes #22272

**Tests performed:** (Does it build, tested in-game, etc.)
Builds and works

**Proof of stability**
```
.go instance 619
.cheat god on
```
enter anh'kahet with 2 characters and keybind the following as a macro
```
.cast 33657
.cooldown
```

**Proof of correctness**
```
.go xyz 5811 2747 670 571 (or wherever your favorite empty place)
.npc add 28203
```
keybind the following as a macro, cast 3 times
```
.cast 33657
.cooldown
```
Add a new target and run the macro again, observe proper stacks.

### CODE REVIEW

File: src/server/game/Spells/Spell.cpp [hunk 1]
```diff
@@ -2763,14 +2763,7 @@ void Spell::DoSpellEffectHit(Unit* unit, uint8 effIndex, TargetInfo& hitInfo)
...
             // delayed spells with multiple targets need to create a new aura object, otherwise we'll access a deleted aura
-            if (m_spellInfo->Speed > 0.0f && !m_spellInfo->IsChanneled())
-            {
-                _spellAura = nullptr;
-                if (Aura* aura = unit->GetAura(m_spellInfo->Id, caster->GetGUID(), m_CastItem ? m_CastItem->GetGUID() : ObjectGuid::Empty, aura_effmask))
-                    _spellAura = aura->ToUnitAura();
-            }
-
-            if (!_spellAura)
+            if (!_spellAura || (m_spellInfo->Speed > 0.0f && !m_spellInfo->IsChanneled()))
```
Comment (PolarCookie) [inline src/server/game/Spells/Spell.cpp]: This conditional is not ideal, we're after multi target spells, but delayed spells is a much broader category.

**Comment by jackpoz** [comment]
is this ready to be merged ?

**Comment by PolarCookie** [comment]
This PR is better than the current state; I.E. it doesn't crash and correct gameplay is restored.
Would still like a better conditional to capture only multi target spells but whatever.

**Comment by jackpoz** [comment]
I'm gonna merge this PR the way it is but please attempt to address the multitarget thinkgy when you have time.

**Comment by jackpoz** [comment]
Thanks for the PR :)

**Comment by Treeston** [comment]
PS: That is not what "proof" means. At all.
