### PR TITLE
Core/Entities: Ethereal Soul-Trader

### LINKED ISSUE #4152: Ethereal Soul-Trader not working as intended
Upon learning the item and summoning him he should :

1: Should emote "I have arrived. Shall we set to work, then?
2: He follows and absorbs souls from slain mobs in return for Ethereal Credits http://www.wowhead.com/item=38186
also to earn the credit mobs must be capable of giving experience / honor, i.e. green or harder, and character must have the killing blow
3: He acts as a vendor where the items he sells are traded for Ethereal Credits http://www.wowhead.com/item=38186

Also this screenshot http://www.wowhead.com/npc=27914#screenshots:id=87517 shows that he also has gossip flags as well

I have seen as well that you cannot sell anything to him.

This first link is for some of the items he sells : http://www.wowhead.com/search?q=soul-trader%27s#
http://www.wowhead.com/item=38308
http://www.wowhead.com/item=38294
http://www.wowhead.com/item=38291
http://www.wowhead.com/item=38300

I am using revision: df3f11dc805a
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65673-ethereal-soul-trader-not-working-as-intended?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by DanVS**
**Changes proposed:**
Implement Ethereal Soul-Trader pet through spell scripts.

1. Just summoned pet says line 0 and casts [Ethereal Pet Aura](https://woehead.way-of-elendil.fr/?spell=50051) on owner.
2. When owner killed target that would give an experience/honor pet says line 1 and casts [Ethereal Pet OnKill Steal Essence](https://woehead.way-of-elendil.fr/?spell=50101) on target.
3. When cast finished pet says line 2 and casts [Ethereal Pet OnKill Give Token (Missile)](https://woehead.way-of-elendil.fr/?spell=50063) on owner.

Thanks to Kaeder for [implementation idea](https://github.com/TrinityCore/TrinityCore/issues/4152#issuecomment-398040422).

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #4152

**Tests performed:** Does build and works in-game.

### CODE REVIEW

File: src/server/scripts/Pet/pet_generic.cpp [hunk 1]
```diff
@@ -320,10 +320,39 @@ class npc_pet_gen_mojo : public CreatureScript
...
+    public:
+        npc_pet_gen_soul_trader() : CreatureScript("npc_pet_gen_soul_trader") { }
+
+        struct npc_pet_gen_soul_traderAI : public ScriptedAI
+        {
+            npc_pet_gen_soul_traderAI(Creature* creature) : ScriptedAI(creature) {}
+
+            void JustAppeared() override
+            {
+                Talk(0);
```
Comment (Keader) [inline src/server/scripts/Pet/pet_generic.cpp]: Magic number, it need be a enum.

File: src/server/scripts/Pet/pet_generic.cpp [hunk 2]
```diff
@@ -320,10 +320,39 @@ class npc_pet_gen_mojo : public CreatureScript
...
+{
+    SPELL_PROC_TRIGGER_ON_KILL_AURA     = 50051
+};
+
+class npc_pet_gen_soul_trader : public CreatureScript
+{
+    public:
+        npc_pet_gen_soul_trader() : CreatureScript("npc_pet_gen_soul_trader") { }
+
+        struct npc_pet_gen_soul_traderAI : public ScriptedAI
```
Comment (Keader) [inline src/server/scripts/Pet/pet_generic.cpp]: will be nice if you use new registers instead old one

File: src/server/scripts/Spells/spell_generic.cpp [hunk 3]
```diff
@@ -1614,6 +1614,59 @@ class spell_gen_elune_candle : public SpellScript
...
+    void OnProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+
+        Player* owner = GetTarget()->ToPlayer();
+        Unit* target = eventInfo.GetActionTarget();
+        if (!owner || !target)
+            return;
+
+        Creature* pet = owner->GetMap()->GetCreature(owner->m_SummonSlot[SUMMON_TYPE_MINIPET]);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: i dont like it.
You can iterate player pets instead

File: src/server/scripts/Spells/spell_generic.cpp [hunk 4]
```diff
@@ -1614,6 +1614,59 @@ class spell_gen_elune_candle : public SpellScript
...
+        pet->CastSpell(target, SPELL_STEAL_ESSENCE_VISUAL, false);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: "false" is default value, you can remove it.

File: src/server/scripts/Spells/spell_generic.cpp [hunk 5]
```diff
@@ -1614,6 +1614,59 @@ class spell_gen_elune_candle : public SpellScript
...
+        pet->AI()->Talk(1);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: magic number

File: src/server/scripts/Spells/spell_generic.cpp [hunk 6]
```diff
@@ -1614,6 +1614,59 @@ class spell_gen_elune_candle : public SpellScript
...
+{
+    SPELL_STEAL_ESSENCE_VISUAL          = 50101,
+    SPELL_CREATE_TOKEN                  = 50063
+};
+
+class spell_ethereal_pet_aura : public AuraScript
+{
+    PrepareAuraScript(spell_ethereal_pet_aura);
+
+    void OnProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: I read in somewhere, that you can just get credit if diff of levels between you and killed monster is <= 9

File: src/server/scripts/Spells/spell_generic.cpp [hunk 7]
```diff
@@ -1614,6 +1614,59 @@ class spell_gen_elune_candle : public SpellScript
...
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        Creature* pet = GetCaster()->ToCreature();
+        Unit* owner = GetCaster()->GetOwner();
+        if (!pet || !owner)
+            return;
+
+        pet->CastSpell(owner, SPELL_CREATE_TOKEN, false);
+        pet->AI()->Talk(2);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: magic number

File: src/server/scripts/Spells/spell_generic.cpp [hunk 8]
```diff
@@ -1614,6 +1614,59 @@ class spell_gen_elune_candle : public SpellScript
...
+    PrepareAuraScript(spell_steal_essence_visual);
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        Creature* pet = GetCaster()->ToCreature();
+        Unit* owner = GetCaster()->GetOwner();
+        if (!pet || !owner)
+            return;
+
+        pet->CastSpell(owner, SPELL_CREATE_TOKEN, false);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: false can be removed

File: sql/updates/world/3.3.5/9999_99_99_99_world.sql [hunk 9]
```diff
@@ -0,0 +1,5 @@
+UPDATE `creature_template` SET `ScriptName`='npc_pet_gen_soul_trader' WHERE `entry`=27914;
+DELETE FROM `spell_script_names` WHERE `spell_id` IN (50051,50101) AND `ScriptName` IN ('spell_ethereal_pet_aura','spell_steal_essence_visual');
```
Comment (Keader) [inline sql/updates/world/3.3.5/9999_99_99_99_world.sql]: Delete by ScriptName only

**Comment by Keader** [comment]
You are skipping some spells.
Some spells like proc one, need be inside of others
Need some sniff to confirm casts

File: src/server/scripts/Spells/spell_generic.cpp (hunk 3 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Why? Isn't it better to access directly?

Comment (ccrs) [reply src/server/scripts/Spells/spell_generic.cpp]: > iterate player pets instead
that

File: src/server/scripts/Pet/pet_generic.cpp [hunk 10]
```diff
@@ -320,10 +320,30 @@ class npc_pet_gen_mojo : public CreatureScript
         }
 };
 
+enum SoulTrader
+{
+    SAY_INRO                        = 0,
```
Comment (illfated) [inline src/server/scripts/Pet/pet_generic.cpp]: Maybe I am too nit-picky here, but shouldn't it be `SAY_INTRO` instead of `SAY_INRO` ?
I googled "inro" to see if it had a useful meaning, but none of them seem related.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 3 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: How should I determine if pet is actually summoned minipet in such case?

File: src/server/scripts/Spells/spell_generic.cpp (hunk 6 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Can you explain what do you mean?

File: src/server/scripts/Spells/spell_generic.cpp (hunk 3 above)
Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: you should use SUMMON_SLOT_MINIPET instead of SUMMON_TYPE_MINIPET.. and the other thing.. the only thing you could try is, accessing TempSummons where you have access on m_properties, but honestly? i think accessing it like you did, is good enough. Can't see a reason why you shouldn't do that.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 6 above)
Comment (illfated) [reply src/server/scripts/Spells/spell_generic.cpp]: The same level diff as required to get XP?

File: src/server/scripts/Spells/spell_generic.cpp (hunk 3 above)
Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: but what you should do is, check if you even got a pet in this slot.. you don't check if its null or not

File: src/server/scripts/Pet/pet_generic.cpp (hunk 10 above)
Comment (DanVS) [reply src/server/scripts/Pet/pet_generic.cpp]: Fixed. Thanks :)

File: src/server/scripts/Spells/spell_generic.cpp (hunk 3 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Added check here.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 6 above)
Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]:
```cpp
int32 levelDiff = GetTarget()->getLevel() - eventInfo.GetProcTarget()->getLevel();
if (levelDiff <= 9 && levelDiff >= -9)
```

Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: uint32 levelDiff = std::abs(GetTarget()->getLevel() - eventInfo.GetProcTarget()->getLevel());
if (levelDiff <= 9)

File: src/server/scripts/Spells/spell_generic.cpp [hunk 11]
```diff
@@ -1614,6 +1614,63 @@ class spell_gen_elune_candle : public SpellScript
...
+    {
+        PreventDefaultAction();
+
+        Player* owner = GetTarget()->ToPlayer();
+        Unit* target = eventInfo.GetActionTarget();
+        if (!owner || !target)
+            return;
+
+        Creature* pet = owner->GetMap()->GetCreature(owner->m_SummonSlot[SUMMON_TYPE_MINIPET]);
+        if (pet)
```
Comment (Jildor) [inline src/server/scripts/Spells/spell_generic.cpp]: forgot { }

File: src/server/scripts/Spells/spell_generic.cpp (hunk 6 above)
Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: ^ yeah, better

File: src/server/scripts/Spells/spell_generic.cpp (hunk 11 above)
Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: Just do 
```cpp
if (!pet)
    return;
```

**Comment by Keader** [comment]
You forgot about remove aura too.
When pet is despawned, player need lose ProcAura

File: src/server/scripts/Spells/spell_generic.cpp [hunk 12]
```diff
@@ -1614,6 +1614,75 @@ class spell_gen_elune_candle : public SpellScript
...
+};
+
+// 50101 - Steal Essence Visual
+class spell_steal_essence_visual : public AuraScript
+{
+    PrepareAuraScript(spell_steal_essence_visual);
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        Creature* pet = GetCaster()->ToCreature();
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_generic.cpp]: Can GetCaster() ever return NULL here ?

Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: Yes, can be null

**Comment by DanVS** [comment]
@Shauren, is it okay now?

File: src/server/scripts/Spells/spell_generic.cpp (hunk 12 above)
Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: DanVS you have to check for null here

File: src/server/scripts/Spells/spell_generic.cpp [hunk 13]
```diff
@@ -1614,6 +1614,74 @@ class spell_gen_elune_candle : public SpellScript
...
+class spell_steal_essence_visual : public AuraScript
+{
+    PrepareAuraScript(spell_steal_essence_visual);
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        if (!GetCaster() || !GetCaster()->GetOwner())
+            return;
+
+        Creature* pet = GetCaster()->ToCreature();
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_generic.cpp]: please @DanVS take the required time to review all the required checks in this function and to understand why they are needed.
When removing an Aura from a Target, the Caster could have already logged out so that's why we need to NULL-check GetCaster().
When we cast Caster to a Creature with ToCreature(), there is no guarantee it actually is a Creature and in case of a Player it will return NULL, requiring a NULL check here too on the "pet" variable (which you added in a previous commit but then removed).
Thanks for the PR :)

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Thanks, jackpoz! Do I understand correctly that previous version was fine? If `GetCaster()` returns NULL, but we have casted it to Creature immediately than NULL will be returned anyway? So we can do check shortly after variables declaration?

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: OK, I understood mistake of mine. Thanks a lot :)

File: src/server/scripts/Spells/spell_generic.cpp [hunk 14]
```diff
@@ -1668,10 +1668,15 @@ class spell_steal_essence_visual : public AuraScript
...
+        Unit* caster = GetCaster();
+        if (!caster)
             return;
 
         Creature* pet = GetCaster()->ToCreature();
+        Unit* owner = caster->GetOwner();
+        if (!pet || !owner)
+            return;
+
         pet->CastSpell(GetCaster()->GetOwner(), SPELL_CREATE_TOKEN);
```
Comment (FireEmerald) [inline src/server/scripts/Spells/spell_generic.cpp]: Why don't you use here `owner` instead of calling `GetCaster()->GetOwner()` again?

Comment (illfated) [reply src/server/scripts/Spells/spell_generic.cpp]: Fair point, even if it is outside of the added code.

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Fixed. Thanks!

**Comment by Keader** [comment]
We need a new hook to fix this.
"OnDespawn" or "BeforeDespawn" in CreatrureScripts :)

**Comment by Keader** [comment]
@DanVS 
Treeston implemented a new hook, check: https://github.com/TrinityCore/TrinityCore/commit/c0a7274ff148b35577bf8c57320142bb08e10710
Use this hook to make pet cast 50055 - [Ethereal Pet Aura Remove] on self.
You need a little spellscript with "on hit hook" in Effect 0: Id 77 (SPELL_EFFECT_SCRIPT_EFFECT) removing proc aura of target

File: src/server/scripts/Pet/pet_generic.cpp [hunk 15]
```diff
@@ -320,10 +320,36 @@ class npc_pet_gen_mojo : public CreatureScript
...
+};
+
+struct npc_pet_gen_soul_trader : public ScriptedAI
+{
+    npc_pet_gen_soul_trader(Creature* creature) : ScriptedAI(creature) { }
+
+    void Reset() override
+    {
+        if (Unit* owner = me->GetOwner())
+            owner->RemoveAurasDueToSpell(SPELL_PROC_TRIGGER_ON_KILL_AURA);
```
Comment (Keader) [inline src/server/scripts/Pet/pet_generic.cpp]: this is wrong.
This pet enter alot of times in evade, will make pet remove proc aura and all events of this pet depends of this proc.

File: src/server/scripts/Spells/spell_generic.cpp [hunk 16]
```diff
@@ -1614,6 +1614,79 @@ class spell_gen_elune_candle : public SpellScript
...
+};
+
+class spell_ethereal_pet_aura : public AuraScript
+{
+    PrepareAuraScript(spell_ethereal_pet_aura);
+
+    bool CheckProc(ProcEventInfo& eventInfo)
+    {
+        uint32 levelDiff = std::abs(GetTarget()->getLevel() - eventInfo.GetProcTarget()->getLevel());
+        if (levelDiff >= 9)
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: change to: return levelDiff <= 9;

File: src/server/scripts/Spells/spell_generic.cpp [hunk 17]
```diff
@@ -1614,6 +1614,79 @@ class spell_gen_elune_candle : public SpellScript
...
+{
+    PrepareAuraScript(spell_steal_essence_visual);
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        Unit* caster = GetCaster();
+        if (!caster)
+            return;
+
+        Creature* pet = GetCaster()->ToCreature();
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: caster->ToCreature()

File: src/server/scripts/Spells/spell_generic.cpp (hunk 16 above)
Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: shouldn't it only proc if your level diff is smaller than 10? With your propsal @Keader it won't proc anymore for diffs under 9

File: src/server/scripts/Pet/pet_generic.cpp [hunk 18]
```diff
@@ -320,10 +320,36 @@ class npc_pet_gen_mojo : public CreatureScript
...
+    }
+
+    void JustAppeared() override
+    {
+        Talk(SAY_SOUL_TRADER_INTRO);
+        if (Unit* owner = me->GetOwner())
+            owner->CastSpell(owner, SPELL_PROC_TRIGGER_ON_KILL_AURA, true);
```
Comment (Keader) [inline src/server/scripts/Pet/pet_generic.cpp]: wrong, he need cast ```SPELL_ETHEREAL_ONSUMMON      = 50052``` on owner
and inside of ```50052``` cast proc trigger.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 16 above)
Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: what? if levelDiff <= 9, it will return true for: 0, 1, 2, 3...9

```cpp
bool CheckProc(ProcEventInfo& eventInfo)
{
    uint32 levelDiff = std::abs(GetTarget()->getLevel() - eventInfo.GetProcTarget()->getLevel());
    return levelDiff <= 9;
}
```

Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: ah didn't read the return xD sry :D

**Comment by DanVS** [comment]
I will continue work a little bit later.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 3 above)
Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]:
```cpp
void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
{
    PreventDefaultAction();
    for (Unit* soulTrader : GetUnitOwner()->m_Controlled)
        if (soulTrader->GetEntry() == NPC_ETHEREAL_SOUL_TRADER)
        {
            soulTrader->CastSpell(eventInfo.GetProcTarget(), SPELL_ETHEREAL_STEAL_ESSENCE);
            return;
        }
}
```

**Comment by Keader** [comment]
with: SPELL_ETHEREAL_PET_AURA = 50051
```cpp
// 50055 - Ethereal Pet Aura Remove
class spell_ethereal_pet_aura_remove : public SpellScript
{
    PrepareSpellScript(spell_ethereal_pet_aura_remove);

    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return ValidateSpellInfo({ SPELL_ETHEREAL_PET_AURA });
    }

    void HandleScriptEffect(SpellEffIndex /*effIndex*/)
    {
        GetHitUnit()->RemoveAurasDueToSpell(SPELL_ETHEREAL_PET_AURA);
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_ethereal_pet_aura_remove::HandleScriptEffect, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};
```
```sql
DELETE FROM `spell_script_names` WHERE `ScriptName`='spell_ethereal_pet_aura_remove';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES 
(50055,'spell_ethereal_pet_aura_remove');
```

**Comment by DanVS** [comment]
After #22054 I'd like to an advice :) Is this the order to apply latest core updates?
```
git fetch upstream
git checkout ethereal
git rebase --autostash upstream/3.3.5
git push
```

**Comment by illfated** [comment]
I only use Git Extensions on Windows, but it looks correct to do a rebase on the PR branch.
Myself, my forked 3.3.5 branch is always merged. I guess that is what fetch does (fast-forward).

**Comment by DanVS** [comment]
Probably done?

File: src/server/scripts/Spells/spell_generic.cpp [hunk 19]
```diff
@@ -1614,6 +1614,120 @@ class spell_gen_elune_candle : public SpellScript
...
+    bool CheckProc(ProcEventInfo& eventInfo)
+    {
+        uint32 levelDiff = std::abs(GetTarget()->getLevel() - eventInfo.GetProcTarget()->getLevel());
+            return levelDiff <= 9;
+    }
+
+    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+        for (Unit* controlled : GetUnitOwner()->m_Controlled)
```
Comment (ccrs) [inline src/server/scripts/Spells/spell_generic.cpp]: TC code style standard: on nested instructions a bracket must be placed on the initial one.

Comment (ccrs) [reply src/server/scripts/Spells/spell_generic.cpp]: btw, you should use ``Unit::GetAllMinionsByEntry``

File: src/server/scripts/Spells/spell_generic.cpp [hunk 20]
```diff
@@ -1614,6 +1614,120 @@ class spell_gen_elune_candle : public SpellScript
...
+    }
+
+    void Register() override
+    {
+        OnEffectHitTarget += SpellEffectFn(spell_ethereal_pet_aura_remove::HandleScriptEffect, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
+    }
+};
+
+// 50101 - Steal Essence Visual
+class spell_steal_essence_visual : public AuraScript
```
Comment (ccrs) [inline src/server/scripts/Spells/spell_generic.cpp]: this effect should not be linked to a visual effect IMO

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Options?

File: src/server/scripts/Spells/spell_generic.cpp [hunk 21]
```diff
@@ -1614,6 +1614,119 @@ class spell_gen_elune_candle : public SpellScript
...
+    }
+
+    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+
+        std::list<Creature*> MinionList;
+        GetUnitOwner()->GetAllMinionsByEntry(MinionList, NPC_ETHEREAL_SOUL_TRADER);
+
+        Creature* soulTrader = MinionList.front()->ToCreature();
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: hmm, any chance of list be empty? xd

File: src/server/scripts/Spells/spell_generic.cpp (hunk 20 above)
Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: @ccrs  should be linked with?
token should be casted after visual fade...

File: src/server/scripts/Spells/spell_generic.cpp [hunk 22]
```diff
@@ -1614,6 +1614,119 @@ class spell_gen_elune_candle : public SpellScript
...
+    PrepareAuraScript(spell_steal_essence_visual);
+
+    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
+    {
+        Unit* caster = GetCaster();
+        if (!caster)
+            return;
+
+        Creature* pet = caster->ToCreature();
+        Unit* owner = caster->GetOwner();
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: not needed.

File: src/server/scripts/Spells/spell_generic.cpp [hunk 23]
```diff
@@ -1614,6 +1614,119 @@ class spell_gen_elune_candle : public SpellScript
...
+        if (!pet || !owner)
+            return;
+
+        pet->CastSpell(owner, SPELL_CREATE_TOKEN);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: `SPELL_CREATE_TOKEN` has `TARGET_UNIT_MASTER`, so not need a explicit target

Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: Maybe the method can be:

```cpp

void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        if (Unit* caster = GetCaster())
        {
            caster->CastSpell(caster, SPELL_ETHEREAL_GIVE_TOKEN, true);
            if (Creature* soulTrader = caster->ToCreature())
                soulTrader->AI()->Talk(ETHEREAL_TALK_TOKEN);
        }
    }
```

File: src/server/scripts/Spells/spell_generic.cpp (hunk 21 above)
Comment (ccrs) [reply src/server/scripts/Spells/spell_generic.cpp]:
```c++
        std::list<Creature*> MinionList;
        GetUnitOwner()->GetAllMinionsByEntry(MinionList, NPC_ETHEREAL_SOUL_TRADER);
        for (Creature* minion : minionList)
        {
            if (minion->IsAIEnabled)
                 minion->GetAI()->DoAction(DO_STUFFS);
        }
```

dont break or return the loop

File: src/server/scripts/Spells/spell_generic.cpp (hunk 20 above)
Comment (ccrs) [reply src/server/scripts/Spells/spell_generic.cpp]: tried spellhittarget or similar ai hooks? does it need to be specifically when the visual fades?

honestly having something periodic in the AI checking for the aura leaving feels ok... also have you thought about what happens if multiple targets are killed? does this have something like a cooldown or?

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Probably, yes. Also, if multiple mobs are killed at the same time it does not work on each. I think I should add some kind if GUID vector inside pet's script, put there victim's GUID at each proc of 50051 and iterate over vector inside of `Update`, shouldn't I?

Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: Multiple targets at same time, need give only 1 token if i remember right.

File: src/server/scripts/Spells/spell_generic.cpp [hunk 24]
```diff
@@ -1614,6 +1614,119 @@ class spell_gen_elune_candle : public SpellScript
...
+    PrepareSpellScript(spell_ethereal_pet_onsummon);
+
+    bool Validate(SpellInfo const* /*spellInfo*/) override
+    {
+        return ValidateSpellInfo({ SPELL_PROC_TRIGGER_ON_KILL_AURA });
+    }
+
+    void HandleScriptEffect(SpellEffIndex /*effIndex*/)
+    {
+        Unit* target = GetHitUnit();
```
Comment (Seyden) [inline src/server/scripts/Spells/spell_generic.cpp]: Not needed.. do GetHitUnit()->AddAura

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: AddAura requires target.
```cpp
Aura* AddAura(uint32 spellId, Unit* target);
Aura* AddAura(SpellInfo const* spellInfo, uint8 effMask, Unit* target);
```

Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: Ah crap, didn't see the second parameter, sry

Comment (Seyden) [reply src/server/scripts/Spells/spell_generic.cpp]: Yeah well then let it stay target or change both to GetHitUnit(), either one or the other. Sry for the comment at all :D

File: src/server/scripts/Spells/spell_generic.cpp (hunk 23 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Good catch!

File: src/server/scripts/Spells/spell_generic.cpp (hunk 24 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: No problem :+1:

Comment (Keader) [reply src/server/scripts/Spells/spell_generic.cpp]: wait, add aura? please no !
Use cast spell instead.

```cpp

void HandleScriptEffect(SpellEffIndex /*effIndex*/)
{
    GetHitUnit()->CastSpell(GetHitUnit(), SPELL_ETHEREAL_PET_AURA, true);
}
```

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Fixed. Thanks!

Comment (ccrs) [reply src/server/scripts/Spells/spell_generic.cpp]: remove ``Unit* target = GetHitUnit();`` then

File: src/server/scripts/Spells/spell_generic.cpp [hunk 25]
```diff
@@ -1614,6 +1614,116 @@ class spell_gen_elune_candle : public SpellScript
...
+    {
+        PreventDefaultAction();
+
+        std::list<Creature*> minionList;
+        GetUnitOwner()->GetAllMinionsByEntry(minionList, NPC_ETHEREAL_SOUL_TRADER);
+        for (Creature* minion : minionList)
+        {
+            if (minion->IsAIEnabled)
+                minion->AI()->Talk(SAY_STEAL_ESSENCE);
+                minion->CastSpell(eventInfo.GetProcTarget(), SPELL_STEAL_ESSENCE_VISUAL);
```
Comment (ccrs) [inline src/server/scripts/Spells/spell_generic.cpp]: either missing brackets or wrong indentation

Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: Weird. My editor shows exactly four spaces.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 24 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: `GetHitUnit()` is used twice. Isn't it better to move it into a variable?

File: src/server/scripts/Spells/spell_generic.cpp (hunk 25 above)
Comment (illfated) [reply src/server/scripts/Spells/spell_generic.cpp]: The indentation looks OK.
You just need brackets before and after the 2 `minion` function calls.

File: src/server/scripts/Spells/spell_generic.cpp [hunk 26]
```diff
@@ -1614,6 +1614,117 @@ class spell_gen_elune_candle : public SpellScript
...
+
+    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+
+        std::list<Creature*> minionList;
+        GetUnitOwner()->GetAllMinionsByEntry(minionList, NPC_ETHEREAL_SOUL_TRADER);
+        for (Creature* minion : minionList)
+        {
+            if (minion->IsAIEnabled) {
```
Comment (illfated) [inline src/server/scripts/Spells/spell_generic.cpp]: TC C++ codestyle: please move the bracket straight underneath `if`.

File: src/server/scripts/Spells/spell_generic.cpp (hunk 24 above)
Comment (DanVS) [reply src/server/scripts/Spells/spell_generic.cpp]: OK :)

File: src/server/scripts/Spells/spell_generic.cpp [hunk 27]
```diff
@@ -1614,6 +1614,118 @@ class spell_gen_elune_candle : public SpellScript
...
+
+// 50051 - Ethereal Pet Aura
+class spell_ethereal_pet_aura : public AuraScript
+{
+    PrepareAuraScript(spell_ethereal_pet_aura);
+
+    bool CheckProc(ProcEventInfo& eventInfo)
+    {
+        uint32 levelDiff = std::abs(GetTarget()->getLevel() - eventInfo.GetProcTarget()->getLevel());
+            return levelDiff <= 9;
```
Comment (FireEmerald) [inline src/server/scripts/Spells/spell_generic.cpp]: No reason to indent this line, there's no if statement before.

**Review by FireEmerald — CHANGES_REQUESTED** [review]

File: src/server/scripts/Spells/spell_generic.cpp [hunk 28]
```diff
@@ -1614,6 +1614,118 @@ class spell_gen_elune_candle : public SpellScript
...
+
+    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+
+        std::list<Creature*> minionList;
+        GetUnitOwner()->GetAllMinionsByEntry(minionList, NPC_ETHEREAL_SOUL_TRADER);
+        for (Creature* minion : minionList)
+        {
+            if (minion->IsAIEnabled)
```
Comment (Keader) [inline src/server/scripts/Spells/spell_generic.cpp]: i wonder if it is needed.
it's a companion, i dont think that AI will be null

Comment (ccrs) [reply src/server/scripts/Spells/spell_generic.cpp]: everytime AI getter is used, this should always be checked before. Edge cases, eeeeeeeeedge cases everywhere 💃.

File: sql/updates/world/3.3.5/9999_99_99_99_world.sql [hunk 29]
```diff
@@ -0,0 +1,7 @@
+UPDATE `creature_template` SET `ScriptName`='npc_pet_gen_soul_trader' WHERE `entry`=27914;
+DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_ethereal_pet_aura','spell_ethereal_pet_onsummon','spell_ethereal_pet_aura_remove','spell_steal_essence_visual');
+INSERT INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES 
+(50051, 'spell_ethereal_pet_aura'),
```
Comment (Keader) [inline sql/updates/world/3.3.5/9999_99_99_99_world.sql]: remove spaces
should be: (50051,'spell_ethereal_pet_aura')
same below.
Btw, PR is ready right?

Comment (DanVS) [reply sql/updates/world/3.3.5/9999_99_99_99_world.sql]: Done :+1: 
I guess so (works for me).

**Review by Keader — APPROVED** [review]
ready to merge.

**Comment by Keader** [comment]
Thank you @DanVS

**Comment by DanVS** [comment]
Thanks everyone for help! :)
