### PR TITLE
Scripts/Stratholme : Fix closed door at Baron Rivendare by @cr4st

### LINKED ISSUE #6377: [NPC/GO] Baron Rivendare - Doors remain closed
http://old.wowhead.com/npc=10440

You enter the room he's in and the doors close and when you kill him and his mobs the doors should open again but do not. End up trapped inside and have to HS, teleport or portal out.

Update: If you go just inside the doors of the room he is in, range attack him, and quickly back up outside the room and up the stairs to the closed outside door and kill him there the doors will open and you can leave as intended. The GO range that detects his death must be too small an area.

2012-04-28 15:10:52 +0200 (b53485e05326+) (Win64, Release)
b53485e05326f9ed6562aa78fee282f255eac339
TDB_full_335.11.46_2012_02_13 (+updates)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64703-npc-go-baron-rivendare-doors-remain-closed?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by StormBytePP**
Should close #6377

### CODE REVIEW

**Comment by Warhearth** [comment]
This fixes the doors confirmed working #6377 I did not encounter evade issue though for #15239

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp [hunk 1]
```diff
@@ -106,7 +106,8 @@ class boss_baron_rivendare : public CreatureScript
         void AttackStart(Unit* who) override
         {
             //can't use entercombat(), boss' dmg aura sets near players in combat, before entering the room's door
-            instance->SetData(TYPE_BARON, IN_PROGRESS);
+            if (instance && instance->GetData(TYPE_BARON) == NOT_STARTED)
```
Comment (Shauren) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp]: There is no need to check 'instance' for nullptr, it will never be empty - the AI will simply not run if spawned outside the instance, thanks to GetInstanceAI<boss_baron_rivendareAI>

**Comment by Shauren** [comment]
Also how is this even related to #15239 if that issue is about Naxxramas and this PR only changes Stratholme?

**Comment by StormBytePP** [comment]
@Shauren That I don't know, I just created a PR to be easy to check, but they were saying something about that.

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/TrinityCore/pull/15257#issuecomment-129833598 sounds like a clueless reply.

The is also no explaination at all about the changes.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp [hunk 2]
```diff
@@ -106,7 +106,8 @@ class boss_baron_rivendare : public CreatureScript
         void AttackStart(Unit* who) override
         {
             //can't use entercombat(), boss' dmg aura sets near players in combat, before entering the room's door
-            instance->SetData(TYPE_BARON, IN_PROGRESS);
+            if (instance->GetData(TYPE_BARON) == NOT_STARTED)
```
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp]: this check should be moved to the instance script itself

**Comment by chaodhib** [comment]
This code (if tested and if it works) will only fix #6377. 

I think the confusion comes from the fact that this boss is also present in the 4 Horsemen encounter at Naxxramas (these are 2 different NPCs with the same name) and that the encounter has a (unconfirmed?) similiar issue (problem with a door not opening: #15239).

So the title should be renamed to something like : Scripts/Stratholme: Fix closed door at Baron Rivendare and the PR should only mention #6377.

File: src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp (hunk 2 above)
Comment (Nyeriah) [inline src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp]: I don't get that check. What makes IN_PROGRESS be set while it's set to anything else but NOT_STARTED?
