### PR TITLE
Fix evade on aggro switch on neutral (yellow) mobs

### LINKED ISSUE #19768: [3.3.5] Faction bug
Description:
https://github.com/TrinityCore/TrinityCore/commit/15a207fcac15d336b848f9759f75386e12b6a35f
After this commit i found strange bug. For example - boss Midnight in Karazhan.
Npc 16151 have faction 7 (this faction don't have any friendly/hostile factions in dbc files), when you start attacking midnight by first player, and after re-aggro boss to second player (by abilities), this check
(https://github.com/TrinityCore/TrinityCore/commit/15a207fcac15d336b848f9759f75386e12b6a35f#diff-f3f953a63e2a008d22de69cb68f735c4R2292) is failing and boss entering evade mode. I think all npc with this faction can have this problem, or, with simular factions.

If creature in AGRESSIVE react state, then traget can't switch target to new, and continue attacking first target using "// search nearby enemy before enter evade mode" case.

Can you please review this situation ? if need i can record video. Can be reprodusing on last rev (3.3.5 branch). In additional you can check this using 20774 npc.

Branch(es):
3.3.5

TC rev. hash/commit:
(last rev)
TrinityCore rev. edd2c1c03995 2017-05-17 07:16:46 +0300 (master branch) (Unix, Release, Static) (worldserver-daemon)

### PR DESCRIPTION
**Pull request by Treeston**
Partial revert of 15a207f, which was causing issues (ref #4943 and #19768). Instead, fixes the underlying issue from 15a207f one level further down - `Unit::getAttackerForHelper()` shouldn't return units that we aren't in combat with (victim can be such a unit for players/player pets, which can startattack from a distance without entering combat).

Fixes the following issues:
- Player pets would aggro neutral mobs as soon as they start autocasting (Imp's Firebolt) if they're in react range (due to victim != null, autocast counts as autoattack and sets victim)
- Neutral mobs would randomly evade when aggro switched between targets.

Closes #19768 and #19485.

### CODE REVIEW

**Comment by ccrs** [comment]
``Unit::getAttackerForHelper() shouldn't return units that we aren't in combat with```
why? guardians without charm info use it to enter combat (for example assist on owner damaged)

**Comment by Treeston** [comment]
Owner damaged means we've been attacked, so we're in combat.

The only situation where a Unit can be not in combat with its victim is when it's player controlled, where "victim" = "thing the player right-clicked to start auto attack". Here, combat should not trigger until the actual attack happens.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -5768,13 +5768,14 @@ void Unit::_removeAttacker(Unit* pAttacker)
 
 Unit* Unit::getAttackerForHelper() const                 // If someone wants to help, who to give them
 {
-    if (GetVictim() != NULL)
-        return GetVictim();
+    if (Unit* victim = GetVictim())
+        if (!IsControlledByPlayer() || IsInCombatWith(victim))
+            return GetVictim();
```
Comment (ariel-) [inline src/server/game/Entities/Unit/Unit.cpp]: return victim;

File: src/server/game/Entities/Unit/Unit.cpp [hunk 2]
```diff
@@ -5768,13 +5768,22 @@ void Unit::_removeAttacker(Unit* pAttacker)
 
 Unit* Unit::getAttackerForHelper() const                 // If someone wants to help, who to give them
 {
-    if (GetVictim() != NULL)
-        return GetVictim();
+    if (Unit* victim = GetVictim())
+        if (!IsControlledByPlayer() || IsInCombatWith(victim) || victim->IsInCombatWith(this))
```
Comment (ariel-) [inline src/server/game/Entities/Unit/Unit.cpp]: Isn't IsInCombatWith reciprocal?

**Comment by ccrs** [comment]
This brings up a mistake on some hooks like
````
OwnerAttackedBy OwnerAttacked
````
they are only triggered for Pet, not for Minions (Guardian etc)

File: src/server/game/Entities/Unit/Unit.cpp (hunk 2 above)
Comment (Treeston) [inline src/server/game/Entities/Unit/Unit.cpp]: No, it checks threat list.

**Comment by Treeston** [comment]
That's beyond the scope of this PR, tbf. (but yes)

**Comment by Regrad** [comment]
Last revision.
Video of this bug:
https://youtu.be/gtvi9TgfLBs

**Comment by Treeston** [comment]
@Regrad is that with this PR applied?

**Comment by Regrad** [comment]
With the last patch the problem was completely solved. Many thanks.
