### PR TITLE
Boss/Script: Fix Mechano-Lord Capacitus's Nether Charges

### LINKED ISSUE #23973: Boss/Script: Fix Mechano-Lord Capacitus's Nether Charges
**Description:** Fix Nether Charges auras, scripts, summon spells and timer
```sql
UPDATE `creature_template` SET `speed_walk`=2.4, `speed_run`=0.857143  WHERE `entry` IN (20405,21534);
UPDATE `creature_template_addon` SET `auras`=""  WHERE `entry` IN (20405,21534);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (20405) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(20405, 0, 0, 0, 60, 0, 100, 0, 1000, 1000, 2000, 2000, 11, 35151, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Nether Charge - IN Update - CAST 'Nether Charge Pulse' (NO REPEAT)"),
(20405, 0, 1, 2, 25, 0, 100, 0, 0, 0, 0, 0, 75, 35150, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Nether Charge - IN Reset - Add aura Nether Charge Passive"),
(20405, 0, 2, 3, 61, 0, 100, 0, 0, 0, 0, 0, 11, 37670, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Nether Charge - IN Reset - Cast Nether Charge Timer"),
(20405, 0, 3, 4, 61, 0, 100, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Nether Charge - IN Reset - React passive"),
(20405, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 89, 20, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Nether Charge - IN Reset - Random movement");
```
``` diff
diff --git a/src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp b/src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
index 467568be24..e6284d588e 100644
--- a/src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
+++ b/src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
@@ -30,7 +30,12 @@ enum Spells
     SPELL_POLARITY_SHIFT            = 39096,
     SPELL_BERSERK                   = 26662,
     SPELL_NETHER_CHARGE_TIMER       = 37670,
-    SPELL_NETHER_CHARGE_PASSIVE     = 37670,
+    SPELL_NETHER_CHARGE_PASSIVE     = 35150,
+	
+    SPELL_SUMMON_NETHER_CHARGE_NE   = 35153,
+    SPELL_SUMMON_NETHER_CHARGE_NW   = 35904,
+    SPELL_SUMMON_NETHER_CHARGE_SE   = 35905,
+    SPELL_SUMMON_NETHER_CHARGE_SW   = 35906,
 
     SPELL_POSITIVE_POLARITY         = 39088,
     SPELL_POSITIVE_CHARGE_STACK     = 39089,
@@ -134,9 +139,19 @@ class boss_mechano_lord_capacitus : public CreatureScript
                             break;
                         case EVENT_SUMMON_NETHER_CHARGE:
                         {
-                            Position pos = me->GetRandomNearPosition(5.0f);
-                            me->SummonCreature(NPC_NETHER_CHARGE, pos, TEMPSUMMON_TIMED_DESPAWN, 18000);
-                            events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, 10s);
+                            uint32 spellId;
+                            uint32 netherChargeTimer;
+                            netherChargeTimer = DUNGEON_MODE(urand(9000, 11000), urand(2000, 5000));
+                            switch (urand(0, 3))
+                            {
+                                case 0: spellId = SPELL_SUMMON_NETHER_CHARGE_NE; break;
+                                case 1: spellId = SPELL_SUMMON_NETHER_CHARGE_NW; break;
+                                case 2: spellId = SPELL_SUMMON_NETHER_CHARGE_SE; break;
+                                default:
+                                case 3: spellId = SPELL_SUMMON_NETHER_CHARGE_SW; break;
+                            }
+                            DoCast(me, spellId, TRIGGERED_NONE);
+                            events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, netherChargeTimer);
                             break;
                         }
                         case EVENT_BERSERK:
```

**Branch(es):** Both

**TC rev. hash/commit:**  rev. 091ff42064ba

### PR DESCRIPTION
**Pull request by Killyana**
**Changes proposed:**

Fix Mechano-Lord Capacitus's Nether Charges

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [X] master

**Issues addressed:** Closes #23973

**Tests performed:**  build OK, tested in-game OK

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Fix Syntax

### CODE REVIEW

File: src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp [hunk 1]
```diff
@@ -134,9 +139,19 @@ class boss_mechano_lord_capacitus : public CreatureScript
...
-                            events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, 10s);
+                            uint32 spellId;
+                            uint32 netherChargeTimer;
+                            netherChargeTimer = DUNGEON_MODE(urand(9000, 11000), urand(2000, 5000));
+                            switch (urand(0, 3))
+                            {
+                                case 0: spellId = SPELL_SUMMON_NETHER_CHARGE_NE; break;
+                                case 1: spellId = SPELL_SUMMON_NETHER_CHARGE_NW; break;
+                                case 2: spellId = SPELL_SUMMON_NETHER_CHARGE_SE; break;
+                                default:
```
Comment (Ovahlord) [inline src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: no need for default here. If all possible cases are between 0 and 3 you can just go with cases.

File: src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp [hunk 2]
```diff
@@ -134,9 +139,19 @@ class boss_mechano_lord_capacitus : public CreatureScript
...
+                                case 3: spellId = SPELL_SUMMON_NETHER_CHARGE_SW; break;
+                            }
+                            DoCast(me, spellId, TRIGGERED_NONE);
```
Comment (Ovahlord) [inline src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: DoCastSelf(spellId); will do perfectly fine here.

File: src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp [hunk 3]
```diff
@@ -134,9 +139,19 @@ class boss_mechano_lord_capacitus : public CreatureScript
                             break;
                         case EVENT_SUMMON_NETHER_CHARGE:
                         {
-                            Position pos = me->GetRandomNearPosition(5.0f);
-                            me->SummonCreature(NPC_NETHER_CHARGE, pos, TEMPSUMMON_TIMED_DESPAWN, 18000);
-                            events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, 10s);
+                            uint32 spellId;
+                            uint32 netherChargeTimer;
```
Comment (Ovahlord) [inline src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: you can initialize the variable right away:
uint32 netherChargeTimer = DUNGEON_MODE(urand(9000, 11000), urand(2000, 5000));

uint32 spellId should also get initialized with 0 at least. It's not necessary because it's covered below but just to keep standards.

File: src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp [hunk 4]
```diff
@@ -134,9 +139,17 @@ class boss_mechano_lord_capacitus : public CreatureScript
                             break;
                         case EVENT_SUMMON_NETHER_CHARGE:
                         {
-                            Position pos = me->GetRandomNearPosition(5.0f);
-                            me->SummonCreature(NPC_NETHER_CHARGE, pos, TEMPSUMMON_TIMED_DESPAWN, 18000);
-                            events.ScheduleEvent(EVENT_SUMMON_NETHER_CHARGE, 10s);
+                            uint32 spellId = 0;
+                            uint32 netherChargeTimer = DUNGEON_MODE(urand(9000, 11000), urand(2000, 5000));
+                            switch (urand(0, 3))
```
Comment (jackpoz) [inline src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: if I remember right there is a 1 liner that returns a random spell id from a list of spells, I'll check if I can find it

Comment (Ovahlord) [reply src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: RAND(spellid1, spellid2, spellid3, spellid4);

Comment (soulfrost) [reply src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: containers::SelectRandomContainerElement

Comment (ccrs) [reply src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: RAND is more suitable here

File: src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp [hunk 5]
```diff
@@ -30,7 +30,12 @@ enum Spells
     SPELL_POLARITY_SHIFT            = 39096,
     SPELL_BERSERK                   = 26662,
     SPELL_NETHER_CHARGE_TIMER       = 37670,
-    SPELL_NETHER_CHARGE_PASSIVE     = 37670,
+    SPELL_NETHER_CHARGE_PASSIVE     = 35150,
```
Comment (jackpoz) [inline src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: @Killyana was this spell id wrong ?

**Comment by jackpoz** [comment]
Codestyle has been updated, please test this PR ingame one last time and then we can merge it

File: src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp (hunk 5 above)
Comment (Killyana) [reply src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp]: Yes.

**Comment by Killyana** [comment]
Tested IG, everything looks good.
