### PR TITLE
Entities/Unit: Fix pet-vs-creature aggression checks

### LINKED ISSUE #16659: [3.3.5] Core/Pet: "Roar of Sacrifice" capable of making pet engage certain NPCs
3.3.5 d4184065b6d51b250ab08f35e88868cef631ed4b

When the hunter pet ability [Roar of Sacrifice](http://wotlk.openwow.com/spell=53480) is used on certain normally-unattackable NPCs, the pet will enter melee combat with them, allowing the hunter to indirectly kill friendly NPCs.

Examples of affected creatures include [Grezla the Hag](http://www.wowhead.com/npc=32683/grezla-the-hag) and [Marcia Chase](http://www.wowhead.com/npc=28742/marcia-chase) in Dalaran.

### PR DESCRIPTION
**Pull request by Treeston**
Entities/Unit: Fix aggression checks when testing player pets vs neutral creatures. Pets will no longer be able to attack unattackable creatures in some situations. Fixes and closes #16659.

### CODE REVIEW

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -12003,25 +12003,23 @@ bool Unit::_IsValidAttackTarget(Unit const* target, SpellInfo const* bySpell, Wo
         || target->GetReactionTo(this) > REP_NEUTRAL)
         return false;
 
+    Player const* playerAffectingAttacker = HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PVP_ATTACKABLE) ? GetAffectingPlayer() : nullptr;
+    Player const* playerAffectingTarget = target->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PVP_ATTACKABLE) ? target->GetAffectingPlayer() : nullptr;
+
     // Not all neutral creatures can be attacked (even some unfriendly faction does not react aggresive to you, like Sporaggar)
-    if (GetReactionTo(target) == REP_NEUTRAL &&
-        target->GetReactionTo(this) <= REP_NEUTRAL)
+    if  (!playerAffectingAttacker != !playerAffectingTarget)
```
Comment (Shauren) [inline src/server/game/Entities/Unit/Unit.cpp]: please rewrite this check to something readable
