### PR TITLE
Scripts/UtgardePinnacle: Svala Sorrowgrave Ritual improvements

### LINKED ISSUE #25970: [3.3.5] - Utgarde Pinnacle: Svala Sorrowgrave Ritual movement
**Description:**

As I have commented here: https://github.com/TrinityCore/TrinityCore/issues/23610#issuecomment-768210146
when the ritual begins (boss health below 50%) and is positioned over the player on the altar, Svala falls towards the player instead of floating up until the sword hits the player

**Expected behaviour:**

she should stay up in the air until the sword hits 
https://www.youtube.com/watch?v=8f8d1aVY75Q <-- min 0:37

Can be fixed adding ```me->SetControlled(true, UNIT_STATE_ROOT);``` when ritual start and remove it when ritual ends, but maybe isn't the proper way, I don't know if need some aura or what can be the proper way

**Steps to reproduce the problem:**

1. .gm on
2. .go cre id 29281
3. .mod hp 10000000
4. .gm off
5. wait until intro ends and svala attack
6. damage svala below 50% hp (.damage 170000)
7. see how svala teleport up but fall to the player position

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

f474418651557acb621e9634993738118fb54a7e

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Set passive, interrupt spells and stop movement when ritual start
-  Set aggressive when ritual end
-  prevent svala fall (visual) when ritual start after wipe
-  Svala should be disarmed before teleport when ritual start
-  Remove unneded SetCombatMovement
- Delay EVENT_FINISH_RITUAL 2 sec more because otherwise it is executed before the end of the duration of SPELL_RITUAL_OF_THE_SWORD

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:**

Closes #25970

**Tests performed:**

 tested in-game

### CODE REVIEW

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp [hunk 1]
```diff
@@ -377,11 +376,13 @@ class boss_svala : public CreatureScript
                             break;
                         case EVENT_FINISH_RITUAL:
                             me->SetDisableGravity(false, true);
-                            SetCombatMovement(true);
-
+                            me->GetMotionMaster()->MoveFall();
```
Comment (offl) [inline src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:379]: `me->SetDisableGravity(false, true);` probably should already make unit fall

Comment (Jildor) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp]: thx

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp [hunk 2]
```diff
@@ -377,11 +376,13 @@ class boss_svala : public CreatureScript
...
+                            me->SetReactState(REACT_AGGRESSIVE);
                             if (Unit* target = me->SelectNearestPlayer(100.0f))
+                            {
                                 AttackStart(target);
-
+                                me->GetMotionMaster()->MoveChase(target);
```
Comment (offl) [inline src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:383]: Looks like `AttackStart(target);` already handles this

Comment (Jildor) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:383]: nope, need movechase after motionmaster clear

Comment (Ovahlord) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:383]: you do not kill the motionmaster via clear.  You do me->SetReactState(REACT_PASSIVE) and  me->AttackStop() after that. that will take of blocking chase movement. UpdateVictim will handle the chase movement on its own when aggressive again.

Comment (Jildor) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:383]: thx ;)

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp [hunk 3]
```diff
@@ -159,14 +158,12 @@ class boss_svala : public CreatureScript
...
 
-                SetCombatMovement(true);
-
                 if (_introCompleted)
                     events.SetPhase(NORMAL);
                 else
                     events.SetPhase(IDLE);
 
-                me->SetDisableGravity(false);
+                me->SetDisableGravity(false, true);
```
Comment (Ovahlord) [inline src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:166]: this is a nope from me. Remove the true from here and from the part at line 373 and make sure that the boss has the no movement flag update extra flag (512)

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp [hunk 4]
```diff
@@ -349,15 +346,19 @@ class boss_svala : public CreatureScript
...
+                                me->InterruptNonMeleeSpells(true);
+                                me->SetReactState(REACT_PASSIVE);
+                                me->AttackStop();
+                                me->StopMoving();
                                 me->SetDisableGravity(true, true);
                                 instance->SetGuidData(DATA_SACRIFICED_PLAYER, sacrificeTarget->GetGUID());
                                 Talk(SAY_SACRIFICE_PLAYER);
                                 DoCast(sacrificeTarget, SPELL_RITUAL_PREPARATION);
-                                SetCombatMovement(false);
+                                DoCast(me, SPELL_RITUAL_DISARM);
```
Comment (Ovahlord) [inline src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:357]: DoCastSelf pls for this and all other DoCast(me  scenarios

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp [hunk 5]
```diff
@@ -366,22 +367,13 @@ class boss_svala : public CreatureScript
...
-                        case EVENT_RITUAL_DISARM:
-                            DoCast(me, SPELL_RITUAL_DISARM);
                             break;
                         case EVENT_FINISH_RITUAL:
                             me->SetDisableGravity(false, true);
-                            SetCombatMovement(true);
-
+                            me->SetReactState(REACT_AGGRESSIVE);
                             if (Unit* target = me->SelectNearestPlayer(100.0f))
                                 AttackStart(target);
```
Comment (Ovahlord) [inline src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp:376]: this should also be obsolete because UpdateVictim will handle care of the attacks

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp (hunk 3 above)
Comment (Jildor) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp]: I have removed it in all four SetDisableGravity, If not, it was still falling after a wipe in ritual, removing it in all also works well, I hope this is the right way ;)

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp (hunk 4 above)
Comment (Jildor) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp]: thx ;)

File: src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp (hunk 5 above)
Comment (Jildor) [reply src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_svala.cpp]: thx ;)

**Comment by jackpoz** [comment]
is this PR ready to be merged ?

**Comment by Jildor** [comment]
for my part yep

**Comment by jackpoz** [comment]
@Ovahlord should anything else be changed before this PR can be merged or ?

**Comment by Ovahlord** [comment]
If tests have been made with all changes and it's working as intended, then sure, green light from me.

**Comment by jackpoz** [comment]
Thanks for the PR :)
