### PR TITLE
[3.3.5] Missing NPC spells and quest credit

### LINKED ISSUE #20224: Venture Co. Straggler missing chop spell on core script
**Description:**

Venture Co. Straggler has a Chop spell written on the core but it is currently not working. 
I checked every wotlk online database possible but none of them have a chop spell for this NPC so I end up checking wowhead.

http://www.wowhead.com/npc=27570/venture-co-straggler#abilities

As you can see the spell is there and the argument of "it could have been changed later on other expansions" is not valid on wotlk content because none of them touched Grizzly Hills ( At least not anything major that i recall).

**Current behaviour:**

No Chop spell.

**Expected behaviour:**

Chop spell in combat.

**Steps to reproduce the problem:**

1. Go to Grizzly Hills, Venture Bay.
2. Engage combat.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 80a886733246 2017-08-24 20:02:04 +0200 (3.3.5 branch)

**TDB version:**  

Using World DB: TDB 335.63

**Operating system:** 

Windows 10

### LINKED ISSUE #20226: [3.3.5] Quest Escape from the Winterfin Caverns
**Description:**

Escape from the Winterfin Caverns, when you escort Lurgglbr at the end of the escort it doesnt give credit for completing quest.

**Current behaviour:**

When you accept quest and escord Lurgglbr to the end, it despanws and doesnt give credit.

**Expected behaviour:**

He should give credit BEFORE he despawns

**Steps to reproduce the problem:**

1. take quest.
2) escord the little bastard.
3) at the end wait.. and wait he despawns but doesnt give credit.

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 4ee16fb53617 2017-08-22 21:24:22 +0200 (3.3.5 branch) (Unix, 

**TDB version:**  TDB 335.63

**Operating system:** ubuntu 14.06 lts

### LINKED ISSUE #20232: [3.3.5] Enraged Spirits missing abilities
**Description:**

In  Shadowmoon Valley we can encounter several npcs that share the same script because of 3 quests.
These npcs are:

- Enraged Water Spirit
- Enraged Earth Spirit
- Enraged Air Spirit
- Enraged Fire Spirit

**Current behaviour:**

Right now all of them are only dealing damage with auto attacks, missing all of their spells.

**Expected behaviour:**

In combat they must cast the following spells:

1. Enraged Water Spirit
Stormbolt https://db.rising-gods.de/?spell=38032

2. Enraged Earth Spirit
Fiery Boulder http://www.wowhead.com/spell=38498/fiery-boulder
Summon enraged earth shard http://www.wowhead.com/spell=38365/summon-enraged-earth-shard

3. Enraged Air Spirit
Chain Lighting http://www.wowhead.com/spell=12058/chain-lightning
Hurricane http://www.wowhead.com/spell=32717/hurricane
Enrage http://www.wowhead.com/spell=8599/enrage

4. Enraged Fire Spirit
Fel Fireball https://db.rising-gods.de/?spell=36247
Enrage https://db.rising-gods.de/?spell=8599

**Steps to reproduce the problem:**

1. Go to Shadowmoon valley
https://db.rising-gods.de/?npc=21061 Enraged Fire Spirit location
https://db.rising-gods.de/?npc=21060 Enraged Air Spirit location
https://db.rising-gods.de/?npc=21059 Enraged Water Spirit location
https://db.rising-gods.de/?npc=21050 Enraged Earth Spirit location

2. Fight the spirits

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 7a62c71a46d9b8d233f3741986255a5cab33ebfd

**TDB version:** 335.63

**Operating system:** Windows 10

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

-  Added chop spell to Venture Co. Straggler
- Added missing script for Enraged Spirits
- Fixed missing credit for Escaping from the Winterfin Caverns

**Target branch(es):** 3.3.5

- [x] 3.3.5

**Issues addressed:** 

Closes #20224 
Closes #20232 
Closes #20226 

**Tests performed:** 

Builds and works in game.

### CODE REVIEW

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp [hunk 1]
```diff
@@ -612,6 +617,14 @@ class npc_venture_co_straggler : public CreatureScript
             if (!UpdateVictim())
                 return;
 
+	    if (Chop_Timer <= diff)
+	    {
+		DoCastVictim(SPELL_CHOP);
+		Chop_Timer = 8000;
+	    }
+	    else
+		Chop_Timer -= diff;
```
Comment (HannibalRoG) [inline src/server/scripts/Northrend/zone_grizzly_hills.cpp]: A lot of tab, dont use tab, change it for 4 spaces.

**Review by HannibalRoG — CHANGES_REQUESTED** [review]
Lot of tab, change tab for 4 spaces.

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp (hunk 1 above)
Comment (hiMalleus) [reply src/server/scripts/Northrend/zone_grizzly_hills.cpp]: will remember it thanks

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp [hunk 2]
```diff
@@ -639,6 +652,7 @@ class npc_venture_co_straggler : public CreatureScript
         }
 };
 
+
```
Comment (Aokromes) [inline src/server/scripts/Northrend/zone_grizzly_hills.cpp]: remove :)

**Comment by hiMalleus** [comment]
sorry for inconvenience on indentation!

**Comment by joschiwald** [comment]
what does this pr change? i only see that you moved to eventmap handling to deprecated timers

**Comment by sirikfoll** [comment]
Just revert all the changes and add something like this, please:
```diff
diff --git a/src/server/scripts/Northrend/zone_grizzly_hills.cpp b/src/server/scripts/Northrend/zone_grizzly_hills.cpp
index de646c0..cf752b1 100644
--- a/src/server/scripts/Northrend/zone_grizzly_hills.cpp
+++ b/src/server/scripts/Northrend/zone_grizzly_hills.cpp
@@ -573,6 +573,11 @@ public:
             me->SetReactState(REACT_AGGRESSIVE);
         }
 
+        void EnterCombat(Unit* /*who*/) override
+        {
+            _events.ScheduleEvent(EVENT_CHOP, Seconds(10), Seconds(12));
+        }
+
         void UpdateAI(uint32 diff) override
         {
             _events.Update(diff);
@@ -602,7 +607,7 @@ public:
                     case EVENT_CHOP:
                         if (UpdateVictim())
                             DoCastVictim(SPELL_CHOP);
-                        _events.ScheduleEvent(EVENT_CHOP, 10000, 12000);
+                        _events.Repeat(Seconds(10), Seconds(12));
                         break;
                     default:
                         break;

**Comment by hiMalleus** [comment]
thanks for clearing it out sirikfoll, will do.

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp [hunk 3]
```diff
@@ -599,19 +604,19 @@ class npc_venture_co_straggler : public CreatureScript
                     case EVENT_STRAGGLER_4:
                         me->DisappearAndDie();
                         break;
-                    case EVENT_CHOP:
-                        if (UpdateVictim())
-                            DoCastVictim(SPELL_CHOP);
-                        _events.ScheduleEvent(EVENT_CHOP, 10000, 12000);
-                        break;
+		    case EVENT_CHOP:
```
Comment (Aokromes) [inline src/server/scripts/Northrend/zone_grizzly_hills.cpp]: tabs2spaces

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp [hunk 4]
```diff
@@ -599,19 +604,19 @@ class npc_venture_co_straggler : public CreatureScript
...
+			break;
                     default:
                         break;
                 }
             }
 
             if (!UpdateVictim())
                 return;
-
+
```
Comment (Aokromes) [inline src/server/scripts/Northrend/zone_grizzly_hills.cpp]: remove whiteline.

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp (hunk 3 above)
Comment (hiMalleus) [reply src/server/scripts/Northrend/zone_grizzly_hills.cpp]: I don't understand, if i tab it isn't in line with the rest.

Comment (hiMalleus) [reply src/server/scripts/Northrend/zone_grizzly_hills.cpp]: Forgive my ignorance, i was doing changes directly through the website and not with gitextensions :$

**Comment by hiMalleus** [comment]
Forgive a noob for his inexperience, i swear to god I learnt my lesson.

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 5]
```diff
@@ -1390,7 +1390,22 @@ enum Enraged_Dpirits
     NPC_ENRAGED_FIRE_SPIRIT                 = 21061,
     NPC_ENRAGED_AIR_SPIRIT                  = 21060,
     NPC_ENRAGED_WATER_SPIRIT                = 21059,
-
+    
+    // ENRAGED WATER SPIRIT SPELLS
+    SPELL_STORMBOLT			                = 38032,
```
Comment (HannibalRoG) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: More tabs here...

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 6]
```diff
@@ -1390,7 +1390,22 @@ enum Enraged_Dpirits
...
+
+    // ENRAGED AIR SPIRIT SPELLS
+    SPELL_AIR_SPIRIT_CHAIN_LIGHTNING        = 12058,
+    SPELL_HURRICANE                         = 32717,
+    SPELL_ENRAGE                            = 8599,
+
+    // ENRAGED FIRE SPIRIT SPELLS - Will be using the enrage spell from Air Spirit
+    SPELL_FEL_FIREBALL			            = 36247,
```
Comment (HannibalRoG) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: and here...

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 7]
```diff
@@ -1413,6 +1428,15 @@ enum Enraged_Dpirits
     SPELL_SOUL_CAPTURED                     = 36115
 };
 
+enum Enraged_Spirits_Events
+{
+    EVENT_ENRAGED_WATER_SPIRIT			        = 1,
+    EVENT_ENRAGED_FIRE_SPIRIT			        = 2,
+    EVENT_ENRAGED_EARTH_SPIRIT			        = 3,
+    EVENT_ENRAGED_AIR_SPIRIT_CHAIN_LIGHTNING	= 4,
+    EVENT_ENRAGED_AIR_SPIRIT_HURRICANE		    = 5
```
Comment (HannibalRoG) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: and a lot more here...

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 8]
```diff
@@ -1427,9 +1451,76 @@ class npc_enraged_spirit : public CreatureScript
...
+			case NPC_ENRAGED_EARTH_SPIRIT:
+				_events.ScheduleEvent(EVENT_ENRAGED_EARTH_SPIRIT, Seconds(0), Seconds(1));
+				break;
+			case NPC_ENRAGED_AIR_SPIRIT:
+				_events.ScheduleEvent(EVENT_ENRAGED_AIR_SPIRIT_CHAIN_LIGHTNING, Seconds(0), Seconds(1));
+				break;
+			default:
+				break;
+		}
+	}
```
Comment (HannibalRoG) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: and a tone here

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 9]
```diff
@@ -1427,9 +1451,76 @@ class npc_enraged_spirit : public CreatureScript
...
+
+		if (!UpdateVictim())
+			return;
+
+		if (me->GetEntry() == NPC_ENRAGED_FIRE_SPIRIT || me->GetEntry() == NPC_ENRAGED_AIR_SPIRIT)
+			if (HealthBelowPct(35) && !me->GetAura(SPELL_ENRAGE))
+				DoCastSelf(SPELL_ENRAGE);
+
+		DoMeleeAttackIfReady();
+	}
```
Comment (HannibalRoG) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: same...

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 10]
```diff
@@ -1488,6 +1580,9 @@ class npc_enraged_spirit : public CreatureScript
                  }
             }
         }
+
+    private:
+	    EventMap _events;
```
Comment (HannibalRoG) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: one more here

**Review by HannibalRoG — CHANGES_REQUESTED** [review]
You need to configure your editor so that when you press the tab key you will replace it with 4 spaces.

If you use notepad++ read https://stackoverflow.com/questions/455037/convert-tabs-to-spaces-in-notepad
If you use VS read https://stackoverflow.com/questions/14167033/visual-studio-replace-tab-with-4-spaces/14167067

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp [hunk 11]
```diff
@@ -599,19 +604,18 @@ class npc_venture_co_straggler : public CreatureScript
                     case EVENT_STRAGGLER_4:
                         me->DisappearAndDie();
                         break;
-                    case EVENT_CHOP:
-                        if (UpdateVictim())
-                            DoCastVictim(SPELL_CHOP);
-                        _events.ScheduleEvent(EVENT_CHOP, 10000, 12000);
-                        break;
+		            case EVENT_CHOP:
```
Comment (Aokromes) [inline src/server/scripts/Northrend/zone_grizzly_hills.cpp]: tabs2spaces

File: src/server/scripts/Northrend/zone_grizzly_hills.cpp [hunk 12]
```diff
@@ -600,18 +605,17 @@ class npc_venture_co_straggler : public CreatureScript
                         me->DisappearAndDie();
                         break;
                     case EVENT_CHOP:
-                        if (UpdateVictim())
-                            DoCastVictim(SPELL_CHOP);
-                        _events.ScheduleEvent(EVENT_CHOP, 10000, 12000);
-                        break;
+			            if (UpdateVictim())
```
Comment (Aokromes) [inline src/server/scripts/Northrend/zone_grizzly_hills.cpp]: tabs2spaces.

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 13]
```diff
@@ -1390,7 +1390,22 @@ enum Enraged_Dpirits
     NPC_ENRAGED_FIRE_SPIRIT                 = 21061,
     NPC_ENRAGED_AIR_SPIRIT                  = 21060,
     NPC_ENRAGED_WATER_SPIRIT                = 21059,
-
+
```
Comment (Aokromes) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: remove whitespaces

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 14]
```diff
@@ -1429,7 +1453,74 @@ class npc_enraged_spirit : public CreatureScript
...
+                        if (UpdateVictim())
+                            DoCastVictim(SPELL_HURRICANE);
+                        _events.ScheduleEvent(EVENT_ENRAGED_AIR_SPIRIT_CHAIN_LIGHTNING, Seconds(10), Seconds(13));
+                        break;
+                    default:
+                        break;
+                }
+            }
+
+		if (!UpdateVictim())
```
Comment (Keader) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: it should be before of: https://github.com/TrinityCore/TrinityCore/pull/20225/files#diff-ba4f7087a55302e25b5ce01e7dcfdbbfR1479

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 15]
```diff
@@ -1429,7 +1453,74 @@ class npc_enraged_spirit : public CreatureScript
...
+			return;
+
+		if (me->GetEntry() == NPC_ENRAGED_FIRE_SPIRIT || me->GetEntry() == NPC_ENRAGED_AIR_SPIRIT)
```
Comment (Keader) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: It should be in DamageTaken hook.

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 16]
```diff
@@ -1429,7 +1453,74 @@ class npc_enraged_spirit : public CreatureScript
...
+			if (HealthBelowPct(35) && !me->GetAura(SPELL_ENRAGE))
```
Comment (Keader) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: should be: !me->HasAura(SPELL_ENRAGE), you dont need get this aura...

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp [hunk 17]
```diff
@@ -1429,7 +1453,74 @@ class npc_enraged_spirit : public CreatureScript
 
         void Reset() override { }
 
-        void EnterCombat(Unit* /*who*/) override { }
+        void EnterCombat(Unit* /*who*/) override
+        {
+            switch (me->GetEntry())
+            {
+                case NPC_ENRAGED_WATER_SPIRIT:
+                    _events.ScheduleEvent(EVENT_ENRAGED_WATER_SPIRIT, Seconds(0), Seconds(1));
```
Comment (Keader) [inline src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: You realy sure about it? 0~1 sec? sniffs show it?

**Review by Keader — CHANGES_REQUESTED** [review]
please change this stuffs

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 17 above)
Comment (hiMalleus) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: I am not sure i don't have accurate data only guessed from fotage

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 16 above)
Comment (hiMalleus) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: If i don't get this aura then the npc is just going to be casting enrage all the time when below 35% health

Comment (hiMalleus) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: I even tried using a boolean to validate the enrage but if the npc is channeling for example hurricane, then he turns it to true and doesn't cast the spell. That's the only reason i chose that logic.

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 15 above)
Comment (hiMalleus) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: what do you mean DamageTaken hook, i only based that enrage logic from patchwerk it works fine in here

Comment (Keader) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: This hook: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp#L551
It's called when creature take some damage.
You can put this logic inside of this function

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 16 above)
Comment (Keader) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: try: 
```cpp
if (HealthBelowPct(35) && !me->HasAura(SPELL_ENRAGE))
    DoCastSelf(SPELL_ENRAGE, true);
```

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 17 above)
Comment (Keader) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: If you dont have access to retail (to sniff it)
ask someone on IRC if can do it.
We dont accept guessed values.

Comment (hiMalleus) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: I closed it because you rather have this broken instead of using some temporary values. Looks like It is impossible to sniff things from retail right now because patch 7.3 has updated the exe to a powerful encryption or so i was told on #Trinity IRC.

**Comment by Shauren** [comment]
Honestly, for spell timing a retail combat log would work as well

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 17 above)
Comment (Keader) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: It's not a temp fix, it's hack.
Shauren should make a new sniffer soon, he always do. Or maybe Aokromes has some old sniff about this creatures. Is not only me... TC Team dont accept guessed values...

**Comment by Keader** [comment]
Looks a good option too.

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 17 above)
Comment (offl) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: > We dont accept guessed values.

One half or more of scripts(SAI, CPP) has wrong guessed timers and scripting methods(how NPC will use ability, for example), so it's strange to hear.
Since TC replaced EAI by SAI some progress was made by ACID(EAI), but it never been ported to TC. Sometimes [you can find there](https://raw.githubusercontent.com/ACID-Scripts/WOTLK/master/acid_wotlk.sql) good scripts with timers from retail for some TBC locations(currently ACID has perfectly scripted Tanaris, for example, and some TBC heroic dungeons. While TC uses old ACID version).
Or you can made script based on other scrips.

**Comment by hiMalleus** [comment]
I'll see if I can find someone to record me a log then

File: src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp [hunk 18]
```diff
@@ -65,7 +65,7 @@ class boss_broggok : public CreatureScript
             {
                 _EnterCombat();
                 Talk(SAY_AGGRO);
-            }
+            }
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp]: remove tailing whitespace.

**Comment by hiMalleus** [comment]
**Enraged water spirit**

https://www.warcraftlogs.com/reports/Kcb34tDYw9pqVZjP/#type=casts&view=events&hostility=1&pins=0%24Separate%24%23244F4B%24damage%241%240.0.0.Any%2421059.0.0.NPC%24true%240.0.0.Any%24false%240&source=1&boss=0&difficulty=0

- Stormbolt cast every 17- 23 Seconds. The first one was cast approximately 1 second on entered combat. 

**Enraged Air Spirit**

https://www.warcraftlogs.com/reports/Kcb34tDYw9pqVZjP/#type=summary&view=events&hostility=1&pins=0%24Separate%24%23244F4B%24damage%241%240.0.0.Any%2421059.0.0.NPC%24true%240.0.0.Any%24false%240&source=6&boss=0&difficulty=0

- First Chain Lightning cast after 10 seconds entering combat and the following one 20 seconds after the first.

File: src/server/scripts/Outland/zone_shadowmoon_valley.cpp (hunk 17 above)
Comment (Faq) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: So this thing is only one what holds for back merge?

Comment (Aokromes) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: old times where different, things changed with time, from when we don't had snifs to now.

Comment (Aokromes) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: PS: even you don't have sniffer now, you can look at combat logs.

Comment (Faq) [reply src/server/scripts/Outland/zone_shadowmoon_valley.cpp]: I suggest to merge other code and leave this script hanging.

**Comment by Aokromes** [comment]
@Keader sooo this can be merged? the only doubtful thing is correct.
