### PR TITLE
[Core/Quests]: Dont immediately update object visibility at PhaseShift and wait for the AI Hooks to be called in Player::RewardQuest

### LINKED ISSUE #28506: Quest gossip closing issue
### Description

Quest gossip should close immediately before a phase change not fade out with the npc. 

### Expected behaviour

After quest reward gossip should close before phase change.

### Steps to reproduce the problem

It can be tested on the exile's Reach ships and possibly in other places.

### Branch

master

### TC rev. hash/commit

TrinityCore rev. badd37e9a499+

### Operating system

Windows 10 x64

### Custom changes

none

### PR DESCRIPTION
**Pull request by Seyden**
**Changes proposed:**

-  Change the order in which Quest Reward Hook / Phase Shift and Update Object Visiblity is called in Player::RewardQuest
-  This change will also fix implicit replace objects
-  

**Issues addressed:**

Closes #28506

**Tests performed:**

(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by malcrom** [comment]
Works

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -14960,15 +14960,69 @@ void Player::RewardQuest(Quest const* quest, LootItemType rewardType, uint32 rew
...
-    SendQuestUpdate(quest_id);
-
     SendQuestGiverStatusMultiple();
 
+    SendQuestUpdate(quest_id, false);
+
     //lets remove flag for delayed teleports
     SetCanDelayTeleport(false);
 
+    bool canHaveNextQuest = !quest->HasFlag(QUEST_FLAGS_AUTOCOMPLETE) ? !questGiver->IsPlayer() : true;
```
Comment (Shauren) [inline src/server/game/Entities/Player/Player.cpp:14970]: whats up with this random condition that wasnt there before?

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -14960,15 +14960,69 @@ void Player::RewardQuest(Quest const* quest, LootItemType rewardType, uint32 rew
...
+            }
+            default:
+                break;
+        }
+    }
+
     sScriptMgr->OnQuestStatusChange(this, quest_id);
     sScriptMgr->OnQuestStatusChange(this, quest, oldStatus, QUEST_STATUS_REWARDED);
+
+    UpdateObjectVisibility();
```
Comment (Shauren) [inline src/server/game/Entities/Player/Player.cpp:15025]: and where does this come from?

Comment (Seyden) [reply src/server/game/Entities/Player/Player.cpp:15025]: Like you see above, I purposefully set false for SendQuestUpdate, so the phases are sent if needed but visibility is updated at a later point after the AI hooks are done

File: src/server/game/Entities/Player/Player.cpp (hunk 1 above)
Comment (Seyden) [reply src/server/game/Entities/Player/Player.cpp:14970]: This condition is in QuestHandlet.cpp in a different kind of form.. we have this condition because there is a assert in CanHaveNextQuest

File: src/server/game/Entities/Player/Player.cpp (hunk 2 above)
Comment (Shauren) [reply src/server/game/Entities/Player/Player.cpp:15025]: reread 2nd sentence in my comment, you changed "update visibility if phases changed earlier" to "update visibility always but later"

Comment (Seyden) [reply src/server/game/Entities/Player/Player.cpp:15025]: Ah yes that’s what I do, otherwise I would have to return a Boolean in OnConditionChanged so I know if a phase changed, the question is: is it worth it ?

File: src/server/game/Entities/Player/Player.cpp (hunk 1 above)
Comment (Shauren) [reply src/server/game/Entities/Player/Player.cpp:14970]: Moving that code from `WorldSession::HandleQuestgiverChooseRewardOpcode` to `Player::RewardQuest` possibly changes the guid that is passed to `SendQuestGiverQuestDetails`, did you check what is the value of `packet.QuestGiverGUID` for quests with QUEST_FLAGS_AUTOCOMPLETE?
