### PR TITLE
Core/Players: Improve trade exchange calculations

### LINKED ISSUE #24434: Core/Players: Incorrect space calculation on trades
**Description:**

When performing a trade, the inventory check in `Player::` will only merge the incoming stacks with a stack that can take every piece of the incoming stack. This means that trades will fail even if the receiving character actually does have room for all incoming items.

**Current behaviour:**

Trades shall fail on account of Character A not having enough space when space exists across multiple partial stacks.

**Expected behaviour:**

A trade that fills up multiple stacks should complete without errors. Observed on retail Classic.

**Steps to reproduce the problem:**

1. Place 2 characters together, Character A and Character B.
2. Give the following items to A:
	* 38 pieces of Linen Cloth: .additem 2589 38
	* Enough non-Linen Cloth items to fill inventory: .additem 6265 255
3. Character A should arrange the Linen Cloth to be in 2 stacks of 19
4. Give the following items to Character B:
	* 2 pieces of Linen Cloth: .additem 2589 2
5. Open a trade between Character A and Character B
6. Character B shall attempt to trade their 2 pieces of Linen to Character A

**Branch(es):**

3.3.5

**TC rev. hash/commit:**

0844ad2f

**Operating system:**

Fedora 31

### PR DESCRIPTION
**Pull request by adeutscher**
**Changes proposed:**

-  When determining whether or not an item can be exchanged in `Player::CanStoreItems`, spread incoming pieces of a stack across multiple pieces of the mock-inventory if necessary.
- Allow merging of incoming items into one free inventory slot.

**Target branch(es):** 3.3.5

- [x] 3.3.5

**Issues addressed:** Closes #24434

**Tests performed:**

Builds successfully.

Test 1: Trade across multiple stacks

1. Place 2 characters together, Character A and Character B.
2. Give the following items to A:
	* 38 pieces of Linen Cloth: `.additem 2589 38`
	* Enough non-Linen Cloth items to fill inventory: `.additem 6265 255`
3. Character A should arrange the Linen Cloth to be in 2 stacks of 19
4. Give the following items to Character B:
	* 2 pieces of Linen Cloth: `.additem 2589 2`
5. Open a trade between Character A and Character B
6. Character B shall attempt to trade their 2 pieces of Linen to Character A

Observed result (Retail Classic): Trade completes without errors
Expected result (3.3.5, broken): Trade shall fail on account of Character A not having enough space
Expected result (branch): Trade shall go through, leaving Character A with 2 stacks of 20 Linen Cloth

This problem was that each inventory-slot calculation in `Player::CanStoreItems` only accepts a full stack merge. It would not accept 2+ partial matches.

Test 2: Multiple incoming stacks competing for free space

1. Place 2 characters together, Character A and Character B.
2. Fill player A's inventory with something like Soul Shards: `.additem 6265 255`
3. Free up one space in player A's inventory.
4. Give Player B 2 Incendite Ore: `.additem 3340 2`
5. Player B should break these 2 pieces into 2 stacks.
6. Open a trade between Character A and Character B
7. Character B shall attempt to trade their 2 incomplete stacks of Incendite Ore to Player A.

Expected result (3.3.5, broken): Trade shall fail on account of Character A not having enough space
Expected result (branch): Trade shall go through, leaving Character A with a stack of 2 Incendite Ore.

Test 3: Free space error check

1. Place 2 characters together, Character A and Character B.
2. Fill player A's inventory with something like Soul Shards: `.additem 6265 255`
3. Free up one space in player A's inventory.
4. Give Player B 12 Incendite Ore: `.additem 3340 12`
5. Player B should break these 12 pieces into 2 stacks of 6.
6. Open a trade between Character A and Character B
7. Character B shall attempt to trade their 2 incomplete stacks of Incendite Ore to Player A.

Expected result (branch): Trade shall fail, as the receiving player has no space

Test 4: Free space error check

1. Place 2 characters together, Character A and Character B.
2. Fill player A's inventory with something like Soul Shards: `.additem 6265 255`
3. Free up two spaces in player A's inventory.
4. Give Player A 8 Incendite Ore: `.additem 3340 8`
5. Give Player B 12 Incendite Ore: `.additem 3340 12`
6. Player B should break these 12 pieces into 2 stacks of 6.
7. Open a trade between Character A and Character B
8. Character B shall attempt to trade their 2 incomplete stacks of Incendite Ore to Player A.

Expected result (branch): Trade shall go through, leaving Character A with 12 pieces of Ore.

This test confirmed that the changes aren't being too generous with allocated space.

**Known issues and TODO list:**
- [x] Fix Test 2. At time of writing, it is failing. This also blocks tests 3 and 4.

### CODE REVIEW

File: src/server/game/Spells/SpellEffects.cpp [hunk 1]
```diff
@@ -1372,6 +1372,8 @@ void Spell::EffectHealthLeech(SpellEffIndex effIndex)
 
 void Spell::DoCreateItem(uint32 /*i*/, uint32 itemtype)
 {
+    TC_LOG_ERROR("spells", "DoCreateItem: %u", itemtype);
```
Comment (jackpoz) [inline src/server/game/Spells/SpellEffects.cpp:1375]: This is probably just some debug log, anyway please remove it from the PR to avoid merging it by accident

Comment (adeutscher) [reply src/server/game/Spells/SpellEffects.cpp:1375]: Oops, that's embarrassing. Axing.

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -11066,61 +11073,87 @@ InventoryResult Player::CanStoreItems(Item** items, int count, uint32* itemLimit
...
             {
                 item2 = GetItemByPos(INVENTORY_SLOT_BAG_0, t);
-                if (item2 && item2->CanBeMergedPartlyWith(pProto) == EQUIP_ERR_OK && currencyCounts[t-CURRENCYTOKEN_SLOT_START] + item->GetCount() <= pProto->GetMaxStackSize())
+                if (item2 && item2->CanBeMergedPartlyWith(pProto) == EQUIP_ERR_OK && currencyCounts[t-CURRENCYTOKEN_SLOT_START] < pProto->GetMaxStackSize())
                 {
-                    currencyCounts[t-CURRENCYTOKEN_SLOT_START] += item->GetCount();
-                    b_found = true;
-                    break;
+                    currencyCounts[t-CURRENCYTOKEN_SLOT_START] += remaining_count;
+                    remaining_count = currencyCounts[t-CURRENCYTOKEN_SLOT_START] - pProto->GetMaxStackSize();
```
Comment (adeutscher) [inline src/server/game/Entities/Player/Player.cpp]: This and all similar checks are probably a source of problems when it doesn't form a complete stack. It is probably the source of my problems with Test 2.

e.g.

1. 5 items added to a 10-stack of a 20-stackable item, forming a 15-stack.
2. `remaining_count` is calculated as 15-20. Since this is a `uint32`, this overflows.

Comment (adeutscher) [reply src/server/game/Entities/Player/Player.cpp]: While this was **a** problem that needed to be solved, it wasn't **the** problem.

I now think that the problem is that we are continually polling `GetItemByPos` to get the state of the item.

1. The first stack's iteration goes to the free-space check and says "This is a 0-stack slot, it's available to throw our items into.
2. The second stack's iteration:
    a. The merge check relies on `GetItemByPos` succeeding. Since the mock-inventory has a new stack that doesn't match the real inventory, this fails and the slot isn't considered for merging.
    b. The free-space check fails because it detects the 1-stack.

Solution:

1. When compiling the mock-inventory, we also need an array of `Item` pointers. This array shall be used in merge checks.
2. When using free-space, assign the value of `item` to the array of item pointers.

Comment (adeutscher) [reply src/server/game/Entities/Player/Player.cpp]: Replacing `GetItemByPos` with another array of Item pointers solved the issue.

Successfully performed all tests using the latest build.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 3]
```diff
@@ -1610,7 +1610,7 @@ void Unit::HandleEmoteCommand(uint32 emoteId)
     damageReduction /= (1.0f + damageReduction);
 
     RoundToInterval(damageReduction, 0.f, 0.75f);
-    return uint32(std::ceilf(std::max(damage * (1.0f - damageReduction), 0.0f)));
+    return uint32(ceilf(std::max(damage * (1.0f - damageReduction), 0.0f)));
```
Comment (Faq) [inline src/server/game/Entities/Unit/Unit.cpp:1613]: this one should not be in this PR

Comment (adeutscher) [reply src/server/game/Entities/Unit/Unit.cpp:1613]: Correct, I only added it in to fix the CI build. I'll take it out to reduce confusion.

Comment (adeutscher) [reply src/server/game/Entities/Unit/Unit.cpp:1613]: Misspoke in my comment for 0f0f3da. Without the fix, the build is outright broken. When I said it worked locally I must have gotten my wires crossed and been thinking of a pre-3.3.5 merge build.

Comment (jackpoz) [reply src/server/game/Entities/Unit/Unit.cpp]: 3.3.5 has the build-fix now

**Comment by jackpoz** [comment]
is this ready to be merged ?

File: src/server/game/Entities/Player/Player.cpp [hunk 4]
```diff
@@ -10990,47 +10992,78 @@ InventoryResult Player::CanStoreItems(Item** items, int count, uint32* itemLimit
     memset(keyringCounts, 0, sizeof(uint32) * (KEYRING_SLOT_END - KEYRING_SLOT_START));
     memset(currencyCounts, 0, sizeof(uint32) * (CURRENCYTOKEN_SLOT_END - CURRENCYTOKEN_SLOT_START));
 
+    // Item pointers
+    Item* inventoryPointers[INVENTORY_SLOT_ITEM_END - INVENTORY_SLOT_ITEM_START];
+    Item* bagPointers[INVENTORY_SLOT_BAG_END - INVENTORY_SLOT_BAG_START][MAX_BAG_SIZE];
+    Item* keyringPointers[KEYRING_SLOT_END - KEYRING_SLOT_START];
+    Item* currencyPointers[CURRENCYTOKEN_SLOT_END - CURRENCYTOKEN_SLOT_START];
+
+    memset(inventoryPointers, 0, sizeof(Item*) * (INVENTORY_SLOT_ITEM_END - INVENTORY_SLOT_ITEM_START));
```
Comment (jackpoz) [inline src/server/game/Entities/Player/Player.cpp:11001]: could there be a more modern C++ way to default initialize all those local arrays to nullptr ?

File: src/server/game/Entities/Player/Player.cpp [hunk 5]
```diff
@@ -11059,62 +11092,84 @@ InventoryResult Player::CanStoreItems(Item** items, int count, uint32* itemLimit
...
                 {
-                    keyringCounts[t-KEYRING_SLOT_START] += item->GetCount();
-                    b_found = true;
-                    break;
+                    keyringCounts[t-KEYRING_SLOT_START] += remaining_count;
+                    remaining_count = keyringCounts[t-KEYRING_SLOT_START] < pProto->GetMaxStackSize() ? 0 : keyringCounts[t-KEYRING_SLOT_START] - pProto->GetMaxStackSize();
+
+                    b_found = remaining_count == 0;
+
+                    // stop checking keyring?
```
Comment (jackpoz) [inline src/server/game/Entities/Player/Player.cpp:11103]: are these questions ToDo's left to solve or ?

File: src/server/game/Entities/Player/Player.cpp (hunk 4 above)
Comment (adeutscher) [reply src/server/game/Entities/Player/Player.cpp:11001]: I could change it to be along the lines of `Item* keyringPointers[KEYRING_SLOT_END - KEYRING_SLOT_START] = {}`. This should remove the need for memset.

File: src/server/game/Entities/Player/Player.cpp (hunk 5 above)
Comment (adeutscher) [reply src/server/game/Entities/Player/Player.cpp:11103]: I meant them to be the questions that the if statements were asking. I'll rephrase to 'if incoming item has been fully allocated, then stop inspecting ___'.

**Comment by adeutscher** [comment]
@jackpoz After I've tidied up the comments and array initialization, things should be clear for merging.

**Comment by jackpoz** [comment]
just to confirm, did you do a fast check after latest commits too ? (even if very little has been modified)

**Comment by adeutscher** [comment]
Successfully performed tests 1 through 4 using an up-to-date build.

**Comment by jackpoz** [comment]
Thanks for the PR :)
