### PR TITLE
Scripts/Events: Fix achievement in Love is in the air: "Lonely?"

### LINKED ISSUE #24139: [3.3.5] [Achievement] [1291] Lonely
**Description:**
For some reason the achievement can't be completed.

**Current behaviour:**
Currently nothing happen except the basket and the umbrella are spawn.

**Expected behaviour:**

When two characters are joining together with [Romantic Picnic Basket](https://wotlk.evowow.com/?item=34480) they should fall in love. I guess the effect is called like that.
They should get hearth above they heads and then, when they start eating [Buttermilk Delight](https://wotlk.evowow.com/?item=22236) they should get the achievement [Lonely?](https://wotlk.evowow.com/?achievement=1291)

**Steps to reproduce the problem:**

1. Go to Dalaran.
2. Use [Romantic Picnic Basket](https://wotlk.evowow.com/?item=34480)
3. Use second character to join your picnic table.
4. Wait for the hearth effect.
5. Eat [Buttermilk Delight](https://wotlk.evowow.com/?item=22236) 

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5fa77744e4495a77dea734330d5ae9e113b8a7f1

**Operating system:**

Ubuntu 16.0.4 LTS

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Getcaster() is null, we don't need check caster in the script, so remove it

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:**

Closes #24139

**Tests performed:**

tested in-game

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks quite good to me.

**Comment by xParad0x** [comment]
Tested in game, looks good @Jildor

**Review by xParad0x — APPROVED** [review]

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 1]
```diff
@@ -42,75 +42,65 @@ enum SpellsPicnic
...
 
-            void OnPeriodic(AuraEffect const* /*aurEff*/)
-            {
-                // Every 5 seconds
-                Unit* target = GetTarget();
-                Unit* caster = GetCaster();
+        // If our player is no longer sit, remove all auras
+        if (target->GetStandState() != UNIT_STAND_STATE_SIT)
+        {
+            target->RemoveAura(SPELL_ROMANTIC_PICNIC_ACHIEV);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_holiday.cpp:64]: RemoveAuraDueToSpell

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 2]
```diff
@@ -42,75 +42,65 @@ enum SpellsPicnic
...
+        }
 
-                // If our player is no longer sit, remove all auras
-                if (target->GetStandState() != UNIT_STAND_STATE_SIT)
-                {
-                    target->RemoveAura(SPELL_ROMANTIC_PICNIC_ACHIEV);
-                    target->RemoveAura(GetAura());
-                    return;
-                }
+        target->CastSpell(target, SPELL_BASKET_CHECK, false); // unknown use, it targets Romantic Basket
```
Comment (Keader) [inline src/server/scripts/Spells/spell_holiday.cpp:69]: triggered = false is default, so can be removed here and below

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 3]
```diff
@@ -42,75 +42,65 @@ enum SpellsPicnic
...
+        }
 
-            void Register() override
-            {
-                AfterEffectApply += AuraEffectApplyFn(spell_love_is_in_the_air_romantic_picnic_AuraScript::OnApply, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY, AURA_EFFECT_HANDLE_REAL);
-                OnEffectPeriodic += AuraEffectPeriodicFn(spell_love_is_in_the_air_romantic_picnic_AuraScript::OnPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
-            }
-        };
+        if (!foundSomeone && target->HasAura(SPELL_ROMANTIC_PICNIC_ACHIEV))
+            target->RemoveAura(SPELL_ROMANTIC_PICNIC_ACHIEV);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_holiday.cpp:96]: RemoveAuraDueToSpell too

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 4]
```diff
@@ -42,75 +42,65 @@ enum SpellsPicnic
     SPELL_ROMANTIC_PICNIC_ACHIEV    = 45123, // Romantic Picnic periodic = 5000
 };
 
-class spell_love_is_in_the_air_romantic_picnic : public SpellScriptLoader
+class spell_love_is_in_the_air_romantic_picnic : public AuraScript
 {
-    public:
-        spell_love_is_in_the_air_romantic_picnic() : SpellScriptLoader("spell_love_is_in_the_air_romantic_picnic") { }
+    PrepareAuraScript(spell_love_is_in_the_air_romantic_picnic);
```
Comment (Keader) [inline src/server/scripts/Spells/spell_holiday.cpp:47]: missing validate spells

**Comment by jackpoz** [comment]
> * Getcaster() is null, we don't need check caster in the script, so remove it

I don't totally understand this sentence. Is GetCaster() supposed to be null ? is that how things are supposed to work ? how does the script change when not using GetCaster() ? what is it used instead ?

**Comment by Jildor** [comment]
> > * Getcaster() is null, we don't need check caster in the script, so remove it
> 
> I don't totally understand this sentence. Is GetCaster() supposed to be null ? is that how things are supposed to work ? how does the script change when not using GetCaster() ? what is it used instead ?

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/GameObject/GameObject.cpp#L768-L781
the picnic gob (187267) is goober and when player click, player get the aura 45102
the owner of the aura is the player, but for some reason, GetCaster() here return null (also return null GetGObjCaster()), you can test with worldobject GetOwner() and you get player clicker.
in the script we don't need GetCaster() because we can use target and playerfound for spellcast (is the current use of GetCaster in this script)

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 4 above)
Comment (Jildor) [reply src/server/scripts/Spells/spell_holiday.cpp:47]: thx, done ;)

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 3 above)
Comment (Jildor) [reply src/server/scripts/Spells/spell_holiday.cpp]: thx, done ;)

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 2 above)
Comment (Jildor) [reply src/server/scripts/Spells/spell_holiday.cpp]: thx, done ;)

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 1 above)
Comment (Jildor) [reply src/server/scripts/Spells/spell_holiday.cpp]: thx, done ;)

**Comment by jackpoz** [comment]
@Keader anything else to do or does this look good ?

**Comment by Keader** [comment]
looks good to me

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 5]
```diff
@@ -42,75 +42,77 @@ enum SpellsPicnic
...
+        // For nearby players, check if they have the same aura. If so, cast Romantic Picnic (45123)
+        // required by achievement and "hearts" visual
+        std::list<Player*> playerList;
+        Trinity::AnyPlayerInObjectRangeCheck checker(target, INTERACTION_DISTANCE*2);
+        Trinity::PlayerListSearcher<Trinity::AnyPlayerInObjectRangeCheck> searcher(target, playerList, checker);
+        Cell::VisitWorldObjects(target, searcher, INTERACTION_DISTANCE * 2);
+        for (std::list<Player*>::const_iterator itr = playerList.begin(); itr != playerList.end(); ++itr)
+        {
+            if (foundSomeone)
+                continue;
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_holiday.cpp:94]: shouldn't this be "break;" instead of "continue;" ?

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 6]
```diff
@@ -42,75 +42,77 @@ enum SpellsPicnic
...
-                            caster->CastSpell(*itr, SPELL_ROMANTIC_PICNIC_ACHIEV, true);
-                            caster->CastSpell(target, SPELL_ROMANTIC_PICNIC_ACHIEV, true);
-                        }
-                        foundSomeone = true;
-                        // break;
-                    }
+                    playerFound->CastSpell(playerFound, SPELL_ROMANTIC_PICNIC_ACHIEV, true);
+                    target->CastSpell(target, SPELL_ROMANTIC_PICNIC_ACHIEV, true);
+                    foundSomeone = true;
                 }
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_holiday.cpp:103]: or even better, how about adding a "break;" here after foundSomeone so we get out of the loop as soon as we are done ?

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 5 above)
Comment (Jildor) [reply src/server/scripts/Spells/spell_holiday.cpp:94]: Yes, it seems more optimal, thx

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 6 above)
Comment (Jildor) [reply src/server/scripts/Spells/spell_holiday.cpp:101]: ok, thx

**Comment by jackpoz** [comment]
just to be sure: is the achievement supposed to support 1 target player only ? https://github.com/TrinityCore/TrinityCore/pull/26083/files#diff-1b0804f59f113e7f4bf3733cba9666d276f450f70956a2790edf3a7d21f5df54R99

**Comment by Jildor** [comment]
I do not have data on how it would work with more players in retail, I don't know.
It seems to me little relevant in short, since the achievement would be completed anyway

**Comment by jackpoz** [comment]
Thanks for the PR :)
