### PR TITLE
Fixed pets repositioning themselves after every cast

### LINKED ISSUE #22857: [3.3.5] Imp pet repositions itself after every cast
**Description:**
The Imp pet (and every pet that has a casting spell) will reposition itself after every cast till it reaches a certain point.
I know this was reported before but all those issues are closed and this problem stll exists.
This video will give a better explanation than my poor english:
https://www.youtube.com/watch?v=hgXEetnqXdc&feature=youtu.be

**Steps to reproduce the problem:**
1. Create a warlock and summon the Imp pet
2. Make sure the Imp pet has Fireball on autocast
3. Make him attack something (like a dummy NPC)

**Branch(es):** 3.3.5
**TC rev. hash/commit:** df641e993ac4e058c55ec97cceb19cf397a51105
**Operating system:** Win 8.1

### PR DESCRIPTION
**Pull request by Ovahlord**
**Changes proposed:**

-  ranged attacking pets, minions etc were also affected by the default chase behaivior which is positioning behind the chase target or at least to the tolerance angle. We have an exception for this now so melee pets will still do this while ranged attacking pets will no longer give a fuck about it.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)
closes #22857

**Tests performed:** (Does it build, tested in-game, etc.)
- tested ingame

### CODE REVIEW

File: src/server/game/AI/CoreAI/PetAI.cpp [hunk 1]
```diff
@@ -420,8 +420,11 @@ void PetAI::DoAttack(Unit* target, bool chase)
 
             if (me->HasUnitState(UNIT_STATE_FOLLOW))
                 me->GetMotionMaster()->Remove(FOLLOW_MOTION_TYPE);
-
-            me->GetMotionMaster()->MoveChase(target, me->GetPetChaseDistance(), float(M_PI));
+            
+            // Pets with ranged attacks should not care about the chase angles or tolerances at all.
+            float chaseDistance = me->GetPetChaseDistance();
+            ChaseAngle angle = ChaseAngle(chaseDistance == 0.f ? float(M_PI) : 0.f, chaseDistance == 0.f ? float(M_PI_4) : float(M_PI * 2));
```
Comment (jackpoz) [inline src/server/game/AI/CoreAI/PetAI.cpp]: I would prefer to see this as a readable if/else block than an unreadable line with 2 ? :

**Comment by Ovahlord** [comment]
How about this? I'm not a fan of many if / else blocks so I'd rather have it go down in one strike

**Comment by jackpoz** [comment]
Looks good and very clear,  can I merge it ?

**Comment by Ovahlord** [comment]
I personally would request approval of a person that's maintaining movements to make sure that I didn't dig up the wrong place

**Comment by ccrs** [comment]
nice catch, I honestly did not think about this, the chase angle, at all.
good job 👍

**Comment by Keader** [comment]
Nice sucker 💃

**Comment by ccrs** [comment]
if this is tested in a clean 335.. looks perfect to me

**Review by ccrs — APPROVED** [review]
test it plx

**Comment by ccrs** [comment]
> test it plx

this is me asking for a test, neat right? like, me, asking for a test, after the mess of a couple weeks ago? 💃

**Comment by Jildor** [comment]
some people learn the hard way 😄

**Comment by Killyana** [comment]
Not fixed, with this change the imp go forward after each cast, also the follow angle is wrong, the pet must be at the left of the master 270°, not behind him.

**Comment by Killyana** [comment]
My bad I forget to remove: 
``` cpp
me->GetMotionMaster()->MoveChase(target, me->GetPetChaseDistance(), float(M_PI));
```
Everything works fine, it could be pushed

**Comment by Ovahlord** [comment]
So someone push the shiny button~

**Comment by jackpoz** [comment]
Thanks for the PR :)
