### PR TITLE
Core/Spells: Implement Ysera's Gift

### LINKED ISSUE #28705: Druid Talent Ysera's Gift
### Description

https://www.wowhead.com/spell=145108/yseras-gift This talent just doesn't work.

### Expected behaviour

Heals you for 3% of your maximum health every 5 sec. If you are at full health, an injured party or raid member will be healed instead.

### Steps to reproduce the problem

Just create druid and use that spell with this learned talent.

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/65e787d18be898532363fea3f8847fa4d7f21192

### Operating system

Debian 11

### Custom changes

None

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement Ysera's Gift

**Issues addressed:**

Closes #28705 #19720

Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_druid.cpp [hunk 1]
```diff
@@ -1662,6 +1664,36 @@ class spell_dru_wild_growth_aura : public AuraScript
...
+        return ValidateSpellInfo
+        ({
+            SPELL_DRUID_YSERAS_GIFT_HEAL_SELF,
+            SPELL_DRUID_YSERAS_GIFT_HEAL_PARTY
+        });
+    }
+
+    void HandleEffectPeriodic(AuraEffect const* aurEff)
+    {
+        int32 healAmount = int32(GetTarget()->CountPctFromMaxHealth(aurEff->GetAmount()));
```
Comment (Nyr97) [inline src/server/scripts/Spells/spell_druid.cpp:1683]: there are effects that increase the % health amount, is there a way to pass target as in CalcValue() so that such effects are taken into account?

Comment (mdX7) [reply src/server/scripts/Spells/spell_druid.cpp:1683]: thats already taken care of in `AuraEffect::CalculateAmount`

Comment (Shauren) [reply src/server/scripts/Spells/spell_druid.cpp:1683]: no, we should not, aurEff amount is already modified

**Review by Shauren — CHANGES_REQUESTED** [review]
145110 requires a target selection script to limit it to a random injured target with Trinity::SelectRandomInjuredTargets(targets, 1, true)

**Comment by aquadeus** [comment]
> 145110 requires a target selection script to limit it to a random injured target with Trinity::SelectRandomInjuredTargets(targets, 1, true)

done
