### PR TITLE
Core/Entities: Some changes to LoS z checking & MotionMaster::MoveJumpTo

### LINKED ISSUE #20966: [3.3.5] Issue with MoveJump in Trial of Crusader
**Description:** In the Northrend Beasts fight, Icehowl should use spell Jump Back (66733) in the middle of room.
Issue is: after casting it, he will go underground of the object.
Spell Jump Back is a `SPELL_EFFECT_LEAP_BACK` .

https://youtu.be/dRUI65GxwLI

**Steps to reproduce the problem:**

1. Go to Trial of Crusader in the middle of room (.go xyz 563.67297 139.571 393.837006 649) - sniffed position
2. Summon a Icehowl (.npc add temp 34797)
3. Use Macro in Icehowl .cast self 66733

He will fall off the map and ignore walls too.

PS: MMaps is disabled in Trial of Crusader.
PS²: Even with MMaps enabled in Trial of Crusader this issue happens.
PS³: Spell works fine if cast by a Player.

This spell is not present in the current script of Icehowl (it is handled by a MoveJump directly) - https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp#L1092

But this spell will enter in your script soon...

**Branch(es):** 3.3.5

**TC rev. hash/commit:** b70a923714d8a6afc7850010404c8ed3f238803f

Scripts like the one below don't work.

<details>

```cpp
class spell_icehowl_jump_back : public SpellScript
{
    PrepareSpellScript(spell_icehowl_jump_back);

    void RelocatePositionOffset(SpellEffIndex /*effIndex*/)
    {
        Unit* caster = GetCaster();
        WorldLocation* location = GetHitDest();
        float z = caster->GetMap()->GetHeight(caster->GetPhaseMask(), location->GetPositionX(), location->GetPositionY(), location->GetPositionZ() + 5.0f);
        location->RelocateOffset({ 0.0f, 0.0f, z, 0.0f });
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_icehowl_jump_back::RelocatePositionOffset, EFFECT_1, SPELL_EFFECT_LEAP_BACK);
    }
};
```

### PR DESCRIPTION
**Pull request by Golrag**
**Changes proposed:**

-  Use Midsection height for LoS checking.
-  Remove CombatReach calculation in MotionMaster::MoveJumpTo
    - Also it will always jump in the direction of the given angle even if it's not in LoS, instead of jumping to the first position with another angle in LoS.
-  ~~Add Midsection height for some position z before calling UpdateAllowdPositionZ~~

This should fix Icehowl jump going lower than expected & fix jormungar going lower than expected.

**Target branch(es):** 3.3.5/master

- 3.3.5
- master

**Issues addressed:** Closes #20966 #19976

**Tests performed:**
Builds
https://github.com/TrinityCore/TrinityCore/issues/20966 was fixed
https://github.com/TrinityCore/TrinityCore/issues/19976 was a bit afk, they did not go under the map, might be lucky.

**Known issues and TODO list:**

- I'm not sure if adding midsection height to z before calling some UpdateAllowedPositionZ is very blizzlike... Adding it in the UpdateAllowedPositionZ may cause some creature to want to walk "on the ceiling" of some caves.
example: that nerubian cave in dragon blight, aggro some weird flying bird and fly towards the ceiling of the cave, bird might go in it.
- **I did some changes to collisionheight calculation to check for scalemod, I maybe should not have done this as I did not verify it.**

So I'm not sure if this is the way to go but yeah, if someone has a better idea, feel free :D any help & feedback is welcome :)
small edit: I won't have much time this month & next month so feel free to add commits !

### CODE REVIEW

**Comment by joschiwald** [comment]
icehowl is a big hack

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -14752,3 +14752,27 @@ void Unit::Whisper(uint32 textId, Player* target, bool isBossWhisper /*= false*/
     ChatHandler::BuildChatPacket(data, isBossWhisper ? CHAT_MSG_RAID_BOSS_WHISPER : CHAT_MSG_MONSTER_WHISPER, LANG_UNIVERSAL, this, target, bct->GetText(locale, getGender()), 0, "", locale);
     target->SendDirectMessage(&data);
 }
+
+float Unit::GetCollisionHeight() const
+{
+    float scaleMod = GetObjectScale(); // 99% sure about this
+
+    if (IsMounted())
```
Comment (Treeston) [inline src/server/game/Entities/Unit/Unit.cpp]: Are you sure this returns the correct value during `Mount`/`Dismount`?

**Comment by Treeston** [comment]
Good observation, GetPosition is bottom of hit sphere, not center.

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Golrag) [reply src/server/game/Entities/Unit/Unit.cpp]: Yes, but I noticed it also returns true when in vehicle. When that's the case, it will just not pass the second if and go to the dismounting case.

Comment (Treeston) [reply src/server/game/Entities/Unit/Unit.cpp]: Alright, good enough for me :+1:

**Comment by Keader** [comment]
This can be merged?

**Review by Treeston — APPROVED** [review]

**Comment by tkrokli** [comment]
Any final comments, @Golrag ? :-)

**Comment by Golrag** [comment]
Was thinking about renaming GetCollisionHeight to ComputeCollisionHeight for #18771 not sure if we leave it in that PR or in this one :p

**Comment by jackpoz** [comment]
let's merge it and see what happens ?

**Comment by Jildor** [comment]
>let's merge it and see what happens ?

I love this 😄

**Comment by jackpoz** [comment]
Tagging here an issue reported at https://github.com/TrinityCore/TrinityCore/commit/95456ab5d8bd623481d315ae55dfbb44b45ba9f5#commitcomment-26280805 about LoS issue in "trial of the crusader"

**Comment by jackpoz** [comment]
Tagging here an issue reported at https://github.com/TrinityCore/TrinityCore/issues/21121 about LoS issue in caves

**Comment by ariel-** [comment]
Tagging #21081
