### PR TITLE
Core/Languages: Refactor to get data from db2

### LINKED ISSUE #25980: 9.0.2 - The languages ​​of different races are understood by all players regardless of race or faction
**Description:**

Players from different factions or races, when using their own language, must be understood by the opponent if it belongs to another race or faction. 

In my server configurations, the interaction between different factions is completely disabled, but the players still understand each other.

(If you know how to solve this problem, write below and I will close this issue.)

**Expected behaviour:**

Example: a human race player, does not understand an orc race player, due to different languages

**Steps to reproduce the problem:**

1. Create characters of different factions.
2. Teleport two players of the opposite faction to the same location.
3. Let the players try to communicate using different languages ​​typical of their race

**Branch(es):**

master

**TC rev. hash/commit:** 

d4ad987

**Operating system:** 

Windows 10 x64

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

-  Include translation PR #26271 (but fully)
-  Removed most langauge constants from code, and now loading them from .db2
-  Removed association between languages, spells and skills, and now loading them from .db2

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

- Closes #25980

**Tests performed:**

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

File: src/server/game/Miscellaneous/Language.h [hunk 1]
```diff
@@ -1162,4 +1162,13 @@ enum TrinityStrings
     LANG_YOUR_POWER_CHANGED                       = 11020,
     LANG_INVALID_POWER_NAME                       = 11021
 };
+
+/* Languages that do not exist in .db2 files and/or are used in code */
+enum Language
```
Comment (Shauren) [inline src/server/game/Miscellaneous/Language.h:1167]: put that in shareddefines or dbcenums

**Comment by Shauren** [comment]
Missing
* removing hyperlinks - all kinds of chat links, item, spell (not sure if it should remove them entirely or keep text between [])
* preserving case of translated message depending on receiver client locale - requires code being utf8 aware; koKR, zhCN, zhTW only uppercase characters from ascii range (if were uppercase in original message), other locales do that for all characters

**Comment by matanshukry** [comment]
Some metrics for future references:

| lang id | lang name | max word length | missing word length | 
| -- | -- | -- | -- |
| 1   | Orcish | 13 | none |
| 2   | Darnassian | 17 | 16 |
| 3   | Taurahe | 15 | 12 |
| 6   | Dwarvish | 17 | 15, 16 |
| 7   | Common | 12 | none |
| 8   | Demonic | 12 | none |
| 9   | Titan | 12 | none |
| 10  | Thalassian | 17 | none |
| 11  | Draconic | 12 | none |
| 12  | Kalimag | 13 | none |
| 13  | Gnomish | 11 | none |
| 14  | Zandali | 9  | none |
| 33  | Forsaken | 12 | none |
| 35  | Draenei | 12 | none | 
| 36  | Zombie | 9  | 6, 8 |
| 37  | Gnomish Binary | 8  | none |
| 38  | Goblin Binary | 8  | none |
| 39  | Gilnean | 1  | none |
| 40  | Goblin | 17 | 11, 16 |
| 42  | Pandaren (Neutral) | 3  | 1 |
| 43  | Pandaren (Alliance) | 3  | 1 |
| 44  | Pandaren (Horde) | 3  | 1 |
| 168 | Sprite | 9  | 3, 8 |
| 178 | Shath'Yar | 11 | none |
| 179 | Nerglish | 12 | 1, 8, 9, 10, 11 |
| 180 | Moonkin | 10 | 7, 8 |
| 181 | Shalassian | 17 | 16 |
| 182 | Thalassian | 17 | none |
| 285 | Vulpera | 10 | none |

**Comment by matanshukry** [comment]
Updated

**Comment by illfated** [comment]
You may want to add the missing NewLine at EOF in the SQL file. Although we try to make sure that SQL files start with a comment line to mitigate missing NewLine at EOF from the previous SQL file, there is no absolute guarantee that it will contain a starting comment.
