### PR TITLE
Core/VMaps: Fix LoS in Strand of the Ancients

### LINKED ISSUE #15798: [3.3.5] Strand of the Ancients LoS on gates
https://github.com/TrinityCore/TrinityCore/issues/6228 gameobject issue has been fixed but not the issue itself.

Screenshot in game: http://puu.sh/l5yKk/4b394bd373.jpg

> But it's not the GameObject, that is bugged but vmaps (I think).
> Little screenshot: http://puu.sh/kNsFY/e75f206abe.jpg

rev: https://github.com/TrinityCore/TrinityCore/commit/570e6baa090793bb5be33a4dbc417fb7b11d0b51

### PR DESCRIPTION
**Pull request by Golrag**
Fixed LoS issues in some places like SotA.
Re extracting VMaps is required.
Thanks @Warpten for the patch.

**Changes proposed:**

-  Don't dump destructible wmo's
-  Better check to skip no collision triangles 

**Target branch(es):** Both.

- 3.3.5
- master

**Issues addressed:** Closes #15798

**Tests performed:** 
- Builds
- Tested in game

### CODE REVIEW

File: src/tools/vmap4_extractor/wmo.h [hunk 1]
```diff
@@ -27,13 +27,15 @@
...
 
 // MOPY flags
-#define WMO_MATERIAL_NOCAMCOLLIDE    0x01
-#define WMO_MATERIAL_DETAIL          0x02
-#define WMO_MATERIAL_NO_COLLISION    0x04
-#define WMO_MATERIAL_HINT            0x08
-#define WMO_MATERIAL_RENDER          0x10
-#define WMO_MATERIAL_COLLIDE_HIT     0x20
-#define WMO_MATERIAL_WALL_SURFACE    0x40
+#define WMO_MATERIAL_UNK01           0x01
```
Comment (ariel-) [inline src/tools/vmap4_extractor/wmo.h]: Can you put these constants inside an enum?

File: src/tools/vmap4_extractor/wmo.cpp [hunk 2]
```diff
@@ -348,8 +348,11 @@ int WMOGroup::ConvertToVMAPGroupWmo(FILE *output, WMORoot *rootWMO, bool precise
         for (int i=0; i<nTriangles; ++i)
         {
             // Skip no collision triangles
-            if (MOPY[2*i]&WMO_MATERIAL_NO_COLLISION ||
-              !(MOPY[2*i]&(WMO_MATERIAL_HINT|WMO_MATERIAL_COLLIDE_HIT)) )
+            bool isRenderFace = (MOPY[2 * i] & WMO_MATERIAL_RENDER) && !(MOPY[2 * i] & WMO_MATERIAL_DETAIL);
+            bool isDetail = (MOPY[2 * i] & WMO_MATERIAL_DETAIL);
+            bool isCollision = (MOPY[2 * i] & WMO_MATERIAL_COLLISION);
+
+            if (!(isRenderFace || isDetail || isCollision))
```
Comment (ariel-) [inline src/tools/vmap4_extractor/wmo.cpp]: if (!isRenderFace && !isDetail && !isCollision)

**Review by ariel- — COMMENTED** [review]
Codestyle

File: src/tools/vmap4_extractor/wmo.h (hunk 1 above)
Comment (Golrag) [inline src/tools/vmap4_extractor/wmo.h]: Sure :)

File: src/tools/vmap4_extractor/wmo.cpp [hunk 3]
```diff
@@ -348,8 +348,11 @@ int WMOGroup::ConvertToVMAPGroupWmo(FILE *output, WMORoot *rootWMO, bool precise
         for (int i=0; i<nTriangles; ++i)
         {
             // Skip no collision triangles
-            if (MOPY[2*i]&WMO_MATERIAL_NO_COLLISION ||
-              !(MOPY[2*i]&(WMO_MATERIAL_HINT|WMO_MATERIAL_COLLIDE_HIT)) )
+            bool isRenderFace = (MOPY[2 * i] & WMO_MATERIAL_RENDER) && !(MOPY[2 * i] & WMO_MATERIAL_DETAIL);
+            bool isDetail = (MOPY[2 * i] & WMO_MATERIAL_DETAIL);
+            bool isCollision = (MOPY[2 * i] & WMO_MATERIAL_COLLISION);
```
Comment (tkrokli) [inline src/tools/vmap4_extractor/wmo.cpp]: From AppVeyor (VS2015):
```
src\tools\vmap4_extractor\wmo.cpp(352): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [src\tools\vmap4_extractor\vmap4extractor.vcxproj]
src\tools\vmap4_extractor\wmo.cpp(353): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning) [src\tools\vmap4_extractor\vmap4extractor.vcxproj]
```
