### PR TITLE
Scripts/Spells: Prayer of Mending

### LINKED ISSUE #26007: 9.0.2 - Prayer of Mending, spell not work (Priest)
**Description:**

Spellid: 33076

"Places a ward on an ally that heals them for (61% of Spell power) the next time they take damage, and then jumps to another ally within 20 yds. Jumps up to 5 times and lasts 30 sec after each jump."

Spell that regenerates health: 33110

**Expected behaviour:**

When used on self or an ally target, restores health based on the description.

**Steps to reproduce the problem:**

1. Create a priest class character.
2. Choose specialization holy.
3. Give character level 43.
4. Cast 33076 on yourself or an ally target

**Branch(es):**

master

**TC rev. hash/commit:** 

23144d0

**Operating system:** 

Windows 10 x64

### PR DESCRIPTION
**Pull request by matanshukry**
**Changes proposed:**

-  Added scripts to implement Prayer of Mending behaviour
-  Added sql script to link the c++ class to the relevant spells

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26007

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

### CODE REVIEW

File: src/server/scripts/Spells/spell_priest.cpp [hunk 1]
```diff
@@ -1122,38 +1125,171 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            return ValidateSpellInfo({ SPELL_PRIEST_PRAYER_OF_MENDING_AURA });
+        }
+
+        void HandleEffectDummy(SpellEffIndex effIndex)
+        {
+            SpellEffectInfo const *effectInfo = GetEffectInfo(effIndex);
+            if (!effectInfo)
+                return;
+
+            Unit *caster = GetCaster();
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_priest.cpp:1180]: `Unit* caster` instead of `Unit *caster` (no space between type and *)

**Review by mdX7 — CHANGES_REQUESTED** [review]

**Comment by mdX7** [comment]
The inheritance thing feels weird somehow though. Having to use duplicate code is more worse though, so it's fine I guess.

File: src/server/scripts/Spells/spell_priest.cpp [hunk 2]
```diff
@@ -1122,38 +1125,171 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            if (!caster)
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_priest.cpp:1181]: caster is never null when a spell is being cast

File: src/server/scripts/Spells/spell_priest.cpp [hunk 3]
```diff
@@ -1122,38 +1125,171 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            bool Validate(SpellInfo const* /*spellInfo*/) override
+            {
+                return ValidateSpellInfo({ SPELL_PRIEST_PRAYER_OF_MENDING_HEAL });
+            }
+
+            void HandleHeal(ProcEventInfo & /*eventInfo*/)
+            {
+                // Caster: the player(priest) that casters the prayer of mending
+                // Owner: the player that currently has the prayer of mending aura on him
+                if (Unit* owner = GetUnitOwner())
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_priest.cpp:1222]: owner should never be null, otherwise this cannot proc. Caster however can be null

File: src/server/scripts/Spells/spell_priest.cpp [hunk 4]
```diff
@@ -1122,38 +1125,171 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+                    if (Unit* caster = GetCaster())
+                        if (Aura* aura = owner->GetAura(SPELL_PRIEST_PRAYER_OF_MENDING_AURA))
```
[the remark this answers is not in the document]
Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp:1224]: Which one? there are 3 checks in here.
Are you talking only about the `GetUnitOwner()` ?

File: sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql [hunk 5]
```diff
@@ -0,0 +1,5 @@
+DELETE FROM `spell_script_names` WHERE `spell_id` = 33110;
```
[the remark this answers is not in the document]
Comment (matanshukry) [reply sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql:1]: Oh yeah I forgot about that, my bad.

File: src/server/scripts/Spells/spell_priest.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mdX7) [reply src/server/scripts/Spells/spell_priest.cpp]: only the caster check is required here

File: src/server/scripts/Spells/spell_priest.cpp [hunk 6]
```diff
@@ -1122,38 +1125,174 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+                targets.remove_if([](WorldObject* worldObject)
+                {
+                    return !worldObject || !(worldObject->ToPlayer());
+                });
+            }
+
+            void HandleJump(SpellEffIndex /*effIndex*/)
+            {
+                Unit* caster = GetCaster(); // the one that has the aura
+                assert(caster != null);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_priest.cpp:1271]: this will never happen, assert not required

File: src/server/scripts/Spells/spell_priest.cpp [hunk 7]
```diff
@@ -1122,38 +1125,174 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
-            void HandleHeal(SpellEffIndex /*effIndex*/)
+            void HandleHeal(ProcEventInfo & /*eventInfo*/)
             {
-                if (Unit* caster = GetOriginalCaster())
-                {
-                    if (AuraEffect* aurEff = caster->GetAuraEffect(SPELL_PRIEST_T9_HEALING_2P, EFFECT_0))
+                // Caster: the player(priest) that casters the prayer of mending
+                // Owner: the player that currently has the prayer of mending aura on him
+                Unit* owner = GetUnitOwner();
+                assert(owner != null);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_priest.cpp:1222]: this will never happen, assert not required

File: src/server/scripts/Spells/spell_priest.cpp [hunk 8]
```diff
@@ -1122,38 +1125,174 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            SpellEffectInfo const* effectInfo = GetEffectInfo(effIndex);
+            if (!effectInfo)
+                return;
+
+            Unit* target = GetExplTargetUnit();
+            if (!target)
+                return;
+
+            Unit* caster = GetCaster();
+            assert(caster != null);
```
Comment (mdX7) [inline src/server/scripts/Spells/spell_priest.cpp:1185]: this will never happen, assert not required

File: sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql [hunk 9]
```diff
@@ -0,0 +1,5 @@
+DELETE FROM `spell_script_names` WHERE `spell_id` IN (33110, 33076, 41635, 155793);
```
Comment (mdX7) [inline sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql:1]: is 33110 an old spellid related to prayer of mending?

Comment (illfated) [reply sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql:1]: Exists both on wowhead (not in Classic) & TC ubuntu aowow (3.3.5), not sure of the history
- https://www.wowhead.com/spell=33110/prayer-of-mending
- https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=33110
- https://wow.gamepedia.com/Prayer_of_Mending

Comment (illfated) [reply sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql:1]: BTW, there used to be a rule that
```sql
DELETE FROM `spell_script_names` WHERE `ScriptName` IN (
```
is the preferred method. Many have debated the validity of that rule.

Comment (illfated) [reply sql/updates/world/master/2021_02_02_00_world_priest_prayer_of_mending.sql:1]: Unless there is a good & obvious reason for deleting by spell ID, TC prefers using
```sql
DELETE FROM `spell_script_names` WHERE `ScriptName` IN ('spell_pri_prayer_of_mending', 'spell_pri_prayer_of_mending_aura', 'spell_pri_prayer_of_mending_jump');
```

**Comment by illfated** [comment]
old-school title format: **Scripts/Spells: Prayer of Mending**

File: src/server/scripts/Spells/spell_priest.cpp (hunk 7 above)
Comment (Ovahlord) [reply src/server/scripts/Spells/spell_priest.cpp]: He should use GetTarget() instead which will return the unit that has the aura.

**Comment by illfated** [comment]
`2021_02_02_00_world_priest_prayer_of_mending.sql`: "No newline at end of file" - add missing NewLine and maybe an empty comment line at the top (`-- `).

**Comment by matanshukry** [comment]
@illfated Like that?

File: src/server/scripts/Spells/spell_priest.cpp (hunk 7 above)
Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp]: @Ovahlord What's the difference? the comments on the properties sounds vaguely similar, and using GetUnitOwner() seems to use the correct unit from the tests I've made.

**Comment by illfated** [comment]
Yeah, looks quite OK to me.

F.Y.I. : The SQL value rows indent is not strictly needed.
Maybe it is on par with non-TC general SQL codestyle, IDK.
You can choose to start every line on column 1 if you want.

**Comment by matanshukry** [comment]
I remember doing it that way from another issue where you fixed my script and you did it, but I could be wrong.
Anyway if you want me to change it without any indent let me know and I'll do it, otherwise I'll just leave it as it is now.

**Comment by illfated** [comment]
Nah, leave it as is for now. I simply meant to inform you for future SQL tickets or PR additions. 🙂

**Comment by matanshukry** [comment]
Cool, no more indents from now on.
Thanks :)

File: src/server/scripts/Spells/spell_priest.cpp [hunk 10]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+    public:
+        spell_pri_prayer_of_mending_jump() : SpellScriptLoader("spell_pri_prayer_of_mending_jump") { }
+
+        class spell_pri_prayer_of_mending_jump_SpellScript : public spell_pri_prayer_of_mending_SpellScriptBase
+        {
+            PrepareSpellScript(spell_pri_prayer_of_mending_jump_SpellScript);
+
+            void OnTargetSelect(std::list<WorldObject*>& targets)
+            {
+                targets.remove_if([](WorldObject* worldObject)
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1258]: This script is incorrect
* (minor) nullptr will be inside the target list
* This is aoe target - you need to pick only one target from the prepopulated list (currently you will cast this on everyone)
* Target is supposed to be a random injured unit (skip full health ones), can hit pets but will always prefer players

File: src/server/scripts/Spells/spell_priest.cpp [hunk 11]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            }
 
-            void HandleHeal(SpellEffIndex /*effIndex*/)
+            void HandleHeal(ProcEventInfo & /*eventInfo*/)
             {
-                if (Unit* caster = GetOriginalCaster())
+                // Caster: the player(priest) that casters the prayer of mending
+                // Owner: the player that currently has the prayer of mending aura on him
+                Unit* owner = GetUnitOwner();
+                Aura* aura = owner->GetAura(SPELL_PRIEST_PRAYER_OF_MENDING_AURA);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1220]: "the aura being scripted" is accessible from `GetAura()`

File: src/server/scripts/Spells/spell_priest.cpp [hunk 12]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
-                        SetHitHeal(heal);
-                    }
+                    // Cast the spell to heal the owner
+                    caster->CastSpell(owner, SPELL_PRIEST_PRAYER_OF_MENDING_HEAL);
+
+                    // Only cast jump if stack is higher than 0
+                    if (aura->GetStackAmount() > 1)
+                        owner->CastSpell(owner, SPELL_PRIEST_PRAYER_OF_MENDING_JUMP, true, nullptr, nullptr, caster->GetGUID());
+                    else
+                        aura->Remove();
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1230]:
```suggestion
                    if (aura->GetStackAmount() > 1)
                        owner->CastSpell(owner, SPELL_PRIEST_PRAYER_OF_MENDING_JUMP, true, nullptr, nullptr, caster->GetGUID());

                    Remove();
```

You always want to remove the aura from original unit

File: src/server/scripts/Spells/spell_priest.cpp [hunk 13]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+        PrepareSpellScript(spell_pri_prayer_of_mending_SpellScript);
+
+        bool Validate(SpellInfo const* /*spellInfo*/) override
+        {
+            return ValidateSpellInfo({ SPELL_PRIEST_PRAYER_OF_MENDING_AURA });
+        }
+
+        void HandleEffectDummy(SpellEffIndex effIndex)
+        {
+            SpellEffectInfo const* effectInfo = GetEffectInfo(effIndex);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1176]: `GetEffectInfo(effIndex)` with the same `effIndex` as script hook argument is equivalent to no-arg `GetEffectInfo()` returning "current effect", it is also guaranteed to never return nullptr

File: src/server/scripts/Spells/spell_priest.cpp [hunk 14]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            if (!effectInfo)
+                return;
+
+            Unit* target = GetExplTargetUnit();
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1180]: Use `GetHitUnit()` in OnEffect** and **Hit hooks

File: src/server/scripts/Spells/spell_priest.cpp [hunk 15]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            if (!target)
+                return;
+
+            Unit* caster = GetCaster();
+            CastPrayerOfMendingAura(caster, target, effectInfo->BasePoints);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1185]: Use `GetEffectValue()`, not `effectInfo->BasePoints`, that gives you the value including all possible modifiers (as a general rule, you should never need to access raw effectInfo->BasePoints in any script)

File: src/server/scripts/Spells/spell_priest.cpp [hunk 16]
```diff
@@ -1122,38 +1125,168 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
 
-// 33110 - Prayer of Mending Heal
-class spell_pri_prayer_of_mending_heal : public SpellScriptLoader
+// Base class used by various prayer of mending spells
+class spell_pri_prayer_of_mending_SpellScriptBase : public SpellScript
+{
+public:
+    bool Load() override
+    {
+        _spellInfoHeal = sSpellMgr->GetSpellInfo(SPELL_PRIEST_PRAYER_OF_MENDING_HEAL, DIFFICULTY_NONE);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_priest.cpp:1134]: If you rely on existence of some spell, do the checking logic in Validate() to get startup logs

File: src/server/scripts/Spells/spell_priest.cpp (hunk 12 above)
Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp:1230]: Jump spell needs the aura to check the stack amount.

File: src/server/scripts/Spells/spell_priest.cpp (hunk 10 above)
Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp:1258]: > (minor) nullptr will be inside the target list
if you mean before, that is why there's a `!worldObject` check inside.
If you mean after, there shouldn't be since `!worldObject` is part of the return (hence if world object is null, it will reutrn true and will be removed)

File: src/server/scripts/Spells/spell_priest.cpp [hunk 17]
```diff
@@ -1253,28 +1253,73 @@ class spell_pri_prayer_of_mending_jump : public SpellScriptLoader
         {
             PrepareSpellScript(spell_pri_prayer_of_mending_jump_SpellScript);
 
+            enum class TargetPriority : uint8
+            {
+                InjuredPlayers,
+                InjuredPets,
+                FullHealthPlayers,
```
Comment (Faq) [inline src/server/scripts/Spells/spell_priest.cpp:1260]: where FullHealthPets? :)

Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp:1260]: If there woudl be, it would be last.
Can it be though? fully healthed pets without any fully healthed players or injured players?

File: src/server/scripts/Spells/spell_priest.cpp [hunk 18]
```diff
@@ -1122,38 +1125,214 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+                            default: return true;
+                        }
+                    });
+
+                    // choose one random target from targets
+                    if (targets.size() > 1)
+                    {
+                        uint32 chosen = urand(0, targets.size() - 1);
+                        uint32 idx = 0;
+                        targets.remove_if([chosen, &idx](WorldObject* worldObject) { return (chosen != idx++); });
```
Comment (illfated) [inline src/server/scripts/Spells/spell_priest.cpp:1312]: Let's hope this line is the last one for now (unused parameter).
```suggestion
                        targets.remove_if([chosen, &idx](WorldObject* /*worldObject*/) { return (chosen != idx++); });
```

Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp:1312]: yeah I saw that. Was trying to make it show up on my VS with cmake flags but couldn't; just did it manually, sadly.

Comment (illfated) [reply src/server/scripts/Spells/spell_priest.cpp:1312]: I know. It can be frustrating to deal with unused parameters/arguments reported by the checks (Travis & ci/circleci) since they stop checking the rest of the code when one is found.

File: src/server/scripts/Spells/spell_priest.cpp (hunk 10 above)
Comment (Shauren) [reply src/server/scripts/Spells/spell_priest.cpp]: fuck, i wrote that comment wrong. there was supposed to be "nullptr will never be inside the target list"

File: src/server/scripts/Spells/spell_priest.cpp (hunk 18 above)
Comment (Shauren) [reply src/server/scripts/Spells/spell_priest.cpp:1312]: There is a better way to do it
```
WorldObject* selected = Trinity::Containers::SelectRandomContainerElement(targets);
targets.clear();
targets.push_back(selected);
```

File: src/server/scripts/Spells/spell_priest.cpp (hunk 17 above)
Comment (matanshukry) [reply src/server/scripts/Spells/spell_priest.cpp:1260]: on second thought: it could be if the pet belongs to the person the aura was on, since he is removed regardless of his health. Will add it.

**Comment by mdX7** [comment]
just checked on retail, it appears that pets never get PoM unless its directly cast on them.
What I did:
1. My ghoul attacked something to get damage (I was at full health)
2. Priest buffed himself PoM and attacked a different mob to trigger PoM
3. I got PoM at full health, while my ghoul was < 100% hp

**Comment by Shauren** [comment]
I wonder if there a injured rule when in a party/raid group and "whatever" when not

**Comment by Warpten** [comment]
Priest main, fairly certain it's supposed to be a smart heal, otherwise it's kind of worthless

**Comment by matanshukry** [comment]
I changed it twice already, someone needs to make a decision or do a poll or w/e,
or merge it and create a different issue for wrong behaviour.

Either way currently it's working the way @mdX7 said on his last comment.

**Comment by mdX7** [comment]
so i just quickly checked a log from guild @ hungering destroyer for the first ~16s and it appears that the PoM is NOT having any priority in terms of hp - meaning it will not always jump to the player with the lowest hp.

Also it seems like that its jumping to an injured target (at least targets < 100% health, even if its just 99%). Didnt notice that its jumping to a full hp target yet (e.g. when it jumps away from tank and everyone else has full hp)

So I'd say:
- it will always prioritize players > pets
- injured players > full health players
- it jumps to a random injured player, even if that player has 99% and a different one 20%

What do you think about that @Warpten ?

**Comment by Fabi** [comment]
I'm pretty sure that it also jumps to players with full health even if there are players that are < 100% hp

File: src/server/scripts/Spells/spell_priest.cpp [hunk 19]
```diff
@@ -1122,38 +1125,207 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+                Pets,
+                None,
+            };
 
-            void HandleHeal(SpellEffIndex /*effIndex*/)
+            void OnTargetSelect(std::list<WorldObject*>& targets)
             {
-                if (Unit* caster = GetOriginalCaster())
+                // find best target
+                // Make sure too exclude the player that had the aura (caster in our case)
```
Comment (illfated) [inline src/server/scripts/Spells/spell_priest.cpp:1266]: Cosmetic/grammar comment details:
```suggestion
                // Find the best target.
                // Make sure to exclude player wearing the aura (caster in this case)
```

File: src/server/scripts/Spells/spell_priest.cpp [hunk 20]
```diff
@@ -1122,38 +1125,207 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+
+            bool Validate(SpellInfo const* /*spellInfo*/) override
+            {
+                return ValidateSpellInfo({ SPELL_PRIEST_PRAYER_OF_MENDING_HEAL });
+            }
+
+            void HandleHeal(ProcEventInfo & /*eventInfo*/)
+            {
+                // Caster: the player(priest) that cast the prayer of mending
+                // Target: the player that currently has the prayer of mending aura on him
```
Comment (illfated) [inline src/server/scripts/Spells/spell_priest.cpp:1219]: Cosmetic/readability:
```suggestion
                // Caster: player(priest) that cast Prayer of Mending
                // Target: player currently wearing Prayer of Mending aura
```

File: src/server/scripts/Spells/spell_priest.cpp [hunk 21]
```diff
@@ -1122,39 +1125,133 @@ class spell_pri_power_word_shield : public SpellScriptLoader
...
+            WorldObject* selected = Trinity::Containers::SelectRandomContainerElement(targets);
+            targets.clear();
+            targets.push_back(selected);
         }
+    }
+
+    void HandleJump(SpellEffIndex /*effIndex*/)
+    {
+        Unit* origCaster = GetOriginalCaster(); // the one that started the prayer of mending chain
+        Unit* target = GetHitUnit(); // the target we decided should jump the aura to
```
Comment (illfated) [inline src/server/scripts/Spells/spell_priest.cpp:1244]: This comment needs cleanup, poor sentence order.
```suggestion
        Unit* target = GetHitUnit(); // the target we decided the aura should jump to
```

**Comment by illfated** [comment]
Also: `unused variable 'owner'` after the last cleanup.

**Comment by illfated** [comment]
Codestyle: `enum PriestSpells` may need to be sorted alphabetically, either in this PR or later.

<details>
<summary>Lines sorted Lexicographically Ascending</summary>

```cpp
enum PriestSpells
{
    SPELL_PRIEST_ABSOLUTION                         = 33167,
    SPELL_PRIEST_ANGELIC_FEATHER_AREATRIGGER        = 158624,
    SPELL_PRIEST_ANGELIC_FEATHER_AURA               = 121557,
    SPELL_PRIEST_ANGELIC_FEATHER_TRIGGER            = 121536,
    SPELL_PRIEST_ARMOR_OF_FAITH                     = 28810,
    SPELL_PRIEST_ATONEMENT                          = 81749,
    SPELL_PRIEST_ATONEMENT_HEAL                     = 81751,
    SPELL_PRIEST_ATONEMENT_TRIGGERED                = 194384,
    SPELL_PRIEST_BLESSED_HEALING                    = 70772,
    SPELL_PRIEST_BODY_AND_SOUL                      = 64129,
    SPELL_PRIEST_BODY_AND_SOUL_DISPEL               = 64136,
    SPELL_PRIEST_BODY_AND_SOUL_SPEED                = 65081,
    SPELL_PRIEST_CURE_DISEASE                       = 528,
    SPELL_PRIEST_DISPEL_MAGIC_FRIENDLY              = 97690,
    SPELL_PRIEST_DISPEL_MAGIC_HOSTILE               = 97691,
    SPELL_PRIEST_DIVINE_AEGIS                       = 47753,
    SPELL_PRIEST_DIVINE_BLESSING                    = 40440,
    SPELL_PRIEST_DIVINE_WRATH                       = 40441,
    SPELL_PRIEST_GLYPH_OF_CIRCLE_OF_HEALING         = 55675,
    SPELL_PRIEST_GLYPH_OF_DISPEL_MAGIC              = 55677,
    SPELL_PRIEST_GLYPH_OF_DISPEL_MAGIC_HEAL         = 56131,
    SPELL_PRIEST_GLYPH_OF_LIGHTWELL                 = 55673,
    SPELL_PRIEST_GLYPH_OF_PRAYER_OF_HEALING_HEAL    = 56161,
    SPELL_PRIEST_GLYPH_OF_SHADOW                    = 107906,
    SPELL_PRIEST_GUARDIAN_SPIRIT_HEAL               = 48153,
    SPELL_PRIEST_ITEM_EFFICIENCY                    = 37595,
    SPELL_PRIEST_LEAP_OF_FAITH                      = 73325,
    SPELL_PRIEST_LEAP_OF_FAITH_EFFECT               = 92832,
    SPELL_PRIEST_LEAP_OF_FAITH_EFFECT_TRIGGER       = 92833,
    SPELL_PRIEST_LEAP_OF_FAITH_TRIGGERED            = 92572,
    SPELL_PRIEST_LEVITATE_EFFECT                    = 111759,
    SPELL_PRIEST_MANA_LEECH_PROC                    = 34650,
    SPELL_PRIEST_ORACULAR_HEAL                      = 26170,
    SPELL_PRIEST_PENANCE_R1                         = 47540,
    SPELL_PRIEST_PENANCE_R1_DAMAGE                  = 47758,
    SPELL_PRIEST_PENANCE_R1_HEAL                    = 47757,
    SPELL_PRIEST_PRAYER_OF_MENDING_AURA             = 41635,
    SPELL_PRIEST_PRAYER_OF_MENDING_HEAL             = 33110,
    SPELL_PRIEST_PRAYER_OF_MENDING_JUMP             = 155793,
    SPELL_PRIEST_REFLECTIVE_SHIELD_R1               = 33201,
    SPELL_PRIEST_REFLECTIVE_SHIELD_TRIGGERED        = 33619,
    SPELL_PRIEST_RENEWED_HOPE                       = 197469,
    SPELL_PRIEST_RENEWED_HOPE_EFFECT                = 197470,
    SPELL_PRIEST_SHADOWFORM_VISUAL_WITHOUT_GLYPH    = 107903,
    SPELL_PRIEST_SHADOWFORM_VISUAL_WITH_GLYPH       = 107904,
    SPELL_PRIEST_SHIELD_DISCIPLINE_ENERGIZE         = 47755,
    SPELL_PRIEST_SHIELD_DISCIPLINE_PASSIVE          = 197045,
    SPELL_PRIEST_SPIRIT_OF_REDEMPTION               = 27827,
    SPELL_PRIEST_STRENGTH_OF_SOUL                   = 197535,
    SPELL_PRIEST_STRENGTH_OF_SOUL_EFFECT            = 197548,
    SPELL_PRIEST_T9_HEALING_2P                      = 67201,
    SPELL_PRIEST_THE_PENITENT_AURA                  = 200347,
    SPELL_PRIEST_TWIN_DISCIPLINES_RANK_1            = 47586,
    SPELL_PRIEST_VAMPIRIC_EMBRACE_HEAL              = 15290,
    SPELL_PRIEST_VAMPIRIC_TOUCH_DISPEL              = 64085,
    SPELL_PRIEST_VOID_SHIELD                        = 199144,
    SPELL_PRIEST_VOID_SHIELD_EFFECT                 = 199145
    SPELL_PRIEST_VOID_SHIELD_EFFECT                 = 199145,
};
```

</details>

**Comment by matanshukry** [comment]
> Codestyle: `enum PriestSpells` may need to be sorted alphabetically, either in this PR or later.
> 
> Lines sorted Lexicographically Ascending
> edit: Forgot to remove the red line from PR source view. Removed now.

Didn't know that btw! cool.

**Comment by illfated** [comment]
Oh, and BTW, also codestyle/cosmetic: The last comma in the enum list should be removed, even though it does not matter for the compiler, strictly speaking. TC prefers to end the enum list without an ending comma.
