### PR TITLE
Core/Players: implement MOUNT_FLAG_SELF_MOUNT

### LINKED ISSUE #19758: Core/Spells: Sandstone Drake mount shows double visual model
**Description:** Sandstone Drakes do not work properly. Instead of you transforming into Sandstone Drake you transform into a Drake sitting on a Drake

**Current behaviour:** You transform into a Drake creature sitting on an identical Drake mount.

**Expected behaviour:**  You transform into only one Drake vehicle.
http://www.wowhead.com/spell=93326/sandstone-drake

**Steps to reproduce the problem:**

1. Get a Vial of the Sands (http://www.wowhead.com/item=65891/vial-of-the-sands)
     `  .additem 65891`
2. Consume the Vial by right clicking it
3. Mount Sandstone Drake

**Branch(es):** `master`

**TC rev. hash/commit:** #19297

**TDB version:**  720

**Operating system:** Windows 10

### LINKED ISSUE #20835: [Master] Sandstone Drake Visual Bug
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**
 (upload to https://gist.github.com/).
wowscrnshot_111017_174052

**Expected behaviour:**

No second Dragon

**Steps to reproduce the problem:**

1.Mount up

**Branch(es):**

Master

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/8654e4ec283aa56be195620891e6edb5d7c07840

**TDB version:**  720

**Operating system:** Windows

### PR DESCRIPTION
**Pull request by DoctorKraft**
**Changes proposed:**

-  Add flag `MOUNT_FLAG_SELF_MOUNT` used for mount with hidden displayid
For example :
[Sandstone Drake](http://www.wowhead.com/spell=93326/sandstone-drake)
[Obsidian Nightwing](http://www.wowhead.com/spell=121820/obsidian-nightwing)

DisplayID are always same in sniff

-  Remove uneeded enum and part spellscript (already called in aura) for Running Wild

**Target branch(es):**

- [X] master

**Issues addressed:**

Closes #20835
Closes #19758

**Tests performed:**

Tested IG & Build

**Known issues and TODO list:** (add/remove lines as needed)

- Nothing

### CODE REVIEW

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 1]
```diff
@@ -2565,7 +2567,7 @@ void AuraEffect::HandleAuraMounted(AuraApplication const* aurApp, uint8 mode, bo
         {
             vehicleId = creatureInfo->VehicleId;
 
-            if (!displayId || vehicleId)
+            if (!displayId)
```
Comment (DoctorKraft) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp]: Idk why `vehicleId` are needed for get a model. I have remove because he override `displayId `by creature model

**Comment by DJScias** [comment]
Hello there,

This seems to break the a few things due to you removing `SPELL_ALTERED_FORM`.

Specifically in these lines where it becomes undeclared:
https://github.com/TrinityCore/TrinityCore/pull/21558/files#diff-7f4f8fd9e7fa96bc9c9b16415f0e6e7bR2969
https://github.com/TrinityCore/TrinityCore/pull/21558/files#diff-7f4f8fd9e7fa96bc9c9b16415f0e6e7bR2996

**Comment by Shauren** [comment]
I restored the script you deleted - its blizzlike to cast that spell at cast start (doing this transforms player before cast bar finishes AND keeps worgen form after dismounting)

**Comment by DoctorKraft** [comment]
ok nice, thanks for extra info :)
