### PR TITLE
Core/Spells fix Arcane Missiles

### LINKED ISSUE #15902: [3.3.5]Spell:arcane-missiles
rev. https://github.com/TrinityCore/TrinityCore/commit/3b90b0368a019d47911062da6257555e88d17fda
branch 3.3.5 
This commit is break spell https://github.com/TrinityCore/TrinityCore/commit/246e568bbd1c741af7204e4a4941c113b7d63e60

Cast http://www.wowhead.com/spell=30451/arcane-blast ,proc http://wotlk.openwow.com/spell=44401/missile-barrage 
cast http://www.wowhead.com/spell=5143/arcane-missiles one charge. 
Normal 5 charges.

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- close #15902 

there is a visual bug in the github diff, it's:
`modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_CASTING_TIME, duration, spell);`

instead of:
`modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_DURATION_TIME, duration, spell);`

in ModSpellDurationTime

### CODE REVIEW

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -13010,7 +13010,7 @@ void Unit::ModSpellDurationTime(SpellInfo const* spellInfo, int32 & duration, Sp
 
     // called from caster
     if (Player* modOwner = GetSpellModOwner())
-        modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_DURATION, duration, spell);
+        modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_CASTING_TIME, duration, spell);
```
Comment (Shauren) [inline src/server/game/Entities/Unit/Unit.cpp]: This is the second time the same line bugs out, are you sure there isnt any non-printing character here?

Comment (DDuarte) [inline src/server/game/Entities/Unit/Unit.cpp]: Seems fine here:

Comment (tkrokli) [inline src/server/game/Entities/Unit/Unit.cpp]: at https://github.com/ShinDarth/TrinityCore/blob/fix/src/server/game/Entities/Unit/Unit.cpp this file looks like it ends (visual EOF) at the same point as this line change cuts here in the diff.

**Comment by ccrs** [comment]
tomorrow ill test this

**Comment by mynew4** [comment]
https://github.com/TrinityCore/TrinityCore/commit/246e568bbd1c741af7204e4a4941c113b7d63e60.diff

    // called from caster
    if (Player* modOwner = GetSpellModOwner())
        modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_DURATION, duration, spell);

We can see that is correct。
I used this patch, the same issue。

**Comment by tkrokli** [comment]
@mynew4 : notice that ShinDarth's suggestion is to change that line. See this diff instead:
```diff
@@ -13010,7 +13010,7 @@ void Unit::ModSpellDurationTime(SpellInfo const* spellInfo, int32 & duration, Sp

     // called from caster
     if (Player* modOwner = GetSpellModOwner())
-        modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_DURATION, duration, spell);
+        modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_CASTING_TIME, duration, spell);
 
     if (!(spellInfo->HasAttribute(SPELL_ATTR0_ABILITY) || spellInfo->HasAttribute(SPELL_ATTR0_TRADESPELL) || spellInfo->HasAttribute(SPELL_ATTR3_NO_DONE_BONUS)) &&
         ((GetTypeId() == TYPEID_PLAYER && spellInfo->SpellFamilyName) || GetTypeId() == TYPEID_UNIT))
```
BTW, my previous comment about the visual end-of-file (EOF) is not precise enough. The issue is constant for long files, regardless of repository. GitHub won't display the entire file in web view.

**Comment by mynew4** [comment]
@tkrokli   OK，The issue seems solved。

**Comment by tkrokli** [comment]
Very good, thanks for the feedback. Please do continue testing to see if it could break something else.

File: src/server/game/Entities/Unit/Unit.cpp (hunk 1 above)
Comment (Runico) [inline src/server/game/Entities/Unit/Unit.cpp]: https://patch-diff.githubusercontent.com/raw/TrinityCore/TrinityCore/pull/15907.diff

**Comment by ccrs** [comment]
proc works correctly now.
