### PR TITLE
Core/Spell: Divine Steed

### LINKED ISSUE #18380: [Master] Paladin Spell: Divine Steed (190784) - No Function
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://www.wowhead.com/spell=190784/divine-steed
**Current behaviour:** (Tell us what happens.)
Casting the paladin spell: divine steed shows animation but has no effect. No mount, no speed buff.
http://imgur.com/a/JJhQD
**Expected behaviour:** (Tell us what should happen instead.)
Casting the paladin spell: divine steed places paladin on a mount which he/she can ride for 3 seconds with a speed buff.
**Steps to reproduce the problem:**

1. .learn 190784
2. cast spell

**Branch(es):** 3.3.5 / master (Tell us which branch(es) this issue affects.)
master
**TC rev. hash/commit:**  
fb4097cc4a95c0c8ac9973ec1557b1ceb1cfdc65
**TDB version:**  
703.00
**Operating system:**  
Windows 8.1

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by DoctorKraft**
[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Fix Divine Steed (http://www.wowhead.com/spell=190784/divine-steed)

**Target branch(es):**

- [*] master

**Issues addressed:**

Closes #18380 

**Tests performed:**

Build & Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

- When you have aura and entering in combat, the aura dismount. i have searching function but not find. If anyone know, tell me
- I have also this spell (31726) in sniff but spell base have same visual so idk why is here !

### CODE REVIEW

File: sql/updates/world/master/9999_99_99_99_world.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+DELETE FROM `spell_script_names` WHERE `ScriptName`='spell_pal_divine_steed';
+INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
+('190784', 'spell_pal_divine_steed');
```
Comment (Aokromes) [inline sql/updates/world/master/9999_99_99_99_world.sql]: missing newline

Comment (DoctorKraft) [inline sql/updates/world/master/9999_99_99_99_world.sql]: Fixed :)

**Comment by streetrat** [comment]
31726 Summon Holy Mount Visual
probably the summon visual

**Comment by DoctorKraft** [comment]
I understand this, but same visual is also present on spell with SPELL_PALADIN_DIVINE_STEED_'RACE'

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 2]
```diff
@@ -340,6 +344,73 @@ class spell_pal_blessing_of_faith : public SpellScriptLoader
...
+        bool Validate(SpellInfo const* /*spellInfo*/) override
+        {
+            if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_HUMAN))
+                return false;
+            if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_DRAENEI))
+                return false;
+            if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_BLOODELF))
+                return false;
+            if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_TAUREN))
+                return false;
```
Comment (offl) [inline src/server/scripts/Spells/spell_paladin.cpp]:
```cpp
        bool Validate(SpellInfo const* /*spellInfo*/) override
        {
            if (!sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_HUMAN) ||
                !sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_DRAENEI) ||
                !sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_BLOODELF) ||
                !sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_TAUREN))
                return false;
            return true;
        }
```

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 3]
```diff
@@ -340,6 +344,73 @@ class spell_pal_blessing_of_faith : public SpellScriptLoader
...
+                    spell_id = SPELL_PALADIN_DIVINE_STEED_BLOODELF;
+                    break;
+                case RACE_TAUREN:
+                    spell_id = SPELL_PALADIN_DIVINE_STEED_TAUREN;
+                    break;
+                default:
+                    break;
+            }
+
+            if (spell_id)
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_paladin.cpp]: in which case (spell_id) condition evaluates to false ?

Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: yeah it's bad, it was a prevention for crash but now it's not correct because spell_id = SPELL_PALADIN_DIVINE_STEED_HUMAN

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 4]
```diff
@@ -340,6 +344,67 @@ class spell_pal_blessing_of_faith : public SpellScriptLoader
...
+                !sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_BLOODELF) ||
+                !sSpellMgr->GetSpellInfo(SPELL_PALADIN_DIVINE_STEED_TAUREN))
+                return false;
+            return true;
+        }
+
+        void HandleOnCast()
+        {
+            Unit* caster = GetCaster();
+            if (!caster)
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_paladin.cpp]: pointless check, GetCaster never returns nullptr in SpellScript

File: src/server/scripts/Spells/spell_paladin.cpp [hunk 5]
```diff
@@ -340,6 +344,67 @@ class spell_pal_blessing_of_faith : public SpellScriptLoader
...
+                return;
+
+            uint32 spell_id = SPELL_PALADIN_DIVINE_STEED_HUMAN;
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_paladin.cpp]: codestyle: variable naming, `spellId`

**Review by Shauren — CHANGES_REQUESTED** [review]

File: src/server/scripts/Spells/spell_paladin.cpp (hunk 4 above)
Comment (DoctorKraft) [inline src/server/scripts/Spells/spell_paladin.cpp]: it's only on AuraScript ?

**Comment by DoctorKraft** [comment]
Fixed
