### PR TITLE
Core/ObjectMgr: Remove ABORT() when faction template does not exist in DB

### LINKED ISSUE #20625: DB/Faction: Server crash on load
**Game Crashes on load:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1Compiles ok, but when loading
https://image.prntscr.com/image/rvLzCviCS5KJ236OV7_cPw.png
loading creature templates... 
d:\Games cores\wow\wow files 7.2.5\trinitycore\src\server\games\globals\objectmgr.cpp:874 in objectmyr::checkcreaturetemplate ABORTED

If i got back to Commits on Oct 13, 2017 020825902c066cee532f1b9a24205c196da2662d it compiles and runs ok so it is from Commits on Oct 15, 2017 

**Branch(es):**TrinityCore/TrinityCore

CHANGEME 7.2.5, master

**TC rev. hash/commit:** 55105c2f8733b5091aaf275e74c468a652afdc0e

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
2017-10-16_13:55:19 TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (worldserver-daemon)

**TDB version:**  TDB_full_720.00_2017_04_18

**Operating system:** windows server 2008 r2

### PR DESCRIPTION
**Pull request by DDuarte**
Set to 35 if it can't find the template

Closes #20625

### CODE REVIEW

File: src/server/game/Globals/ObjectMgr.cpp [hunk 1]
```diff
@@ -870,8 +870,8 @@ void ObjectMgr::CheckCreatureTemplate(CreatureTemplate const* cInfo)
     FactionTemplateEntry const* factionTemplate = sFactionTemplateStore.LookupEntry(cInfo->faction);
     if (!factionTemplate)
     {
-        TC_LOG_FATAL("sql.sql", "Creature (Entry: %u) has non-existing faction template (%u). This can lead to crashes, aborting.", cInfo->Entry, cInfo->faction);
-        ABORT();
+        TC_LOG_ERROR("sql.sql", "Creature (Entry: %u) has non-existing faction template (%u). This can lead to crashes, set to faction 35.", cInfo->Entry, cInfo->faction);
+        factionTemplate = sFactionTemplateStore.LookupEntry(35);
```
Comment (jackpoz) [inline src/server/game/Globals/ObjectMgr.cpp]: maybe add an assert here on the result ?

Comment (DDuarte) [reply src/server/game/Globals/ObjectMgr.cpp]: done

**Review by Shauren — APPROVED** [review]
