### PR TITLE
Core/Spells: Add flags to spell_area

### LINKED ISSUE #20934: spell_area QUEST_STATUS_REWARDED update
**Description:**
When player rewards a quest, related spell_area auras are immediately updated. In some cases, it is unwanted behavior to update auras right after quest is rewarded. Instead, they should be updated after re-entering area. (it was working like this some time ago)
Similar discussion was [here](https://github.com/TrinityCore/TrinityCore/pull/18146), related to phase_area update after QUEST_STATUS_REWARDED
[Video](https://youtu.be/LLatvrnML2g?t=1m24s) - after rewarding quest, the audience NPCs are there clapping and cheering. On TC they disappear because auras are updated.

**Current behaviour:**
Player rewards a quest and auras are immediately updated.

**Expected behaviour:**
In quests like [Stronger Than Reeds](http://www.wowhead.com/quest=29662), [Stronger Than Wood](http://www.wowhead.com/quest=29771) and [Stronger Than Bone](http://www.wowhead.com/quest=29782) it is necessary to keep the zone auras active until player leaves the area.
New item in disables table could solve this issue.

**Steps to reproduce the problem:**
1. go to the quest giver and reward quest
2. see that all NPCs that should stay there until player leaves area now disappear immediately

**Branch(es):** master

**TC rev. hash/commit:** b12b37058c863bcfecfefc965da45f31b604ee3b

**TDB version:**  TDB 720.00

**Operating system:** Win 7 x64

### PR DESCRIPTION
**Pull request by funjoker**
If the player is in zone/area and the entry has flag `SPELL_AREA_FLAG_AUTOREMOVE` then it will be removed (SendQuestUpdate).

**If the player is leaving zone/area it is always removed no matter if entry has flag. (I think this is the most blizzlike method)**

The flag SPELL_AREA_FLAG_AUTOCAST is handling same way like autocast bool.

**Changes proposed:**

-  Adding flags to control behavior
- Remove autocast bool (uses flag instead)
- Chance to add more flags to specify it even more

MYSQL PART:
```sql
ALTER TABLE `spell_area` CHANGE COLUMN `autocast` `flags` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3' AFTER `gender`;

UPDATE `spell_area` SET `flags` = `flags` | 2;
```

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes #20934

**Tests performed:** (Does it build, tested in-game, etc.)

### CODE REVIEW

File: sql/updates/world/master/9999_99_99_99_world .sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+ALTER TABLE `spell_area` CHANGE COLUMN `autocast` `flags` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3' AFTER `gender`;
+UPDATE `spell_area` SET `flags` = `flags` + 2;
```
Comment (joschiwald) [inline sql/updates/world/master/9999_99_99_99_world .sql]:
```sql
UPDATE `spell_area` SET `flags` = `flags` & 2;
```

Comment (Shauren) [reply sql/updates/world/master/9999_99_99_99_world .sql]: flags | 2, its intended here that they are added

Comment (joschiwald) [reply sql/updates/world/master/9999_99_99_99_world .sql]: yeah, thats what i meant ^^

Comment (funjoker) [reply sql/updates/world/master/9999_99_99_99_world .sql]: Ya ok :D.

**Review by Shauren — APPROVED** [review]

File: src/server/game/Spells/SpellMgr.h [hunk 2]
```diff
@@ -450,6 +450,12 @@ class TC_GAME_API PetAura
 };
 typedef std::map<uint32, PetAura> SpellPetAuraMap;
 
+enum SpellAreaFlag
+{
+    SPELL_AREA_FLAG_AUTOCAST = 0x1, // if has autocast, spell is applied on enter
```
Comment (tkrokli) [inline src/server/game/Spells/SpellMgr.h]: cosmetic/codestyle: align with the line below by adding 3 spaces before `= 0x1`

**Review by ghost — APPROVED** [review]
