### PR TITLE
Boss/Script: Vazruden_Fix

### LINKED ISSUE #21504: Scripts/Hellfire Ramparts: Nazan (Vazruden's Mount) movement, repeated evade & reset
**Description:**

This has been an issue for as long as i remember and is desperate for a re-write. I couldn't find an open ticket for it, so here goes.

Phase 1: Two trash mobs. Nothing special

Phase 2: Vazruden
Vazruden will come after you. Simple tank and spank. His mount (Nazan) will randomly shoot fireballs. These may leave fire behind.

Phase 3: Nazan lands
Abilities: AE breath attack. He will randomly fireball people which leaves behind the fire on the ground.
Nazan will land in the middle of the platform. It should have lots of magic resistance.

**Current behaviour:**

Phase 1 - Nazan's flight movement is a mix of flight and walking on air. It does at least allow you to continue.
Phase 2 - Working although ugly.
Phase 3 - Nazan decends but starts to evade and attack, over and over again to the point you have to .die it.

**Expected behaviour:**

Nazan flies in a circling motion around the central arena, comes to the center and drops Vazruden off for phase 2
Once complete, Nazan descends to the center and fights the third phase, after which the loot box is accessible.

**Steps to reproduce the problem:**

Go to Hellfire Ramparts and fight Nazan and Vazruden Bosses

**Branch(es):**

Only tested on 3.3.5 but probably both.

**TC rev. hash/commit:** 

TC rev. hash/commit: acdf7be

**TDB version:**  335.64

**Operating system:** Ubuntu 17:10

### PR DESCRIPTION
**Pull request by skipperheartbeat**
**Changes proposed:**
Fixes the unattackable Vazruden.  
-  These are fixes by Aokromes that have not yet been submit. Just got them all together into a pull.
-  
-  

**Target branch(es):** 3.3.5/
- [ ] 3.3.5

**Issues addressed:** Closes #21504
 
**Tests performed:** (Built and tested in game. It makes it playable to the same degree it was before it got broke.)

**Known issues and TODO list:** (Probably a full re-write :))

- [ ] 
- [ ]

### CODE REVIEW

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 1]
```diff
@@ -1,5 +1,6 @@
 /*
- * This file is part of the TrinityCore Project. See AUTHORS file for Copyright information
+ * Copyright (C) 2008-2019 TrinityCore <https://www.trinitycore.org/>
+ * Copyright (C) 2006-2009 ScriptDev2 <https://scriptdev2.svn.sourceforge.net/>
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: could you explain a bit more in detail the reason for these 2 line changes ?

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 2]
```diff
@@ -91,12 +92,12 @@ class boss_nazan : public CreatureScript
...
             }
 
-            void JustEngagedWith(Unit* /*who*/) override { }
+            void JustEngagedWith(Unit* who) override { }
 
             void IsSummonedBy(WorldObject* summoner) override
             {
                 if (summoner->GetEntry() == NPC_VAZRUDEN_HERALD)
-                    VazrudenGUID = summoner->GetGUID();
+		Vazruden = me->FindNearestCreature(NPC_VAZRUDEN, 5000);
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: we use 4 spaces instead of tabs. most IDEs support it in the settings.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 3]
```diff
@@ -193,7 +193,7 @@ class boss_nazan : public CreatureScript
                 uint32 Fly_Timer;
                 uint32 Turn_Timer;
                 bool flight;
-                ObjectGuid VazrudenGUID;
+                Creature* Vazruden;
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: never store a Creature* pointer. if a gm despawns it with a command, it will crash the server

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 4]
```diff
@@ -482,7 +490,7 @@ class npc_hellfire_sentry : public CreatureScript
                 Initialize();
             }
 
-            void JustEngagedWith(Unit* /*who*/) override { }
+            void JustEngagedWith(Unit* who) override { }
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: this will throw a warning about unused who variable

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 1 above)
Comment (Aokromes) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: for sure he is using outdated base.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 4 above)
Comment (skipperheartbeat) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: I didn't see any when i built it.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 1 above)
Comment (skipperheartbeat) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: I have no idea where they come from. Let me check on those. I've had this script around for a while though.

Comment (skipperheartbeat) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Wow .. never even saw them when i looked at the changes. I must be blind. Those two can be removed.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 4 above)
Comment (jackpoz) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: >[ 60%] Building CXX object src/server/scripts/CMakeFiles/scripts_outland.dir/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp.o
/home/circleci/project/src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:95:40: fatal error: unused parameter 'who' [-Wunused-parameter]
            void JustEngagedWith(Unit* who) override { }

from https://circleci.com/gh/TrinityCore/TrinityCore/5683?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 3 above)
Comment (skipperheartbeat) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: This one i don't have the knowledge to fix. Maybe someone can find a better way to do that.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 2 above)
Comment (skipperheartbeat) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Updated

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 4 above)
Comment (skipperheartbeat) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: OK .. Left those the same.

**Comment by illfated** [comment]
(Ref. **#21504** **Scripts/Hellfire Ramparts: Nazan (Vazruden's Mount) movement, repeated evade & reset** )

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 3 above)
Comment (jackpoz) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: well the way to fix it is to use the old code which you changed from ObjectGuid to Creature* . But if you don't know how to fix it, maybe you don't know what the changes in this PR do either ?
Maybe it's better if the original author of the changes opens the PR so he can implement the required changes.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 5]
```diff
@@ -349,7 +348,11 @@ class boss_vazruden_the_herald : public CreatureScript
                     if (Creature* Vazruden = me->SummonCreature(NPC_VAZRUDEN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
                         VazrudenGUID = Vazruden->GetGUID();
                     if (Creature* Nazan = me->SummonCreature(NPC_NAZAN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
+                    {
                         NazanGUID = Nazan->GetGUID();
+			Unit* player = Nazan->SelectNearestPlayer(60.00f);
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: fix indentation

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 6]
```diff
@@ -436,6 +439,10 @@ class boss_vazruden_the_herald : public CreatureScript
                                 return;
                             }
                         }
+			if (!(Nazan && Nazan->IsAlive()) && !(Vazruden && Vazruden->IsAlive()))
+			{
+				me->DisappearAndDie();
+			}
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: fix indentation

Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: (1 tab = 4 blank spaces, otherwise GitHub will show the tab width = 8 spaces)

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 7]
```diff
@@ -349,7 +348,11 @@ class boss_vazruden_the_herald : public CreatureScript
                     if (Creature* Vazruden = me->SummonCreature(NPC_VAZRUDEN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
                         VazrudenGUID = Vazruden->GetGUID();
                     if (Creature* Nazan = me->SummonCreature(NPC_NAZAN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
+                    {
                         NazanGUID = Nazan->GetGUID();
+			Unit* player = Nazan->SelectNearestPlayer(60.00f);
+			Nazan->AI()->AttackStart(player);
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: need proper indentation here too, replace tabs with spaces (maybe you need to configure your editor to convert tabs to spaces)

**Comment by jackpoz** [comment]
> * These are fixes by Aokromes that have not yet been submit. Just got them all together into a pull.

btw where there these fixes posted ?

**Comment by Aokromes** [comment]
xd he must be time traveler or from a parallel universe.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 3 above)
Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: I am guessing that this code was contributed to Aokromes' GitHub or GitLab repo, but considering the implication, that user might not want to contribute to the TC repository (as I said, I am just guessing, but it is based on previous experience from the TC issue tickets).

**Review by jackpoz — CHANGES_REQUESTED** [review]
Please revert the "ObjectGuid to Creature*" change

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 8]
```diff
@@ -193,7 +192,7 @@ class boss_nazan : public CreatureScript
                 uint32 Fly_Timer;
                 uint32 Turn_Timer;
                 bool flight;
-                ObjectGuid VazrudenGUID;
+                Creature* Vazruden;
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: This one.
```suggestion
                ObjectGuid VazrudenGUID;
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 9]
```diff
@@ -349,7 +348,11 @@ class boss_vazruden_the_herald : public CreatureScript
                     if (Creature* Vazruden = me->SummonCreature(NPC_VAZRUDEN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
                         VazrudenGUID = Vazruden->GetGUID();
                     if (Creature* Nazan = me->SummonCreature(NPC_NAZAN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
+                    {
                         NazanGUID = Nazan->GetGUID();
+			            Unit* player = Nazan->SelectNearestPlayer(60.00f);
+			            Nazan->AI()->AttackStart(player);
+		    }
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: fix this tabs + spaces mix into spaces.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 10]
```diff
@@ -349,7 +348,11 @@ class boss_vazruden_the_herald : public CreatureScript
                     if (Creature* Vazruden = me->SummonCreature(NPC_VAZRUDEN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
                         VazrudenGUID = Vazruden->GetGUID();
                     if (Creature* Nazan = me->SummonCreature(NPC_NAZAN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
+                    {
                         NazanGUID = Nazan->GetGUID();
+			            Unit* player = Nazan->SelectNearestPlayer(60.00f);
+			            Nazan->AI()->AttackStart(player);
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: tabs `->` spaces
```suggestion
                        Unit* player = Nazan->SelectNearestPlayer(60.00f);
                        Nazan->AI()->AttackStart(player);
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 11]
```diff
@@ -436,6 +439,10 @@ class boss_vazruden_the_herald : public CreatureScript
                                 return;
                             }
                         }
+            if (!(Nazan && Nazan->IsAlive()) && !(Vazruden && Vazruden->IsAlive()))
+            {
+                me->DisappearAndDie();
+			}
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Tabs `->` spaces
```suggestion
            }
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 12]
```diff
@@ -436,6 +439,10 @@ class boss_vazruden_the_herald : public CreatureScript
                                 return;
                             }
                         }
+            if (!(Nazan && Nazan->IsAlive()) && !(Vazruden && Vazruden->IsAlive()))
+            {
+                me->DisappearAndDie();
+            }
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: here needs fix indent.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 9 above)
Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Right, seems I forgot to include this line in my previous comments.
```suggestion
                    }
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 12 above)
Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Thanks. I forgot to compare with the previous indents above.

Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]:
```suggestion
                    if (!(Nazan && Nazan->IsAlive()) && !(Vazruden && Vazruden->IsAlive()))
                    {
                        me->DisappearAndDie();
                    }
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 13]
```diff
@@ -436,6 +439,10 @@ class boss_vazruden_the_herald : public CreatureScript
                                 return;
                             }
                         }
+                    if (!(Nazan && Nazan->IsAlive()) && !(Vazruden && Vazruden->IsAlive()))
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: not sure if it needs more spaces xd

Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Dang. I added 4 less spaces than there should have been. Fair enough, new fix incoming.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 14]
```diff
@@ -436,6 +439,10 @@ class boss_vazruden_the_herald : public CreatureScript
...
+                    {
+                        me->DisappearAndDie();
+                    }
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]:
```suggestion
                        if (!(Nazan && Nazan->IsAlive()) && !(Vazruden && Vazruden->IsAlive()))
                        {
                            me->DisappearAndDie();
                        }
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 15]
```diff
@@ -96,7 +96,7 @@ class boss_nazan : public CreatureScript
             void IsSummonedBy(WorldObject* summoner) override
             {
                 if (summoner->GetEntry() == NPC_VAZRUDEN_HERALD)
-                    VazrudenGUID = summoner->GetGUID();
+                Vazruden = me->FindNearestCreature(NPC_VAZRUDEN, 5000);
```
Comment (Aokromes) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: this needs 4 spaces?

Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]:
```suggestion
                    Vazruden = me->FindNearestCreature(NPC_VAZRUDEN, 5000);
```

**Comment by illfated** [comment]
Nice. The normal source view now displays the same content as in "Hide whitespace changes".

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 16]
```diff
@@ -96,7 +96,7 @@ class boss_nazan : public CreatureScript
             void IsSummonedBy(WorldObject* summoner) override
             {
                 if (summoner->GetEntry() == NPC_VAZRUDEN_HERALD)
-                    VazrudenGUID = summoner->GetGUID();
+                    Vazruden = me->FindNearestCreature(NPC_VAZRUDEN, 5000);
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: what is the meaning of this change ? what issue is it trying to fix and how is the new code fixing it ?

Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Wish I knew for certain, but could it be a distance issue, making the `summoner` not getting the GUID in the original code?

Comment (jackpoz) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: @illfated that's mostly speculation. If I have to merge this PR, I want someone with some C++ and TC knowledge to have checked it before, otherwise I might just take it as suggestion and debug the issue on my own.

The only case where that code returns something different is if there are 2+ NPC_VAZRUDEN, otherwise summoner is already what me->FindNearestCreature(NPC_VAZRUDEN, 5000) returns.

Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: OK, very well, fair point. I worry that the OP does not know these details either.

Comment (jackpoz) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: I would like to have this line reverted and know if the rest of the PR still solves any issue

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 17]
```diff
@@ -132,7 +132,6 @@ class boss_nazan : public CreatureScript
 
                 if (flight) // phase 1 - the flight
                 {
-                    Creature* Vazruden = ObjectAccessor::GetCreature(*me, VazrudenGUID);
```
Comment (jackpoz) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: this line is most likely needed

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 16 above)
Comment (illfated) [reply src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp]: Yes, this change causes the build to fail, so it is not a solution.

**Comment by jackpoz** [comment]
@skipperheartbeat any follow up on my comments ?

**Comment by illfated** [comment]
Seems to be no activity logged on GitHub since February 25 (18 days ago) for @skipperheartbeat .

**Comment by Tauriella** [comment]
Any News for this important Boss ?

**Comment by illfated** [comment]
> Any News for this important Boss ?

No, it does not look like @skipperheartbeat has been available, or at least done anything logged here on GitHub, since February 25 (38 days ago). Unless @skipperheartbeat posts any new updates or someone else asks to take over this work, it is unlikely that this PR will progress any further.

**Comment by offl** [comment]
First two changes makes zero sense
The issue this PR tries to solve:
>Nazan decends but starts to evade and attack, over and over again to the point you have to .die it.

P.S. maybe the problem lies here?
```c++
                        if (Unit* victim = SelectTarget(SELECT_TARGET_MINDISTANCE, 0))
```
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp#L144

**Comment by illfated** [comment]
Thanks, that looks like something worth checking out.
BTW, is this in any way related to https://github.com/TrinityCore/TrinityCore/issues/23026#issuecomment-489756473 ?
```cpp
Unit* closest = SelectTarget(SELECT_TARGET_MINDISTANCE, 0, 500.0f)
```

**Comment by offl** [comment]
It is more related to [this change](https://github.com/TrinityCore/TrinityCore/commit/f2cd721d5358f7febf36dc757f5e3e9693a6a7b6#diff-1e70986028695157dbb217ea1d37564cL387)
So if I'm not mistaken the way to engage NPC was changed from SelectTarget > AttackStart to DoZoneInCombat();

**Comment by illfated** [comment]
Good point. Even though `DoZoneInCombat();` was present before the commit you linked (https://github.com/TrinityCore/TrinityCore/commit/f2cd721d5358f7febf36dc757f5e3e9693a6a7b6), it makes me wonder if it is possible to use `DoZoneInCombat();` in the Vazruden / Nazan scenario. To me, it looks difficult to find good arguments for using it or where it could be used.

**Comment by offl** [comment]
Here https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp#L136-L151
Anyway if the solution from this PR works, no reason to find another way to fix it since this script is too old, complicated and needs a full rewrite

**Comment by illfated** [comment]
> Anyway if the solution from this PR works, no reason to find another way to fix it since this script is too old, complicated and needs a full rewrite

😉 https://github.com/TrinityCore/TrinityCore/issues/21504#issuecomment-368482044 😄

**Comment by jackpoz** [comment]
@offl would you like to make a PR with just the bare minimum changes required to fix the boss (or post them as suggestion using the github feature on this PR so I can approve them) ?

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 16 above)
Comment (offl) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:99]:
```suggestion
                    VazrudenGUID = summoner->GetGUID();
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp (hunk 17 above)
Comment (offl) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:135]: It is
P.S Applying suggestions on deleted lines in not supported.

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 18]
```diff
@@ -132,7 +132,6 @@ class boss_nazan : public CreatureScript
...
                     if (Fly_Timer < diff || !(Vazruden && Vazruden->IsAlive() && Vazruden->HealthAbovePct(20)))
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:135]: Fair point, but a workaround is to insert a new line on top of the following line (or below the preceding one):
```suggestion
                    Creature* Vazruden = ObjectAccessor::GetCreature(*me, VazrudenGUID);
                    if (Fly_Timer < diff || !(Vazruden && Vazruden->IsAlive() && Vazruden->HealthAbovePct(20)))
```

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 19]
```diff
@@ -132,7 +132,6 @@ class boss_nazan : public CreatureScript
 
                 if (flight) // phase 1 - the flight
                 {
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:134]:
```suggestion
                {
                    Creature* Vazruden = ObjectAccessor::GetCreature(*me, VazrudenGUID);
```
Not sure which one you like better, mark the one you don't want as Resolved (if you have got access to that feature button).

**Review by jackpoz — APPROVED** [review]

**Comment by jackpoz** [comment]
@offl I approved the code changes you and @illfated submitted. Could you please do a final test so I can safely merge this PR ? Thanks

File: src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp [hunk 20]
```diff
@@ -349,7 +349,11 @@ class boss_vazruden_the_herald : public CreatureScript
                     if (Creature* Vazruden = me->SummonCreature(NPC_VAZRUDEN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
                         VazrudenGUID = Vazruden->GetGUID();
                     if (Creature* Nazan = me->SummonCreature(NPC_NAZAN, VazrudenMiddle[0], VazrudenMiddle[1], VazrudenMiddle[2], 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 6000000))
+                    {
                         NazanGUID = Nazan->GetGUID();
+                        if (Unit* player = Nazan->SelectNearestPlayer(60.00f))
```
Comment (illfated) [inline src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:354]:
```cpp
/home/circleci/project/src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp:
  354:35:  fatal error: cannot initialize a variable of type 'Unit *' with an rvalue of type 'Player *'

                        if (Unit* player = Nazan->SelectNearestPlayer(60.00f))
                                  ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
(I don't remember how this one should be solved)

**Comment by offl** [comment]
@jackpoz I can't test it right now, sorry. Try to ask someone else

**Comment by illfated** [comment]
Maybe @TecDian has got time to test this?

**Comment by jackpoz** [comment]
anyone up to test this PR ?

**Comment by illfated** [comment]
Downloading the artifacts from the AppVeyor build now, but I still need to build the DB and add the dependency. (I know, I have been incredibly slow at rebuilding my local setup).

**Comment by Tauriella** [comment]
@illfated and @jackpoz 
I have testet your changes
It's works perfekt again.
Nice job :+1: 


[boss_vazruden_the_herald.zip](https://github.com/TrinityCore/TrinityCore/files/4497908/boss_vazruden_the_herald.zip)

**Comment by Tauriella** [comment]
Here the proof
WoWScrnShot_041920_002850
WoWScrnShot_041920_002839
WoWScrnShot_041920_002822
WoWScrnShot_041920_002804

**Comment by illfated** [comment]
@Tauriella : Thank you for testing this. You @mentioned me in your comment above, although I did not contribute to that change, but thank you for making me aware of your post anyway.
