### PR TITLE
Core/Scripts: Archmage Arugal event script

### LINKED ISSUE #17916: [3.3.5] Archmage Arugal not scripted
**Description:** Archmage Arugal in Shadowfang Keep attacks in melee and doesn't use spells.

**Current behaviour:** When you attack last boss in Shadowfang Keep, he attacks in melee and does not do anything else.

**Expected behaviour:** Arugal should cast spells and we should have a short Arugal Event upon entering the dungeon on each fresh instance start.

**Steps to reproduce the problem:**
1. enter Shadowfang Keep, or `.go creature id 4275` (.gm on if you want to get range for combat?)
2. attack Archmage Arugal
3. , you can also check  .npc info -- he doesn't have any ScriptName or AIName

**Branch(es)**: 3.3.5

**TC hash/commit:**  https://github.com/TrinityCore/TrinityCore/commit/19e757af5cb6bbde3f9263f0f4aaec87a7e0301c

**TDB version:**  TDB 335.61

**Operating system:**  Windows 8.1 x64

### PR DESCRIPTION
**Pull request by ghost**
**Changes proposed:**

Implement actual boss script for Archmage Arugal
- add yells used in boss event to DB
- use proper spells instead of only melee fighting
- add DataType in shadowfang_keep.h
- event scheduling in the script

by Riztazz

**Target branch(es):** **3.3.5** (the instance is different in retail and Archmage Arugal is not there)

**Issues addressed:** Closes #17916

**Tests performed:** (Does it build, tested in-game, etc)
- Builds without issues
- Works as intended in-game

**Known issues and TODO list:**
- [x] Check the visual details in-game to see if there is any unwanted behaviour
- [x] Needs feedback from TC developers (and others) for recommended improvements

### CODE REVIEW

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp [hunk 1]
```diff
@@ -205,6 +205,131 @@ class npc_arugal_voidwalker : public CreatureScript
...
+class boss_archmage_arugal : public CreatureScript
+{
+public:
+    boss_archmage_arugal() : CreatureScript("boss_archmage_arugal") { }
+
+    struct boss_archmage_arugalAI : public BossAI
+    {
+        boss_archmage_arugalAI(Creature* creature) : BossAI(creature, BOSS_ARUGAL) { }
+
+        void Reset() override
```
Comment (Keader) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: realy needed?

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp [hunk 2]
```diff
@@ -205,6 +205,131 @@ class npc_arugal_voidwalker : public CreatureScript
...
+            Talk(SAY_ARUGAL_AGGRO);
+            events.ScheduleEvent(EVENT_ARUGAL_CURSE, Seconds(7));
+            events.ScheduleEvent(EVENT_ARUGAL_TELEPORT, Seconds(15));
+            events.ScheduleEvent(EVENT_ARUGAL_VOID_BOLT, Seconds(1));
+            events.ScheduleEvent(EVENT_ARUGAL_THUNDERSHOCK, Seconds(10));
+        }
+
+        void AttackStart(Unit* who) override
+        {
+            if (!who)
```
Comment (Keader) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: realy necessary this check? who realy can be null?

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp [hunk 3]
```diff
@@ -205,6 +205,131 @@ class npc_arugal_voidwalker : public CreatureScript
...
+        {
+            if (!UpdateVictim())
+                return;
+
+            if (me->HasUnitState(UNIT_STATE_CASTING))
+                return;
+
+            events.Update(diff);
+
+            while (auto eventId = events.ExecuteEvent())
```
Comment (Keader) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: while (uint32 eventId = events.ExecuteEvent())

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp (hunk 1 above)
Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Check with Riztazz in #trinity (unless someone else wants to answer this)

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp (hunk 2 above)
Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Check with Riztazz in #trinity (unless someone else wants to answer this)

**Comment by tkrokli** [comment]
```
[2016.09.09, 20:32:51] <Riztazz> const uint32 spellsSize = 3;
[2016.09.09, 20:33:06] <Riztazz> and change this std::array<uint32, 3> arugalTeleportSpells =  to  std::array<uint32, spellsSize> arugalTeleportSpells =
[2016.09.09, 20:33:15] <Riztazz> or somewhere in enum
[2016.09.09, 20:33:38] <Riztazz> and this comment is pointless // rotate array, can be done with some kind of shuffle. Up to you to figure out what is best.
[2016.09.09, 20:33:45] <Riztazz> at this point, it was only useful in issue itself:P
```

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp (hunk 3 above)
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Yeah, we don't really do `auto`.

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp [hunk 4]
```diff
@@ -205,6 +204,126 @@ class npc_arugal_voidwalker : public CreatureScript
...
+                            break;
+                    }
+
+                    if (me->HasUnitState(UNIT_STATE_CASTING))
+                        return;
+                }
+                DoMeleeAttackIfReady();
+            }
+
+            uint32 _teleportSpells[NUM_TELEPORT_SPELLS];
```
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: don't call static and class field with the same name except a small _ difference, it's confusing and prone to errors.
doesn't it make more sense to avoid the whole static array idea and just initialize the class field to whatever you need to ?

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp [hunk 5]
```diff
@@ -205,6 +205,131 @@ class npc_arugal_voidwalker : public CreatureScript
...
+                            DoCast(target, SPELL_ARUGAL_CURSE);
+
+                        events.ScheduleEvent(eventId, Seconds(15));
+                        break;
+                    case EVENT_ARUGAL_TELEPORT:
+                    {
+                        auto spell = arugalTeleportSpells.front();
+                        DoCast(spell); 
+                        // rotate array, can be done with some kind of shuffle. Up to you to figure out what is best.
+                        std::rotate(arugalTeleportSpells.begin(), arugalTeleportSpells.begin() + 1, arugalTeleportSpells.end());
```
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: you CANNOT modify a global variable in EVERY class instance of boss_archmage_arugalAI without any locking mechanism, it will cause the very much dreaded race conditions. I strongly suggest you to spend some time reading up about "race condition" to fully understand what and why is bad.

Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: I wonder if Riztazz will have a constructive reply to this / a better solution.
It was after all something he wrote to pass time on a train station.

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp (hunk 4 above)
Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Good point, thanks for pointing it out.

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp (hunk 5 above)
Comment (Treeston) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: This is an outdated diff. The current version is thread safe assuming only one thread is accessing the creature at any given time (this is the case, each map is single-threaded).

Comment (Riztazz) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Derp, it was supposed to be within class, dunno why i did it like that. my excuse is it was written quickly while waiting for a train :P

Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: It always confuses me to see PRs opened by other people than the author of the code, I thought tkrokli wrote all the changes

Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Hmm. Point taken. Would it have made any difference if I had put "by
Riztazz" in caps + bold in the PR description & commit msg?

**Comment by cooler-SAI** [comment]
why not merge? all works good!

**Comment by jackpoz** [comment]
@cooler-SAI providing feedback to PRs helps understand if it works or if there might be some open issue, something like "I have been testing this PR in last week and got no player reports about it" will surely speed things up, just like your "all works good".

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp (hunk 4 above)
Comment (jackpoz) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: what happened to this commend ? was the code updated ? (github is still showing me the static teleportSpells variable)

Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: @Treeston : do you have a suggestion for a change/improvement in this part of the code?

**Comment by wrathix** [comment]
was awsome to test this with my gaming community, great work on Arugal

**Comment by SnapperRy** [comment]
Hope I didn't break anything. Arrays aren't my thing.

**Comment by Aokromes** [comment]
what's missing here?

**Comment by tkrokli** [comment]
Good question. I think the few issues I talked about in #trinity before opening this PR have been fixed, but
I will do my best to test this again today (solo). It would be really nice if someone could test this with a couple of friends, just to observe that it works as intended and does not need more fixing.

**Comment by Keader** [comment]
looking only c++ part, looks ready for me

**Comment by tkrokli** [comment]
Should I change `'author'` to be Riztazz instead of me for my main commits? To be effective, I guess it would need me to merge the PR, although there may be some other way in git that I don't know yet.

**Comment by cooler-SAI** [comment]
I tested with Friends - all works GOOD!!

File: src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp [hunk 6]
```diff
@@ -207,124 +206,124 @@ class npc_arugal_voidwalker : public CreatureScript
...
                     }
-                    case EVENT_ARUGAL_THUNDERSHOCK:
-                        DoCastAOE(SPELL_THUNDERSHOCK);
-                        events.ScheduleEvent(eventId, Seconds(30));
-                        break;
-                    case EVENT_ARUGAL_VOID_BOLT:
-                        DoCastVictim(SPELL_VOIDBOLT);
-                        events.ScheduleEvent(eventId, Seconds(5));
-                        break;
+
```
Comment (Riztazz) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: whats the point of that if?

Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Will remove it and push again.
Anything else I should remove too?

Comment (tkrokli) [inline src/server/scripts/EasternKingdoms/ShadowfangKeep/shadowfang_keep.cpp]: Should I remove the `return;` line too?

**Comment by tkrokli** [comment]
@SnapperRy , @Treeston : please take a quick look to check that I haven't messed up your changes. :-)
