### PR TITLE
Core/Spells: Fix Burning Rush

### LINKED ISSUE #19650: Core/Script The Talent Burning Rush has a critical mortal issue.
**Description:**

The Warlock's Talent "Burning Rush" (ID: 111400) learned at level 75 Talent's branch, has a critical mortal issue.

Burning Rush: Increases your movement speed by 50%, but also damages you for 4% of your maximum health every 1 sec. Movement impairing effects may not reduce you below 100% of normal movement speed. Last until cancelled.

**Current behaviour:**

The Talent increases the movement speed propperly, but can not be cancelled, it keeps damaging you until death.

**Expected behaviour:**

Once you activate Burning Rush, you should be able to cancel it at any time.

**Steps to reproduce the problem:**

1. Create a Warlock character.
2. Reach level 60 And choose the talent "Burning Rush" from level 60 talent's branch.
3. Use Burning Rush, then try to cancel it.

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=111400/burning-rush

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement warlock talent Burning Rush

**Issues addressed:**

Closes #19650

**Tests performed:**

Tested in-game

### CODE REVIEW

File: src/server/game/Spells/SpellInfo.cpp [hunk 1]
```diff
@@ -4566,6 +4566,15 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, SpellEffectInfo const& ef
             if ((spellInfo->SpellFamilyFlags[0] & 0x20200000) != 0)
                 return false;
             break;
+        case SPELLFAMILY_WARLOCK:
+            switch (spellInfo->Id)
+            {
+                case 111400: // Burning Rush
+                    return true;
```
Comment (mdX7) [inline src/server/game/Spells/SpellInfo.cpp:4573]: add `SPELL_ATTR4_AURA_IS_BUFF` in `SpellMgr.cpp` instead

Comment (aquadeus) [reply src/server/game/Spells/SpellInfo.cpp]: done
