### PR TITLE
[Needs testing] Core/Spells: Creature spellcast facing

### LINKED ISSUE #2947: [Spell] Slime Spray
Rotface ability Slime Spray (id: 69508) isn't hitting the original trigger's cone, but he hits a cone in front of him, given by the tank usually.

I don't know if it's the same issue as Ick's spray toxic waste.

Rev: e67a33eaaa5e1c1f46ba268e02254a087b0f2ec3

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65769-spell-slime-spray?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #15393: [3.3.5a] Utgarde Keep: Ingvar the Plunderer - Smash / Dark Smash
Branch 3.3.5a, Revision 0cdf3b7a73d8, TDB 335.59

While testing the "Ingvar the Plunderer" encounter in Utgarde Keep, I encountered two issues related to the behavior of his Smash/Dark Smash abilities:
*Reference: http://www.wowhead.com/npc=23954/ingvar-the-plunderer#comments*

**1)** When casting "Smash" (during phase 1) and "Dark Smash" (during phase 2), the damage cone is projected in the direction of its target's current position when the cast finishes. Expected behavior would be to have it project in the direction of its target's position when the cast starts. This means dodging the ability is impossible for the tank, and attempting to do so will likely make the boss smack your party instead.
**2)** If Ingvar is not moved between casts of "Smash" (phase 1) or "Dark Smash" (phase 2), he will face the direction he was facing during the previous cast, even if his target is no longer positioned in that direction. This makes the visual facing of the model inconsistent with the direction of the damage cone.

**Reproduction steps for issue 1:**
1a) Engage Ingvar
1b) Tank Ingvar until he begins channeling Smash/Dark Smash
1c) Run through Ingvar
1d) The damage cone will be projected towards you, hitting you and anyone standing near/behind you. Expected behavior would be the damage cone being projected towards where you were when Ingvar started casting.

**Reproduction steps for issue 2:**
2a) Engage Ingvar
2b) Tank Ingvar until he begins channeling Smash/Dark Smash once. Ensure you are in melee range of Ingvar so he does not move.
2c) Run through Ingvar so he turns to face you. Remain in melee range of him so he does not move.
2d) The next time Ingvar begins channeling Smash/Dark Smash, he will visually turn away from you (towards the position you were in for step 2b) throughout the channel. Expected behavior would be Ingvar channeling in your direction.

**In addition, a minor (what I believe to be) issue, but I cannot present any non-anecdotal evidence for this:**
3) In my recollection of Retail behavior, Ingvar would always cast a spell (not sure which one, either roar or smash) right after resurrecting for phase two.

**And a minor visual thing:**
4) Ingvar displays the level-up animation when transitioning to phase two on heroic. Not sure how we could suppress this, as P1 Ingvar is a level 81, and P2 Ingvar is a level 82, which will always (?) trigger a level up animation when the client receives a changed level for the guid.

### PR DESCRIPTION
**Pull request by Treeston**
**This PR needs testing to ensure it performs as expected in various fringe cases. Any feedback is much appreciated.**

Core/Spells:
- Fixes creatures turning just before a spellcast finishes and smacking players with supposedly-unavoidable damage. Fixes and closes #15393, #10803, and probably others.
- Fixes visual effects not lining up with the correct target for spells that have their visual aligned with the caster's orientation (examples: Anub'rekhan Impale, Ingvar's Smash/Dark Smash, etc.). Fixes and closes #2947 and probably a bunch of others, including the aforementioned #15393 and #10803.
- Creatures' displayed target now properly matches the unit they are targeting with spells for a split second (blizzlike). This is necessary to get proper client-side orientation.

### CODE REVIEW

File: src/server/game/Entities/Creature/Creature.cpp [hunk 1]
```diff
@@ -2607,23 +2608,52 @@ void Creature::SetDisplayId(uint32 modelId)
...
 void Creature::SetTarget(ObjectGuid guid)
 {
-    if (!_focusSpell)
+    if (!IsFocusing())
         SetGuidValue(UNIT_FIELD_TARGET, guid);
 }
 
 void Creature::FocusTarget(Spell const* focusSpell, WorldObject const* target)
 {
+    /*if(GetEntry() == 15956)
```
Comment (MitchesD) [inline src/server/game/Entities/Creature/Creature.cpp]: I guess this should not be part of PR :D

Comment (Treeston) [inline src/server/game/Entities/Creature/Creature.cpp]: > Note: Yes, there's a bunch of commented debug statements in there. I am aware.

;)

File: src/server/game/Entities/Creature/Creature.cpp [hunk 2]
```diff
@@ -2632,14 +2662,14 @@ void Creature::ReleaseFocus(Spell const* focusSpell)
...
-    else
-        SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
+    _focusSpell = nullptr;
+    _focusDelay = getMSTime(); // don't allow re-target right away to prevent visual bugs
 
     if (focusSpell->GetSpellInfo()->HasAttribute(SPELL_ATTR5_DONT_TURN_DURING_CAST))
-        ClearUnitState(UNIT_STATE_ROTATING);
+        ClearUnitState(UNIT_STATE_CANNOT_TURN);
+
+    /*if (GetEntry() == 15956)
```
Comment (MitchesD) [inline src/server/game/Entities/Creature/Creature.cpp]: the same here :D

**Comment by Golrag** [comment]
@Treeston does this PR replaces https://github.com/TrinityCore/TrinityCore/pull/15546 ? :)

**Comment by Treeston** [comment]
@Golrag at a glance, yes - it fixes everything that is fixed by that PR, in addition to client visuals.

**Comment by Golrag** [comment]
Good ! Will close mine then ! :)

**Comment by Treeston** [comment]
I've been running this PR on our f&f server for the last week without issue, but this is obviously not sufficient.

This does, however, mean that there are no _glaring_ bugs left, in case this convinces anyone to give it a spin. Thanks!

**Comment by Golrag** [comment]
@Treeston mmh, He still faces the tank instead of the spelltarget while casting. https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L12768 should be removed imo. Take a look at my PR I fixed it there :p

**Comment by Treeston** [comment]
Yup, we do SetInFront in Attack or somewhere anyway.

**Comment by Treeston** [comment]
@Golrag I cannot seem to reproduce this behavior. Could you elaborate?

**Comment by Golrag** [comment]
So, you will need at least 2 players.
One player who is tanking, and the other one will be the one focused by the spell.
Creature casts spell on not-tank player. (example: you can try .cast back 10181)
Creature's orientation (server side) switch to the not-tank player. This is good.
But on the next Unit::SelectVictim server side orientation is back to the tank. This is not good.

**Comment by Treeston** [comment]
Ah, yes, good point. Server side orientation will indeed switch.

**Comment by ccrs** [comment]
Is there any todo left or did you have any devs feedback?

**Comment by Aokromes** [comment]
We need people to test it.

**Comment by ccrs** [comment]
I'll indeed test it, just wondering if there is any todo or some thoughts from core devs.

**Comment by ccrs** [comment]
maybe this needs to be updated too.
````c++
bool CreatureAI::UpdateVictimWithGaze()
{
...
    if (Unit* victim = me->SelectVictim())
        AttackStart(victim);
}
````

**Comment by Treeston** [comment]
@ccrs: Good catch! Fixed.

File: src/server/game/Spells/Spell.cpp [hunk 3]
```diff
@@ -2936,6 +2938,27 @@ void Spell::prepare(SpellCastTargets const* targets, AuraEffect const* triggered
     else
         m_casttime = m_spellInfo->CalcCastTime(this);
 
+    if (m_caster->GetTypeId() == TYPEID_UNIT) // _UNIT actually means creature. for some reason.
```
Comment (ccrs) [inline src/server/game/Spells/Spell.cpp]: _UNIT means Unit; GetTypeId returns the m_objectTypeId of the object, that is Player.

Comment (Shauren) [inline src/server/game/Spells/Spell.cpp]: pfffffffft, please. dont try to lecture people if you dont know yourself

Comment (Treeston) [inline src/server/game/Spells/Spell.cpp]: @ccrs Check Entities/Object/Object.h for the definition of WorldObject::ToCreature().

Comment (ccrs) [inline src/server/game/Spells/Spell.cpp]: y would i even bother

Comment (Treeston) [inline src/server/game/Spells/Spell.cpp]: @ccrs: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Object/Object.h#L188
```cpp
Creature* ToCreature() { if (GetTypeId() == TYPEID_UNIT) return reinterpret_cast<Creature*>(this); else return NULL; }
```

**Comment by ccrs** [comment]
This seems to break Lanathel bite with 4 or more players.

**Comment by Treeston** [comment]
I will investigate

**Comment by Treeston** [comment]
Rebased, and tracked down & fixed the issue @ccrs reported above.

@ccrs: Could you re-test and ensure this is no longer present in the latest PR rev? Thanks a lot for the help with testing!

**Comment by ccrs** [comment]
Sure, its nice to open 4 different clients to test this XD

**Comment by Treeston** [comment]
Guess [how I did it](http://i.imgur.com/htaRDQe.jpg) ;)

File: src/server/game/Spells/Spell.cpp [hunk 4]
```diff
@@ -2971,18 +2994,14 @@ void Spell::prepare(SpellCastTargets const* targets, AuraEffect const* triggered
         }
 
         m_caster->SetCurrentCastSpell(this);
-        SendSpellStart();
-
-        // set target for proper facing
-        if ((m_casttime || m_spellInfo->IsChanneled()) && !(_triggeredCastFlags & TRIGGERED_IGNORE_SET_FACING))
-            if (m_caster->GetTypeId() == TYPEID_UNIT && m_targets.GetObjectTarget() && m_caster != m_targets.GetObjectTarget())
-                m_caster->ToCreature()->FocusTarget(this, m_targets.GetObjectTarget());
+        if(!m_isDelayedInstantCast)
```
Comment (ccrs) [inline src/server/game/Spells/Spell.cpp]: codestyle

**Comment by ccrs** [comment]
Lanathel bite is no longer bugged :+1:

File: src/server/game/Spells/Spell.cpp (hunk 4 above)
Comment (tkrokli) [inline src/server/game/Spells/Spell.cpp]: missing space after `if` could trigger a Coverity warning if left unchanged.

Comment (Treeston) [inline src/server/game/Spells/Spell.cpp]: yes, yes, i'm aware

**Comment by ccrs** [comment]
Maybe add an exception to player controlled vehicles, if u use spells like http://www.wowhead.com/spell=62575/shield-breaker camera is moved.

**Comment by Treeston** [comment]
Yup, good thinking @ccrs. Fixed.

**Comment by Treeston** [comment]
@ccrs could you check if this actually fixes the issue on your end?

**Comment by ccrs** [comment]
Check strange movements on onyxia's air phase while casting fireball.
Also anubarak second phase has some weird facing movements.

**Comment by Killyana** [comment]
About Onyxia I think it's not related to this PR, test it in clean install and you will see she's freezing in the air.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 5]
```diff
@@ -1956,6 +1957,9 @@ void Unit::AttackerStateUpdate (Unit* victim, WeaponAttackType attType, bool ext
     if (attType != BASE_ATTACK && attType != OFF_ATTACK)
         return;                                             // ignore ranged case
 
+    if (!IsControlledByPlayer())
```
Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.cpp]: m_ControlledByPlayer is set on any charm type, i guess u should use ispossessed().

Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.cpp]: correction, HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED).

UNIT_STATE_POSSESSED is only set on CHARM_TYPE_POSSESS but UNIT_FLAG_PLAYER_CONTROLLED is set on both CHARM_TYPE_VEHICLE and CHARM_TYPE_POSSESS

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp [hunk 6]
```diff
@@ -39,6 +39,9 @@ void TargetedMovementGeneratorMedium<T, D>::_setTargetLocation(T* owner, bool up
     if (owner->GetTypeId() == TYPEID_UNIT && !i_target->isInAccessiblePlaceFor(owner->ToCreature()))
         return;
 
+    if (owner->GetTypeId() == TYPEID_UNIT && owner->ToCreature()->IsFocusing(nullptr, true))
+        return;
```
Comment (ccrs) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: does this break movement, or does it continue when focus is released ?

File: src/server/game/Entities/Unit/Unit.cpp (hunk 5 above)
Comment (Treeston) [inline src/server/game/Entities/Unit/Unit.cpp]: Vehicles should never turn without player input anyway? Not sure what change you want here.

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 6 above)
Comment (Treeston) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: Movement continues when focus is released.

**Comment by Golrag** [comment]
Tested slime spray, still having issues tho :s
Target is not updated when he is casting it so he keeps focusing the tank while clientside he faces the trigger.

http://puu.sh/lTM7V/aea7c2f441.jpg
http://puu.sh/lTM8t/17ef961d1f.jpg

**Comment by Treeston** [comment]
Don't use .cast back, it forces the mob to cast at you.

File: src/server/game/Entities/Unit/Unit.cpp (hunk 5 above)
Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.cpp]: Charms with PetAI have also ````m_ControlledByPlayer = true```` and I think Pets must use this system too ^^

**Comment by Shauren** [comment]
Also you need to have Rotface cast it during the encounter, there are more things involved than just the spell cast.

File: src/server/game/Entities/Unit/Unit.cpp (hunk 5 above)
Comment (Treeston) [inline src/server/game/Entities/Unit/Unit.cpp]: I see, that makes sense.

Comment (ccrs) [inline src/server/game/Entities/Unit/Unit.cpp]: be aware to write the typeid check again :)

**Comment by chaodhib** [comment]
I found a bug introduced by this PR. I'm not sure whether I should put the explanation here or elsewhere? in a new bug ticket? Anyway, here it goes:

When a unit casts a spell, `SendUpdateToPlayer(player)` is called here: https://github.com/TrinityCore/TrinityCore/pull/15641/files#diff-f3f953a63e2a008d22de69cb68f735c4R2726

From what I understood, it updates players of the new `UNIT_FIELD_TARGET` of the caster mob. The problem is that the wrong packet is (sometimes) sent. `SendUpdateToPlayer()` calls `BuildCreateUpdateBlockForPlayer()` to construct the update packet.

The problem lies in the type of update sent. A `UpdateType: CreateObject1` is sent instead of an `UpdateType: Values`. In other words, the packet sent will re-spawn the caster mob from scratch instead of updating it. Visually, it looks like the mob is jumping, pretty weird stuff.

**Comment by chaodhib** [comment]
I might be wrong but I'm having doubts on part of this PR. I think the third part ("Creatures' displayed target now properly matches the unit they are targeting with spells for a split second (blizzlike)") should be not be in the 3.3.5 branch. I think that aspect was added in another expansion.

Here is why: In Naxxramas, when Gluth eats a zombie, this is the chain of events that occurs: 
* he looses focus of its main target
* he charges the zombie
* he casts an instant kill spell to kill the zombie
* he returns on its main target

Here s a video on 3.X (at 3:40):
https://www.youtube.com/watch?v=2SOAxujWmUs#t=27
Here is a video on 4.X:
https://www.youtube.com/watch?v=1WVClNQeqPs
Here is a video on 5.X: (between 4:10 & 5:10)
https://www.youtube.com/watch?v=3BC9KpeN2UM

Notice how on 3.X & 4.X, Gluth doesn't target at any moment the zombie he is killing, even when he is casting the spell. Notice how this is no longer true in 5.X.

**Comment by Shauren** [comment]
You should find a different wotlk video, cant see shit in that first person view...

**Comment by chaodhib** [comment]
@Shauren 
The UI is hard to read but it's still manageable. I have marked the target's target of the player:
show target s target

This is before eating: (Gluth's target is the tank)
before

This is during: (Gluth has no target)
during

This is after (Gluth's target is the tank once more)
after

I will try to find other examples on other bosses.

**Comment by MrSmite** [comment]
At the moment just as in issue https://github.com/TrinityCore/TrinityCore/issues/16824, NPCs will briefly drop target after casting which was not normal behavior. Perhaps for certain spells but not all of them.

Example: [Kobold Miner](http://wotlk.openwow.com/npc=40) will drop then reacquire their target after casting [Pierce Armor](http://wotlk.openwow.com/spell=6016)

**Comment by Treeston** [comment]
I'll look into that one, that sounds like a bug.

**Comment by Treeston** [comment]
@MrSmite 1cf1d4a should fix most (all?) cases of wonkyness with displayed target while casting.

**Comment by MrSmite** [comment]
@Treeston Thanks, I'll try to pull / compile it this weekend.
