### PR TITLE
Core/ArenaTeam: Remove queues of members if a character is removed

### LINKED ISSUE #21487: [3.3.5] Core/Arena: Enter in rated match without team
**Description:**

You can enter in Rated Arena without team, maybe this can cause some exploit or crash, I don't know

**Expected behaviour:**

I do not know what the proper functioning will be.
Maybe you can't leave Team if you are in rated queue

**Steps to reproduce the problem:**

1. Log 4 players in game
2. Create 2 Arena Teams
3. Join with 2 Teams to rated queue
4. Before enter in Arena, leave Team
5. Enter in Arena

**Branch(es):** 3.3.5

**TC rev. hash/commit:** 31f14dadde46445ae7e3e0330a3811b185bd8a61

**TDB version:**  TDB335.64

**Operating system:** Debian

### PR DESCRIPTION
**Pull request by Gooyeth**
**Changes proposed:**

If a character is removed of arena team, then the queues are removed of members.

**Target branch(es):** 3.3.5

**Issues addressed:** Closes #21487

**Tests performed:** Build

PR closed: #21490

### CODE REVIEW

**Comment by Gooyeth** [comment]
@Jildor: Test, please.

**Comment by Jildor** [comment]
I like more another PR :(

Test:
When you join to Rated match queue and call to enter in the arena, if a member leave team, you can't enter in the arena although you press enter button (any member) and you still in arena queue bugged until you relog.
The another team can enter in the Arena.

**Comment by Gooyeth** [comment]
@Jildor: Try again, please

**Comment by Jildor** [comment]
Now I like it :wink:

But I can't test it until tomorrow, I'm sorry :disappointed:

**Comment by Jildor** [comment]
Test:
All ok except when you are in Rated Queue without call to enter in Arena, if you leave team, you still get bugged queue untill you relog.

**Comment by Gooyeth** [comment]
@Jildor, now should be solved :smile:

Test again, please.

**Comment by Jildor** [comment]
Tested, now yes, all ok 👍

File: src/server/game/Battlegrounds/ArenaTeam.cpp [hunk 1]
```diff
@@ -317,6 +318,25 @@ void ArenaTeam::DelMember(ObjectGuid guid, bool cleanDb)
     // Remove member from team
     for (MemberList::iterator itr = Members.begin(); itr != Members.end(); ++itr)
     {
+        // Remove queues of members
+        if (Player* player = ObjectAccessor::FindPlayer(itr->Guid))
```
Comment (jackpoz) [inline src/server/game/Battlegrounds/ArenaTeam.cpp]: I wonder what happens if one player is being teleported to the arena while the other leaves the party

Comment (tkrokli) [reply src/server/game/Battlegrounds/ArenaTeam.cpp]: Deadlock or nullptr exception, maybe.

File: src/server/game/Battlegrounds/ArenaTeam.cpp [hunk 2]
```diff
@@ -315,25 +315,30 @@ void ArenaTeam::SetCaptain(ObjectGuid guid)
 
 void ArenaTeam::DelMember(ObjectGuid guid, bool cleanDb)
 {
+    Player* player = ObjectAccessor::FindPlayer(guid);
```
Comment (Gooyeth) [inline src/server/game/Battlegrounds/ArenaTeam.cpp]: I would not know if it would be correct FindConnectedPlayer

Comment (Gooyeth) [inline src/server/game/Battlegrounds/ArenaTeam.cpp]: @jackpoz, I would not know if it would be correct FindConnectedPlayer

File: src/server/game/Battlegrounds/ArenaTeam.cpp (hunk 1 above)
Comment (Gooyeth) [reply src/server/game/Battlegrounds/ArenaTeam.cpp]: @jackpoz, this seems better to you: https://github.com/TrinityCore/TrinityCore/pull/21491/commits/425b8a82c495e0cf49ad2b4c8b214eeaae00e11f?

File: src/server/game/Battlegrounds/ArenaTeam.cpp (hunk 2 above)
Comment (Jildor) [reply src/server/game/Battlegrounds/ArenaTeam.cpp]: @jackpoz can you review it please?

File: src/server/game/Battlegrounds/ArenaTeam.cpp [hunk 3]
```diff
@@ -314,9 +315,33 @@ void ArenaTeam::SetCaptain(ObjectGuid guid)
...
+    
     // Remove member from team
     for (MemberList::iterator itr = Members.begin(); itr != Members.end(); ++itr)
     {
+        // Remove queues of members
+        if (Player* playerMember = ObjectAccessor::FindConnectedPlayer(itr->Guid))
+        {
+            if (player && player->GetGroup() && playerMember->GetGroup() && player->GetGroup()->GetGUID() == playerMember->GetGroup()->GetGUID())
```
Comment (jackpoz) [inline src/server/game/Battlegrounds/ArenaTeam.cpp]: you could move the "player && player->GetGroup()" check outside of the for loop, maybe saving the group in a variable, so avoid the loop totally if the player is not in group.

File: src/server/game/Battlegrounds/ArenaTeam.cpp (hunk 2 above)
Comment (Gooyeth) [reply src/server/game/Battlegrounds/ArenaTeam.cpp]: @jackpoz: Possibly the player is removed by the leader, while the player loads screen.

**Comment by Gooyeth** [comment]
@jackpoz: Something to be corrected or comments?
