### PR TITLE
Core/Spells Implemented SpellScripts Needed for Achievement Pilgrim's…

### LINKED ISSUE #8352: [3.3.5][6.x] Core/Achievement: Pilgrim's Paunch
Hi Tc.

this is the last achievement  that doesn't work in the world event: pilgrim's bounty

the problem is that all works fine and you get "the spirit of sharing" but when u look at the achiev if you get it complete you see it as uncompleted it just dont mark the city where you tried to do the achievement.
Wowhead link:http://www.wowhead.com/achievement=3557

here some video from youtube to see how it need to work:http://www.youtube.com/watch?v=mDi33abkHtw  

Tnx alot.

Tbd:335.11.47+

Hash:ba20aa8 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63795-pilgrim-s-paunch-achievement?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sirikfoll**
… Paunch
Added spells to the chairs, 
Now is possible to eat the foods, 
is possible to obtain the buff Spirit of Sharing by eating 5 of each food,
fixed Achievement Pilgrim's Paunch
Based on https://github.com/gc/TrinityCore/commit/ec46d922c945107628177debfcdd4e5732f55ee2

It works, open to suggestions

Closes #8352

### CODE REVIEW

**Comment by tkrokli** [comment]
Glad to see that you're working on this. Seems you have had some minor issues getting the last ones to pass travis testing, though. Not sure if the SQL version will be needed if this version works.

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 1]
```diff
@@ -410,6 +411,90 @@ class spell_pilgrims_bounty_buff_food : public SpellScriptLoader
...
+                        if (Player* player = target->ToPlayer())
+                        {
+                            player->CastSpell(player, SPELL_ON_PLATE_EAT_VISUAL, true);
+                            caster->CastSpell(player, _spellId, true, NULL, NULL, player->GetGUID());
+                        }
+
+                if (Aura* aura = caster->GetAura(GetSpellInfo()->Effects[EFFECT_0].CalcValue()))
+                {
+                    SpellInfo const* spellInfo = aura->GetSpellInfo();
+                    if (!spellInfo)
```
Comment (jackpoz) [inline src/server/scripts/Spells/spell_holiday.cpp]: is there a case where aura->GetSpellInfo() can return NULL ?

Comment (sirikfoll) [inline src/server/scripts/Spells/spell_holiday.cpp]: I supposed not, but i'm not sure, so decided to check

Comment (Shauren) [inline src/server/scripts/Spells/spell_holiday.cpp]: This is impossible.

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 2]
```diff
@@ -410,6 +411,90 @@ class spell_pilgrims_bounty_buff_food : public SpellScriptLoader
...
+    public:
+        spell_pilgrims_bounty_feast_on() : SpellScriptLoader("spell_pilgrims_bounty_feast_on") { }
+
+        class spell_pilgrims_bounty_feast_on_SpellScript : public SpellScript
+        {
+            PrepareSpellScript(spell_pilgrims_bounty_feast_on_SpellScript);
+
+            void HandleDummy(SpellEffIndex /*effIndex*/)
+            {
+                Unit* caster = GetCaster();
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_holiday.cpp]: caster in SpellScript is never NULL

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 3]
```diff
@@ -484,6 +569,78 @@ class spell_pilgrims_bounty_turkey_tracker : public SpellScriptLoader
...
+                if (!target)
+                    return;
+
+                if (Aura const* aura = target->GetAura(GetSpellInfo()->Id))
+                {
+                    if (aura->GetStackAmount() == 5)
+                        target->CastSpell(target, _triggeredSpellId, true);
+                }
+
+                Aura const* Turkey = target->GetAura(SPELL_TURKEY_HELPINS);
```
Comment (Shauren) [inline src/server/scripts/Spells/spell_holiday.cpp]: local variable naming - lowerCamel

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 4]
```diff
@@ -410,6 +411,84 @@ class spell_pilgrims_bounty_buff_food : public SpellScriptLoader
...
+
+                if (Vehicle* vehicle = caster->GetVehicleKit())
+                    if (Unit* target = vehicle->GetPassenger(0))
+                        if (Player* player = target->ToPlayer())
+                        {
+                            player->CastSpell(player, SPELL_ON_PLATE_EAT_VISUAL, true);
+                            caster->CastSpell(player, _spellId, true, NULL, NULL, player->GetGUID());
+                        }
+
+                if (Aura* aura = caster->GetAura(GetSpellInfo()->Effects[EFFECT_0].CalcValue()))
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_holiday.cpp]: `GetEffectValue()` instead of `GetSpellInfo()->Effects[EFFECT_0].CalcValue()`

File: src/server/scripts/Spells/spell_holiday.cpp [hunk 5]
```diff
@@ -410,6 +411,84 @@ class spell_pilgrims_bounty_buff_food : public SpellScriptLoader
...
+                        if (Player* player = target->ToPlayer())
+                        {
+                            player->CastSpell(player, SPELL_ON_PLATE_EAT_VISUAL, true);
+                            caster->CastSpell(player, _spellId, true, NULL, NULL, player->GetGUID());
+                        }
+
+                if (Aura* aura = caster->GetAura(GetEffectValue()))
+                {
+                    if (aura->GetStackAmount() == 1)
+                        caster->RemoveAurasDueToSpell(aura->GetSpellInfo()->Effects[EFFECT_0].CalcValue());
```
Comment (joschiwald) [inline src/server/scripts/Spells/spell_holiday.cpp]: why do you ned this case, doesn't work `aura->ModStackAmount(-1);`?

**Comment by joschiwald** [comment]
missing override keywords

File: src/server/scripts/Spells/spell_holiday.cpp (hunk 5 above)
Comment (sirikfoll) [inline src/server/scripts/Spells/spell_holiday.cpp]: i have 2 auras to remove.
for instance, `caster->GetAura(GetEffectValue())` returns http://wotlk.openwow.com/spell=61804
if is its last charge, `aura->GetSpellInfo()->Effects[EFFECT_0].CalcValue()` returns http://wotlk.openwow.com/spell=61798
and I remove them both
