### PR TITLE
Core/Player: fix periodic eating and drinking emotes

### LINKED ISSUE #12567: [BUG]visual bug about drink and food
db : up-to-date
core : 5d5cbf04dfdc5e962b8b9fadbdce7c0f95fd1483

when player drink and food, there should be a cup or food in hands until you finish the action, at times player will do drink or eat action.
In trinitycore, the cup and food will soon disapear, and player do nothing.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3200233-bug-visual-bug-about-drink-and-food?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Ovahlord**
Fixes drinking and eating periodic emotes. Blizzlike timings, blizzlike first timer. So ye. This is fixed. Mangos did it wrong, I did it right. Sniffs confirm it.

**Changes proposed:**
-  you may now feel like on retail when pointlessly drinking or eating stuff

**Target branch(es):** 3.3.5
- [x] 3.3.5

**Issues addressed:** Closes #12567

**Tests performed:** 
https://www.youtube.com/watch?v=xKGFQ3EF1rc
434 client so differences may occur.

### CODE REVIEW

File: src/server/game/Entities/Player/Player.cpp [hunk 1]
```diff
@@ -2031,6 +2033,39 @@ void Player::RegenerateAll()
...
+    // According to sniffs there is a background timer going on that repeats independed from the time window where the aura applies.
+    // That's why we dont need to reset the timer on apply. In sniffs I have seen that the first call for the spell visual is totally random, then after
+    // 5 seconds over and over again which confirms my theory that we have a independed timer.
+    if (m_foodEmoteTimerCount >= 5000)
+    {
+        std::vector<Aura*> auraList;
+        AuraEffectList const& ModRegenAuras = GetAuraEffectsByType(SPELL_AURA_MOD_REGEN);
+        AuraEffectList const& ModPowerRegenAuras = GetAuraEffectsByType(SPELL_AURA_MOD_POWER_REGEN);
+
+        for (auto itr = ModRegenAuras.begin(); itr != ModRegenAuras.end(); ++itr)
```
Comment (ariel-) [inline src/server/game/Entities/Player/Player.cpp]: Please! you know exactly how much elements your vector will have, seems like a place to use reserve.

Also, you can use vector::insert to copy list elements without for

Comment (Ovahlord) [reply src/server/game/Entities/Player/Player.cpp]: Not necessarily. There may be more regeneration affecting auras aside from drinking food. such as buffs.

File: src/server/game/Entities/Player/Player.cpp [hunk 2]
```diff
@@ -2031,6 +2033,39 @@ void Player::RegenerateAll()
...
+            auraList.emplace_back((*itr)->GetBase());
```
Comment (ccrs) [inline src/server/game/Entities/Player/Player.cpp]: emplace_back? why over push_back?

File: src/server/game/Entities/Player/Player.cpp (hunk 1 above)
Comment (Ovahlord) [reply src/server/game/Entities/Player/Player.cpp]: In how far? At this point we don't know how many auras we will get. We might be just getting one aura. We might also get 10 or 20.
Also I used emplace_back to get a sorted list to prevent random behaivior between food and drinking auras.

File: src/server/game/Entities/Player/Player.cpp (hunk 2 above)
Comment (ccrs) [reply src/server/game/Entities/Player/Player.cpp]: unrelated to the point

**Comment by Ovahlord** [comment]
So after several test results (Thanks to Kittnz) it appears that 335 uses different spell visual id's compared to 4.x and above. does someone have a spare 335 sniff to investigate that?

**Comment by Kittnz** [comment]
Tested and works perfectly.

**Comment by Treeston** [comment]
You enjoy additional timer members on `Player` way too much.

Is there any sort of periodic effect on the eat/drink buffs?

**Comment by Ovahlord** [comment]
No.

**Comment by ariel-** [comment]
Could it be a global timer? as opposed to specific for each player?

**Comment by Ovahlord** [comment]
Wouldn't a global timer look weird when multiple players sit next to each other and play the same animation at the same time? I don't think this is blizzlike

**Comment by Kittnz** [comment]
Nothing suggests it's taking worldstate as an advantage on this. Nothing in sniffs.

**Comment by Mihapro** [comment]
```
V4_3_4_15595 sniff
22:05:38.796 - Spell Go - starts drinking (spell id 80167)
22:05:38.920 - SpellVisualKit ID: 438
22:05:44.131 - SpellVisualKit ID: 438
22:05:49.357 - SpellVisualKit ID: 438
22:05:54.567 - SpellVisualKit ID: 438
```
Starts right after drinking (so probably not a global timer) and in my case timer seems to be periodic 😬  can't find any client-side aura with 5000 ms periodic tho, server-side? 😛

**Comment by Ovahlord** [comment]
Told you it is player depending. And I am certain that there is no global timer because this would look ugly as hell when all players do the exact same thing at the same time.

File: src/server/game/Entities/Unit/Unit.cpp [hunk 3]
```diff
@@ -12770,7 +12770,7 @@ void Unit::SendPlaySpellVisual(uint32 id)
     WorldPacket data(SMSG_PLAY_SPELL_VISUAL, 8 + 4);
     data << uint64(GetGUID());
     data << uint32(id); // SpellVisualKit.dbc index
-    SendMessageToSet(&data, false);
+    SendMessageToSet(&data, true);
```
Comment (joschiwald) [inline src/server/game/Entities/Unit/Unit.cpp]: does this change affect other Unit::SendPlaySpellVisual calls?

Comment (Kittnz) [reply src/server/game/Entities/Unit/Unit.cpp]: No, i tested the ones that use this function and still works fine.

Comment (Ovahlord) [reply src/server/game/Entities/Unit/Unit.cpp]: It is required to make the player itself also see the visual. On 335 this was used for creatures only before and this is needed to expand this to the player itself as well. On 434 and probably master as well this is already changed.

**Comment by Kittnz** [comment]
Can we merge this one?
