### PR TITLE
Core/Pet: Fix pet at rest distance

### LINKED ISSUE #10865: [Core / Pet] [Patch] Pets at rest are too far away
__Rev:__ All

__Bug:__

When pets are idle, they are too far away from their owner

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1412994-core-pet-patch-pets-at-rest-are-too-far-away?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Aokromes**
**Changes proposed**:
- Fix pet at rest distance

**Target branch(es)**: 335

**Issues addressed**: Closes #10865

**Tests performed**: (Does it build, tested in-game, etc)

By MrSmite, closes #10865

### CODE REVIEW

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp [hunk 1]
```diff
@@ -73,8 +73,8 @@ void TargetedMovementGeneratorMedium<T, D>::_setTargetLocation(T* owner, bool up
             //   doing a "dance" while fighting
             if (owner->IsPet() && i_target->GetTypeId() == TYPEID_PLAYER)
             {
-                dist = i_target->GetCombatReach();
-                size = i_target->GetCombatReach() - i_target->GetObjectSize();
+                dist = 1.0f; //i_target->GetCombatReach();
```
Comment (jackpoz) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: what are the original values ?

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp [hunk 2]
```diff
@@ -168,8 +168,15 @@ bool TargetedMovementGeneratorMedium<T, D>::DoUpdate(T* owner, uint32 time_diff)
     if (i_recheckDistance.Passed())
     {
         i_recheckDistance.Reset(100);
+
         //More distance let have better performance, less distance let have more sensitive reaction at target move.
-        float allowed_dist = owner->GetCombatReach() + sWorld->getRate(RATE_TARGET_POS_RECALCULATION_RANGE);
+        float allowed_dist = 0.0f;
+
+        if ((owner->GetTypeId() == TYPEID_UNIT && owner->IsPet()) && (owner->GetCharmerOrOwnerGUID() == i_target->GetGUID()))
```
Comment (jackpoz) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: are you sure == TYPEID_UNIT check is required in addition to IsPet() ?

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 1 above)
Comment (tkrokli) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: I thought the original values could be variable since the checks for `GetCombatReach()` and `GetObjectSize()` were used. I don't know if the results could be a fixed value. Maybe @MrSmite knows more about it, since he wrote it.

Comment (jackpoz) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: please don't add comments that don't give any additional info then

Comment (SnapperRy) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: A moth from the Draenei starting area has the same CombatReach and ObjectSize of 1.5f.

Dist would be 1.5f, and size would be 0.

Other pets might have other values.

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 2 above)
Comment (GitVerge) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: he isn't doing any cast after this check, so you are probably right.

Comment (MrSmite) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: > are you sure == TYPEID_UNIT check is required in addition to IsPet() ?

Probably not anymore. The original IsPet() was this:

```C++
bool IsPet() const { return m_unitTypeMask & UNIT_MASK_PET; }
```

and I used the TYPEID_UNIT check just to make sure that owner was in fact a unit. The new IsPet() is quite different though:

```C++
bool IsPet() const { return GetHigh() == HighGuid::Pet; }
```

HighGuid is something that was added after my original commit.

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 1 above)
Comment (MrSmite) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: > CombatReach and ObjectSize values are 1.5f for a Draenei

These values are for the pet, not the player. All pets should have the same reach.

Comment (MrSmite) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: > please don't add comments that don't give any additional info then

My original commit https://github.com/TrinityCore/TrinityCore/commit/d1e6b603394357f3772e81779ff2741c6fdb6e8f had these comments:

```C++
dist = 1.0f; //i_target->GetCombatReach();
size = 1.0f; //i_target->GetCombatReach() - i_target->GetObjectSize();
```
I was trying to normalize the values because all pets should have the same reach / size.

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 2 above)
Comment (jackpoz) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: 335 still checks "m_unitTypeMask & UNIT_MASK_PET"

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 1 above)
Comment (jackpoz) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: "please don't add comments that don't give any additional info then" was about a comment that the original author removed, not to your code. now it all look weird o.O

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 2 above)
Comment (Shauren) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: so does 6.x, you must have used grep or viewed it in some other form completely out of context - GetHigh is a method inside ObjectGuid, Unit::IsPet is `m_unitTypeMask & UNIT_MASK_PET`

Comment (MrSmite) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: > you must have used grep or viewed it in some other form completely out of context

I quoted from here: https://github.com/TrinityCore/TrinityCore/blob/9bbca372b6395ebf97d898f018459cc88f3c3a38/src/server/game/Entities/Object/ObjectGuid.h

Comment (jackpoz) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: GetTypeId() == TYPEID_UNIT checks if the object is a Creature, not a Unit.
If there's no chance for "GetTypeId() != TYPEID_UNIT && IsPet()" to be true then the GetTypeId() check can be removed.

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 1 above)
Comment (SnapperRy) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: > These values are for the pet, not the player. All pets should have the same reach.

But in that case, i_target is the player, so the player's combat reach/object size are used.

It makes sense that pets stay further away from, say, a Tauren compared to a Blood Elf.

File: src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp (hunk 2 above)
Comment (MrSmite) [inline src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp]: > If there's no chance for "GetTypeId() != TYPEID_UNIT && IsPet()" to be true

Yeah, that's something I wasn't sure about. Is there ever a possibility a pet can't be a unit (eg: an object)?

**Comment by SnapperRy** [comment]
Seems fine, on retail pet distance from owner is the same regardless of a race's model size, and the values on the pr seem correct.

[Distance without PR](http://imgur.com/0rAOxQo) - [Distance with PR](http://imgur.com/YCTLSyY) - [Retail](https://imgur.com/uAHRegC) (thanks Aok!).

allowed_dist is correct too, pets must be more responsive to player movement.
