### PR TITLE
Core/Achievement Fix Achievement Defense of the Ancients

### LINKED ISSUE #3170: [Achievement/Bug] Defense of the Ancients
Hey Everyone,

Tried to do the "Defense of the Ancients" achievement and I found out that is bugged and
unachieveable, please help me...

Related Links:
http://www.wowhead.com/achievement=1757
http://www.wowhead.com/achievement=2200

TDB: 335.11.42+
Hash: f356f65
Addons: wg(not tc) / ac1 / tc2 / armory / pvprank

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65719-achievement-bug-defense-of-the-ancients?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sirikfoll**
The spell that trigger the achievement check, needs to be cast before setting up the variables used for the second round, otherwise the achievement will be granted to the wrong team.
Also, SPELL_END_OF_ROUND needs to be cast on the end of the second round too, this was confirmed in retail.

Closes #3170

### CODE REVIEW

File: src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp [hunk 1]
```diff
@@ -957,6 +957,8 @@ void BattlegroundSA::ToggleTimer()
 
 void BattlegroundSA::EndBattleground(uint32 winner)
 {
+    CastSpellOnTeam(SPELL_END_OF_ROUND, ALLIANCE);
+    CastSpellOnTeam(SPELL_END_OF_ROUND, HORDE);
```
Comment (joschiwald) [inline src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp]: that causes double casts, move it to line 413
