### PR TITLE
DB/Wandering Isle: Implement quest 29664 (The Challenger's Fires) and…

### LINKED ISSUE #30628: DB/QUEST :  Quest : The Challenger's Fires (Pandaren starting zone)
### Description

Quest: https://www.wowhead.com/quest=29664/the-challengers-fires
When you click on Brazier they tell you that you are in wrong zone.

### Expected behaviour

Debug Braziers

like this video: https://www.wowhead.com/quest=29664/the-challengers-fires#videos:id=86551

### Steps to reproduce the problem

Take the quest or do .quest add 29420
Click on braziers

### Branch

master

### TC rev. hash/commit

TrinityCore rev. https://github.com/TrinityCore/TrinityCore/commit/2a51a6454912df635099572d07789a1d6789ff4d 2025-01-21 14:11:54 +0100 (master branch)

### Operating system

Windows 10

### Custom changes

None

### PR DESCRIPTION
**Pull request by aquadeus**
… add serverside spells for Flame Spouts

**Changes proposed:**

-  Implement quest 29664 (The Challenger's Fires) and add serverside spells for Flame Spouts

**Issues addressed:**

Closes #30628

**Tests performed:**

Tested in-game

### CODE REVIEW

File: sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `EmoteOnCompleteDelay`, `EmoteOnIncompleteDelay`, `VerifiedBuild`) VALUES
+(29664, 0, 1, 0, 0, 55461); -- The Challenger's Fires
+
+-- Creature
+UPDATE `creature_template_difficulty` SET `StaticFlags1`=536871168, `VerifiedBuild`=55461 WHERE (`Entry`=57625 AND `DifficultyID`=0); -- 57625 (Generic Sparkle Bunny (CSA)) - Sessile, Floating
+
+-- Gameobjects
+DELETE FROM `gameobject_template_addon` WHERE `entry` IN (209369, 209803, 209802, 209801);
+DELETE FROM `gameobject` WHERE `guid` IN (300150, 300151, 300153); -- Duplicated spawns
+DELETE FROM `creature` WHERE `guid` IN (450604, 450603, 450602); -- Duplicated spawns
```
Comment (Naddley) [inline sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql]: are you sure theyre duplicate and should not be in a different phase?

File: sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+DELETE FROM `quest_offer_reward_locale` WHERE (`locale`='esES' AND `ID` IN (29664,29420));
+INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
+(29664, 'esES', 'Esas llamas te darán la fuerza que aún no has obtenido. Iluminarán tu potencial.', 55461),
+(29420, 'esES', 'El objetivo de la vida no es encontrarse a uno mismo: es crearse a uno mismo. Un camino se extiende ante ti, pero eres tú quien debe elegir las pruebas a las que te enfrentarás... y las pruebas que superarás.', 55461);
+
+DELETE FROM `quest_template_addon` WHERE `ID` IN (29420, 29664, 29421);
+INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`, `ScriptName`) VALUES 
+(29420, 0, 0, 0, 29418, 29664, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ''),
+(29664, 0, 0, 0, 29420, 29421, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ''),
+(29421, 0, 0, 0, 29664, 29422, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');
```
Comment (Naddley) [inline sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql]: NextQuest is used together with ExclusiveGroups to unlock the "next" quest.
if you want to unlock a quest which needs 3 Quests done, you need to put the 3 Quests into a negative exclusiveGroup and put the Quest into NextQuest which is the quest you unlock.

**Comment by aquadeus** [comment]
im marking this as draft since i need to take a look at glowing stuff too

File: sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql (hunk 2 above)
Comment (aquadeus) [reply sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql]: is not for unlock quest, but the chain quest until Huo, the Spirit of Fire quest

File: sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql (hunk 1 above)
Comment (aquadeus) [reply sql/updates/world/master/2025_99_99_99_wandering_isle_quest_29664.sql]: yes, the phased ones have another entry

**Comment by aquadeus** [comment]
ok the glowing/spark flags must be a core issue
