### PR TITLE
[3.3.5] Core/Spells: Fix Shattered Barrier triggering on dispel

### LINKED ISSUE #14555: 3.3.5 Mage: Ice Barrier
Core revision: https://github.com/TrinityCore/TrinityCore/commit/df4b175d689fa99aa3876a2c26bb24ba09970a98
DB version: TDB 335.58
Script version: Mage_ai
Ice Barrier (http://wotlk.openwow.com/spell=43039)
Shattered Barrier (http://wotlk.openwow.com/spell=54787)
ice barrier gets dispelled it activates the Shattered Barrier
Ice Barrier's removal should only freeze surrounding enemies when the shield is broken by damage, not when it is dispelled or spell stolen.

Please excuse my English.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11210853-3-3-5-mage-ice-barrier?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LuqJensen**
Prevents Shattered Barrier talent from triggering when Ice Barrier is dispelled. It should only trigger when Ice Barrier is removed by damage(destroyed).
Closes #14555
Closes #14605

### CODE REVIEW

File: src/server/scripts/Spells/spell_mage.cpp [hunk 1]
```diff
@@ -341,10 +347,23 @@ class spell_mage_ice_barrier : public SpellScriptLoader
                 }
             }
 
+            void AfterRemove(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
+            {
+                AuraRemoveMode removeMode = GetTargetApplication()->GetRemoveMode();
```
Comment (ccrs) [inline src/server/scripts/Spells/spell_mage.cpp]: unused

Comment (LuqJensen) [inline src/server/scripts/Spells/spell_mage.cpp]: oops, i was using it at the start, but figured it was useless checking against removal by enemy spell. i will update it in a moment

**Comment by chaodhib** [comment]
It's cleaner that way, indeed.

File: src/server/scripts/Spells/spell_mage.cpp [hunk 2]
```diff
@@ -341,10 +347,22 @@ class spell_mage_ice_barrier : public SpellScriptLoader
...
 
+            void AfterRemove(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
+            {
+                // Shattered Barrier
+                // Procs only if removed by damage.
+                if (aurEff->GetAmount() <= 0)
+                    if (Unit* caster = GetCaster())
+                        if (AuraEffect* dummy = caster->GetDummyAuraEffect(SPELLFAMILY_MAGE, SPELL_ICON_MAGE_SHATTERED_BARRIER, EFFECT_0))
+                            if (roll_chance_i(dummy->GetSpellInfo()->ProcChance))
+                                caster->CastSpell(GetTarget(), SPELL_MAGE_SHATTERED_BARRIER, true, nullptr, aurEff);
```
Comment (Vincent-Michael) [inline src/server/scripts/Spells/spell_mage.cpp]: Add for SPELL_MAGE_SHATTERED_BARRIER valid check for spell

Comment (LuqJensen) [inline src/server/scripts/Spells/spell_mage.cpp]: done

File: src/server/scripts/Spells/spell_mage.cpp [hunk 3]
```diff
@@ -341,10 +354,22 @@ class spell_mage_ice_barrier : public SpellScriptLoader
                 }
             }
 
+            void AfterRemove(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
+            {
+                // Shattered Barrier
+                // Procs only if removed by damage.
+                if (aurEff->GetAmount() <= 0)
```
Comment (ccrs) [inline src/server/scripts/Spells/spell_mage.cpp]: Is damage the only way to remove it? (check removemode?)
