### PR TITLE
Code/Battleground Opening a game object(banner) under absorb effects …

### LINKED ISSUE #6222: Opening a game object(banner) under absorb effects in battlegrounds should result an interupt
If you're opening a banner for example at arathi basin and got hit by an enemy player, your current opening should be interupted. Problem is that it doesn't work on players with absorbing shields (like Ice barrier and so on)

TrinityCore rev. 2012-04-12 23:58:10 +0300 (296de924f108+) (Unix, Release)
TDB 335.11.46

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64885-opening-a-game-object-banner-under-absorb-effects-in-battlegrounds-should-result-an-interupt?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Aokromes**
**Changes proposed**:
- If you're opening a banner for example at arathi basin and got hit by an enemy player, your current opening should be interupted. Problem is that it doesn't work on players with absorbing shields (like Ice barrier and so on)

**Target branch(es)**: 335/6x

**Issues addressed**: Closes #6222

**Tests performed**: (Does it build, tested in-game, etc)

…in battlegrounds should result an interupt

By zwerg, closes #6222

### CODE REVIEW

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -627,6 +627,17 @@ uint32 Unit::DealDamage(Unit* victim, uint32 damage, CleanDamage const* cleanDam
...
             victim->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_TAKE_DAMAGE, 0);
 
+       // interrupt spells with SPELL_INTERRUPT_FLAG_ABORT_ON_DMG on absorbed damage (no dots)
+       if (!damage && damagetype != DOT && cleanDamage && cleanDamage->absorbed_damage)
+           if (victim != this && victim->GetTypeId() == TYPEID_PLAYER)
+               if (Spell* spell = victim->m_currentSpells[CURRENT_GENERIC_SPELL])
+                   if (spell->getState() == SPELL_STATE_PREPARING)
+                   {
+                       uint32 interruptFlags = spell->m_spellInfo->InterruptFlags;
+                       if (interruptFlags & SPELL_INTERRUPT_FLAG_ABORT_ON_DMG)
```
Comment (DDuarte) [inline src/server/game/Entities/Unit/Unit.cpp]: `if ((interruptFlags & SPELL_INTERRUPT_FLAG_ABORT_ON_DMG) != 0)`
