### PR TITLE
Core/Auras: Implemented SPELL_AURA_COSMETIC_MOUNTED

### LINKED ISSUE #26203: Paladin/Spell Divine Steed (190784)
**Description:**

Divine Steed mount visuel is missing.

**Expected behaviour:**

The Paladin should ride (visuel) his Paladin Race special Mount while the Spell is active.

**Steps to reproduce the problem:**

1. create a Paladin 
2. levelup to lvl 17
3. use Divine Steed

**Branch(es):**

master

**TC rev. hash/commit:** 

1086007f98c8d120f353650d7567d82f6b9aa0f8

**Operating system:** 

Win10

### PR DESCRIPTION
**Pull request by mdX7**
**Changes proposed:**

-  implemented SPELL_AURA_COSMETIC_MOUNTED (SPELL_AURA_487)

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #26203

**Tests performed:**

(Does it build, tested in-game, etc.)
build, tested ingame

### CODE REVIEW

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 1]
```diff
@@ -6003,6 +6003,25 @@ void AuraEffect::HandleStoreTeleportReturnPoint(AuraApplication const* aurApp, u
...
 }
 
+void AuraEffect::HandleCosmeticMounted(AuraApplication const* aurApp, uint8 mode, bool apply) const
+{
+    if (!(mode & AURA_EFFECT_HANDLE_REAL))
+        return;
+
+    if (apply)
+    {
+        aurApp->GetTarget()->Dismount();
```
Comment (Shauren) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp:6013]: Not needed here, lack of `SPELL_ATTR0_CASTABLE_WHILE_MOUNTED` is supposed to take care of it

File: src/server/game/Spells/Auras/SpellAuraEffects.cpp [hunk 2]
```diff
@@ -6003,6 +6003,25 @@ void AuraEffect::HandleStoreTeleportReturnPoint(AuraApplication const* aurApp, u
...
+        aurApp->GetTarget()->SetCosmeticMountDisplayId(GetMiscValue());
+    }
+    else
+        aurApp->GetTarget()->SetCosmeticMountDisplayId(0);
```
Comment (Shauren) [inline src/server/game/Spells/Auras/SpellAuraEffects.cpp:6017]: This is correct, even if you have two auras of this type (tested zandalari racial + divine steed, got set to 0 after steed expired), please document it

**Review by Shauren — CHANGES_REQUESTED** [review]
Missing: Using actual mount immediately removes SPELL_AURA_COSMETIC_MOUNTED auras

**Review by Shauren — APPROVED** [review]
