### PR TITLE
Script/Commands: Add ".pdump copy" command

### LINKED ISSUE #22921: pcopy command
**Description:**

pcopy command will be the fast way for pdump + pload

**Current behaviour:**

When we have to test bugs we must levelup characters, equip them, learn talents and spells or pdump a character and load to one new account

**Expected behaviour:**

with pcopy it will allow use pcopy "source character" "target account" we will have a copy of one existing character.

**Steps to reproduce the problem:**

1. go test some bug

**Branch(es):**

CHANGEME both

**TC rev. hash/commit:** 

N/R d12f0841f198

**Operating system:** N/R

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

- Add ".pdump copy" command
Syntax: .pdump copy $playerNameOrGUID $account [$newname] [$newguid]
Copy character with name/guid $playerNameOrGUID into character list of $account with $newname, with first free or $newguid guid.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #22921

**Tests performed:**

Everything was tested, but then more code changes have been applied so need to re-test it again.

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] ".pdump write" needs to be tested
- [ ] ".pdump load" needs to be tested
- [ ] ".pdump copy" needs to be tested

### CODE REVIEW

**Comment by Treeston** [comment]
is there ever a case where $newname can be optional considering the character already exists?

**Comment by Aokromes** [comment]
> is there ever a case where $newname can be optional considering the character already exists?

core already forces to rename duplicated names.

**Comment by Treeston** [comment]
Oh it will force rename on login? Nice.

**Comment by jackpoz** [comment]
This command is just a shortcut for ".pdump write" + ".pdump load" without passing through a File stored on disk, keeping every validation check that each single command does.

File: src/server/game/Tools/PlayerDump.h [hunk 1]
```diff
@@ -19,6 +19,7 @@
 #define _PLAYER_DUMP_H
 
 #include <string>
+#include <istream>
```
Comment (Shauren) [inline src/server/game/Tools/PlayerDump.h:22]:
```suggestion
#include <iosfwd>
```

File: src/server/game/Tools/PlayerDump.cpp [hunk 2]
```diff
@@ -820,14 +826,13 @@ DumpReturn PlayerDumpReader::LoadDump(std::string const& file, uint32 account, s
...
-                break;
+        input.getline(buf, BUFFER_SIZE);
+        if (input.eof())
+            break;
+        if (input.fail())
             return DUMP_FILE_BROKEN;
-        }
 
         std::string line;
         line.assign(buf);
```
Comment (Shauren) [inline src/server/game/Tools/PlayerDump.cpp:838]: All of this could be just
```
std::string line;
while (std::getline(input, line))
{
    // do stuff with line
}
if (input.fail())
    return DUMP_FILE_BROKEN;

// normal success code... think it commits transaction there?
```

Comment (jackpoz) [reply src/server/game/Tools/PlayerDump.cpp:838]: looks like some nice refactoring to me (that maybe I don't want to include in this PR)

Comment (Shauren) [reply src/server/game/Tools/PlayerDump.cpp:838]: You are already killing FILE* and replacing it with as-similar-as-possible looking code using istream (which is not how you should be using istreams)
