### PR TITLE
Core/Vehicle: Setting home position of creature passenger on AtEngage

### LINKED ISSUE #26481: Core/Vehicle: Passengers can't engage if to far away from home
**Description:**

Some vehicles (Chillmaw 33687) have other creatures as passengers.
If you engage Chillmaw, the passenger will start attacking you too.
If you engage Chillmaw too far away from home, the passenger will not start attacking you.

**Expected behaviour:**

The passengers should (if hostile) attack the player, regardless of engaging position.
Proof (warning loud music) that passenger attack players on vehicles 
https://www.youtube.com/watch?v=RE9go8P6I98

**Steps to reproduce the problem:**

1. .go c 200851
2. wait for it to fly on his waypoints around the sharp rock
3. engage him at around 48/31

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

5991dcb

**Operating system:** 

Win 10 x64

Will open a PR to fix this

### PR DESCRIPTION
**Pull request by Edder**
**Changes proposed:**

- Setting the home position of a passenger to current position like creature does it AtEngage on waypoint movement
- Fixes passengers if they are too far away from home because "their" vehicle moves on waypoints (example Chillmaw 33687)

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #26481

**Tests performed:**

build, test ingame

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

### CODE REVIEW

File: src/server/game/Entities/Creature/Creature.cpp [hunk 1]
```diff
@@ -3343,8 +3343,22 @@ void Creature::AtEngage(Unit* target)
...
         SetHomePosition(GetPosition());
 
+        // if its a vehicle, set the home positon of every creature passenger at engage
+        // so that they are in combat range if hostile
+        if (Vehicle* vehicle = GetVehicleKit())
+        {
+            for (auto seat = vehicle->Seats.begin(); seat != vehicle->Seats.end(); ++seat)
+                if (Unit* passenger = vehicle->GetPassenger(seat->first))
+                    if (Creature* creature = passenger->ToCreature())
+                    {
```
Comment (jackpoz) [inline src/server/game/Entities/Creature/Creature.cpp:3356]: not sure what we usually do, but probably have no { } if there are no "else" cases and if there is only 1 line.
Everything else looks ok imo.

Comment (Edder) [reply src/server/game/Entities/Creature/Creature.cpp:3356]: Oh, you're right, It was a two liner before.

File: src/server/game/Entities/Creature/Creature.cpp [hunk 2]
```diff
@@ -3343,8 +3343,20 @@ void Creature::AtEngage(Unit* target)
...
     if (movetype == WAYPOINT_MOTION_TYPE || movetype == POINT_MOTION_TYPE || (IsAIEnabled() && AI()->IsEscorted()))
+    {
         SetHomePosition(GetPosition());
 
+        // if its a vehicle, set the home positon of every creature passenger at engage
+        // so that they are in combat range if hostile
+        if (Vehicle* vehicle = GetVehicleKit())
+        {
+            for (auto seat = vehicle->Seats.begin(); seat != vehicle->Seats.end(); ++seat)
+                if (Unit* passenger = vehicle->GetPassenger(seat->first))
```
Comment (jackpoz) [inline src/server/game/Entities/Creature/Creature.cpp:3354]: if I check other usages of `Seats.begin()`, usually the Unit* is retrieved from `seat->second.Passenger.Guid`, like
```
if (Unit* passenger = ObjectAccessor::GetUnit(*this, seat->second.Passenger.Guid))
```
as vehicle->GetPassenger() does one extra lookup calling Seats.find()

**Review by jackpoz — CHANGES_REQUESTED** [review]

File: src/server/game/Entities/Creature/Creature.cpp (hunk 2 above)
Comment (Edder) [reply src/server/game/Entities/Creature/Creature.cpp]: Done

**Review by jackpoz — APPROVED** [review]
