### PR TITLE
Core/Spells - DK: Fix Icy Clutch dispel

### LINKED ISSUE #24269: Spell: Icy Clutch
**Description:**
Patch 3.2.0 (04-Aug-2009): Icy Clutch can no longer miss when Frost Fever hits, however, when Frost Fever is dispelled Icy Clutch will also be dispelled.

This change is not implemented in TC:  when Frost Fever is dispelled Icy Clutch will also be dispelled.

**Branch(es):** 3.3.5

**TC rev. hash/commit:** rev. 49e77d7

### PR DESCRIPTION
**Pull request by Jildor**
**Changes proposed:**

-  Patch 3.2.0 (04-Aug-2009): Icy Clutch can no longer miss when Frost Fever hits, however, when Frost Fever is dispelled Icy Clutch will also be dispelled.

**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #24269

**Tests performed:** Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_dk.cpp [hunk 1]
```diff
@@ -1333,6 +1333,25 @@ class spell_dk_hysteria : public AuraScript
...
 
+// 55095 - Frost Fever
+class spell_dk_frost_fever : public AuraScript
+{
+    PrepareAuraScript(spell_dk_frost_fever);
+
+    void HandleDispel(DispelInfo* /*dispelInfo*/)
+    {
+        if (Unit* caster = GetCaster())
+            if (Unit* target = GetUnitOwner())
```
Comment (Keader) [inline src/server/scripts/Spells/spell_dk.cpp]: cant be null in aurascript

Comment (Jildor) [reply src/server/scripts/Spells/spell_dk.cpp]: ok 👍
