### PR TITLE
Core/Spells: Make some spells negative

### LINKED ISSUE #21634: [3.3.5]  Debuffs dispellable by target player
**Description:**

Some Debuffs that are applied to the target can be removed by the target player because they remain as buffs (not debuff).

**Current behaviour:**

Warlock Haunt, Dk Ebone Plague, Paladin Judgment Debuffs in the objective they are applied as buffs and can be eliminated by the objective

**Expected behaviour:**

Debuffs should not be applied as buffs

**Steps to reproduce the problem:**

1. With Warlock, apply Haunt, The target can right click on the buff that is applied, not debuff.
2. With DK, apply Ebone Plague. The target can right click on the buff that is applied, not debuff.
3. With Pally apply Judgment of Justice. The target can right click on the buff that is applied, not debuff.

**Branch(es):**  3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. ddd60a948c43 2018-03-14 20:50:54 +0100 (3.3.5 branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

**Operating system:** WIN SERVER 2012 R2

### PR DESCRIPTION
**Pull request by lost-illusion**
**Changes proposed:**

- Spells with auras 
    - `SPELL_AURA_MOD_DAMAGE_FROM_CASTER`
        - [Shadow Embrace](https://woehead.way-of-elendil.fr/?spell=32386) (increase incoming damage)
        - [Haunt](https://woehead.way-of-elendil.fr/?spell=59164)(deal damage and increase incoming damage)
        - [Frost Vulnerability](https://woehead.way-of-elendil.fr/?spell=51714) (increase incoming damage)
    - `SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT`
        - [Mangle (Cat)](https://woehead.way-of-elendil.fr/?spell=33876)
        - [Mangle (Bear)](https://woehead.way-of-elendil.fr/?spell=33878)
        - [Trauma](https://woehead.way-of-elendil.fr/?spell=46857)
        - [Stampede](https://woehead.way-of-elendil.fr/?spell=57386) (hunter pet spell, deal damage, increase incoming damage
    - `SPELL_AURA_PREVENTS_FLEEING`
        - [Judgement of Justice](https://woehead.way-of-elendil.fr/?spell=20184)
        - [Glyph of Rake](https://woehead.way-of-elendil.fr/?spell=54820)
- [Ebon Plague](https://woehead.way-of-elendil.fr/?spell=51735)

All this spells displayed as buffs, but isn't buffs.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #21634

**Tests performed:** Builds OK, Not tested in-game (should work)

**Known issues and TODO list:**

None that I know of.

### CODE REVIEW

File: src/server/game/Spells/SpellInfo.cpp [hunk 1]
```diff
@@ -3442,6 +3442,11 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             // Starfall
             if (spellInfo->SpellFamilyFlags[2] == 0x00000100)
                 return false;
+            break
```
Comment (tkrokli) [inline src/server/game/Spells/SpellInfo.cpp]:
```cpp
src/server/game/Spells/SpellInfo.cpp:3445:18:
 fatal error: expected ';' after break statement
            break
                 ^
                 ;
1 error generated.
```

**Comment by tkrokli** [comment]
I have edited parts of your PR post, but it needs a bit more information.
1. under "Changes proposed:" you have listed 3 auras and a spell, but not written anything about what kind of changes you suggest to be done in them. Please add some text to explain the intended changes.
2. it is expected that you post links to the referenced spells/auras so people can look them up more easily (if the spells are removed from wowhead.com, use https://woehead.way-of-elendil.fr/ or any similar friendly 3.3.5-based pages)

**Comment by lost-illusion** [comment]
@tkrokli Fix compile and update description with spell examples

File: src/server/game/Spells/SpellInfo.cpp [hunk 2]
```diff
@@ -3442,6 +3442,11 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             // Starfall
             if (spellInfo->SpellFamilyFlags[2] == 0x00000100)
                 return false;
+            break;
+        case SPELLFAMILY_DEATHKNIGHT:
+            if (spellInfo->SpellIconID == 1933) // Ebon Plague
```
Comment (Seyden) [inline src/server/game/Spells/SpellInfo.cpp]: Wasn't the idea to identify spells over the icon dropped? @Shauren

Comment (lost-illusion) [reply src/server/game/Spells/SpellInfo.cpp]: Can change to SpellFamilyFlags, if needed

Comment (Shauren) [reply src/server/game/Spells/SpellInfo.cpp]: it definitely was dropped - icons can change over patches (but ebon plague doesnt exist in legion)

Comment (lost-illusion) [reply src/server/game/Spells/SpellInfo.cpp]: I know, but PR only just for 3.3.5. Maybe partialy can be useful for master

Comment (Gooyeth) [reply src/server/game/Spells/SpellInfo.cpp]: @lost-illusion: It seems to me that Shauren is saying that the solution is fine since it does not affect Legion

Comment (lost-illusion) [reply src/server/game/Spells/SpellInfo.cpp]: This solution can't affect legion because ebon plague doesnt exist in legion, but, im understand, i change iconid check to spell family

File: src/server/game/Spells/SpellInfo.cpp [hunk 3]
```diff
@@ -3442,6 +3442,11 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             // Starfall
             if (spellInfo->SpellFamilyFlags[2] == 0x00000100)
                 return false;
+            break;
+        case SPELLFAMILY_DEATHKNIGHT:
+            if (spellInfo->SpellFamilyFlags[2] == 00000040) // Ebon Plague
```
Comment (Faq) [inline src/server/game/Spells/SpellInfo.cpp]: Shouldnt be 0x ?

Comment (Shauren) [reply src/server/game/Spells/SpellInfo.cpp]: it should

File: src/server/game/Spells/SpellInfo.cpp [hunk 4]
```diff
@@ -3625,6 +3630,8 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             case SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE:
             case SPELL_AURA_MOD_POWER_COST_SCHOOL:
             case SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT:
+            case SPELL_AURA_MOD_DAMAGE_FROM_CASTER:
+            case SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT:
```
Comment (ariel-) [inline src/server/game/Spells/SpellInfo.cpp]: all spell with this aura type is negative

File: src/server/game/Spells/SpellInfo.cpp [hunk 5]
```diff
@@ -3625,6 +3630,8 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             case SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE:
             case SPELL_AURA_MOD_POWER_COST_SCHOOL:
             case SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT:
+            case SPELL_AURA_MOD_DAMAGE_FROM_CASTER:
```
Comment (ariel-) [inline src/server/game/Spells/SpellInfo.cpp]: all spells with this aura type are negative (move to L3495)

File: src/server/game/Spells/SpellInfo.cpp [hunk 6]
```diff
@@ -3701,6 +3708,7 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
             case SPELL_AURA_MELEE_ATTACK_POWER_ATTACKER_BONUS:
             case SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS:
+            case SPELL_AURA_PREVENTS_FLEEING:
```
Comment (ariel-) [inline src/server/game/Spells/SpellInfo.cpp]: same here

File: src/server/game/Spells/SpellInfo.cpp [hunk 7]
```diff
@@ -3442,6 +3442,11 @@ bool _isPositiveEffectImpl(SpellInfo const* spellInfo, uint8 effIndex, std::unor
             // Starfall
             if (spellInfo->SpellFamilyFlags[2] == 0x00000100)
                 return false;
+            break;
+        case SPELLFAMILY_DEATHKNIGHT:
+            if (spellInfo->SpellFamilyFlags[2] == 0x00000040) // Ebon Plague
```
Comment (ariel-) [inline src/server/game/Spells/SpellInfo.cpp]: maybe handle SPELL_AURA_LINKED like SPELL_AURA_PERIODIC_TRIGGER_SPELL?

Comment (lost-illusion) [reply src/server/game/Spells/SpellInfo.cpp]: We can define SPELL_AURA_LINKED, and add addtional checks for non positive target in trigger/linked spell, but in this case its not work. Linked spell have 0 in basepoints, this make linked from ebon plague is positive and ebon plague - positive

**Comment by lost-illusion** [comment]
@ariel- Any news ?

**Comment by Foereaper** [comment]
Found a few more spells causing the same issue:
71204 Touch of Insignificance, Lady Deathwhisper, Icecrown Citadel
72410 Rune of Blood, Saurfang, Icecrown Citadel

**Comment by lost-illusion** [comment]
@Foereaper done
@tje3d Examples ?

**Comment by Foereaper** [comment]
- All the marks from 4 horsemen in Naxxramas also show as normal buffs
- Sanity cast by Yogg'Saron shows as a buff
- The threat debuff from Loatheb in Naxxramas uses the same aura mod as Lady Deathwhisper's Touch of Insignificance, might be better to add the aura mod instead of spell ID case

**Comment by tje3d** [comment]
Death Bringer: Rune of Blood

screen shot 1397-02-08 at 11 19 16 pm

**Comment by lost-illusion** [comment]
@Foereaper We have buffs for decrease threat amount. Maybe target check. But no 100% sure

**Comment by Foereaper** [comment]
@lost-illusion Yeah, I added it to the negative target and basepoint < 0 check

**Comment by DanVS** [comment]
Can this be merged?

**Comment by Keader** [comment]
Already checked if all spells with:

SPELL_AURA_MOD_DAMAGE_FROM_CASTER
SPELL_AURA_PREVENTS_FLEEING
SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT

Is negative? Has no positive spells?

**Comment by DanVS** [comment]
I didn't found any.

**Comment by Keader** [comment]
Thank you.
