### PR TITLE
Core/Scripts: minor fixes in boss_the_lich_king

### LINKED ISSUE #4427: [The Lich King] Summoning effect of adds
Summoning effect of adds (Ghouls, Horrors) is broken. When adds climb out of the ground and they have some pet around themself, they skip summoning effect and instantly attack nearby pet. After ~3 seconds (so after time when summoning effect should end) they attack players. During this ~3sec they can not be pulled (pull does not have any effect.. they still attack pet and after it attack players) and they also ignore aggro from attacks.
It is very unpleasant for tanks who try tank them, because they have big melee DMG so they easily kill healer or any cloth class.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65595-the-lich-king-summoning-effect-of-adds?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7091: [ICC] LICH KING Tiron jump and souls graphics
Trinity Core revision. (799b2c146b)
Trinity Database revision. (335.11.47)

Problem:
When LK use Fury of Frostmourne and he is talking, tirion is releasing from his ice trap and run too LK destroy frostmourne he should jump but he goes through LK, and break frostmourne disappeared there is no souls visuals which release from frostmourne, Tirion should say''THE LICH KING MUST FALL'' when player is revive but he doesnt say this.pls fix this:)
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64327-icc-lich-king-tiron-jump-and-souls-graphics?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sirikfoll**
**Changes proposed:**

-  Fix a bug where the boss wouldn't cast Remorseless Winter if he was casting any other spell
-  Despawn shadow traps at the end of phase one
-  Make boss agressive
-  Improve Vile Spirits and Raging Spirit behavior when frostmourne heroic phase begins(all become passiveVile Spirits return to Home and move random)
-  Fix Valkyr Shadowguard behavior in heroic mode, they should not despawn in this case
-  Add randomization to the Harvest Souls teleport
-  Fix speed from Wicked Spirits and Spirit Bombs
-  Fix Tirion Jump and Knockback(based on fix from SunwellCore)
-  Register OnObjectAreaTargetSelect in spell_the_lich_king_necrotic_plague_SpellScript
-  Change Shadow Trap radius to 5yards

Knockback exception in SpellEffects.cpp may be wrong, accepting ideas ^^

**Target branch(es):** 3.3.5/master
- [x] 3.3.5

**Issues addressed:** Closes #4427 closes #7091

**Tests performed:** Built and tested

**Known issues and TODO list:** (add/remove lines as needed)

- [x] Tirion's knockback will depende on a change done in another PR, to allow knockback on bosses under certain conditions.

### CODE REVIEW

File: src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp [hunk 1]
```diff
@@ -1498,7 +1534,7 @@ class npc_valkyr_shadowguard : public CreatureScript
                 {
                     case POINT_DROP_PLAYER:
                         DoCastAOE(SPELL_EJECT_ALL_PASSENGERS);
-                        me->DespawnOrUnsummon(1000);
+                        IsHeroic() ? me->GetMotionMaster()->MoveTargetedHome() : me->DespawnOrUnsummon(1000);
```
Comment (Shauren) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: absolutely not. ternary operator is not a replacement for `if`

File: src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp [hunk 2]
```diff
@@ -1498,7 +1534,10 @@ class npc_valkyr_shadowguard : public CreatureScript
                 {
                     case POINT_DROP_PLAYER:
                         DoCastAOE(SPELL_EJECT_ALL_PASSENGERS);
-                        me->DespawnOrUnsummon(1000);
+                        if (IsHeroic())
+                            me->GetMotionMaster()->MoveTargetedHome();
```
Comment (Riztazz) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: AFAIK they move to the middle of the platform, not home pos. Home pos can be anywhere on the platform, depends where group tanks lich king

Comment (sirikfoll) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: Seems true, i was following the behavior that is already scripted([when they drop player by reach 50% hp](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L1475)).
What can I use to get those Positions?

Comment (ariel-) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: The room is full of triggers, IIRC one of them was in the center

Comment (Riztazz) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: @ariel- There isnt one in the middle, other triggers are for finding to which location valkyr should move. What i would do is just define a const position (middle of the room) and then generate random near position to that position and move there, because they're not supposed to stack on top of each other

Comment (Keader) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: yeah, issue with stun still valid. Sometimes she "blink" after get stun too

Comment (Riztazz) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: This is caused by spline being finalized on root/stun and so on. If you time ur stuns correctly (timing is crucial) when valkyr picks up player and calls movepoint, unit will teleport to point destination

Comment (sirikfoll) [inline src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp]: They now do move to the middle, to a random position with at a maximum of 4.0f from the center, this number may not be pretty accurate, but I don't think it can be deducted from sniffs
