### PR TITLE
Scripts/Spells: fixed Light's Hammer

### LINKED ISSUE #19671: Core/Script Talent Light's Hammer this presenting problems.
**Description:**

The power Light's Hammer of the paladin "Holy" it is presenting problems. 

**Current behaviour:**

The power Light's Hammer not this carrying out damage to the enemies neither curing.

**Expected behaviour:**

When using Light's Hammer this it should damage the enemies in 10 yards and to cure 6 allies the quantity indicated in the description of the power. 

**Steps to reproduce the problem:**

1. create a player class paladin
2. reach level 10 and to choose the specialization "Holy"
3. choose Light's Hammer as talent point in level 15
4. use Light's Hammer

**Branch(es):**

Master

**TC rev. hash/commit:** 

7c66e7bbc7a401e7a2d8f2bdcead6531678262ea

**TDB version:**  7.2.0+updates

**Operating system:** Windows 10

Description in wowhead http://www.wowhead.com/spell=114158/lights-hammer

### PR DESCRIPTION
**Pull request by Nyr97**
**Changes proposed:**

-  added appropriate .cpp for paladin's pets.

**Issues addressed:** Closes https://github.com/TrinityCore/TrinityCore/issues/19671.

**Tests performed:** It builds and it was tested in-game.

**Known issues and TODO list:** None.

### CODE REVIEW

File: sql/updates/world/master/2022_01_29_02_world.sql [hunk 1]
```diff
@@ -0,0 +1,6 @@
+DELETE FROM `spell_script_names` WHERE `ScriptName`='spell_pal_light_hammer_periodic';
+INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES 
+(114918,'spell_pal_light_hammer_periodic');
+
+UPDATE `creature_template` SET `unit_flags`=33554440, `unit_flags2`=67143680, `unit_flags3`=1, `ScriptName`='npc_pet_pal_light_hammer' WHERE `entry`=59738;
+
```
Comment (Aokromes) [inline sql/updates/world/master/2022_01_29_02_world.sql:6]: missing -- and excesive row.
