### PR TITLE
Core/Quest: Fix wrong feedback sent to the quest sharing sender with auto-accept quests

### LINKED ISSUE #25474: Quest: Accepting shared quest shows as decline in sharer's chat log
**Description:**

Hello, as I've mentioned in the Discord server. When another player accepts a shared quest, it shows up as declined.

I created 2 new paladins for this test and made sure that they are not gm accounts. The below is a picture of the chat log.

image

**Expected behaviour:**

It should say that War has accepted the quest.

**Steps to reproduce the problem:**

1. Create two new accounts
2. Create a paladin on each account
3. One paladin should take the first quest and invite the other paladin to the party
4. Share first quest
5. Other paladin accept the quest

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

6215da0d640b

**Operating system:** 

Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jackpoz**
**Changes proposed:**

-  Core/Quest: Fix wrong feedback sent to the quest sharing sender with auto-accept quests

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**

Closes #25474

**Tests performed:**

Steps described in #25474

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] Maybe autocomplete quests have a similar issue

### CODE REVIEW

**Comment by Faq** [comment]
Thee are no autocomplete sharable q, but there are auto_rewarded with qflag 1032.
```
11874
11937
12186
12187
12494
12600
13807
13990
14185
14186
14187
11197
11226
```

File: src/server/game/Handlers/QuestHandler.cpp [hunk 1]
```diff
@@ -608,15 +608,24 @@ void WorldSession::HandlePushQuestToParty(WorldPacket& recvPacket)
 
         sender->SendPushToPartyResponse(receiver, QUEST_PARTY_MSG_SHARING_QUEST);
 
+        bool questAutoAccepted = false;
         if (quest->IsAutoAccept() && receiver->CanAddQuest(quest, true) && receiver->CanTakeQuest(quest, true))
+        {
             receiver->AddQuestAndCheckCompletion(quest, sender);
+            questAutoAccepted = true;
+        }
```
Comment (Treeston) [inline src/server/game/Handlers/QuestHandler.cpp:616]:
```suggestion
        if (quest->IsAutoAccept() && receiver->CanAddQuest(quest, true) && receiver->CanTakeQuest(quest, true))
        {
            receiver->AddQuestAndCheckCompletion(quest, sender);
            sender->SendPushToPartyResponse(receiver, QUEST_PARTY_MSG_ACCEPT_QUEST);
            return;
        }
```

Comment (jackpoz) [reply src/server/game/Handlers/QuestHandler.cpp:616]: @Treeston does that still show the quest gossip ?

Comment (Treeston) [reply src/server/game/Handlers/QuestHandler.cpp:616]: Oh, should it? I thought auto-accept just went straight to log.

**Comment by Faq** [comment]
rechecked, is ok
