### PR TITLE
Core/GameObject: Make TYPEID_UNIT handle DestroyGate

### LINKED ISSUE #22138: BG/IoC : Bosses Doors bug & Bosses missing
**Description:**

Some bugs related to bosses and keeps of both faction (alliance & horde) in IoC.

**Current behaviour:**

There are no faction bosses in keeps
The door that allow players to access bosses is not opening the right way (not opening at all)

**Expected behaviour:**
There should be a boss in alliance keep and in the horde keep
The door that allow players to access bosses should be opened from as soon as one of the keep doors has been destroyed.

**Steps to reproduce the problem:**

1. Start a IoC BG (in debug mode) 
2. Destroy one of the ennemy keep doors using siege machine
You will see that the door to access boss is still closed
4. Activate gm mode and click on the door to open it
5. Walk to the location of the boss
You will see that the boss isn't spawned.

**Branch(es):**

3.3.5 (maybe on master, i'm not working on the master one at the moment so...)

**TC rev. hash/commit:** 
https://github.com/TrinityCore/TrinityCore/commit/076c7a7b32c0804013f24f46596fe316258bde1a

**Operating system:**
Linux/Debian 9

### PR DESCRIPTION
**Pull request by Maphaze**
**Changes proposed:**

-  Handle Battleground DestroyGate event when player is in a siege machine
- This PR is fixing IoC final phase (doors & bosses spawns) contained in `BattlegroundIC::DestroyGate`

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Issues addressed:**
Closes #22138

**Tests performed:** (Does it build, tested in-game, etc.)
- [x] Build
- [x] Tested in-game

### CODE REVIEW

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 1]
```diff
@@ -2195,6 +2195,13 @@ void GameObject::SetDestructibleState(GameObjectDestructibleState state, WorldOb
             if (attackerOrHealer && attackerOrHealer->GetTypeId() == TYPEID_PLAYER)
                 if (Battleground* bg = attackerOrHealer->ToPlayer()->GetBattleground())
                     bg->DestroyGate(attackerOrHealer->ToPlayer(), this);
+            // Fix for https://github.com/TrinityCore/TrinityCore/issues/22138
```
Comment (Aokromes) [inline src/server/game/Entities/GameObject/GameObject.cpp]: no need of the fix for github part

File: src/server/game/Entities/GameObject/GameObject.cpp [hunk 2]
```diff
@@ -2195,6 +2195,13 @@ void GameObject::SetDestructibleState(GameObjectDestructibleState state, WorldOb
...
+            // When player is in a siege machine, the attackerOrHealer->GetTypeId() is equal to TYPEID_UNIT. The first if statement at line 2196 (above) is not executed.
+            // So, the bg->DestroyGate, at line 2198, isn't called
```
Comment (Aokromes) [inline src/server/game/Entities/GameObject/GameObject.cpp]: lines will change on the future xd

**Comment by Maphaze** [comment]
@Aokromes comments has been removed.

**Comment by Aokromes** [comment]
No need of delete the whole comment, only github and line part :)

**Comment by illfated** [comment]
Cosmetic detail: the PR title can be simplified to only use **Core/GameObject:**

**Comment by Maphaze** [comment]
@Aokromes Well, it should be could like that ^^
@illfated Thanks for the tip !

**Comment by illfated** [comment]
👍 Heh, now that I think about it, I have got a pet peeve for the general usage of "Fix" in PR and commit titles.
I prefer reading a slightly more detailed description (even if abbreviated) in the titles.
In this particular case, I would have written **Core/GameObject: include DestroyGate for TYPEID_UNIT**
Then again, I often pick too much on details and overestimate the importance of titles. 😄

**Comment by Maphaze** [comment]
That's a good point, what about **Core/GameObject: handle DestroyGate for TYPEID_UNIT** ? 😄

**Comment by illfated** [comment]
Fair enough, although in English it is better to say "make TYPEID_UNIT handle DestroyGate" (although that probably makes less sense in programming). I think it makes more sense to say something to the effect that you are adding the call to `DestroyGate` for `TYPEID_UNIT` (compared to the already existing one for players).

BTW: in theory, you could also have used "Core/Battleground: " in the title and still be correct.

**Comment by Maphaze** [comment]
Title updated !

Yeah, i choose Core/GameObject because i thought it was not only for Battleground. Maybe this PR can have other effects on certain situations outside of Battlegrounds.

**Review by Shauren — APPROVED** [review]
