### PR TITLE
Scripts/Diremaul - Dire Maul crystal and forcefield fix

### LINKED ISSUE #14685: [3.3.5] Dire Maul West pylons and Immol thar
Dire Maul West pylons are not clickable. There are 5, players should click (or kill all the elementals i don't remember) to unlock Immol thar
Just the two pylons in the Immol that prison are clickable, but the first 3 are not. A GM can click it but not players so the magic cage never opens.

http://www.wowwiki.com/Immol%27thar

DB 335.58
rev 2b95a5fe3562 2015-04-26
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/14396343-3-3-5-dire-maul-west-pylons-and-immol-thar?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Jinnaix**
Diremaul Crystal and Forcefield fix

**Changes proposed:**

-  Corrected Dire Maul Crystal behavior
-  Forcefield is removed when all crystals are inactive
-  Immol'thar is non attackable until the forcefield is deactivated to prevent players with pets to pull him out without clearing the crystals

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:**

Closes #14685

**Tests performed:**

- [x] builds
- [x] tested ingame

**Sidenotes:**

This script is an adaption of the runes script in Blackrock Spire.
Big parts of Dire Maul need a respawn (On Retail, there are 8 creatures around each crystal, we currently have 4).
Faction change of [Prince Tortheldrin](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=11486) after you kill Immol'thar is still undone.
The whole Dungeon is currently done in SAI/DB, that makes it complicated to check how stuff work right now.

### CODE REVIEW

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 1]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+                // activate forcefield to make it disappear
+                if (GameObject* ffield = instance->GetGameObject(forcefield))
+                    ffield->SetGoState(GO_STATE_ACTIVE);
+                // remove previously set non attackable flag
+                if (Creature* Immo =  instance->GetCreature(immoGUID))
+                    Immo->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
+            }
+        }
+
+        protected:
```
Comment (MaxtorCoder) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:273]: Remove indent here

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 2]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+            if (GetBossState(DATA_CRYSTAL_01) == DONE && GetBossState(DATA_CRYSTAL_02) == DONE && GetBossState(DATA_CRYSTAL_03) == DONE &&
+                GetBossState(DATA_CRYSTAL_04) == DONE && GetBossState(DATA_CRYSTAL_05) == DONE)
+            {
+                // if all crystals are done, we set encounter forcefield to done
+                SetBossState(DATA_FORCEFIELD, DONE);
+                // activate forcefield to make it disappear
+                if (GameObject* ffield = instance->GetGameObject(forcefield))
+                    ffield->SetGoState(GO_STATE_ACTIVE);
+                // remove previously set non attackable flag
+                if (Creature* Immo =  instance->GetCreature(immoGUID))
```
Comment (MaxtorCoder) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:268]:
```suggestion
                if (Creature* Immo = instance->GetCreature(immoGUID))
```

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 3]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+            for (uint8 i = 0; i < 5; ++i)
+            {
+                bool _mobAlive = false;
+                go = instance->GetGameObject(go_crystals[i]);
+                if (!go)
+                    continue;
+
+                if (go->GetGoState() == GO_STATE_READY)
+                {
+                    for (uint8 ii = 0; ii < 4; ++ii)
```
Comment (MaxtorCoder) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:219]:
```suggestion
                    for (uint8 j = 0; j < 4; ++j)
```

**Review by MaxtorCoder — CHANGES_REQUESTED** [review]

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 4]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+                // remove previously set non attackable flag
+                if (Creature* Immo = instance->GetCreature(immoGUID))
+                    Immo->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
+            }
+        }
+
+protected:
+        InstanceScript* _instance;
+        EventMap _events;
+        ObjectGuid go_crystals[5];
```
Comment (Ovahlord) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:276]: _goCrystals pls and go with std::array<ObjectGuid, 5> while at it

all private members should go with   _memberName

Comment (Jinnaix) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp]: Okay, well, i understand that stuff with _private members.
But that std::array<ObjectGuid, 5> goes beyond my understanding of c++.
Do you have the time to explain what this does compared to what i do and therefore why this should be changed?

Comment (MaxtorCoder) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp]: https://en.cppreference.com/w/cpp/container/array

**Comment by Jinnaix** [comment]
oh, okay, that makes stuff really clear - thank you very much @Ovahlord

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 5]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+                }
+            }
+        }
+
+        void Crystalcreaturecheck()
+        {
+            Creature* mob = nullptr;
+            GameObject* go = nullptr;
+
+            for (uint8 i = 0; i < 5; ++i)
```
Comment (Warpten) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:210]: `i < crystalCreatureGUID.size()`

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 6]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+            {
+                bool _mobAlive = false;
+                go = instance->GetGameObject(_crystalGUIDs[i]);
+                if (!go)
+                    continue;
+
+                if (go->GetGoState() == GO_STATE_READY)
+                {
+                    for (uint8 j = 0; j < 4; ++j)
```
Comment (Warpten) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:219]: `i < _crystalCreatureGUIDs[I].size()`

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 7]
```diff
@@ -60,8 +78,205 @@ class instance_dire_maul : public InstanceMapScript
...
+            }
+        }
+
+        void Crystalcreaturestore()
+        {
+            uint8 creatureCount;
+
+            for (uint8 i = 0; i < 5; ++i) // we store creatures in a list for all 5 crystals
+            {
+                creatureCount = 0;
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:184]: should creatureCount be declared here as uint8 creatureCount = 0; ? as you don't use it outside of the loop

**Comment by jackpoz** [comment]
is this PR ready to be merged ?

**Comment by Jinnaix** [comment]
While this script _can_ be improved by using ObjectData to get rid of some guid fetching, i run into problems doing so - i cant solve that with my current knowledge.
Since i have some other Dungeon improvements on my list, i will cover it in these cases and come back to Dire Maul at a later time.

Therefore, from my point this PR in its current state is ready.

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 8]
```diff
@@ -60,8 +78,203 @@ class instance_dire_maul : public InstanceMapScript
...
+
+                if (GameObject* crystal = instance->GetGameObject(_crystalGUIDs[i]))
+                {
+                    for (uint8 j = 0; j < 2; ++j)  // once per creature type from CrystalMobs
+                    {
+                        std::list<Creature*> creatureList;
+                        GetCreatureListWithEntryInGrid(creatureList, crystal, CrystalMobs[j], 30.0f);
+                        for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
+                        {
+                            if (Creature* creature = *itr)
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:192]: can this ever be null ? it sounds strange for that to happen. You can probably just
```cpp
(*itr)->GetGUID();
```

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 9]
```diff
@@ -60,8 +78,203 @@ class instance_dire_maul : public InstanceMapScript
...
+            if (GetBossState(DATA_CRYSTAL_01) == DONE && GetBossState(DATA_CRYSTAL_02) == DONE && GetBossState(DATA_CRYSTAL_03) == DONE &&
+                GetBossState(DATA_CRYSTAL_04) == DONE && GetBossState(DATA_CRYSTAL_05) == DONE)
+            {
+                // if all crystals are done, we set encounter forcefield to done
+                SetBossState(DATA_FORCEFIELD, DONE);
+                // activate forcefield to make it disappear
+                if (GameObject* ffield = instance->GetGameObject(_forcefieldGUID))
+                    ffield->SetGoState(GO_STATE_ACTIVE);
+                // remove previously set non attackable flag
+                if (Creature* Immo = instance->GetCreature(_immoGUID))
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:266]: please name local variable with the first letter lowercase

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 10]
```diff
@@ -60,8 +78,203 @@ class instance_dire_maul : public InstanceMapScript
...
+                                _crystalCreatureGUIDs[i][creatureCount] = creature->GetGUID();
+                                ++creatureCount;
+                            }
+                        }
+                    }
+                }
+            }
+        }
+
+        void Crystalcreaturecheck()
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:203]: please use an uppercase letter at the start of every word (PascalCasing), i.e. CrystalCreatureCheck()

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 11]
```diff
@@ -60,8 +78,203 @@ class instance_dire_maul : public InstanceMapScript
...
+                {
+                    for (uint8 j = 0; j < 2; ++j)  // once per creature type from CrystalMobs
+                    {
+                        std::list<Creature*> creatureList;
+                        GetCreatureListWithEntryInGrid(creatureList, crystal, CrystalMobs[j], 30.0f);
+                        for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
+                        {
+                            if (Creature* creature = *itr)
+                            {
+                                _crystalCreatureGUIDs[i][creatureCount] = creature->GetGUID();
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:194]: should the other values be cleared out ? this seems to set only the ones found

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 12]
```diff
@@ -60,8 +78,203 @@ class instance_dire_maul : public InstanceMapScript
...
             SetBossNumber(EncounterCount);
         }
+
+        void OnCreatureCreate(Creature* creature) override
+        {
+            switch (creature->GetEntry())
+            {
+                case NPC_IMMOLTHAR:
+                    _immoGUID = creature->GetGUID();
+                    // we make Immolthar non attackable, otherwise players with pets can pull him out of the forcefield
```
Comment (offl) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: Really? Seems like now I understand the point of boundaries in places where Blizzard already added boundaries(that thing is called door)

Comment (offl) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: @Jinnaix could you please add a boundary here instead of flags? But only if he shouldn't have unnattackable flags

Comment (Jinnaix) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: Will try, wanted to finish the PR this weekend anyway.
Never did boundaries before but that shouldn't be witchcraft :) 
Im using unattackable here since our mmaps dont support door type gameobjects for pets/minions. Not the only place where this is problematic btw.

Comment (offl) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: Nvm, I forgot one thing, I have no idea if he should not be pulled out of that circle **after 5 pylons are done**, maybe in retail there's no boundary
Without info maybe it's better to hold that flag

Comment (Aokromes) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: on retail the boss is targeteable, but you cannot send pet to attack it.

Comment (offl) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: PTR https://i.imgur.com/GQpzNsb.png https://i.imgur.com/4rt11mR.png

Comment (Jinnaix) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: Well, i would like to keep it this way with a note that as long as mmaps doesnt support doors, we keep this as a workaround?
Or should i completely leave this one out, so players with pets/minions can bypass the pylon event?

Comment (offl) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:91]: Keep the flag

**Comment by jackpoz** [comment]
is there anything left here to do ?

**Comment by jackpoz** [comment]
putting this PR back to draft until the last bits of the review have been addressed (no hurry)

**Comment by Aokromes** [comment]
what's missing here?

**Comment by Jinnaix** [comment]
Yes, sorry, i took a full break from WoW developing - im slowly starting again and will eventually come back to finalize this PR.

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp (hunk 11 above)
Comment (Jinnaix) [reply src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp]: Doing so blews up the script

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 13]
```diff
@@ -59,8 +78,201 @@ class instance_dire_maul : public InstanceMapScript
...
+                bool _mobAlive = false;
+                go = instance->GetGameObject(_crystalGUIDs[i]);
+                if (!go)
+                    continue;
+
+                if (go->GetGoState() == GO_STATE_READY)
+                {
+                    for (uint8 j = 0; j < _crystalCreatureGUIDs[i].size(); ++j)
+                    {
+                        mob = instance->GetCreature(_crystalCreatureGUIDs[i][j]);
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:217]: could "Creature* mob" be declared here or do you need it outside of this loop too ?

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 14]
```diff
@@ -59,8 +78,201 @@ class instance_dire_maul : public InstanceMapScript
...
+
+        void CrystalCreatureCheck()
+        {
+            Creature* mob = nullptr;
+            GameObject* go = nullptr;
+
+            for (uint8 i = 0; i < _crystalGUIDs.size(); ++i)
+            {
+                bool _mobAlive = false;
+                go = instance->GetGameObject(_crystalGUIDs[i]);
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:209]: could "GameObject* go" be declared here or do you need it outside of the loop too ?

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 15]
```diff
@@ -59,8 +78,200 @@ class instance_dire_maul : public InstanceMapScript
...
+                if (!go)
+                    continue;
+
+                if (go->GetGoState() == GO_STATE_READY)
+                {
+                    for (uint8 j = 0; j < _crystalCreatureGUIDs[i].size(); ++j)
+                    {
+                        Creature* mob = nullptr;
+                        mob = instance->GetCreature(_crystalCreatureGUIDs[i][j]);
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:216]:
```suggestion
                        Creature* mob = instance->GetCreature(_crystalCreatureGUIDs[i][j]);
```

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 16]
```diff
@@ -59,8 +78,200 @@ class instance_dire_maul : public InstanceMapScript
...
+            }
+        }
+
+        void CrystalCreatureCheck()
+        {
+            for (uint8 i = 0; i < _crystalGUIDs.size(); ++i)
+            {
+                GameObject* go = nullptr;
+                bool _mobAlive = false;
+                go = instance->GetGameObject(_crystalGUIDs[i]);
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:207]:
```suggestion
                bool _mobAlive = false;
                GameObject* go = instance->GetGameObject(_crystalGUIDs[i]);
```

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 17]
```diff
@@ -59,8 +78,200 @@ class instance_dire_maul : public InstanceMapScript
...
+                    continue;
+
+                if (go->GetGoState() == GO_STATE_READY)
+                {
+                    for (uint8 j = 0; j < _crystalCreatureGUIDs[i].size(); ++j)
+                    {
+                        Creature* mob = nullptr;
+                        mob = instance->GetCreature(_crystalCreatureGUIDs[i][j]);
+                        if (mob && mob->IsAlive())
+                            _mobAlive = true;
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:218]:
```suggestion
                        if (mob && mob->IsAlive())
                        {
                            _mobAlive = true;
                            break;
                        }
```

File: src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp [hunk 18]
```diff
@@ -59,8 +78,200 @@ class instance_dire_maul : public InstanceMapScript
...
+                if (GameObject* ffield = instance->GetGameObject(_forcefieldGUID))
+                    ffield->SetGoState(GO_STATE_ACTIVE);
+                // remove previously set non attackable flag
+                if (Creature* immo = instance->GetCreature(_immoGUID))
+                    immo->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
+            }
+        }
+
+protected:
+        InstanceScript* _instance;
```
Comment (jackpoz) [inline src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp:269]: is this field used ?

**Comment by jackpoz** [comment]
I made some suggestions to the code and added a comment

**Comment by Jinnaix** [comment]
Thank you @jackpoz.
Everything still works as expected.

**Comment by jackpoz** [comment]
is there anything left or is this ready to be merged ?

**Comment by Jinnaix** [comment]
Everything i wanted to do in this PR is done in my eyes.

**Comment by jackpoz** [comment]
Thanks for the PR :)
