### PR TITLE
[Core/Spells] [Request extensive testing] Spell internals rework

### LINKED ISSUE #8844: [ICC/Mutated Transformation]Disease bug
Mutated Transformation ticks refreshes Spirit of Redemption duration so the priest with this talant can never die if there is an abomination alive. Indeed the priest dies from these ticks and come alive in the same second. It is possible to use this mechanic for honorable kills grind if mixed(horde+alliance) raids are enabled.

Mutated Transformation: http://wotlk.openwow.com/?spell=70402
Spirit of Redemption: Spirit of Redemption
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/104295-icc-mutated-transformation-disease-bug?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #15088: [3.3.5][Core/Spell] Mind Control - Diminishing return issue
Mind control applies a diminishing for buff and debuff of the spell. 

Issue: 
- Open 3 wow clients and login with different characters (Priest and 2 more random characters)
- Go to Ring of Trials (so they all will be enemies)
- Cast Mind Control on random player 1 (Mind Control buff is applied to the priest, and mind control debuff is applied to the random player 1 (current target))
- Cast Mind Control on random player 2 right after this: 

THERE is the issue, the buff for priest is at half duration, but the debuff for random player 2 is on full duration. 

When the buff for the priest expires, random player 2 is still in Mind Control, but priest now wont be able to cancelaura Mind Control because the buff for him is already gone bcuz of the diminishing from previous mind control on random player 1.

Priest's MC buff diminishing should be equal to current target diminishing state for MECHANIC_CHARM

3.3.5a
Hash: a6c7f78

### LINKED ISSUE #18395: Spell Effects applied in wrong order
**Description:** Spell Effects applied in wrong order.

**Expected behaviour:** Spell Effect sould be applied in correct order: EFFECT_0 -> EFFECT_1 -> EFFECT_2

**Current behaviour:** EFFECT_1 is applied before EFFECT_0.

**Steps to reproduce the problem:**

1. Target self
2.  ```.cast 41377```
3. You will not receive damage

> Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
> BasePoints = 7444 to 7557
> Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
> 
> Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 1
> Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
> Aura Id 40 (SPELL_AURA_DAMAGE_IMMUNITY), value = 1, misc = 127 (127), miscB = 0, periodic = 0

Damage should be applied before Immunity.

In sniffs packet order is:

> ServerToClient: SMSG_SPELL_NON_MELEE_DAMAGE_LOG (0x4315) Length: 45 ConnIdx: 2 Time: 05/30/2012 10:34:48.876 Number: 432310
> Target GUID: xxxxxxxxx
> Caster GUID: Full: 0xF1305B7C000050B4 Type: Creature Entry: 23420 (Essence of Anger) Low: 20660
> Spell ID: Spite (41377)
> Damage: 7525
> Overkill: -1
> SchoolMask: 8
> Absorb: 0
> Resist: 0
> Show spellname in log: false
> Unk byte: 1
> Blocked: 0
> HitType: SPELL_HIT_TYPE_UNK3 (4)
> Debug output: false
> 
> ServerToClient: SMSG_AURA_UPDATE (0x4707) Length: 30 ConnIdx: 2 Time: 05/30/2012 10:34:48.876 Number: 432311
> GUID: Full: xxxxxxxxxxx
> [0] Slot: 25
> [0] Spell ID: Spite (41377)
> [0] Flags: EffectIndex1, Duration, Negative (162)
> [0] Level: 73
> [0] Charges: 0
> [0] Caster GUID: Full: 0xF1305B7C000050B4 Type: Creature Entry: 23420 (Essence of Anger) Low: 20660
> [0] Max Duration: 2000
> [0] Duration: 2000

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  881cd78ae32d8078e247f64a73c651959a76e746

### LINKED ISSUE #21244: Core/Spells: "Placing Beacon Torch" (ID 17016) in quest "All Along The Watchtowers"
Description:
Accepted the quest from the quest starter and then headed of to the 4 towers and then used the item needed at the door of the towers and can't get the item to be used and cannot complete the objectives.

Current behaviour:
Go to any of the 4 towers and if you use the Beacon Torch item that is given to you by the quest giver at the tower but not the door it says required Andorhal Tower but then go to the door (slightly inside) it says You have no target. It gives a slight effect on the character but keeps all the charges on the beacon torch and nothing happens. If it is suppose to give a circle to place on the floor like a spell it does not and no objectives complete at any of the 4 towers.

Expected behaviour:
Go to the 4 towers and use the Beacon Torch at the doorway and it should give a objective complete for that tower. Not sure if it is suppose to leave a beacon on the floor.

Steps to reproduce the problem:
The steps I have taken to reproduce the problem from abandon the quest and get it again was.
1) Level 58 Human Paladin (not sure if that is relevant)
2) get the quest from the plaguelands
3) go to tower 1,2,3 or 4 as all of them do the same and use the beacon torch in the doorway outside of combat

Branch(es):
3.3.5a

TC rev. hash/commit:
TrinityCore rev. 6892404b270f+ 2017-04-26 04:20:38 -0300 (3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

TDB version: TDB 335.63

Operating system: Windows 10 (64bit)

Extra information:
I have looked on the issues list and there was 1 similar issue but closed and I added the second DB code and added it but same result.

30 minutes later: This issue was bugging me so much I looked into the DB and found out the beacon torch item has a spell id of 17016 but could not find the spell id of 17016 in the DB

### LINKED ISSUE #21330: Core/GameObject/Spells: incorrect handling of spell executing GObjects
**Description:**

The behavior in TC is totaly different to Retail and hacked.
This causes a lot of cosmetic and logic error which need to fixed by hacks again.
This issue is caused by TC spell system.
This system needs a rewrite to support gameobject casts.

I donno if there are other related issues. Or if there are other systems which need to be rewirten for this working properly.

**Current behaviour:**

At the moment, gameobjects which execute a spell, make the player cast the spell.
This way targets are incorrect and visuals are getting lost, because gameobjects in TC can't cast spells.
This causes many gobjects not to work properly.

**Expected behaviour:**
On Retail gameobjects are able to cast spells. Proven a lot of times in sniffs.

**Steps to reproduce the problem:**

1. Use some newer unhacked fixed gameobjects which should cast a spell on you.

**Branch(es):**

3.3.5, master

**TC rev. hash/commit:** 

0f5b8447d0c82120e5ff58eb1931e80911017cdc

**TDB version:**  
TDB 3.3.5
TDB 7.2.0

**Operating system:** Win

### PR DESCRIPTION
**Pull request by ariel-**
**Changes proposed:**

- Implements long overdue changes to the spell system (e.g. Gameobject casting)
- Fixes some old bugs and clears the way to fix others
- Removed assertion from GetFactionTemplateEntry as it was being null-checked and still needs to be analyzed if Gameobjects need to have a faction defined
- Improved positive detection logic (positive/negative stuff was being used to mark spells as debuffs on UI only, but things like dealing damage were considered "positive")
- Split up target selection logic (Target check only determines what kind of entities we can target, spell positivity determines if that entity is valid for attack/assist) ie when targetting a negative spell to an ally
- Spells now only handle at most one UnitAura and one DynObjAura during its lifetime (caused issues with DR as aura objects were present on both target and caster)
- Iterate over effects first, then over targets, this is blizzlike and overdue change

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master (after it has been tested)

**Issues addressed:** 
Closes #8844 
Closes #15088
Closes #18395 
Closes #18885
Closes #21244 
Closes #21330 
Ref #18752 
Ref #19518 
Ref #20560
Ref #21142 
Ref #21330

**Tests performed:**
- Tested summon effects and summon RAF player, they all work properly across different maps
- Tested basic interaction with gameobjects (ie hunter traps) they work properly. All other cases of gameobjects (GOOBER. world traps, need to be tested and fixed, this only opens the way for those)
- Locally compared lists of positive/negative spells before and after the change, 

**Known issues and TODO list:** (add/remove lines as needed)

- [x] GameObjects without faction casting spells (see above description). Does it need to be a part of this PR?

### CODE REVIEW

**Comment by Treeston** [comment]
> Gameobject casting
mind blown

**Comment by Treeston** [comment]
> Gameobject casting

mind blown

**Comment by Treeston** [comment]
> Iterate over effects first, then over targets, this is blizzlike and overdue change

Can you explain in detail what bugs this fixed and/or how this changes behavior?

> GameObjects without faction casting spells (see above description). Does it need to be a part of this PR?

How does this work in the current core? Assuming it's not a regression (and you leave code in a state that is easily extended in a follow-up) I wouldn't say this needs to be in this PR.

**Comment by ariel-** [comment]
> Can you explain in detail what bugs this fixed and/or how this changes behavior?

From https://github.com/TrinityCore/TrinityCore/issues/18395#issuecomment-264652281:
> It makes a huge difference if one of the effects is INSTAKILL and spell targets multiple units including caster (and caster being the target for INSTAKILL). Also in 7.x each effect can have different landing times

> How does this work in the current core? Assuming it's not a regression (and you leave code in a state that is easily extended in a follow-up) I wouldn't say this needs to be in this PR.

Has no effect on current core because gameobjects don't really cast spells. Faction used is the faction from the trigger who casts those on their behalf, and it's a hardcoded 14 for hostile spells and 35 for positive.

Now that gameobjects do cast, faction is used for reaction checks (IsHostile, IsFriendly), if faction == 0, the code defaults to neutral reaction (which may cause unintended behavior, that is why I removed the assertion but left the log, so it'll basically be a runtime log spam if a gameobject is supposed to cast but hasn't correct faction defined in DB)

**Comment by Treeston** [comment]
How much effort would it be to replicate the 14/35 thing?

**Comment by Treeston** [comment]
A lot of this PR appears to be `Unit*` -> `WorldObject*` refactors. Would it be feasible to split these off into a separate sub-PR (akin to #19966) to make reviewing the actual changes made easier?

**Comment by ariel-** [comment]
I tried to split the PR in as much whole chunks as I could, naturally the gameobject casting is the bigger one (and is the one responsible of the Unit -> WorldObject refactor)

**Comment by Treeston** [comment]
Is there any downside to having current TC simply pass `WorldObject*` around (even if it's only ever gonna be `Unit*` in practice?)

**Comment by ariel-** [comment]
Code won't simply compile (ie it would require lots of `->ToUnit()`)

**Comment by Treeston** [comment]
alright then

**Comment by joschiwald** [comment]
what happens with all our spellscripts where caster is guarantee to be never null?

**Comment by ariel-** [comment]
> what happens with all our spellscripts where caster is guarantee to be never null?

GameObjects only cast a handful of (as of now) unscripted spells, which should be handled gracefully by default effect handlers. I see no reason for any of the existing scripts to fail, as they're spells casted by players/creatures.

**Comment by ariel-** [comment]
> How much effort would it be to replicate the 14/35 thing?

That was a hack, I don't intend to replicate it, what needs to be done is fix those gameobjects on a per-case basis

**Comment by Treeston** [comment]
Yes, but as a fallback with error log to avoid regressions until we can fix them.

**Comment by ariel-** [comment]
Error log already done here:
https://github.com/TrinityCore/TrinityCore/pull/21395/files#diff-29afb15ead2a8204cac07d94f074f260R2617

**Comment by Ovahlord** [comment]
Does this PR also covering checking spell_attributes for each single effect? Like ignoring player_only attributes for area_entry target effects for example?

**Comment by ariel-** [comment]
9106c0f27208cc2eb15626e975b929edbf62ad84?

**Comment by joschiwald** [comment]
No, implementation of area aura targets is completely wrong like I
mentioned in several issues (and out of scope of this pr)

>

**Comment by ariel-** [comment]
This is not touching area auras, only regular auras which have more than one target (for example Mind Control which applies a dummy on the caster and the posess aura on the enemy)

**Comment by Faq** [comment]
TBD is planned in this PR?

**Comment by tkrokli** [comment]
The Dark Below? I thought he meant "To Be Determined" 😆

**Comment by ariel-** [comment]
If there's no opposition I'll merge this in one week

PS: @Laintime still waiting your constructive feedback after https://github.com/TrinityCore/TrinityCore/commit/cb9e72e521d3cc415dd15bf6912c87f89e41b92a#commitcomment-26866970

**Comment by Seyden** [comment]
@joschiwald what do you say about it?
@ariel- i would let joschi recheck the PR, before you merge.. he is good in finding things :D

**Comment by joschiwald** [comment]
@Seyden impossible to merge on master, too big commits

File: src/server/game/Spells/Spell.cpp [hunk 1]
```diff
@@ -2225,312 +2238,373 @@ void Spell::AddItemTarget(Item* item, uint32 effectMask)
...
+    // Reset damage/healing counter
+    spell->m_damage = Damage;
+    spell->m_healing = Healing;
 
-    // Do not take combo points on dodge and miss
-    if (missInfo != SPELL_MISS_NONE && m_needComboPoints && m_targets.GetUnitTargetGUID() == target->targetGUID)
-        m_needComboPoints = false;
+    // Get original caster (if exist) and calculate damage/healing from him data
+    // Skip if m_originalCaster not available
+    Unit* caster = spell->m_originalCaster ? spell->m_originalCaster : spell->m_caster->ToUnit();
```
Comment (D0d0) [inline src/server/game/Spells/Spell.cpp]: this is problem when casting from gameobjects. When spell is created Spell.cpp:559 function '->toUnit()' returns 'NUL'. So the reset of this function is not executed -> no damge or cast from gameObject

Comment (jackpoz) [reply src/server/game/Spells/Spell.cpp]: are you working on a fix ?

Comment (jackpoz) [reply src/server/game/Spells/Spell.cpp]: @ariel- any idea about how to fix this ? should half of the Unit:: spell related functions be moved to WorldObject ?

Comment (ariel-) [reply src/server/game/Spells/Spell.cpp]: @jacpoz One of my original ideas was to create another entity (SpellCaster) from which both Unit and GameObject would inherit from. I don't remember why I didn't follow that path. Anyways, from what I can recall about this specifically: unit spellcasting functions deal with spells from units, while gameobject spell casting functions deal with spells from GOs.

The functionality is different by definition, and the GO casting is really limited to some trap spells on its majority. I say no to moving functions to WorldObject, because of those differences.

**Comment by Laintime** [comment]
@ariel- thx am back)need you view)
https://github.com/TrinityCore/TrinityCore/issues/23031

**Comment by Rushor** [comment]
wb @Laintime

File: src/server/game/Spells/Spell.cpp (hunk 1 above)
Comment (jackpoz) [reply src/server/game/Spells/Spell.cpp]: @D0d0 do you have any detailed how to reproduce steps ?

Comment (D0d0) [reply src/server/game/Spells/Spell.cpp]: @jackpoz As far as I remember, just go to Heigan in Naxx and stay in green floor
