### PR TITLE
Fixed problem where item dependent auras are not properly updated

### LINKED ISSUE #18506: [3.3.5] Spell/Warrior: Poleaxe Specialization not work properly with equipment methods
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
Poleaxe Specialization (Rank 5): Increases your chance to get a critical strike and the critical damage caused with Axes and Polearms by 5%.
If the warrior equips an axe/polearm Poleaxe Specialization works ok (crit chance increases by 5%). The problem is when the warrior (with axe/polearm equipped) changes the weapon by another (not axe/polearm) for example a mace. If the method used is "drag and drop" Poleaxe Specialization works ok (crit chance decreases 5%) but if the method used is "right click" or "macros" the crit chance does not decrease.

**Current behaviour:** 
The "right click" and "macros" equipment methods do not work with the Poleaxe specialization.

**Expected behaviour:** 
The "right click" and "macros" equipment methods should work ok with the Poleaxe specialization.

**Steps to reproduce the problem:**
1. Look the initial crit chance and equip an axe.

2. Swap weapon using "drag and drop" method. Poleaxe Specialization works ok (crit chance decreases 5%).

3. Equip the axe again.

4. Swap weapon using "macros" or "right click". Poleaxe Specialization not work (crit chance not decrease).

**Branch(es):** 3.3.5

**TC rev. hash/commit:**  2dbda3d

**TDB version:**  TDB_full_world_335.62_2016_10_17 + updates

**Operating system:**  Windows

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing C++, create a Pull Request.)

### PR DESCRIPTION
**Pull request by ghost**
**Target branch(es):** 3.3.5

- [x] 3.3.5

**Issues addressed:** Closes #18506

**Tests performed:** Compiles and fixes the problem

### CODE REVIEW

File: src/server/game/Handlers/ItemHandler.cpp [hunk 1]
```diff
@@ -253,6 +253,11 @@ void WorldSession::HandleAutoEquipItemOpcode(WorldPacket& recvData)
             _player->EquipItem(eSrc, pDstItem, true);
 
         _player->AutoUnequipOffhandIfNeed();
+
+        // if inventory item was moved, check if we can remove dependent auras, because they were not removed in Player::RemoveItem (update was set to false)
+        // do this after swaps are done, we pass nullptr because both weapons could be swapped and none of them should be ignored
+        if ((srcbag == INVENTORY_SLOT_BAG_0 && srcslot < INVENTORY_SLOT_BAG_END) || (dstbag == INVENTORY_SLOT_BAG_0 && dstslot < INVENTORY_SLOT_BAG_END))
+            _player->ApplyItemDependentAuras((Item*)nullptr, false);
```
Comment (Naios) [inline src/server/game/Handlers/ItemHandler.cpp]: Might be too late but use `static_cast` instead of raw c-casts please.

Comment (Keader) [inline src/server/game/Handlers/ItemHandler.cpp]: @Naios should be used in SpellScripts too? has alot of ```me->CastSpell((Unit*) nullptr, SPELL_ID);```

Comment (Naios) [inline src/server/game/Handlers/ItemHandler.cpp]: Yep

Comment (ariel-) [inline src/server/game/Handlers/ItemHandler.cpp]: Even for nullptr casting?

Comment (Naios) [inline src/server/game/Handlers/ItemHandler.cpp]: Technically it doesn't make any difference when casting a nullpointer, however one should never use a c-cast from C++ because there are 4 alternatives which express your intention better then c-casts:

See http://stackoverflow.com/questions/103512/in-c-why-use-static-castintx-instead-of-intx

> The first problem is that it's almost impossible to tell which one will occur in a C-style cast without looking at large and disperse pieces of code and knowing all the rules.

Comment (xinef1) [inline src/server/game/Handlers/ItemHandler.cpp]: There can be only one intention of nullptr cast, but I agree that we should use c++ casts.

Comment (Shauren) [inline src/server/game/Handlers/ItemHandler.cpp]: There is one valid case for casting a nullptr - function overload resolution, like in the case of CastSpell
