### PR TITLE
Fix evade issues when a projectile hits the target as it's evading

### LINKED ISSUE #4943: [General] Evade/Movement Issues
Hey
I didnt really know how to classify these problems im having

It started with the issue in ToC where some mobs got stuck in evade - this was fixed by applying this #4877 by @Vincent-Michael

The problem persist with other, more general mobs like world mobs etc
Players attack a mob, he keeps evading and when they try to run away he keeps following them to the end of time (or till server crashes/they die)

I have no idea how to reproduce this but im sure many of you have seen this problem or heard of it at least 1 time

Please confirm.

Hash: 8776158
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65437-general-evade-movement-issues?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1310&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Treeston**
Creatures should no longer get stuck in evade mode following a target if a spell hits the creature just as it's entering evade mode.
Fixes and closes #4943. Finally.

Reliable repro on f2b0819:
* Level 1 Human Warlock with Imp pet
* Begin Imp autocast on a Diseased Young Wolf
* Just as the first Imp Firebolt is about to finish casting, start casting your own shadow bolt
* If done correctly, your Shadow Bolt will impact just before the Imp's second Firebolt.
* The Shadow Bolt will trigger bug #19768, giving a reliable evade state.
* The Firebolt will then hit before the home motion finishes, causing ::AttackStart to trigger MoveChase.

Fix details:
* I correct this behavior by checking evade state for creatures in Unit::Attack, and rejecting the attack command if the creature is evading.
  * This causes AttackStart to properly abort and not trigger the movechase.

[Before](https://gfycat.com/ShallowBeautifulAsiansmallclawedotter) / [After](https://gfycat.com/EnlightenedGraveCock)

### CODE REVIEW

File: src/server/game/Entities/Unit/Unit.cpp [hunk 1]
```diff
@@ -5790,6 +5790,11 @@ bool Unit::Attack(Unit* victim, bool meleeAttack)
     if (GetTypeId() == TYPEID_PLAYER && IsMounted())
         return false;
 
+    Creature* mCreature = ToCreature();
```
Comment (Shauren) [inline src/server/game/Entities/Unit/Unit.cpp]: this naming, u wot?

Comment (Treeston) [inline src/server/game/Entities/Unit/Unit.cpp]: bad habits, should be `* creature`, sec.
