### PR TITLE
Spells/Rogue: Implement Cheat death

### LINKED ISSUE #28739: Immortal Rogue
### Description

Due to the talent [Cheat Death](https://www.wowhead.com/spell=31230/cheat-death) ,becomes immortal
I think it's because of the debuff that is not applied when the talent procs

### Expected behaviour

Fatal attacks instead reduce you to 7% of your maximum health. For 3 sec afterward, you take 85% reduced damage. Cannot trigger more often than once per 6 min.

### Steps to reproduce the problem

Just create rogue and check 

### Branch

master

### TC rev. hash/commit

https://github.com/TrinityCore/TrinityCore/commit/fada839526aad1ff7ee1d0f38f77ab5c2a29ab7e

### Operating system

Debian 11

### Custom changes

None

### PR DESCRIPTION
**Pull request by aquadeus**
**Changes proposed:**

-  Implement Cheat death

**Issues addressed:**

Closes #28739

**Tests performed:**

Tested in-game

### CODE REVIEW

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 1]
```diff
@@ -162,6 +165,36 @@ class spell_rog_blade_flurry : public AuraScript
...
+{
+    bool Validate(SpellInfo const* spellInfo) override
+    {
+        return ValidateSpellInfo({ SPELL_ROGUE_CHEAT_DEATH_DUMMY, SPELL_ROGUE_CHEATED_DEATH, SPELL_ROGUE_CHEATING_DEATH })
+            && ValidateSpellEffect({ { spellInfo->Id, EFFECT_1 } });
+    }
+
+    void HandleAbsorb(AuraEffect* /*aurEff*/, DamageInfo& dmgInfo, uint32& absorbAmount)
+    {
+        PreventDefaultAction();
```
Comment (Seyden) [inline src/server/scripts/Spells/spell_rogue.cpp:179]: shouldn't this also be called if "cheated death" is not applied?

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 2]
```diff
@@ -162,6 +165,36 @@ class spell_rog_blade_flurry : public AuraScript
...
+// 31230 - Cheat Death
+class spell_rog_cheat_death : public AuraScript
+{
+    bool Validate(SpellInfo const* spellInfo) override
+    {
+        return ValidateSpellInfo({ SPELL_ROGUE_CHEAT_DEATH_DUMMY, SPELL_ROGUE_CHEATED_DEATH, SPELL_ROGUE_CHEATING_DEATH })
+            && ValidateSpellEffect({ { spellInfo->Id, EFFECT_1 } });
+    }
+
+    void HandleAbsorb(AuraEffect* /*aurEff*/, DamageInfo& dmgInfo, uint32& absorbAmount)
```
Comment (Seyden) [inline src/server/scripts/Spells/spell_rogue.cpp:177]: You need to set the absorbAmount to 0 if you dont want to absorb anything, because right now you're absorbing the amount that is stored in the basepoints

File: src/server/scripts/Spells/spell_rogue.cpp [hunk 3]
```diff
@@ -162,6 +165,36 @@ class spell_rog_blade_flurry : public AuraScript
...
+    {
+        PreventDefaultAction();
+
+        if (!GetTarget()->HasAura(SPELL_ROGUE_CHEATED_DEATH))
+        {
+            int32 healAmount = int32(GetTarget()->CountPctFromMaxHealth(GetEffectInfo(EFFECT_1).CalcValue(GetTarget())));
+            GetTarget()->CastSpell(GetTarget(), SPELL_ROGUE_CHEAT_DEATH_DUMMY, true);
+            GetTarget()->CastSpell(GetTarget(), SPELL_ROGUE_CHEATED_DEATH, true);
+            GetTarget()->CastSpell(GetTarget(), SPELL_ROGUE_CHEATING_DEATH, true);
```
Comment (Seyden) [inline src/server/scripts/Spells/spell_rogue.cpp:186]: You could do that, if you like

```suggestion
            for (uint32 const& spellId : { SPELL_ROGUE_CHEAT_DEATH_DUMMY, SPELL_ROGUE_CHEATED_DEATH, SPELL_ROGUE_CHEATING_DEATH })
                GetTarget()->CastSpell(GetTarget(), spellId, true);
```

File: src/server/scripts/Spells/spell_rogue.cpp (hunk 2 above)
Comment (aquadeus) [reply src/server/scripts/Spells/spell_rogue.cpp:177]: the sniff shows spell absorb

Comment (Seyden) [reply src/server/scripts/Spells/spell_rogue.cpp:177]: > the sniff shows spell absorb

how much? even if you have Cheated Death active?

Comment (aquadeus) [reply src/server/scripts/Spells/spell_rogue.cpp:177]: yes, first you cast spells then absorb log (on sniff)

Comment (Seyden) [reply src/server/scripts/Spells/spell_rogue.cpp:177]: > yes, first you cast spells then absorb log (on sniff)

How much do you absorb if cheat death is on CD?

Comment (aquadeus) [reply src/server/scripts/Spells/spell_rogue.cpp:177]: if cheat death is on cd you die

Comment (Seyden) [reply src/server/scripts/Spells/spell_rogue.cpp:177]: If that’s the case, read my first comment again
