### PR TITLE
Scripts/Spells: fix Turkey Timer duration

### LINKED ISSUE #23387: Achievements [Friend or Fowl?]
**Describe the bug**
The process doesn't count the amount of killed turkeys you do.

**To Reproduce**

Howling Fjord
Start killing turkeys.
Even if you killed 50 under 3 minutes, the achievement wont be marked as completed for some reason. I see that this issue was marked and solved but it still doesnt work.

**Expected behavior**
After killing 15 turkeys in 3 minutes, You gain the achievement: [Friend or Fowl?]

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
4051d4c61e5292d2c6a9fefd316d246cb72ac4e8

### PR DESCRIPTION
**Pull request by adeutscher**
**Changes proposed:**

-  In `spell_gen_turkey_marker::OnPeriodic`, remove tracking timestamps from list as they expire. This prevents older applications from taking all stacks of the aura with them.

**Target branch(es):** 3.3.5

- [x] 3.3.5
- [ ] master

**Issues addressed:** Closes #23387

**Tests performed:**

Builds successfully, Fedora 30.

Testing in-game:

1. Spawn as many turkeys as you need: `.npc add temp 24746`
2. Confirm that GM mode is off.
3. Kill 3 turkeys, start timer. Observe stack count, should be 3.
4. At 1:30, kill 7 more turkeys. Observe stack count, should be 10.
5. Wait until 3:00. Observe stack count, should fall to 7 and stay there.
6. Before 4:30, kill 7 more turkeys. Observe stack count, should be 14.
7. Kill 1 more turkey. This brings you to 15, spawning angry turkeys and granting the achievement.

### CODE REVIEW

File: src/server/scripts/Spells/spell_generic.cpp [hunk 1]
```diff
@@ -3463,12 +3463,18 @@ class spell_gen_turkey_marker : public AuraScript
...
-        if (_applyTimes.front() + GetMaxDuration() < GameTime::GetGameTimeMS())
-            ModStackAmount(-1, AURA_REMOVE_BY_EXPIRE);
+        // pop expired times off of the stack
+        while(!_applyTimes.empty() && _applyTimes.front() + GetMaxDuration() < GameTime::GetGameTimeMS())
+        {
+            _applyTimes.pop_front();
+            removeCount++;
+        }
+
+        if(removeCount){
```
Comment (P-Kito) [inline src/server/scripts/Spells/spell_generic.cpp]: Add a space after `while` and `if` 👍

**Comment by illfated** [comment]
Suggestion for the PR title, the original way TC pull requests are named:

**Scripts/Spells: fix Turkey Timer duration**

**Comment by jackpoz** [comment]
Thanks for the PR :)
